// packages/svelte/src/Additional.svelte
<script lang="ts">
  import type { KrdsAdditionalProps, KrdsTone } from '@krds-community/recipes';

  type Props = Omit<KrdsAdditionalProps, 'className'> & {
    children?: import('svelte').Snippet;
    className?: string;
  };
  type Item = NonNullable<Props['items']>[number];

  let {
    kind = 'surface', id = 'krds-additional', label = '레이블', title = '제목', description = '', hint = '', tone = 'primary', appearance = 'outline', size = 'medium', number = false,
    href = '#', message = '도움말', position = 'top', open = false, disabled = false, value = '', modelValue = '', options = [], items = [], links = [], slides = [], tabs = [], panels = {}, steps = [], columns = [], rows = [], className = '', children,
    ...rest
  }: Props = $props();
  let isOpen = $state(false);
  let selected = $state('');
  let activeIndex = $state(0);
  let checked = $state(false);
  let currentValue = $state('');
  const toneClass: Record<KrdsTone, string> = { primary: 'primary', secondary: 'secondary', gray: 'gray', point: 'point', danger: 'danger', warning: 'warning', success: 'success', information: 'information', disabled: 'disabled' };
  const labelOf = (item: Item) => typeof item === 'string' ? item : 'label' in item ? item.label : item.title;
  const setValue = (event: Event) => { currentValue = (event.currentTarget as HTMLInputElement | HTMLTextAreaElement).value; };
  $effect(() => { isOpen = open; });
  $effect(() => { selected = String(modelValue || options[0]?.value || tabs[0]?.id || ''); });
  $effect(() => { checked = Boolean(modelValue); });
  $effect(() => { currentValue = String(value || modelValue || ''); });
</script>

{#if kind === 'badge' || kind === 'badge-number' || kind === 'badge-size'}
  <span {...rest} class={`krds-badge ${appearance === 'outline' ? `outline-${toneClass[tone]}` : `bg-${appearance === 'light' ? 'light-' : ''}${toneClass[tone]}`} ${size} ${number ? 'number' : ''} ${className}`}>{label}</span>
{:else if kind === 'breadcrumb'}
  <nav {...rest} class={`krds-breadcrumb-wrap ${className}`} aria-label="현재 경로"><ol>{#each items as item, index}<li class:home={index === 0}><a href={'href' in item ? item.href ?? '#' : '#'} aria-current={index === items.length - 1 ? 'page' : undefined}>{labelOf(item)}</a></li>{/each}</ol></nav>
{:else if kind === 'button-icon'}
  <button {...rest} type="button" class={`krds-btn icon ${size} ${className}`} aria-label={label}><span aria-hidden="true">⌕</span></button>
{:else if kind === 'button-text' || kind === 'button-with-icon'}
  <button {...rest} type="button" class={`krds-btn ${kind === 'button-text' ? 'text' : ''} ${className}`}>{label}{kind === 'button-with-icon' ? ' →' : ''}</button>
{:else if kind === 'button-hierarchy' || kind === 'button-size'}
  <button {...rest} type="button" disabled={disabled} class={`krds-button ${className}`} data-variant={tone} data-size={size}>{label}</button>
{:else if kind === 'calendar' || kind === 'date-input'}
  <label class={`krds-field ${className}`}><span class="krds-field-label">{label}</span><input {...rest} id={id} type="date" value={currentValue} oninput={setValue} class="krds-input" />{#if hint}<span class="krds-field-message">{hint}</span>{/if}</label>
{:else if kind === 'calendar-range'}
  <fieldset {...rest} class={`krds-calendar-area ${className}`}><legend>{label}</legend><input type="date" aria-label="시작일" /><span aria-hidden="true">–</span><input type="date" aria-label="종료일" /></fieldset>
{:else if kind === 'carousel' || kind === 'carousel-banner'}
  {@const slide = slides[activeIndex] ?? { id: 'empty', title }}
  <section {...rest} class={`krds-carousel ${className}`} aria-roledescription="carousel" aria-label={label}><p aria-live="polite">{activeIndex + 1} / {Math.max(slides.length, 1)}</p><h3>{slide.title}</h3>{#if slide.description}<p>{slide.description}</p>{/if}<button type="button" aria-label="이전 슬라이드" onclick={() => activeIndex = (activeIndex - 1 + slides.length) % slides.length}>이전</button><button type="button" aria-label="다음 슬라이드" onclick={() => activeIndex = (activeIndex + 1) % slides.length}>다음</button></section>
{:else if kind === 'checkbox-chip' || kind === 'radio-chip' || kind === 'checkbox-size' || kind === 'radio-size'}
  <label {...rest} class={`krds-form-chip ${className}`}><input type={kind.startsWith('radio') ? 'radio' : 'checkbox'} name={rest.name} value={value} disabled={disabled} /><span>{label}</span></label>
{:else if kind === 'coach-mark'}
  <aside {...rest} class={`krds-coach-mark ${className}`} aria-label={title}><h2>{title}</h2><p>{description}</p><button type="button">다음</button><button type="button" onclick={() => isOpen = false}>닫기</button></aside>
{:else if kind === 'contextual-help'}
  <details {...rest} class={`krds-contextual-help ${position} ${className}`}><summary>{label}</summary><div class="tooltip-txt">{description || message}</div></details>
{:else if kind === 'critical-alerts'}
  <div {...rest} class={`krds-critical-alerts ${className}`} role="alert"><ul>{#each items as item}<li>{labelOf(item)}</li>{/each}</ul></div>
{:else if kind === 'disclosure'}
  <details {...rest} class={`krds-disclosure ${className}`} open={isOpen} ontoggle={(event) => isOpen = (event.currentTarget as HTMLDetailsElement).open}><summary>{title}</summary><div class="expand-wrap">{description}{#if children}{@render children()}{/if}</div></details>
{:else if kind === 'favicon'}
  <link rel="icon" href={href} sizes={size === 'medium' ? '32x32' : size} type="image/png" />
{:else if kind === 'file-upload'}
  <div {...rest} class={`krds-file-upload ${className}`}><label>{label}<input type="file" multiple={Boolean(rest.multiple)} onchange={(event) => currentValue = Array.from((event.currentTarget as HTMLInputElement).files ?? []).map((file) => file.name).join(', ')} /></label>{#if currentValue}<p aria-live="polite">{currentValue}</p>{/if}</div>
{:else if kind === 'footer'}
  <footer {...rest} class={`krds-footer ${className}`}><strong>{title}</strong>{#if links.length}<nav aria-label="하단 메뉴"><ul>{#each links as item}<li><a href={item.href ?? '#'}>{item.label}</a></li>{/each}</ul></nav>{/if}</footer>
{:else if kind === 'header' || kind === 'main-menu-mobile' || kind === 'main-menu-pc'}
  <svelte:element this={kind === 'header' ? 'header' : 'nav'} {...rest} aria-label={kind === 'header' ? undefined : kind === 'main-menu-mobile' ? '모바일 메뉴 컨테이너' : '데스크톱 메뉴 컨테이너'} class={`krds-${kind === 'header' ? 'header' : kind === 'main-menu-mobile' ? 'main-menu-mobile' : 'main-menu'} ${className}`}><a href="/">{title}</a><button type="button" aria-expanded={isOpen} aria-controls={`${id}-${kind}-menu`} onclick={() => isOpen = !isOpen}>메뉴</button><nav id={`${id}-${kind}-menu`} aria-label={kind === 'header' ? '헤더 주 메뉴' : kind === 'main-menu-mobile' ? '모바일 주 메뉴' : '주 메뉴'} hidden={!isOpen && kind === 'main-menu-mobile'}><ul>{#each links as item}<li><a href={item.href ?? '#'}>{item.label}</a></li>{/each}</ul></nav></svelte:element>
{:else if kind === 'help-panel' || kind === 'tutorial-panel'}
  <aside {...rest} class={`krds-help-panel ${className}`} hidden={!isOpen} aria-label={title}><div>{description}{#if children}{@render children()}{/if}</div><button type="button" onclick={() => isOpen = false}>접어두기</button></aside>
{:else if kind === 'identifier'}
  <div {...rest} class={`krds-identifier ${className}`}><span class="logo" aria-hidden="true">◎</span><span>{title}</span>{#if description}<small>{description}</small>{/if}</div>
{:else if kind === 'in-page-navigation'}
  <nav {...rest} class={`krds-in-page-navigation-area ${className}`} aria-label={title}><strong>{title}</strong><ul>{#each links as item}<li><a href={item.href ?? `#${item.id ?? item.label}`}>{item.label}</a></li>{/each}</ul></nav>
{:else if kind === 'language-switcher' || kind === 'language-switcher-page'}
  <label {...rest} class={`krds-language ${className}`}><span class="sr-only">언어 선택</span><select bind:value={selected}>{#each options as option}<option value={option.value} disabled={option.disabled}>{option.label}</option>{/each}</select></label>
{:else if kind === 'link'}
  <a {...rest} href={href} class={`krds-link ${className}`}>{label}{rest.target ? ' ↗' : ''}</a>
{:else if kind === 'masthead'}
  <div {...rest} class={`krds-masthead ${className}`} role="note">{description || '이 누리집은 대한민국 공식 전자정부 누리집입니다.'}</div>
{:else if kind === 'modal' || kind === 'modal-sample'}
  <dialog {...rest} class={`krds-modal ${className}`} open={isOpen} aria-labelledby={`${id}-title`}><h2 id={`${id}-title`}>{title}</h2><div>{description}{#if children}{@render children()}{/if}</div><button type="button" onclick={() => isOpen = false}>닫기</button></dialog>
{:else if kind === 'pagination'}
  <nav {...rest} class={`krds-pagination ${className}`} aria-label="페이지 이동"><button type="button" disabled={Number(modelValue) <= 1}>이전</button><div class="page-links">{#each [1, 2, 3, 4, 5] as page}<button type="button" class:active={page === Number(modelValue || 1)} aria-current={page === Number(modelValue || 1) ? 'page' : undefined} onclick={() => modelValue = String(page)}>{page}</button>{/each}</div><button type="button">다음</button></nav>
{:else if kind === 'resize'}
  <label {...rest} class={`krds-resize ${className}`}>화면크기<select bind:value={selected}><option value="100">기본</option><option value="125">크게</option><option value="150">가장 크게</option></select></label>
{:else if kind === 'select' || kind === 'select-size' || kind === 'select-state' || kind === 'select-sorting'}
  <label {...rest} class={`krds-field ${className}`}><span class="krds-field-label">{label}</span><select id={id} bind:value={selected} class={`krds-form-select ${kind === 'select-sorting' ? 'krds-form-select-sort' : ''} ${kind === 'select-state' && !selected ? 'is-error' : ''}`}>{#each options as option}<option value={option.value} disabled={option.disabled}>{option.label}</option>{/each}</select>{#if hint}<span class="krds-field-message">{hint}</span>{/if}</label>
{:else if kind === 'side-navigation'}
  <nav {...rest} class={`krds-side-navigation ${className}`} aria-label={title}><h2>{title}</h2><ul>{#each links as item}<li><a href={item.href ?? '#'}>{item.label}</a></li>{/each}</ul></nav>
{:else if kind === 'skip-link'}
  <div {...rest} class={`krds-skip-link ${className}`}><a href={href}>{label || '본문 바로가기'}</a></div>
{:else if kind === 'spinner'}
  <output {...rest} class={`krds-spinner ${className}`} aria-live="polite">⟳ {label || '처리 중'}</output>
{:else if kind === 'step-indicator'}
  <ol {...rest} class={`krds-step-wrap ${className}`}>{#each steps as step, index}<li class:done={index < Number(modelValue || 0)} aria-current={index === Number(modelValue || 0) ? 'step' : undefined}><span>{index + 1}</span><strong>{step.label}</strong></li>{/each}</ol>
{:else if kind === 'structured-list'}
  <ul {...rest} class={`krds-structured-list ${className}`}>{#each items as item}<li><strong>{labelOf(item)}</strong>{#if 'description' in item}<p>{item.description}</p>{/if}</li>{/each}</ul>
{:else if kind === 'structured-list-table' || kind === 'table'}
  <div {...rest} class={`krds-table-wrap ${className}`}><table><caption>{title}</caption><thead><tr>{#each columns as column}<th scope="col">{column.label}</th>{/each}</tr></thead><tbody>{#each rows as row, rowIndex}<tr>{#each columns as column, columnIndex}{#if columnIndex === 0}<th scope="row">{row[column.key]}</th>{:else}<td>{row[column.key]}</td>{/if}{/each}</tr>{/each}</tbody></table></div>
{:else if kind === 'tab'}
  {@const active = selected || tabs[0]?.id || ''}
  <div {...rest} class={`krds-tab-area ${className}`}><div role="tablist">{#each tabs as tab}<button type="button" role="tab" id={`tab-${tab.id}`} aria-selected={active === tab.id} aria-controls={`panel-${tab.id}`} onclick={() => selected = tab.id}>{tab.label}</button>{/each}</div>{#each tabs as tab}<div role="tabpanel" tabindex="0" id={`panel-${tab.id}`} aria-labelledby={`tab-${tab.id}`} hidden={active !== tab.id}>{panels[tab.id] ?? (tab.id === active ? description : '')}</div>{/each}</div>
{:else if kind === 'tag' || kind === 'tag-link'}
  {#if kind === 'tag-link'}<a {...rest} href={href} class={`krds-btn-tag link ${className}`}>{label}</a>{:else}<span {...rest} class={`krds-btn-tag bg-${toneClass[tone]} ${className}`}>{label}</span>{/if}
{:else if kind === 'textarea'}
  <label class={`krds-field ${className}`}><span class="krds-field-label">{label}</span><textarea id={id} class="krds-input" maxlength="100" value={currentValue} oninput={setValue}></textarea><span aria-live="polite">{currentValue.length}/100</span></label>
{:else if kind === 'text-input-icon'}
  <div {...rest} class={`krds-input-with-icon ${className}`}><input id={id} class="krds-input" aria-label={label || '입력 보조 텍스트'} value={currentValue} oninput={setValue} /><button type="button" aria-label="입력 보조 기능">⌕</button></div>
{:else if kind === 'text-list' || kind === 'text-list-ordered'}
  <svelte:element this={kind === 'text-list-ordered' ? 'ol' : 'ul'} {...rest} class={`krds-info-list ${className}`}>{#each items as item}<li>{labelOf(item)}</li>{/each}</svelte:element>
{:else if kind === 'tooltip' || kind === 'tooltip-box' || kind === 'tooltip-vertical'}
  <span class="krds-tooltip-wrap"><button {...rest} type="button" class={`krds-btn krds-tooltip ${className}`} aria-describedby={`${id}-tip`}>{label}</button><span id={`${id}-tip`} role="tooltip">{message}</span></span>
{:else if kind === 'tts' || kind === 'tts-icon' || kind === 'tts-size'}
  <button {...rest} type="button" class={`krds-tts ${className}`} aria-pressed={checked} onclick={() => checked = !checked}><span class="krds-tts-icon" aria-hidden="true">{checked ? '▶' : '🔊'}</span>{kind === 'tts-icon' ? `<span class="sr-only">${label}</span>` : label}</button>
{:else if kind === 'toggle-switch' || kind === 'toggle-switch-size'}
  <div {...rest} class={`krds-form-toggle-switch ${size} ${className}`}><input id={id} type="checkbox" bind:checked disabled={disabled} /><label for={id}><span class="switch-toggle" aria-hidden="true"><i></i></span>{label}</label></div>
{:else if kind === 'radio-button' || kind === 'radio-size'}
  <label {...rest} class={`krds-form-check ${className}`}><input type="radio" name={rest.name} value={value} /><span>{label}</span></label>
{:else if children}
  {@render children()}
{:else}
  <div {...rest} class={className}>{description}</div>
{/if}

// packages/angular/src/additional.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type {
  KrdsAdditionalProps,
  KrdsCarouselSlide,
  KrdsListItem,
  KrdsNavItem,
  KrdsOption,
  KrdsStep,
  KrdsTableColumn,
  KrdsTableRow,
  KrdsTabItem,
  KrdsTone,
} from '@krds-community/recipes';

@Component({
  selector: 'krds-additional',
  standalone: true,
  imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @switch (renderKind) {
      @case ('badge') {
        <span
          [class]="
            'krds-badge ' +
            (appearance === 'outline' ? 'outline-' : 'bg-') +
            tone +
            ' ' +
            size +
            (number ? ' number' : '')
          "
          >{{ label }}</span
        >
      }
      @case ('breadcrumb') {
        <nav class="krds-breadcrumb-wrap" aria-label="현재 경로">
          <ol>
            @for (item of items; track $index) {
              <li [class.home]="$index === 0">
                <a [href]="navHref(item)">{{ navLabel(item) }}</a>
              </li>
            }
          </ol>
        </nav>
      }
      @case ('accordion') {
        <div class="krds-accordion">
          @for (item of items; track $index) {
            <details class="krds-accordion-item">
              <summary class="krds-accordion-trigger">{{ navLabel(item) }}</summary>
              <div class="krds-accordion-panel">{{ itemDescription(item) }}</div>
            </details>
          }
        </div>
      }
      @case ('button-icon') {
        <button type="button" class="krds-btn icon" [attr.aria-label]="label">⌕</button>
      }
      @case ('button-text') {
        <button type="button" class="krds-btn text">{{ label }}</button>
      }
      @case ('button-with-icon') {
        <button type="button" class="krds-btn">
          {{ label }} <span aria-hidden="true">→</span>
        </button>
      }
      @case ('button-hierarchy') {
        <button
          [type]="type"
          class="krds-button"
          [disabled]="disabled"
          [attr.data-variant]="tone"
          [attr.data-size]="size"
        >
          {{ label }}
        </button>
      }
      @case ('calendar') {
        <label class="krds-field"
          ><span class="krds-field-label">{{ label }}</span
          ><input class="krds-input" type="date" [(ngModel)]="value" [id]="id" />
          @if (hint) {
            <span class="krds-field-message">{{ hint }}</span>
          }
        </label>
      }
      @case ('calendar-range') {
        <fieldset class="krds-calendar-area">
          <legend>{{ label }}</legend>
          <input type="date" aria-label="시작일" /><span aria-hidden="true">–</span
          ><input type="date" aria-label="종료일" />
        </fieldset>
      }
      @case ('carousel') {
        <section class="krds-carousel" aria-roledescription="carousel" [attr.aria-label]="label">
          <p aria-live="polite">{{ slideIndex + 1 }} / {{ slides.length || 1 }}</p>
          <h3>{{ slides[slideIndex]?.title || title }}</h3>
          <p>{{ slides[slideIndex]?.description }}</p>
          <button type="button" (click)="previousSlide()">이전</button
          ><button type="button" (click)="nextSlide()">다음</button>
        </section>
      }
      @case ('checkbox-chip') {
        <label class="krds-form-chip"
          ><input type="checkbox" [disabled]="disabled" [value]="value" /><span>{{
            label
          }}</span></label
        >
      }
      @case ('radio-chip') {
        <label class="krds-form-chip"
          ><input type="radio" [name]="name" [value]="value" /><span>{{ label }}</span></label
        >
      }
      @case ('coach-mark') {
        <aside class="krds-coach-mark" aria-label="따라하기 가이드">
          <h2>{{ title }}</h2>
          <p>{{ description }}</p>
          <button type="button">다음</button
          ><button type="button" (click)="open = false">닫기</button>
        </aside>
      }
      @case ('contextual-help') {
        <details class="krds-contextual-help">
          <summary>{{ label }}</summary>
          <div class="tooltip-txt">{{ description || message }}</div>
        </details>
      }
      @case ('critical-alerts') {
        <div class="krds-critical-alerts" role="alert">
          <ul>
            @for (item of items; track $index) {
              <li>{{ navLabel(item) }}</li>
            }
          </ul>
        </div>
      }
      @case ('disclosure') {
        <details class="krds-disclosure" [open]="open">
          <summary>{{ title }}</summary>
          <div class="expand-wrap">{{ description }}</div>
        </details>
      }
      @case ('file-upload') {
        <div class="krds-file-upload">
          <label
            >{{ label }}<input type="file" multiple (change)="fileNames = fileList($event)"
          /></label>
          @if (fileNames) {
            <p aria-live="polite">{{ fileNames }}</p>
          }
        </div>
      }
      @case ('footer') {
        <footer class="krds-footer">
          <strong>{{ organization }}</strong>
          @if (links.length) {
            <nav aria-label="하단 메뉴">
              <ul>
                @for (item of links; track $index) {
                  <li>
                    <a [href]="item.href || '#'">{{ item.label }}</a>
                  </li>
                }
              </ul>
            </nav>
          }
        </footer>
      }
      @case ('header') {
        <header class="krds-header">
          <a href="/">{{ title }}</a
          ><button
            type="button"
            [attr.aria-expanded]="open"
            [attr.aria-controls]="id + '-header-menu'"
            (click)="open = !open"
          >
            메뉴
          </button>
          <nav [id]="id + '-header-menu'" [hidden]="!open" aria-label="헤더 주 메뉴">
            @for (item of links; track $index) {
              <a [href]="item.href || '#'">{{ item.label }}</a>
            }
          </nav>
        </header>
      }
      @case ('help-panel') {
        <aside
          class="krds-help-panel"
          [hidden]="!open"
          [attr.aria-label]="kind === 'help-panel' ? '도움말 패널' : '튜토리얼 패널'"
        >
          <p>{{ description }}</p>
          <button type="button" (click)="open = false">접어두기</button>
        </aside>
      }
      @case ('identifier') {
        <div class="krds-identifier">
          <span class="logo" aria-hidden="true">◎</span><span>{{ organization }}</span
          ><small>{{ description }}</small>
        </div>
      }
      @case ('in-page-navigation') {
        <nav class="krds-in-page-navigation-area" aria-label="페이지 내비게이션">
          <strong>{{ title }}</strong>
          <ul>
            @for (item of links; track $index) {
              <li>
                <a [href]="item.href || '#'">{{ item.label }}</a>
              </li>
            }
          </ul>
        </nav>
      }
      @case ('language-switcher') {
        <label class="krds-language"
          ><span class="sr-only">언어 선택</span
          ><select [(ngModel)]="selected">
            @for (option of options; track option.value) {
              <option [value]="option.value" [disabled]="option.disabled">
                {{ option.label }}
              </option>
            }
          </select></label
        >
      }
      @case ('link') {
        <a class="krds-link" [href]="href">{{ label }}</a>
      }
      @case ('main-menu-mobile') {
        <nav class="krds-main-menu-mobile">
          <button
            type="button"
            [attr.aria-expanded]="open"
            [attr.aria-controls]="id + '-mobile-menu'"
            (click)="open = !open"
          >
            메뉴
          </button>
          <ul [id]="id + '-mobile-menu'" [hidden]="!open">
            @for (item of links; track $index) {
              <li>
                <a [href]="item.href || '#'">{{ item.label }}</a>
              </li>
            }
          </ul>
        </nav>
      }
      @case ('main-menu-pc') {
        <nav class="krds-main-menu" aria-label="주 메뉴">
          <ul>
            @for (item of links; track $index) {
              <li>
                <a [href]="item.href || '#'">{{ item.label }}</a>
              </li>
            }
          </ul>
        </nav>
      }
      @case ('masthead') {
        <div class="krds-masthead" role="note">
          {{ description || '이 누리집은 대한민국 공식 전자정부 누리집입니다.' }}
        </div>
      }
      @case ('modal') {
        <dialog class="krds-modal" [open]="open" [attr.aria-labelledby]="id + '-title'">
          <h2 [id]="id + '-title'">{{ title }}</h2>
          <p>{{ description }}</p>
          <button type="button" (click)="open = false">닫기</button>
        </dialog>
      }
      @case ('pagination') {
        <nav class="krds-pagination" aria-label="페이지 이동">
          <button type="button" [disabled]="current <= 1" (click)="current = current - 1">
            이전
          </button>
          <div class="page-links">
            @for (page of pages; track page) {
              <button
                type="button"
                [class.active]="page === current"
                [attr.aria-current]="page === current ? 'page' : null"
                (click)="current = page"
              >
                {{ page }}
              </button>
            }
          </div>
          <button type="button" (click)="current = current + 1">다음</button>
        </nav>
      }
      @case ('resize') {
        <label class="krds-resize"
          >화면크기<select [(ngModel)]="selected">
            <option value="100">기본</option>
            <option value="125">크게</option>
            <option value="150">가장 크게</option>
          </select></label
        >
      }
      @case ('select') {
        <label class="krds-field"
          ><span class="krds-field-label">{{ label }}</span
          ><select class="krds-form-select" [(ngModel)]="selected">
            @for (option of options; track option.value) {
              <option [value]="option.value" [disabled]="option.disabled">
                {{ option.label }}
              </option>
            }
          </select>
          @if (hint) {
            <span class="krds-field-message">{{ hint }}</span>
          }
        </label>
      }
      @case ('side-navigation') {
        <nav class="krds-side-navigation" aria-label="{{ title }}">
          <h2>{{ title }}</h2>
          <ul>
            @for (item of links; track $index) {
              <li>
                <a [href]="item.href || '#'">{{ item.label }}</a>
              </li>
            }
          </ul>
        </nav>
      }
      @case ('skip-link') {
        <div class="krds-skip-link">
          <a [href]="href">{{ label || '본문 바로가기' }}</a>
        </div>
      }
      @case ('spinner') {
        <output class="krds-spinner" aria-live="polite">⟳ {{ label || '처리 중' }}</output>
      }
      @case ('step-indicator') {
        <ol class="krds-step-wrap">
          @for (step of steps; track step.id) {
            <li
              [class.done]="$index < current"
              [attr.aria-current]="$index === current ? 'step' : null"
            >
              <span>{{ $index + 1 }}</span
              ><strong>{{ step.label }}</strong>
            </li>
          }
        </ol>
      }
      @case ('structured-list') {
        <ul class="krds-structured-list">
          @for (item of items; track $index) {
            <li>
              <strong>{{ navLabel(item) }}</strong>
            </li>
          }
        </ul>
      }
      @case ('table') {
        <div class="krds-table-wrap">
          <table>
            <caption>
              {{
                title
              }}
            </caption>
            <thead>
              <tr>
                @for (column of columns; track column.key) {
                  <th scope="col">{{ column.label }}</th>
                }
              </tr>
            </thead>
            <tbody>
              @for (row of rows; track $index) {
                <tr>
                  @for (column of columns; track column.key; let columnIndex = $index) {
                    @if (columnIndex === 0) {
                      <th scope="row">{{ row[column.key] }}</th>
                    } @else {
                      <td>{{ row[column.key] }}</td>
                    }
                  }
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
      @case ('tab') {
        <div class="krds-tab-area">
          <div role="tablist">
            @for (tab of tabs; track tab.id) {
              <button
                type="button"
                role="tab"
                [id]="'tab-' + tab.id"
                [attr.aria-selected]="activeTab === tab.id"
                [attr.aria-controls]="'panel-' + tab.id"
                (click)="selected = tab.id"
              >
                {{ tab.label }}
              </button>
            }
          </div>
          @for (tab of tabs; track tab.id) {
            <section
              role="tabpanel"
              [id]="'panel-' + tab.id"
              [attr.aria-labelledby]="'tab-' + tab.id"
              [hidden]="activeTab !== tab.id"
            >
              {{ panels[tab.id] || (tab.id === activeTab ? description : '') }}
            </section>
          }
        </div>
      }
      @case ('tag') {
        <span class="krds-btn-tag" [class]="'krds-btn-tag bg-' + tone">{{ label }}</span>
      }
      @case ('tag-link') {
        <a class="krds-btn-tag link" [href]="href">{{ label }}</a>
      }
      @case ('textarea') {
        <label class="krds-field"
          ><span class="krds-field-label">{{ label }}</span
          ><textarea class="krds-input" [(ngModel)]="value" maxlength="100"></textarea
          ><span aria-live="polite">{{ value.length }}/100</span></label
        >
      }
      @case ('text-input-icon') {
        <div class="krds-input-with-icon">
          <input
            class="krds-input"
            [attr.aria-label]="label || '입력 보조 텍스트'"
            [(ngModel)]="value"
          /><button type="button" aria-label="입력 보조 기능">⌕</button>
        </div>
      }
      @case ('text-list') {
        <ul class="krds-info-list">
          @for (item of items; track $index) {
            <li>{{ navLabel(item) }}</li>
          }
        </ul>
      }
      @case ('text-list-ordered') {
        <ol class="krds-info-list">
          @for (item of items; track $index) {
            <li>{{ navLabel(item) }}</li>
          }
        </ol>
      }
      @case ('tooltip') {
        <span class="krds-tooltip-wrap"
          ><button
            type="button"
            class="krds-btn krds-tooltip"
            [attr.aria-describedby]="id + '-tip'"
          >
            {{ label }}</button
          ><span [id]="id + '-tip'" role="tooltip">{{ message }}</span></span
        >
      }
      @case ('tts') {
        <button
          type="button"
          class="krds-tts"
          [attr.aria-pressed]="playing"
          (click)="playing = !playing"
        >
          <span class="krds-tts-icon" aria-hidden="true">{{ playing ? '▶' : '🔊' }}</span
          >{{ label }}
        </button>
      }
      @case ('toggle-switch') {
        <div class="krds-form-toggle-switch">
          <input [id]="id" type="checkbox" [(ngModel)]="checked" [disabled]="disabled" /><label
            [for]="id"
            ><span class="switch-toggle" aria-hidden="true"><i></i></span>{{ label }}</label
          >
        </div>
      }
      @case ('radio-button') {
        <label class="krds-form-check"
          ><input type="radio" [name]="name" [value]="value" /><span>{{ label }}</span></label
        >
      }
      @case ('surface') {
        <label class="krds-field"
          ><span class="krds-field-label">{{ label }}</span
          ><input class="krds-input" [value]="value" [disabled]="disabled" [readonly]="readonly"
        /></label>
      }
      @default {
        <div>{{ description }}</div>
      }
    }
  `,
})
export class KrdsAdditionalComponent implements KrdsAdditionalProps {
  @Input() kind = 'surface';
  @Input() id = 'krds-additional';
  @Input() label = '레이블';
  @Input() title = '제목';
  @Input() description = '';
  @Input() hint = '';
  @Input() tone: KrdsTone = 'primary';
  @Input() appearance: 'outline' | 'solid' | 'light' = 'outline';
  @Input() size = 'medium';
  @Input() number = false;
  @Input() href = '#';
  @Input() message = '도움말';
  @Input() position = 'top';
  @Input() open = false;
  @Input() disabled = false;
  @Input() value = '';
  @Input() modelValue: string | number | boolean | string[] = '';
  @Input() name = '';
  @Input() required = false;
  @Input() readonly = false;
  @Input() organization = 'KRDS Community';
  @Input() current = 1;
  @Input() selected = '';
  @Input() checked = false;
  @Input() playing = false;
  @Input() options: KrdsOption[] = [];
  @Input() items: (KrdsNavItem | KrdsListItem | string)[] = [];
  @Input() links: KrdsNavItem[] = [];
  @Input() slides: KrdsCarouselSlide[] = [];
  @Input() tabs: KrdsTabItem[] = [];
  @Input() panels: Record<string, string> = {};
  @Input() steps: KrdsStep[] = [];
  @Input() columns: KrdsTableColumn[] = [];
  @Input() rows: KrdsTableRow[] = [];
  get renderKind(): string {
    const aliases: Record<string, string> = {
      'badge-number': 'badge',
      'badge-size': 'badge',
      'accordion-line': 'accordion',
      'button-size': 'button-hierarchy',
      'checkbox-size': 'checkbox-chip',
      'radio-size': 'radio-button',
      'carousel-banner': 'carousel',
      'date-input': 'calendar',
      'language-switcher-page': 'language-switcher',
      'modal-sample': 'modal',
      'select-size': 'select',
      'select-sorting': 'select',
      'select-state': 'select',
      'structured-list-table': 'table',
      'text-input-size': 'surface',
      'text-input-state': 'surface',
      'toggle-switch-size': 'toggle-switch',
      'tooltip-box': 'tooltip',
      'tooltip-vertical': 'tooltip',
      'tts-icon': 'tts',
      'tts-size': 'tts',
      'tutorial-panel': 'help-panel',
    };
    return aliases[this.kind] ?? this.kind;
  }
  get activeTab(): string {
    return this.selected || this.tabs[0]?.id || '';
  }
  pages = [1, 2, 3, 4, 5];
  slideIndex = 0;
  fileNames = '';
  navLabel(item: KrdsNavItem | KrdsListItem | string): string {
    return typeof item === 'string' ? item : 'label' in item ? item.label : item.title;
  }
  itemDescription(item: KrdsNavItem | KrdsListItem | string): string {
    return typeof item !== 'string' && 'description' in item
      ? (item.description ?? '')
      : this.description;
  }
  navHref(item: KrdsNavItem | KrdsListItem | string): string {
    return typeof item !== 'string' && 'href' in item ? item.href || '#' : '#';
  }
  previousSlide(): void {
    this.slideIndex =
      (this.slideIndex - 1 + Math.max(this.slides.length, 1)) % Math.max(this.slides.length, 1);
  }
  nextSlide(): void {
    this.slideIndex = (this.slideIndex + 1) % Math.max(this.slides.length, 1);
  }
  fileList(event: Event): string {
    return Array.from((event.target as HTMLInputElement).files ?? [])
      .map((file) => file.name)
      .join(', ');
  }
}

export {
  KrdsAdditionalComponent as KrdsBadgeComponent,
  KrdsAdditionalComponent as KrdsAccordionLineComponent,
  KrdsAdditionalComponent as KrdsBadgeNumberComponent,
  KrdsAdditionalComponent as KrdsBadgeSizeComponent,
  KrdsAdditionalComponent as KrdsBreadcrumbComponent,
  KrdsAdditionalComponent as KrdsButtonHierarchyComponent,
  KrdsAdditionalComponent as KrdsButtonIconComponent,
  KrdsAdditionalComponent as KrdsButtonSizeComponent,
  KrdsAdditionalComponent as KrdsButtonTextComponent,
  KrdsAdditionalComponent as KrdsButtonWithIconComponent,
  KrdsAdditionalComponent as KrdsCalendarComponent,
  KrdsAdditionalComponent as KrdsCalendarRangeComponent,
  KrdsAdditionalComponent as KrdsCarouselComponent,
  KrdsAdditionalComponent as KrdsCarouselBannerComponent,
  KrdsAdditionalComponent as KrdsCheckboxChipComponent,
  KrdsAdditionalComponent as KrdsCheckboxSizeComponent,
  KrdsAdditionalComponent as KrdsCoachMarkComponent,
  KrdsAdditionalComponent as KrdsContextualHelpComponent,
  KrdsAdditionalComponent as KrdsCriticalAlertsComponent,
  KrdsAdditionalComponent as KrdsDateInputComponent,
  KrdsAdditionalComponent as KrdsDisclosureComponent,
  KrdsAdditionalComponent as KrdsFaviconComponent,
  KrdsAdditionalComponent as KrdsFileUploadComponent,
  KrdsAdditionalComponent as KrdsFooterComponent,
  KrdsAdditionalComponent as KrdsHeaderComponent,
  KrdsAdditionalComponent as KrdsHelpPanelComponent,
  KrdsAdditionalComponent as KrdsIdentifierComponent,
  KrdsAdditionalComponent as KrdsInPageNavigationComponent,
  KrdsAdditionalComponent as KrdsLanguageSwitcherComponent,
  KrdsAdditionalComponent as KrdsLanguageSwitcherPageComponent,
  KrdsAdditionalComponent as KrdsLinkComponent,
  KrdsAdditionalComponent as KrdsMainMenuMobileComponent,
  KrdsAdditionalComponent as KrdsMainMenuPcComponent,
  KrdsAdditionalComponent as KrdsMastheadComponent,
  KrdsAdditionalComponent as KrdsModalComponent,
  KrdsAdditionalComponent as KrdsModalSampleComponent,
  KrdsAdditionalComponent as KrdsPaginationComponent,
  KrdsAdditionalComponent as KrdsRadioButtonComponent,
  KrdsAdditionalComponent as KrdsRadioChipComponent,
  KrdsAdditionalComponent as KrdsRadioSizeComponent,
  KrdsAdditionalComponent as KrdsResizeComponent,
  KrdsAdditionalComponent as KrdsSelectComponent,
  KrdsAdditionalComponent as KrdsSelectSizeComponent,
  KrdsAdditionalComponent as KrdsSelectSortingComponent,
  KrdsAdditionalComponent as KrdsSelectStateComponent,
  KrdsAdditionalComponent as KrdsSideNavigationComponent,
  KrdsAdditionalComponent as KrdsSkipLinkComponent,
  KrdsAdditionalComponent as KrdsSpinnerComponent,
  KrdsAdditionalComponent as KrdsStepIndicatorComponent,
  KrdsAdditionalComponent as KrdsStructuredListComponent,
  KrdsAdditionalComponent as KrdsStructuredListTableComponent,
  KrdsAdditionalComponent as KrdsTabComponent,
  KrdsAdditionalComponent as KrdsTableComponent,
  KrdsAdditionalComponent as KrdsTagComponent,
  KrdsAdditionalComponent as KrdsTagLinkComponent,
  KrdsAdditionalComponent as KrdsTextareaComponent,
  KrdsAdditionalComponent as KrdsTextInputIconComponent,
  KrdsAdditionalComponent as KrdsTextInputSizeComponent,
  KrdsAdditionalComponent as KrdsTextInputStateComponent,
  KrdsAdditionalComponent as KrdsTextListComponent,
  KrdsAdditionalComponent as KrdsTextListOrderedComponent,
  KrdsAdditionalComponent as KrdsToggleSwitchComponent,
  KrdsAdditionalComponent as KrdsToggleSwitchSizeComponent,
  KrdsAdditionalComponent as KrdsTooltipComponent,
  KrdsAdditionalComponent as KrdsTooltipBoxComponent,
  KrdsAdditionalComponent as KrdsTooltipVerticalComponent,
  KrdsAdditionalComponent as KrdsTtsComponent,
  KrdsAdditionalComponent as KrdsTtsIconComponent,
  KrdsAdditionalComponent as KrdsTtsSizeComponent,
  KrdsAdditionalComponent as KrdsTutorialPanelComponent,
};
