// packages/react/src/components/Badge.tsx
import type { ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsTone } from "@krds-community/recipes";
import { toneClass, outlineToneClass } from "./_utils.js";
import type { BoxProps } from "./_utils.js";

export interface BadgeProps extends BoxProps {
  tone?: KrdsTone;
  appearance?: "outline" | "solid" | "light";
  size?: "small" | "medium" | "large";
  number?: boolean;
  label?: ReactNode;
}
export function Badge({
  tone = "primary",
  appearance = "outline",
  size,
  number,
  label,
  children,
  className,
}: BadgeProps) {
  const appearanceClass =
    appearance === "outline"
      ? outlineToneClass[tone]
      : appearance === "light"
        ? `bg-light-${toneClass[tone]}`
        : `bg-${toneClass[tone]}`;
  return (
    <span className={cx("krds-badge", appearanceClass, size, number && "number", className)}>
      {children ?? label}
    </span>
  );
}
export const BadgeNumber = (props: Omit<BadgeProps, "number">) => <Badge {...props} number />;
export const BadgeSize = Badge;

// packages/svelte/src/Badge.svelte
<script lang="ts">
  import { toneClass, invoke } from './lib/shared.js';
  import type { KrdsTone } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    label?: string;
    tone?: KrdsTone;
    appearance?: 'outline' | 'solid' | 'light';
    size?: string;
    number?: boolean;
    className?: string;
    class?: string;
    onclick?: (event: Event) => void;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class'>;

  let {
    label = '레이블',
    tone = 'primary',
    appearance = 'outline',
    size = '',
    number = false,
    className = '',
    class: classProp = '',
    onclick,
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<span
  {...rest}
  class={`krds-badge ${
    appearance === 'outline'
      ? `outline-${toneClass[tone]}`
      : `bg-${appearance === 'light' ? 'light-' : ''}${toneClass[tone]}`
  } ${size} ${number ? 'number' : ''} ${rootClass}`}
  onclick={(event) => invoke(onclick, event)}
>{label}</span>
