// packages/react/src/components/BottomSheet.tsx
import { useEffect, useId, useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

const CLOSE_ANIMATION_MS = 200;

export interface BottomSheetProps extends BoxProps {
  open?: boolean;
  defaultOpen?: boolean;
  title?: ReactNode;
  description?: ReactNode;
  closeLabel?: string;
  onOpenChange?: (open: boolean) => void;
}

export function BottomSheet({
  open: controlledOpen,
  defaultOpen = false,
  title,
  description,
  closeLabel = "닫기",
  onOpenChange,
  id,
  className,
  children,
}: BottomSheetProps) {
  const generatedId = useId();
  const sheetId = id ?? `krds-bottom-sheet-${generatedId}`;
  const titleId = `${sheetId}-title`;
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const open = controlledOpen ?? uncontrolledOpen;
  const [rendered, setRendered] = useState(open === true);
  const [closing, setClosing] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);
  const restoreFocusRef = useRef<HTMLElement | null>(null);
  const wasVisibleRef = useRef(open && rendered);

  const close = () => {
    if (controlledOpen === undefined) setUncontrolledOpen(false);
    onOpenChange?.(false);
  };

  const focusableElements = () =>
    Array.from(
      panelRef.current?.querySelectorAll<HTMLElement>(
        '[autofocus], button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
      ) ?? [],
    );

  useEffect(() => {
    if (open === true) {
      setClosing(false);
      setRendered(true);
      return;
    }
    if (!rendered) return;
    setClosing(true);
    const timer = setTimeout(() => {
      setRendered(false);
      setClosing(false);
    }, CLOSE_ANIMATION_MS);
    return () => clearTimeout(timer);
  }, [open, rendered]);

  useEffect(() => {
    const panel = panelRef.current;
    const visible = open && rendered;
    if (!panel) return;
    if (visible && !wasVisibleRef.current) {
      const activeElement = panel.ownerDocument.activeElement;
      const view = panel.ownerDocument.defaultView;
      restoreFocusRef.current =
        view && activeElement instanceof view.HTMLElement && !panel.contains(activeElement)
          ? activeElement
          : null;
      focusableElements()[0]?.focus();
    } else if (!visible && wasVisibleRef.current) {
      if (restoreFocusRef.current?.isConnected) restoreFocusRef.current.focus();
      restoreFocusRef.current = null;
    }
    wasVisibleRef.current = visible;
  }, [open, rendered]);

  useEffect(
    () => () => {
      if (restoreFocusRef.current?.isConnected) restoreFocusRef.current.focus();
    },
    [],
  );

  if (!rendered) return null;

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === "Escape" || event.key === "Esc") {
      event.preventDefault();
      close();
      return;
    }
    if (event.key !== "Tab") return;
    const focusables = focusableElements();
    if (focusables.length === 0) return;
    const first = focusables[0];
    const last = focusables[focusables.length - 1];
    const activeElement = panelRef.current?.ownerDocument.activeElement;
    if (
      event.shiftKey &&
      (activeElement === first || !activeElement || !panelRef.current?.contains(activeElement))
    ) {
      event.preventDefault();
      last?.focus();
    } else if (!event.shiftKey && activeElement === last) {
      event.preventDefault();
      first?.focus();
    }
  };

  return (
    <div
      id={sheetId}
      className={cx("krds-bottom-sheet", closing && "closing", className)}
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? titleId : undefined}
      onKeyDown={handleKeyDown}
      onClick={(event) => {
        if ((event.target as HTMLElement).closest?.("[data-close]")) close();
      }}
    >
      <div className="bottom-sheet-overlay" data-close />
      <div className="bottom-sheet-panel" role="document" ref={panelRef}>
        <button
          type="button"
          className="bottom-sheet-handle"
          data-close
          aria-hidden="true"
          tabIndex={-1}
        />
        {title ? (
          <div className="bottom-sheet-header">
            <h2 id={titleId} className="bottom-sheet-title">
              {title}
            </h2>
            {description ? <p className="bottom-sheet-description">{description}</p> : null}
          </div>
        ) : null}
        <div className="bottom-sheet-body">{children}</div>
        <button
          type="button"
          className="krds-btn medium icon bottom-sheet-close"
          aria-label={closeLabel ?? "닫기"}
          onClick={close}
        >
          <SvgIcon name="ico-modal-close" />
        </button>
      </div>
    </div>
  );
}

// packages/svelte/src/BottomSheet.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import type { Snippet } from 'svelte';

  const CLOSE_ANIMATION_MS = 200;

  type Props = {
    open?: boolean;
    defaultOpen?: boolean;
    title?: string;
    description?: string;
    closeLabel?: string;
    onopenchange?: (open: boolean) => void;
    children?: Snippet;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  const generatedId = $props.id();

  let {
    id = generatedId,
    open = $bindable<boolean | undefined>(),
    defaultOpen = false,
    title = '',
    description = '',
    closeLabel = '닫기',
    onopenchange,
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const controlled = $derived(open !== undefined);

  let rendered = $state(open === true || (open === undefined && defaultOpen === true));
  let closing = $state(false);
  let wasOpen = false;
  let wasRendered = false;
  let removeTimer: ReturnType<typeof setTimeout> | undefined;
  let sheetRoot: HTMLElement | undefined = $state();
  let restoreFocus: HTMLElement | null = null;

  const startClose = () => {
    if (!rendered || closing) return;
    closing = true;
    restoreFocus?.focus();
    restoreFocus = null;
    removeTimer = setTimeout(() => {
      rendered = false;
      closing = false;
      onopenchange?.(false);
    }, CLOSE_ANIMATION_MS);
  };

  const requestClose = () => {
    if (controlled) {
      onopenchange?.(false);
    } else {
      startClose();
    }
  };

  $effect(() => {
    const isOpen = controlled ? open === true : rendered;
    if (isOpen && !wasOpen) {
      if (removeTimer) clearTimeout(removeTimer);
      closing = false;
      rendered = true;
    } else if (!isOpen && wasOpen) {
      startClose();
    }
    wasOpen = isOpen;
  });

  $effect(() => {
    if (rendered && !wasRendered) {
      restoreFocus =
        typeof document !== 'undefined' && document.activeElement instanceof HTMLElement
          ? document.activeElement
          : null;
      queueMicrotask(() => {
        sheetRoot
          ?.querySelector<HTMLElement>(
            'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
          )
          ?.focus();
      });
    }
    wasRendered = rendered;
  });

  const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      requestClose();
      return;
    }
    if (event.key !== 'Tab') return;
    const focusable = Array.from(
      sheetRoot?.querySelectorAll<HTMLElement>(
        'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
      ) ?? [],
    );
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    const activeElement = sheetRoot?.ownerDocument.activeElement;
    if (event.shiftKey && (activeElement === first || !sheetRoot?.contains(activeElement))) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  };

  onDestroy(() => {
    if (removeTimer) clearTimeout(removeTimer);
  });
</script>

{#if rendered}
  <div
    {...rest}
    bind:this={sheetRoot}
    class={`krds-bottom-sheet ${rootClass}`}
    class:closing={closing}
    role="dialog"
    aria-modal="true"
    aria-labelledby={title ? `${id}-title` : undefined}
    onkeydown={handleKeydown}
  >
    <div class="bottom-sheet-overlay" data-close onclick={requestClose}></div>
    <div class="bottom-sheet-panel" role="document">
      <button type="button" class="bottom-sheet-handle" aria-hidden="true" tabindex="-1"></button>
      {#if title}
        <div class="bottom-sheet-header">
          <h2 id={`${id}-title`} class="bottom-sheet-title">{title}</h2>
          {#if description}
            <p class="bottom-sheet-description">{description}</p>
          {/if}
        </div>
      {/if}
      <div class="bottom-sheet-body">{@render children?.()}</div>
      <button type="button" class="krds-btn medium icon bottom-sheet-close" aria-label={closeLabel} onclick={requestClose}>
        <i class="svg-icon ico-modal-close"></i>
      </button>
    </div>
  </div>
{/if}
