// packages/react/src/components/Breadcrumb.tsx
import { useId, type HTMLAttributes, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsNavItem } from "@krds-community/recipes";
import { type NativeCommonProps } from "./_utils.js";

export interface BreadcrumbProps extends NativeCommonProps, HTMLAttributes<HTMLElement> {
  items?: KrdsNavItem[];
  label?: string;
}
export function Breadcrumb({
  items = [],
  label = "현재 경로",
  id: providedId,
  className,
  "aria-label": ariaLabel,
  ref,
  ...props
}: BreadcrumbProps & { ref?: Ref<HTMLElement> }) {
  const generatedId = useId();
  return (
    <nav
      {...props}
      ref={ref}
      id={providedId ?? `krds-breadcrumb-${generatedId}`}
      className={cx("krds-breadcrumb-wrap", className)}
      aria-label={ariaLabel ?? label}
    >
      <ol className="breadcrumb">
        {items.map((item, index) => (
          <li className={index === 0 ? "home" : undefined} key={item.id ?? item.label}>
            <a className="txt" href={item.href ?? "#"}>
              {item.label}
            </a>
          </li>
        ))}
      </ol>
    </nav>
  );
}

// packages/svelte/src/Breadcrumb.svelte
<script lang="ts">
  import { invoke, labelOf, hrefOf } from './lib/shared.js';
  import type { KrdsNavItem } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    id?: string;
    items?: KrdsNavItem[];
    links?: KrdsNavItem[];
    nav?: KrdsNavItem[];
    className?: string;
    class?: string;
    onclick?: (event: Event) => void;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  const generatedId = $props.id();
  let {
    id = generatedId,
    items = [],
    links = [],
    nav = [],
    className = '',
    class: classProp = '',
    onclick,
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const navigationItems = $derived(items.length ? items : links.length ? links : nav);
</script>

<nav {...rest} id={id} class={`krds-breadcrumb-wrap ${rootClass}`} aria-label="현재 경로">
  <ol class="breadcrumb">
    {#each navigationItems as item, index}
      <li class:home={index === 0}>
        <a class="txt" href={hrefOf(item)} onclick={(event) => invoke(onclick, event)}>{labelOf(item)}</a>
      </li>
    {/each}
  </ol>
</nav>
