// packages/angular/src/components/card.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

export interface KrdsCardAction {
  label: string;
  onClick?: () => void;
}

@Component({
  selector: "krds-card",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article [class]="'krds-card ' + type">
      @if (image || badges.length > 0) {
        <div class="card-top">
          @if (image) {
            <img class="card-image" [src]="image" [attr.alt]="imageAlt" />
          }
          @for (badge of badges; track $index) {
            <span class="krds-badge bg-primary card-badge">{{ badge }}</span>
          }
        </div>
      }
      <div class="card-conts">
        <h3 class="card-title">{{ title }}</h3>
        @if (description) {
          <p class="card-description">{{ description }}</p>
        }
        @if (actions.length > 0) {
          <div class="card-actions">
            @for (action of actions; track $index) {
              <button type="button" class="krds-btn small primary" (click)="action.onClick?.()">
                {{ action.label }}
              </button>
            }
          </div>
        }
      </div>
    </article>
  `,
})
export class KrdsCardComponent {
  @Input() id = createStableId("krds-card");
  @Input() type: "vertical" | "horizontal" = "vertical";
  @Input() image = "";
  @Input() imageAlt = "";
  @Input() title = "";
  @Input() description = "";
  @Input() badges: string[] = [];
  @Input() actions: KrdsCardAction[] = [];
}

// packages/svelte/src/Card.svelte
<script lang="ts">
  import Badge from './Badge.svelte';
  import Button from './Button.svelte';
  import Checkbox from './Checkbox.svelte';

  type Action = { label: string; onClick?: () => void };

  type Props = {
    type?: 'vertical' | 'horizontal';
    image?: string;
    imageAlt?: string;
    title: string;
    description?: string;
    badges?: string[];
    actions?: Action[];
    checkbox?: Record<string, unknown>;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    type = 'vertical',
    image = '',
    imageAlt = '',
    title,
    description = '',
    badges = [],
    actions = [],
    checkbox,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<article {...rest} class={`krds-card ${type} ${rootClass}`}>
  {#if image || badges.length || checkbox}
    <div class="card-top">
      {#if image}
        <img class="card-image" src={image} alt={imageAlt} />
      {/if}
      {#each badges as badge}
        <Badge label={badge} appearance="solid" className="card-badge" />
      {/each}
      {#if checkbox}
        <Checkbox {...checkbox} />
      {/if}
    </div>
  {/if}
  <div class="card-conts">
    <h3 class="card-title">{title}</h3>
    {#if description}
      <p class="card-description">{description}</p>
    {/if}
    {#if actions.length}
      <div class="card-actions">
        {#each actions as action}
          <Button size="small" variant="primary" onclick={action.onClick}>{action.label}</Button>
        {/each}
      </div>
    {/if}
  </div>
</article>
