// packages/solid/src/components/CheckboxSize.tsx
import { createSignal, createUniqueId, mergeProps, splitProps, type JSX } from "solid-js";

export interface CheckboxSizeProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  id?: string;
  name?: string;
  size?: string;
  checked?: boolean;
  disabled?: boolean;
  playing?: boolean;
  modelValue?: boolean;
  [key: string]: unknown;
}

export function CheckboxSize(rawProps: CheckboxSizeProps) {
  const merged = mergeProps({ id: `krds-checkbox-${createUniqueId()}` }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "id",
    "name",
    "size",
    "checked",
    "disabled",
    "playing",
    "modelValue",
  ]);
  const [localChecked, setLocalChecked] = createSignal(false);
  const checked = () =>
    props.playing !== undefined
      ? Boolean(props.playing)
      : props.checked !== undefined
        ? Boolean(props.checked)
        : typeof props.modelValue === "boolean"
          ? props.modelValue
          : localChecked();
  const setChecked = (next: boolean) => {
    if (
      props.playing === undefined &&
      props.checked === undefined &&
      typeof props.modelValue !== "boolean"
    )
      setLocalChecked(next);
  };
  const updateChecked = (event: Event & { currentTarget: HTMLInputElement }) => {
    setChecked(event.currentTarget.checked);
    (native as Record<string, any>).onChange?.(event);
  };
  const content = () => props.children ?? props.label;
  const className = () => props.class ?? props.className ?? "";
  return (
    <div class={["krds-form-check", props.size, className()].filter(Boolean).join(" ")}>
      <input
        {...(native as Record<string, any>)}
        id={props.id}
        type="checkbox"
        name={props.name}
        checked={checked()}
        disabled={props.disabled}
        onChange={updateChecked}
      />
      <label for={props.id}>{content()}</label>
    </div>
  );
}

// packages/svelte/src/CheckboxSize.svelte
<script lang="ts">
  type Props = {
    id?: string;
    name?: string;
    value?: string | number | boolean;
    label?: string;
    disabled?: boolean;
    required?: boolean;
    form?: string;
    size?: string;
    modelValue?: string | number | boolean | string[];
    checked?: boolean;
    onchange?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    name = '',
    value,
    label = '레이블',
    disabled = false,
    required = false,
    form,
    size = '',
    modelValue = $bindable<string | number | boolean | string[] | undefined>(),
    checked = $bindable<boolean | undefined>(),
    onchange,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const chipChecked = $derived(
    Array.isArray(modelValue)
      ? modelValue.includes(String(value))
      : modelValue !== undefined
        ? modelValue === value
        : checked,
  );
  const setChip = (event: Event) => {
    const next = (event.currentTarget as HTMLInputElement).checked;
    if (Array.isArray(modelValue)) {
      const item = String(value);
      modelValue = next
        ? modelValue.includes(item)
          ? modelValue
          : [...modelValue, item]
        : modelValue.filter((entry) => entry !== item);
      checked = next;
      if (onchange) onchange(event);
    } else {
      checked = next;
      if (typeof modelValue === 'boolean' || modelValue === undefined) modelValue = next;
      if (onchange) onchange(event);
    }
  };
</script>

<div class={`krds-form-check ${size} ${rootClass}`}>
  <input
    {...rest}
    type="checkbox"
    id={id}
    name={name || undefined}
    value={value}
    checked={chipChecked}
    {disabled}
    {required}
    {form}
    onchange={setChip}
  />
  <label for={id}>{label}</label>
</div>
