// packages/angular/src/components/contextual-help.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-contextual-help",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="contextualHelpClass">
      <p class="tooltip-txt">{{ caption }}</p>
      <div class="tooltip-action">
        <button
          type="button"
          class="krds-btn medium icon tooltip-btn"
          aria-expanded="false"
          [attr.aria-controls]="tooltipPopoverId"
        >
          <span class="sr-only">{{ label }}</span>
          <i class="svg-icon ico-tooltip"></i>
        </button>
        <div [id]="tooltipPopoverId" class="tooltip-popover" role="tooltip">
          <h4 class="tooltip-title">{{ title }}</h4>
          <div class="tooltip-contents">
            <p>{{ description }}</p>
            <div class="btn-wrap">
              <a [href]="href" class="krds-btn xsmall link basic">
                {{ linkLabel }} <i class="svg-icon ico-angle right"></i>
              </a>
            </div>
          </div>
          <button type="button" class="krds-btn xsmall icon tooltip-close">
            <span class="sr-only">{{ closeLabel }}</span>
            <i class="svg-icon ico-modal-close"></i>
          </button>
        </div>
      </div>
    </div>
  `,
})
export class KrdsContextualHelpComponent {
  @Input() id = createStableId("krds-contextual-help");
  @Input() label = "레이블";
  @Input() caption = "";
  @Input() title = "제목";
  @Input() description = "";
  @Input() href = "#";
  @Input() linkLabel = "";
  @Input() closeLabel = "";
  @Input() position = "top";

  get contextualHelpClass(): string {
    return `krds-contextual-help ${this.position.split("-").join(" ")}`;
  }

  get tooltipPopoverId(): string {
    return `${this.id}-tooltip`;
  }
}

// packages/svelte/src/ContextualHelp.svelte
<script lang="ts">
  import { invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    label?: string;
    title?: string;
    description?: string;
    message?: string;
    caption?: string;
    position?: string;
    href?: string;
    linkLabel?: string;
    closeLabel?: string;
    open?: boolean;
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    label = '레이블',
    title = '제목',
    description = '',
    message = '도움말',
    caption = '',
    position = 'top',
    href = '#',
    linkLabel = '',
    closeLabel = '',
    open = $bindable<boolean | undefined>(),
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
</script>

<div {...rest} class={`krds-contextual-help ${position.split('-').reverse().join(' ')} ${rootClass}`}>
  {#if caption}<p class="tooltip-txt">{caption}</p>{/if}
  <div class="tooltip-action">
    <button
      class="icon krds-btn medium tooltip-btn"
      type="button"
      aria-expanded={isOpen}
      aria-controls={`${id}-popover`}
      onclick={() => toggleOpen()}
    >
      <span class="sr-only">{label}</span>
      <i class="ico-tooltip svg-icon"></i>
    </button>
    <div class="tooltip-popover" id={`${id}-popover`} role="tooltip">
      <h4 class="tooltip-title">{title}</h4>
      <div class="tooltip-contents">
        <p>{description || message}</p>
        {#if linkLabel}<div class="btn-wrap"><a class="basic krds-btn link xsmall" href={href}>{linkLabel}<i class="ico-angle right svg-icon"></i></a></div>{/if}
      </div>
      <button class="icon krds-btn tooltip-close xsmall" type="button" onclick={() => toggleOpen()}>
        <span class="sr-only">{closeLabel}</span>
        <i class="ico-modal-close svg-icon"></i>
      </button>
    </div>
  </div>
</div>
