// packages/react/src/components/Disclosure.tsx
import {
  useId,
  useState,
  type HTMLAttributes,
  type MouseEventHandler,
  type ReactNode,
} from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface DisclosureProps
  extends
    Omit<BoxProps, "id" | "items" | "open">,
    Omit<HTMLAttributes<HTMLDivElement>, "children" | "title" | "onToggle" | "className"> {
  title: ReactNode;
  items?: ReactNode[];
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  onToggle?: MouseEventHandler<HTMLButtonElement>;
}
export function Disclosure({
  title,
  items,
  open: controlledOpen,
  defaultOpen = false,
  onOpenChange,
  onToggle,
  children,
  id: providedId,
  className,
  ...props
}: DisclosureProps) {
  const generatedId = useId();
  const panelId = providedId ?? `krds-disclosure-${generatedId}`;
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const open = controlledOpen ?? uncontrolledOpen;
  return (
    <div {...props} className={cx("krds-disclosure", "conts-expand-area", open && "active", className)}>
      <button
        id={`${panelId}-trigger`}
        type="button"
        className="btn-conts-expand"
        aria-controls={panelId}
        aria-expanded={open}
        onClick={(event) => {
          const next = !open;
          onToggle?.(event);
          if (event.defaultPrevented) return;
          if (controlledOpen === undefined) setUncontrolledOpen(next);
          onOpenChange?.(next);
        }}
      >
        {title}
      </button>
      <div
        id={panelId}
        className="expand-wrap"
        role="region"
        aria-labelledby={`${panelId}-trigger`}
        inert={!open}
      >
        <div className="expand-in">
          {items ? (
            <ul className="krds-info-list dash" role="list">
              {items.map((item, index) => (
                <li role="listitem" key={index}>
                  {item}
                </li>
              ))}
            </ul>
          ) : (
            children
          )}
        </div>
      </div>
    </div>
  );
}

// packages/svelte/src/Disclosure.svelte
<script lang="ts">
  import { inertWhen, labelOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    title?: string;
    open?: boolean;
    description?: string;
    items?: unknown[];
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    title = '제목',
    open = $bindable<boolean | undefined>(),
    description = '',
    items = [] as unknown[],
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
</script>

<div {...rest} class={`conts-expand-area krds-disclosure ${rootClass}`} class:active={isOpen}>
  <button
    id={`${id}-trigger`}
    class="btn-conts-expand"
    type="button"
    aria-controls={`${id}-content`}
    aria-expanded={isOpen}
    onclick={() => toggleOpen()}
  >{title}</button>
  <div
    class="expand-wrap"
    id={`${id}-content`}
    role="region"
    aria-labelledby={`${id}-trigger`}
    use:inertWhen={!isOpen}
  >
    <div class="expand-in">
      {#if items.length}
        <ul class="dash krds-info-list" role="list">
          {#each items as item}<li role="listitem">{labelOf(item)}</li>{/each}
        </ul>
      {:else if children}
        {@render children()}
      {:else}
        {description}
      {/if}
    </div>
  </div>
</div>
