// packages/angular/src/components/disclosure.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId, type AngularNavItem } from "../kinds";

@Component({
  selector: "krds-disclosure",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [":host { display: contents; }"],
  template: `
    <div class="krds-disclosure conts-expand-area" [class.active]="open">
      <button
        [id]="id + '-trigger'"
        type="button"
        class="btn-conts-expand"
        [attr.aria-controls]="id + '-contents'"
        [attr.aria-expanded]="open"
        (click)="open = !open"
      >
        {{ title }}
      </button>
      <div
        class="expand-wrap"
        [id]="id + '-contents'"
        [attr.aria-labelledby]="id + '-trigger'"
        role="region"
        [attr.inert]="!open ? '' : null"
      >
        <div class="expand-in">
          @if (items.length > 0) {
            <ul class="krds-info-list dash" role="list">
              @for (item of items; track $index) {
                <li role="listitem">{{ navLabel(item) }}</li>
              }
            </ul>
          } @else {
            <ng-content></ng-content>
          }
        </div>
      </div>
    </div>
  `,
})
export class KrdsDisclosureComponent {
  @Input() id = createStableId("krds-disclosure");
  @Input() title = "제목";
  @Input() open = false;
  @Input() items: (AngularNavItem | string)[] = [];

  navLabel(item: unknown): string {
    if (typeof item === "string" || typeof item === "number") return String(item);
    if (!item || typeof item !== "object") return "";
    if ("label" in item) return String((item as { label?: unknown }).label ?? "");
    if ("title" in item) return String((item as { title?: unknown }).title ?? "");
    if ("text" in item) return String((item as { text?: unknown }).text ?? "");
    if ("message" in item) return String((item as { message?: unknown }).message ?? "");
    return "";
  }
}

// packages/svelte/src/Disclosure.svelte
<script lang="ts">
  import { inertWhen, labelOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    title?: string;
    open?: boolean;
    description?: string;
    items?: unknown[];
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    title = '제목',
    open = $bindable<boolean | undefined>(),
    description = '',
    items = [] as unknown[],
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
</script>

<div {...rest} class={`conts-expand-area krds-disclosure ${rootClass}`} class:active={isOpen}>
  <button
    id={`${id}-trigger`}
    class="btn-conts-expand"
    type="button"
    aria-controls={`${id}-content`}
    aria-expanded={isOpen}
    onclick={() => toggleOpen()}
  >{title}</button>
  <div
    class="expand-wrap"
    id={`${id}-content`}
    role="region"
    aria-labelledby={`${id}-trigger`}
    use:inertWhen={!isOpen}
  >
    <div class="expand-in">
      {#if items.length}
        <ul class="dash krds-info-list" role="list">
          {#each items as item}<li role="listitem">{labelOf(item)}</li>{/each}
        </ul>
      {:else if children}
        {@render children()}
      {:else}
        {description}
      {/if}
    </div>
  </div>
</div>
