// packages/angular/src/components/help-panel.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-help-panel",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-help-panel" [class.expand]="open">
      <div class="help-panel-wrap" [attr.tabindex]="open ? '0' : null">
        <div class="help-conts-area">
          <div class="krds-tab-area layer">
            <div class="tab line">
              <ul role="tablist">
                @for (tab of tabs; track tab.id) {
                  <li role="presentation" [class.active]="helpTabValue(tab) === activeTab">
                    <button
                      [id]="tab.id"
                      type="button"
                      class="btn-tab"
                      role="tab"
                      [attr.aria-selected]="helpTabValue(tab) === activeTab"
                      [attr.aria-controls]="helpTabPanelId(tab)"
                      [attr.tabindex]="helpTabValue(tab) === activeTab ? '0' : '-1'"
                      (click)="setActiveTab(helpTabValue(tab))"
                    >
                      {{ tab.label }}
                      @if (helpTabValue(tab) === activeTab) {
                        <i class="sr-only created"> {{ selectedLabel }}</i>
                      }
                    </button>
                  </li>
                }
              </ul>
            </div>
            <div class="tab-conts-wrap">
              @if (tabs[0]) {
                <section
                  [id]="helpTabPanelId(tabs[0])"
                  role="tabpanel"
                  [attr.aria-labelledby]="tabs[0].id"
                  class="tab-conts"
                  [class.active]="helpTabValue(tabs[0]) === activeTab"
                  [hidden]="helpTabValue(tabs[0]) !== activeTab"
                >
                  <h3 class="sr-only">{{ tabs[0].label }}</h3>
                  <div class="help-conts-area-inner">
                    <div class="conts-area help-conts">
                      <div class="conts-wrap">
                        <h4 class="help-title">
                          {{ helpTitle }}
                          <span class="krds-btn medium icon">
                            <span class="sr-only">{{ label }}</span>
                            <i class="svg-icon ico-help"></i>
                          </span>
                        </h4>
                        <div class="conts-desc">
                          <p>{{ helpDescription }}</p>
                        </div>
                        <ul class="link-list">
                          @for (link of downloadLinks; track $index) {
                            <li>
                              <a
                                [href]="link.href"
                                [attr.target]="link.target || null"
                                [attr.title]="link.title || null"
                                class="krds-btn xsmall link basic"
                              >
                                {{ link.label }} <i class="svg-icon ico-go"></i>
                              </a>
                            </li>
                          }
                        </ul>
                      </div>
                    </div>
                    <div class="conts-area related-service">
                      @for (group of relatedGroups; track $index) {
                        <div class="conts-wrap">
                          <h4 class="help-title">{{ group.title }}</h4>
                          <ul class="link-list">
                            @for (link of group.links; track $index) {
                              <li>
                                <a [href]="link.href" class="krds-btn xsmall link basic">
                                  @if (link.icon) {
                                    <i [class]="'svg-icon ico-' + link.icon"></i>
                                  }
                                  {{ link.label }}
                                  @if (!link.icon) {
                                    <i class="svg-icon ico-angle right"></i>
                                  }
                                </a>
                              </li>
                            }
                          </ul>
                        </div>
                      }
                    </div>
                  </div>
                </section>
              }
              @if (tabs[1]) {
                <section
                  [id]="helpTabPanelId(tabs[1])"
                  role="tabpanel"
                  [attr.aria-labelledby]="tabs[1].id"
                  class="tab-conts"
                  [class.active]="helpTabValue(tabs[1]) === activeTab"
                  [hidden]="helpTabValue(tabs[1]) !== activeTab"
                >
                  <h3 class="sr-only">{{ tabs[1].label }}</h3>
                  <div class="help-conts-area-inner">
                    <div class="conts-area">
                      <h4 class="help-title">
                        <a href="#;" [attr.title]="tutorialBackTitle">{{ tutorialTitle }}</a>
                      </h4>
                      <ul class="coach-help-process">
                        @for (task of tasks; track $index; let taskIndex = $index) {
                          <li>
                            <h4 class="tit" [class.current]="task.current">{{ task.title }}</h4>
                            <div class="krds-disclosure conts-expand-area">
                              <button
                                type="button"
                                class="btn-conts-expand"
                                [attr.aria-controls]="helpDisclosureId(taskIndex)"
                                aria-expanded="false"
                              >
                                {{ task.summary }}
                              </button>
                              <div class="expand-wrap" [id]="helpDisclosureId(taskIndex)" inert>
                                <div class="expand-in">
                                  <ul class="krds-info-list decimal" role="list">
                                    @for (step of task.steps; track $index) {
                                      <li role="listitem">{{ step }}</li>
                                    }
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </li>
                        }
                      </ul>
                    </div>
                    <div class="help-panel-action">
                      <button type="button" class="krds-btn medium secondary coach-btn-stop">
                        {{ stopLabel }}
                      </button>
                    </div>
                  </div>
                </section>
              }
            </div>
          </div>
          <button
            type="button"
            class="krds-btn small tertiary btn-help-panel fold"
            (click)="open = false"
          >
            <span class="sr-only">{{ label }}</span> {{ collapseLabel }}
            <i class="svg-icon ico-angle right"></i>
          </button>
        </div>
      </div>
    </div>
  `,
})
export class KrdsHelpPanelComponent {
  @Input() id = createStableId("krds-help-panel");
  @Input() open = false;
  @Input() label = "레이블";
  @Input() selectedLabel = "";
  @Input() collapseLabel = "";
  @Input() helpTitle = "";
  @Input() helpDescription = "";
  @Input() tutorialTitle = "";
  @Input() tutorialBackTitle = "";
  @Input() stopLabel = "";
  @Input() activeTab = "";
  @Input() tabs: Array<{ id: string; label: string; panelId?: string; value?: string }> = [];
  @Output() activeTabChange = new EventEmitter<string>();
  @Input() downloadLinks: Array<{ label: string; href: string; target?: string; title?: string }> =
    [];
  @Input() relatedGroups: Array<{
    title: string;
    links: Array<{ label: string; href: string; icon?: string }>;
  }> = [];
  @Input() tasks: Array<{
    title: string;
    current?: boolean;
    summary: string;
    steps: string[];
  }> = [];

  helpTabValue(tab: { id: string; value?: string }): string {
    return tab.value ?? tab.id;
  }

  helpTabPanelId(tab: { id: string; panelId?: string }): string {
    return tab.panelId ?? `${tab.id}-panel`;
  }

  helpDisclosureId(index: number): string {
    return `${this.id}-disclosure-${index}`;
  }

  setActiveTab(value: string): void {
    this.activeTab = value;
    this.activeTabChange.emit(value);
  }
}

// packages/svelte/src/HelpPanel.svelte
<script lang="ts">
  import type { KrdsNavItem } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf, labelOf, hrefOf, listOf, invoke, flagOf } from './lib/shared.js';

  type Props = {
    title?: string;
id?: string;
    tabs?: { id: string; label: string; panelId?: string }[];
    activeTab?: 'help' | 'tutorial';
    selectedLabel?: string;
    label?: string;
    helpTitle?: string;
    helpDescription?: string;
    downloadLinks?: KrdsNavItem[];
    relatedGroups?: Record<string, unknown>[];
    tutorialTitle?: string;
    backTitle?: string;
    tutorialBackTitle?: string;
    tasks?: Record<string, unknown>[];
    stopLabel?: string;
    externalTitle?: string;
    open?: boolean;
    collapseLabel?: string;
    onclick?: (event: Event) => void;
    children?: Snippet;
    class?: string;
    className?: string;
  } & Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-help-panel',
    tabs = [],
    activeTab = $bindable<'help' | 'tutorial'>('help'),
    selectedLabel = '',
    label = '',
    title,
    helpTitle = '',
    helpDescription = '',
    downloadLinks = [],
    relatedGroups = [],
    tutorialTitle = '',
    backTitle = '',
    tutorialBackTitle = '',
    tasks = [],
    stopLabel = '',
    externalTitle = '',
    open = $bindable<boolean | undefined>(),
    collapseLabel = '',
    onclick,
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);

  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event) invoke(onclick, event);
  };
</script>

<div
  {...rest}
  class={`krds-help-panel ${isOpen ? 'expand' : ''} ${rootClass}`}
  hidden={!isOpen}
>
  <div class="help-panel-wrap" tabindex={isOpen ? 0 : undefined}>
    <div class="help-conts-area">
      <div class="krds-tab-area layer">
        <div class="tab line">
          <ul role="tablist">
            {#each tabs as tab, index}
              {@const tabName = index === 0 ? 'help' : 'tutorial'}
              <li role="presentation" class:active={activeTab === tabName}>
                <button
                  id={tab.id}
                  type="button"
                  class="btn-tab"
                  role="tab"
                  aria-selected={activeTab === tabName}
                  aria-controls={fieldOf(tab, 'panelId')}
                  tabindex={activeTab === tabName ? 0 : -1}
                  onclick={(event) => {
                    activeTab = tabName;
                    invoke(onclick, event);
                  }}
                >
                  {tab.label}
                  {#if activeTab === tabName}<i class="sr-only created"> {selectedLabel}</i>{/if}
                </button>
              </li>
            {/each}
          </ul>
        </div>
        <div class="tab-conts-wrap">
          {#each tabs as tab, index}
            {@const tabName = index === 0 ? 'help' : 'tutorial'}
            <section
              id={fieldOf(tab, 'panelId')}
              role="tabpanel"
              aria-labelledby={tab.id}
              class="tab-conts"
              class:active={activeTab === tabName}
              hidden={activeTab !== tabName}
            >
              {#if tab.label}<h3 class="sr-only">{tab.label}</h3>{/if}
              <div class="help-conts-area-inner">
                {#if tabName === 'help'}
                  <div class="conts-area help-conts">
                    <div class="conts-wrap">
                      <h4 class="help-title">
                        {helpTitle}
                        <span class="krds-btn medium icon">
                          <span class="sr-only">{label}</span>
                          <i class="svg-icon ico-help"></i>
                        </span>
                      </h4>
                      <div class="conts-desc"><p>{helpDescription}</p></div>
                      <ul class="link-list">
                        {#each downloadLinks as item}
                          <li>
                            <a
                              href={hrefOf(item)}
                              target={fieldOf(item, 'target') || undefined}
                              title={fieldOf(item, 'title') || externalTitle || undefined}
                              class="krds-btn xsmall link basic"
                            >
                              {labelOf(item)} <i class="svg-icon ico-go"></i>
                            </a>
                          </li>
                        {/each}
                      </ul>
                    </div>
                  </div>
                  <div class="conts-area related-service">
                    {#each relatedGroups as group}
                      <div class="conts-wrap">
                        <h4 class="help-title">{fieldOf(group, 'title')}</h4>
                        <ul class="link-list">
                          {#each listOf(group, 'links') as item}
                            <li>
                              <a href={hrefOf(item)} class="krds-btn xsmall link basic">
                                {#if fieldOf(item, 'icon')}<i class={`svg-icon ico-${fieldOf(item, 'icon')}`}></i>{/if}
                                {labelOf(item)}
                                {#if !fieldOf(item, 'icon')}<i class="svg-icon ico-angle right"></i>{/if}
                              </a>
                            </li>
                          {/each}
                        </ul>
                      </div>
                    {/each}
                  </div>
                {:else}
                  <div class="conts-area">
                    <h4 class="help-title">
                      <a href="#;" title={tutorialBackTitle || backTitle || undefined}>
                        {tutorialTitle}
                      </a>
                    </h4>
                    <ul class="coach-help-process">
                      {#each tasks as task, taskIndex}
                        <li>
                          <h4 class="tit" class:current={flagOf(task, 'current')}>
                            {fieldOf(task, 'title')}
                          </h4>
                          <div class="krds-disclosure conts-expand-area">
                            <button
                              type="button"
                              class="btn-conts-expand"
                              aria-label={fieldOf(task, 'summary') || fieldOf(task, 'title') || undefined}
                              aria-controls={`${id}-help-disclosure-${taskIndex}`}
                              aria-expanded="false"
                            >
                              {fieldOf(task, 'summary')}
                            </button>
                            <div
                              class="expand-wrap"
                              id={`${id}-help-disclosure-${taskIndex}`}
                              inert
                            >
                              <div class="expand-in">
                                <ul class="krds-info-list decimal" role="list">
                                  {#each listOf(task, 'steps') as taskStep}
                                    <li role="listitem">{labelOf(taskStep)}</li>
                                  {/each}
                                </ul>
                              </div>
                            </div>
                          </div>
                        </li>
                      {/each}
                    </ul>
                  </div>
                  <div class="help-panel-action">
                    <button type="button" class="krds-btn medium secondary coach-btn-stop">
                      {stopLabel}
                    </button>
                  </div>
                {/if}
              </div>
            </section>
          {/each}
        </div>
      </div>
      <button
        type="button"
        class="krds-btn small tertiary btn-help-panel fold"
        onclick={toggleOpen}
      >
        <span class="sr-only">{label}</span> {collapseLabel}
        <i class="svg-icon ico-angle right"></i>
      </button>
    </div>
  </div>
</div>
