// packages/solid/src/components/Infobox.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface InfoboxProps {
  class?: string;
  className?: string;
  type?: "primary" | "secondary";
  size?: "default" | "slim";
  message: JSX.Element;
  ariaLabel?: string;
  [key: string]: unknown;
}

export function Infobox(rawProps: InfoboxProps) {
  const merged = mergeProps({ type: "primary" as const, size: "default" as const }, rawProps);
  const [props, native] = splitProps(merged, ["class", "className", "type", "size", "message", "ariaLabel"]);

  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-infobox ${props.type} ${props.size}${className() ? ` ${className()}` : ""}`}
      role="region"
      aria-label={props.ariaLabel ?? "알림"}
    >
      <p class="infobox-text">{props.message}</p>
    </div>
  );
}

// packages/svelte/src/Infobox.svelte
<script lang="ts">
  type Props = {
    type?: 'primary' | 'secondary';
    size?: 'default' | 'slim';
    message: string;
    ariaLabel?: string;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    type = 'primary',
    size = 'default',
    message,
    ariaLabel = '알림',
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div {...rest} class={`krds-infobox ${type} ${size} ${rootClass}`} role="region" aria-label={ariaLabel}>
  <p class="infobox-text">{message}</p>
</div>
