// packages/react/src/components/Infobox.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface InfoboxProps extends BoxProps {
  type?: "primary" | "secondary";
  size?: "default" | "slim";
  message: ReactNode;
  "aria-label"?: string;
}

export function Infobox({
  type = "primary",
  size = "default",
  message,
  "aria-label": ariaLabel,
  className,
}: InfoboxProps) {
  return (
    <div
      className={cx("krds-infobox", type, size, className)}
      role="region"
      aria-label={ariaLabel ?? "알림"}
    >
      <p className="infobox-text">{message}</p>
    </div>
  );
}

// packages/svelte/src/Infobox.svelte
<script lang="ts">
  type Props = {
    type?: 'primary' | 'secondary';
    size?: 'default' | 'slim';
    message: string;
    ariaLabel?: string;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    type = 'primary',
    size = 'default',
    message,
    ariaLabel = '알림',
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div {...rest} class={`krds-infobox ${type} ${size} ${rootClass}`} role="region" aria-label={ariaLabel}>
  <p class="infobox-text">{message}</p>
</div>
