// packages/solid/src/components/InPageNavigation.tsx
import { For, mergeProps, splitProps } from "solid-js";
import type { KrdsNavItem } from "@krds-community/recipes";

export interface InPageNavigationProps {
  class?: string;
  className?: string;
  title?: string;
  pageTitle?: string;
  actionLabel?: string;
  actionInfo?: string;
  actionCount?: string;
  nav?: KrdsNavItem[];
  links?: KrdsNavItem[];
  items?: (KrdsNavItem | string | number)[];
  [key: string]: unknown;
}

export function InPageNavigation(rawProps: InPageNavigationProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "pageTitle",
    "actionLabel",
    "actionInfo",
    "actionCount",
    "nav",
    "links",
    "items",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const navigation = () =>
    (props.nav?.length
      ? props.nav
      : props.links?.length
        ? props.links
        : (props.items ?? []).filter(
            (item): item is KrdsNavItem => typeof item !== "string" && typeof item !== "number",
          )) as KrdsNavItem[];
  return (
    <div class="krds-in-page-navigation-type">
      <div
        {...(native as Record<string, any>)}
        class={`krds-in-page-navigation-area${className() ? ` ${className()}` : ""}`}
      >
        <div class="in-page-navigation-header">
          <p class="quick-caption">{props.title}</p>
          <p class="quick-title">{props.pageTitle}</p>
        </div>
        <nav class="in-page-navigation-list" aria-label={props.title || undefined}>
          <ul>
            <For each={navigation()}>
              {(item) => (
                <li>
                  <a href={item.href ?? "#"} classList={{ active: item.current }}>
                    {item.label}
                  </a>
                </li>
              )}
            </For>
          </ul>
        </nav>
        <div class="in-page-navigation-action">
          <button type="button" class="krds-btn medium">
            {props.actionLabel}
          </button>
          <p class="quick-info">
            {props.actionInfo} <strong>{props.actionCount}</strong>
          </p>
        </div>
      </div>
    </div>
  );
}

// packages/svelte/src/InPageNavigation.svelte
<script lang="ts">
  import { labelOf, hrefOf, flagOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    title?: string;
    pageTitle?: string;
    items?: unknown[];
    links?: unknown[];
    nav?: unknown[];
    actionLabel?: string;
    actionInfo?: string;
    actionCount?: string;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    title = '',
    pageTitle = '',
    items = [] as unknown[],
    links = [] as unknown[],
    nav = [] as unknown[],
    actionLabel = '',
    actionInfo = '',
    actionCount = '',
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const navigationItems = $derived(items.length ? items : links.length ? links : nav);
</script>

<div class="krds-in-page-navigation-type">
  <div {...rest} class={`krds-in-page-navigation-area ${rootClass}`}>
    <div class="in-page-navigation-header">
      <p class="quick-caption">{title}</p>
      <p class="quick-title">{pageTitle}</p>
    </div>
    <nav class="in-page-navigation-list" aria-label={title || undefined}>
      <ul>
        {#each navigationItems as item}
          <li><a class:active={flagOf(item, 'current')} href={hrefOf(item)}>{labelOf(item)}</a></li>
        {/each}
      </ul>
    </nav>
    <div class="in-page-navigation-action">
      <button class="krds-btn medium" type="button">{actionLabel}</button>
      <p class="quick-info">{actionInfo} <strong>{actionCount}</strong></p>
    </div>
  </div>
</div>
