// packages/solid/src/components/LanguageSwitcher.tsx
import { For, Show, createSignal, createUniqueId, mergeProps, splitProps } from "solid-js";
import type { KrdsOption } from "@krds-community/recipes";

export interface LanguageSwitcherProps {
  class?: string;
  className?: string;
  label?: string;
  open?: boolean;
  currentLabel?: string;
  selected?: string;
  selectedLabel?: string;
  externalTitle?: string;
  defaultValue?: string;
  value?: string;
  modelValue?: string;
  options?: KrdsOption[];
  languages?: KrdsOption[];
  [key: string]: unknown;
}

function LanguageSwitcherInner(rawProps: LanguageSwitcherProps, isPage: boolean) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "label",
    "open",
    "currentLabel",
    "selected",
    "selectedLabel",
    "externalTitle",
    "defaultValue",
    "value",
    "modelValue",
    "options",
    "languages",
  ]);
  const [localOpen, setLocalOpen] = createSignal(false);
  const open = () => (props.open !== undefined ? Boolean(props.open) : localOpen());
  const setOpen = (next: boolean) => {
    if (props.open === undefined) setLocalOpen(next);
  };
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "string" || typeof mv === "number") return String(mv);
    return props.selected ?? localSelected() ?? props.defaultValue ?? optionItems()[0]?.value ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const optionItems = () => props.languages ?? props.options ?? [];
  const dropMenuId = `krds-language-drop-${createUniqueId()}`;
  return (
    <div
      {...(native as Record<string, any>)}
      class={["krds-drop-wrap", "krds-language", className()].filter(Boolean).join(" ")}
    >
      <button
        type="button"
        class="krds-btn small text drop-btn"
        aria-expanded={open()}
        aria-controls={dropMenuId}
        onClick={() => setOpen(!open())}
      >
        <i class="svg-icon ico-global" /> {props.label} <i class="svg-icon ico-toggle" />
      </button>
      <div class="drop-menu" id={dropMenuId} style={{ display: open() ? "block" : undefined }}>
        <div class="drop-in">
          <Show when={isPage}>
            <div class="drop-top">
              <p class="current-laguage">
                <span>{props.currentLabel}</span>
                <strong>
                  {optionItems().find((option) => option.value === selected())?.label}
                </strong>
              </p>
            </div>
          </Show>
          <ul class="drop-list">
            <For
              each={
                isPage
                  ? optionItems().filter((option) => option.value !== selected())
                  : optionItems()
              }
            >
              {(option) => {
                const language = option as KrdsOption & {
                  href?: string;
                  lang?: string;
                  target?: string;
                  title?: string;
                };
                return (
                  <li>
                    <a
                      href={language.href ?? "#"}
                      class="item-link"
                      classList={{ active: !isPage && selected() === language.value }}
                      lang={language.lang ?? language.value}
                      target={isPage ? (language.target ?? "_blank") : language.target}
                      title={isPage ? (language.title ?? props.externalTitle) : language.title}
                      onClick={(event) => {
                        setSelected(language.value);
                        (native as Record<string, any>).onChange?.(event);
                      }}
                    >
                      {language.label}
                      <Show when={isPage}>
                        <i class="svg-icon ico-go" />
                      </Show>
                      <span class="sr-only">
                        {!isPage && selected() === language.value ? props.selectedLabel : undefined}
                      </span>
                    </a>
                  </li>
                );
              }}
            </For>
          </ul>
        </div>
      </div>
    </div>
  );
}

export function LanguageSwitcher(rawProps: LanguageSwitcherProps) {
  return LanguageSwitcherInner(rawProps, false);
}

export function LanguageSwitcherPage(rawProps: LanguageSwitcherProps) {
  return LanguageSwitcherInner(rawProps, true);
}

// packages/svelte/src/LanguageSwitcher.svelte
<script lang="ts">
  import { fieldOf, flagOf, invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    label?: string;
    kind?: 'default' | 'page' | string;
    open?: boolean;
    languages?: unknown[];
    options?: unknown[];
    selected?: string;
    modelValue?: string;
    defaultValue?: string;
    selectedLabel?: string;
    currentLabel?: string;
    externalTitle?: string;
    onclick?: (event: Event) => void;
    onchange?: (event: Event) => void;
    className?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    label = '레이블',
    kind = 'default',
    open = $bindable<boolean | undefined>(),
    languages = [],
    options = [],
    selected = $bindable<string | undefined>(),
    modelValue = $bindable<string | undefined>(),
    defaultValue = '',
    selectedLabel = '',
    currentLabel = '',
    externalTitle = '새 창 열림',
    onclick,
    onchange,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const languageItems = $derived(languages.length ? languages : options);
  const selection = $derived(
    modelValue !== undefined
      ? String(modelValue)
      : selected !== undefined
        ? selected
      : defaultValue || fieldOf(languageItems[0], 'value'),
  );
  const currentLanguage = $derived(languageItems.find((language) => fieldOf(language, 'value') === selection));
  const isOpen = $derived(open ?? false);
  const isPage = $derived(kind === 'page');
  const visibleLanguages = $derived(
    isPage ? languageItems.filter((language) => fieldOf(language, 'value') !== selection) : languageItems,
  );
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
  const setSelection = (next: string, event?: Event) => {
    selected = next;
    modelValue = next;
    open = false;
    if (event) invoke(onchange, event);
  };

</script>

<div {...rest} class={`krds-drop-wrap krds-language ${rootClass}`.trim()}>
  <button
    class="krds-btn small text drop-btn"
    class:active={isOpen}
    type="button"
    aria-expanded={isOpen}
    aria-controls={`${id}-menu`}
    onclick={() => toggleOpen()}
  ><i class="svg-icon ico-global"></i>{' '}{label}{' '}<i class="svg-icon ico-toggle"></i></button>
  <div class="drop-menu" id={`${id}-menu`}>
    <div class="drop-in">
      {#if isPage}
        <div class="drop-top">
          <p class="current-laguage">
            <span>{currentLabel}</span>
            <strong>{fieldOf(currentLanguage, 'label')}</strong>
          </p>
        </div>
      {/if}
      <ul class="drop-list">
        {#each visibleLanguages as language}
          {@const value = fieldOf(language, 'value')}
          {@const external = isPage || flagOf(language, 'external') || fieldOf(language, 'target') === '_blank'}
          {@const target = fieldOf(language, 'target') || (external ? '_blank' : '')}
          {@const title = fieldOf(language, 'title') || (external ? externalTitle : '')}
          <li>
            <a
              class="item-link"
              class:active={!isPage && selection === value}
              href={fieldOf(language, 'href') || './'}
              lang={fieldOf(language, 'lang') || value}
              target={target || undefined}
              title={title || undefined}
              aria-disabled={flagOf(language, 'disabled') || undefined}
              onclick={(event: Event) => {
                event.preventDefault();
                if (!flagOf(language, 'disabled')) setSelection(value, event);
              }}
            >
              {fieldOf(language, 'label')}
              {#if isPage}<i class="svg-icon ico-go"></i>{/if}
              <span class="sr-only">{!isPage && selection === value ? selectedLabel : ''}</span>
            </a>
          </li>
        {/each}
      </ul>
    </div>
  </div>
</div>
