// packages/react/src/components/MainMenuPc.tsx
import { useId, useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx, type KrdsNavItem } from "@krds-community/recipes";
import { SvgIcon } from "./_utils.js";

interface MainMenuDescriptionItem {
  title: ReactNode;
  description?: ReactNode;
  href?: string;
  target?: string;
  externalTitle?: string;
}
interface MainMenuBanner {
  badge?: ReactNode;
  label?: ReactNode;
}
export interface MainMenuItem extends Omit<KrdsNavItem, "children" | "title"> {
  active?: boolean;
  button?: boolean;
  target?: string;
  title?: string;
  titleHref?: string;
  titleLinkLabel?: ReactNode;
  descriptionItems?: MainMenuDescriptionItem[];
  banner?: MainMenuBanner;
  children?: MainMenuItem[];
}

function MainMenuBannerView({ banner }: { banner?: MainMenuBanner }) {
  return banner ? (
    <div className="gnb-sub-banner">
      {banner.badge ? <span className="krds-badge bg-secondary">{banner.badge}</span> : null}
      {banner.label ? (
        <button type="button" className="krds-btn medium text">
          {banner.label}
          <SvgIcon name="ico-angle right" />
        </button>
      ) : null}
    </div>
  ) : null;
}
export interface MainMenuPcProps extends Omit<HTMLAttributes<HTMLElement>, "children"> {
  items?: MainMenuItem[];
  menuLabel?: string;
  sample?: boolean;
  onItemChange?: (id: string) => void;
}
export function MainMenuPc({
  items = [],
  menuLabel,
  sample = true,
  className,
  onItemChange,
  "aria-label": ariaLabel,
  ref,
  ...props
}: MainMenuPcProps & { ref?: Ref<HTMLElement> }) {
  const generatedId = useId();
  const [openTop, setOpenTop] = useState<number | undefined>(() => {
    const activeIndex = items.findIndex((item) => item.active);
    return activeIndex >= 0 ? activeIndex : undefined;
  });
  const [openSubs, setOpenSubs] = useState<Record<string, number | undefined>>(() =>
    Object.fromEntries(
      items.map((item, index) => {
        const activeIndex = item.children?.findIndex((child) => child.active) ?? -1;
        const firstTriggerIndex = item.children?.findIndex((child) => !child.href) ?? -1;
        const initialIndex = activeIndex >= 0 ? activeIndex : sample ? -1 : firstTriggerIndex;
        return [item.id ?? String(index), initialIndex >= 0 ? initialIndex : undefined];
      }),
    ),
  );
  const renderSubContent = (item: MainMenuItem) => (
    <>
      <div className="gnb-sub-content">
        {item.title ? (
          <h2 className="sub-title">
            {item.titleHref ? (
              <>
                {item.title}
                <a href={item.titleHref} className="krds-btn link basic small">
                  <span className="underline">{item.titleLinkLabel}</span>
                  <SvgIcon name="ico-angle right" />
                </a>
              </>
            ) : (
              <span>{item.title}</span>
            )}
          </h2>
        ) : null}
        {item.descriptionItems?.length ? (
          <ul className="type-description">
            {item.descriptionItems.map((description, index) => (
              <li key={index}>
                <h3 className="tit">
                  <a
                    href={description.href ?? "#"}
                    target={description.target}
                    title={description.externalTitle}
                  >
                    {description.title}
                    {description.target ? <SvgIcon name="ico-go" /> : null}
                  </a>
                </h3>
                {description.description ? <p className="txt">{description.description}</p> : null}
              </li>
            ))}
          </ul>
        ) : item.children?.length ? (
          <ul>
            {item.children.map((child) => (
              <li key={child.id ?? child.label}>
                {child.href ? (
                  <a href={child.href}>{child.label}</a>
                ) : (
                  <button type="button">{child.label}</button>
                )}
              </li>
            ))}
          </ul>
        ) : null}
      </div>
      {item.banner ? <MainMenuBannerView banner={item.banner} /> : null}
    </>
  );
  return (
    <nav
      {...props}
      ref={ref}
      aria-label={ariaLabel ?? (sample ? undefined : menuLabel)}
      className={cx("krds-main-menu", sample && "sample", className)}
    >
      <div className="inner">
        <ul className="gnb-menu" aria-label={sample ? undefined : menuLabel}>
          {items.map((item, topIndex) => {
            if (item.href) {
              return (
                <li key={item.id ?? item.label}>
                  <a
                    href={item.href}
                    className="gnb-main-trigger is-link"
                    data-trigger="gnb"
                    target={item.target}
                    title={item.title}
                  >
                    {item.label}
                  </a>
                </li>
              );
            }
            if (item.button) {
              return (
                <li key={item.id ?? item.label}>
                  <button type="button" className="gnb-main-trigger is-link" data-trigger="gnb">
                    {item.label}
                  </button>
                </li>
              );
            }
            const topKey = item.id ?? String(topIndex);
            const topOpen = openTop === topIndex;
            const single = Boolean(item.title);
            const mainPanelId = `${generatedId}-main-${topIndex}`;
            return (
              <li key={item.id ?? item.label}>
                <button
                  type="button"
                  className={cx("gnb-main-trigger", topOpen && "active")}
                  data-trigger="gnb"
                  aria-controls={sample ? undefined : mainPanelId}
                  aria-expanded={sample ? undefined : topOpen}
                  aria-haspopup={sample ? undefined : true}
                  onClick={() => {
                    const next = topOpen ? undefined : topIndex;
                    setOpenTop(next);
                    if (next !== undefined) onItemChange?.(topKey);
                  }}
                >
                  {item.label}
                </button>
                <div
                  id={sample ? undefined : mainPanelId}
                  className={cx("gnb-toggle-wrap", topOpen && "is-open")}
                >
                  <div className="gnb-main-list" data-has-submenu={single ? undefined : "true"}>
                    {single ? (
                      <div className="gnb-sub-list single-list between">
                        {renderSubContent(item)}
                      </div>
                    ) : (
                      <ul>
                        {item.children?.map((subItem, subIndex) => {
                          if (subItem.href) {
                            return (
                              <li key={subItem.id ?? subItem.label}>
                                <a
                                  href={subItem.href}
                                  className={cx(
                                    "gnb-sub-trigger",
                                    "is-link",
                                    subItem.target && "external-link",
                                  )}
                                  data-trigger="gnb"
                                  target={subItem.target}
                                  title={subItem.title}
                                >
                                  {subItem.label}
                                </a>
                              </li>
                            );
                          }
                          const subOpen = openSubs[topKey] === subIndex;
                          const subPanelId = `${generatedId}-sub-${topIndex}-${subIndex}`;
                          return (
                            <li key={subItem.id ?? subItem.label}>
                              <button
                                type="button"
                                className={cx("gnb-sub-trigger", subOpen && "active")}
                                data-trigger="gnb"
                                aria-controls={sample ? undefined : subPanelId}
                                aria-expanded={sample ? undefined : subOpen}
                                aria-haspopup={sample ? undefined : true}
                                onClick={() => {
                                  setOpenSubs((current) => ({
                                    ...current,
                                    [topKey]: subIndex,
                                  }));
                                  onItemChange?.(subItem.id ?? String(subIndex));
                                }}
                              >
                                {subItem.label}
                              </button>
                              <div
                                id={sample ? undefined : subPanelId}
                                className={cx(
                                  "gnb-sub-list",
                                  subOpen && "active",
                                  subIndex > 0 && "between",
                                )}
                              >
                                {renderSubContent(subItem)}
                              </div>
                            </li>
                          );
                        })}
                      </ul>
                    )}
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </div>
    </nav>
  );
}

// packages/svelte/src/MainMenuPc.svelte
<script lang="ts">
  import type { KrdsNavItem } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf, flagOf, labelOf, hrefOf, childrenOf, recordOf, listOf } from './lib/shared.js';

  type Props = {
    id?: string;
    items?: KrdsNavItem[];
    links?: KrdsNavItem[];
    nav?: KrdsNavItem[];
    menuLabel?: string;
    sample?: boolean;
    children?: Snippet;
    class?: string;
    className?: string;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-main-menu',
    items = [],
    links = [],
    nav = [],
    menuLabel = '',
    sample = false,
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const navigationItems = $derived(items.length ? items : links.length ? links : nav);
</script>

<nav {...rest} class={`krds-main-menu ${rootClass}`} class:sample={sample}>
  <div class="inner">
    <ul class="gnb-menu" aria-label={sample ? undefined : menuLabel || undefined}>
      {#each navigationItems as item, topIndex}
        {@const topChildren = childrenOf(item)}
        {@const topBanner = recordOf(item, 'banner')}
        {@const mainPanelId = `${id}-main-${topIndex}`}
        <li>
          {#if fieldOf(item, 'href')}
            <a
              href={hrefOf(item)}
              class="gnb-main-trigger is-link"
              data-trigger="gnb"
              target={fieldOf(item, 'target') || undefined}
              title={fieldOf(item, 'title') || undefined}
            >{labelOf(item)}</a>
          {:else if flagOf(item, 'button')}
            <button type="button" class="gnb-main-trigger is-link" data-trigger="gnb">
              {labelOf(item)}
            </button>
          {:else}
            <button
              type="button"
              class="gnb-main-trigger"
              class:active={flagOf(item, 'active')}
              data-trigger="gnb"
              aria-controls={sample ? undefined : mainPanelId}
              aria-expanded={sample ? undefined : 'false'}
              aria-haspopup={sample ? undefined : 'true'}
            >{labelOf(item)}</button>
            <div
              id={sample ? undefined : mainPanelId}
              class="gnb-toggle-wrap"
              class:is-open={flagOf(item, 'active')}
            >
              <div
                class="gnb-main-list"
                data-has-submenu={fieldOf(item, 'title') ? undefined : 'true'}
              >
                {#if fieldOf(item, 'title')}
                  <div class="gnb-sub-list single-list between">
                    <div class="gnb-sub-content">
                      <h2 class="sub-title"><span>{fieldOf(item, 'title')}</span></h2>
                      <ul>
                        {#each topChildren as leaf}
                          <li>
                            {#if fieldOf(leaf, 'href')}
                              <a href={hrefOf(leaf)}>{labelOf(leaf)}</a>
                            {:else}
                              <button type="button">{labelOf(leaf)}</button>
                            {/if}
                          </li>
                        {/each}
                      </ul>
                    </div>
                    {#if topBanner}
                      <div class="gnb-sub-banner">
                        <span class="krds-badge bg-secondary">{fieldOf(topBanner, 'badge')}</span>
                        <button type="button" class="krds-btn medium text">
                          {labelOf(topBanner)} <i class="svg-icon ico-angle right"></i>
                        </button>
                      </div>
                    {/if}
                  </div>
                {:else}
                  <ul>
                    {#each topChildren as child, childIndex}
                      {@const childChildren = childrenOf(child)}
                      {@const descriptionItems = listOf(child, 'descriptionItems')}
                      {@const childBanner = recordOf(child, 'banner')}
                      {@const childPanelId = `${id}-sub-${topIndex}-${childIndex}`}
                      {@const runtimeSubActive = !sample && childIndex === 0}
                      <li>
                        {#if fieldOf(child, 'href') && !childChildren.length && !descriptionItems.length}
                          <a
                            href={hrefOf(child)}
                            class="gnb-sub-trigger is-link"
                            class:external-link={fieldOf(child, 'target') === '_blank'}
                            data-trigger="gnb"
                            target={fieldOf(child, 'target') || undefined}
                            title={fieldOf(child, 'title') || undefined}
                          >{labelOf(child)}</a>
                        {:else}
                          <button
                            type="button"
                            class="gnb-sub-trigger"
                            class:active={flagOf(child, 'active') || runtimeSubActive}
                            data-trigger="gnb"
                            aria-controls={sample ? undefined : childPanelId}
                            aria-expanded={sample ? undefined : runtimeSubActive ? 'true' : 'false'}
                            aria-haspopup={sample ? undefined : 'true'}
                          >{labelOf(child)}</button>
                          <div
                            class="gnb-sub-list"
                            class:active={flagOf(child, 'active') || runtimeSubActive}
                            class:between={childIndex > 0}
                            id={sample ? undefined : childPanelId}
                          >
                            <div class="gnb-sub-content">
                              <h2 class="sub-title">
                                {#if fieldOf(child, 'titleHref')}
                                  {fieldOf(child, 'title')}
                                  <a
                                    href={fieldOf(child, 'titleHref')}
                                    class="krds-btn link basic small"
                                  >
                                    <span class="underline">{fieldOf(child, 'titleLinkLabel')}</span>
                                    <i class="svg-icon ico-angle right"></i>
                                  </a>
                                {:else}
                                  <span>{fieldOf(child, 'title')}</span>
                                {/if}
                              </h2>
                              {#if descriptionItems.length}
                                <ul class="type-description">
                                  {#each descriptionItems as detail}
                                    <li>
                                      <h3 class="tit">
                                        <a
                                          href={hrefOf(detail)}
                                          target={fieldOf(detail, 'target') || undefined}
                                          title={fieldOf(detail, 'externalTitle') || undefined}
                                        >
                                          {fieldOf(detail, 'title')} <i class="svg-icon ico-go"></i>
                                        </a>
                                      </h3>
                                      <p class="txt">{fieldOf(detail, 'description')}</p>
                                    </li>
                                  {/each}
                                </ul>
                              {:else}
                                <ul>
                                  {#each childChildren as leaf}
                                    <li>
                                      {#if fieldOf(leaf, 'href')}
                                        <a href={hrefOf(leaf)}>{labelOf(leaf)}</a>
                                      {:else}
                                        <button type="button">{labelOf(leaf)}</button>
                                      {/if}
                                    </li>
                                  {/each}
                                </ul>
                              {/if}
                            </div>
                            {#if childBanner}
                              <div class="gnb-sub-banner">
                                <span class="krds-badge bg-secondary">{fieldOf(childBanner, 'badge')}</span>
                                <button type="button" class="krds-btn medium text">
                                  {labelOf(childBanner)} <i class="svg-icon ico-angle right"></i>
                                </button>
                              </div>
                            {/if}
                          </div>
                        {/if}
                      </li>
                    {/each}
                  </ul>
                {/if}
              </div>
            </div>
          {/if}
        </li>
      {/each}
    </ul>
  </div>
</nav>
