// packages/angular/src/components/modal.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId, type AngularNavItem } from "../kinds";

@Component({
  selector: "krds-modal, krds-modal-sample",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (kind === "modal-sample") {
      <section
        [id]="id"
        class="krds-modal fade in shown"
        role="dialog"
        [attr.aria-labelledby]="id + '-title'"
      >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h2 [id]="id + '-title'" class="modal-title">{{ title }}</h2>
            </div>
            <div class="modal-conts">
              <div class="conts-area">{{ description }}</div>
            </div>
            <div class="modal-btn btn-wrap">
              <button type="button" class="krds-btn medium tertiary close-modal">
                {{ cancelLabel }}
              </button>
              <button type="button" class="krds-btn medium primary close-modal">
                {{ confirmLabel }}
              </button>
            </div>
            <button type="button" class="krds-btn medium icon btn-close close-modal">
              <span class="sr-only">{{ closeLabel }}</span>
              <i class="svg-icon ico-popup-close"></i>
            </button>
          </div>
        </div>
        <div class="modal-back in"></div>
      </section>
    } @else {
      <section
        [id]="id"
        class="krds-modal fade"
        [class.in]="open"
        [class.shown]="open"
        role="dialog"
        [attr.aria-labelledby]="id + '-title'"
      >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h2 [id]="id + '-title'" class="modal-title">{{ title }}</h2>
            </div>
            <div class="modal-conts">
              <div class="conts-area">
                @if (items.length > 0) {
                  @for (item of items; track $index) {
                    {{ navLabel(item) }}
                    @if (!$last) {
                      <br />
                    }
                  }
                } @else {
                  {{ description }}
                }
              </div>
            </div>
            <div class="modal-btn btn-wrap">
              <button type="button" class="krds-btn medium tertiary close-modal">
                {{ cancelLabel }}
              </button>
              <button type="button" class="krds-btn medium primary close-modal">
                {{ confirmLabel }}
              </button>
            </div>
            <button type="button" class="krds-btn medium icon btn-close close-modal">
              <span class="sr-only">{{ closeLabel }}</span>
              <i class="svg-icon ico-popup-close"></i>
            </button>
          </div>
        </div>
        <div class="modal-back" [class.in]="open"></div>
      </section>
    }
  `,
})
export class KrdsModalComponent {
  @Input() id = createStableId("krds-modal");
  @Input() open = false;
  @Input() title = "제목";
  @Input() description = "";
  @Input() cancelLabel = "";
  @Input() confirmLabel = "";
  @Input() closeLabel = "닫기";
  @Input() kind: "modal" | "modal-sample" = "modal";
  @Input() items: (AngularNavItem | string)[] = [];

  navLabel(item: unknown): string {
    if (typeof item === "string" || typeof item === "number") return String(item);
    if (!item || typeof item !== "object") return "";
    if ("label" in item) return String(item.label ?? "");
    if ("title" in item) return String(item.title ?? "");
    if ("text" in item) return String(item.text ?? "");
    if ("message" in item) return String(item.message ?? "");
    return "";
  }
}
export { KrdsModalComponent as KrdsModalSampleComponent };

// packages/svelte/src/Modal.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { labelOf, invoke } from './lib/shared.js';

  type Props = {
    id?: string;
    title?: string;
    items?: unknown[];
    description?: string;
    cancelLabel?: string;
    confirmLabel?: string;
    closeLabel?: string;
    open?: boolean;
    oncancel?: (event: Event) => void;
    onclose?: (event: Event) => void;
    children?: Snippet;
    className?: string;
    class?: string;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    title = '제목',
    items = [],
    description = '',
    cancelLabel = '',
    confirmLabel = '',
    closeLabel = '닫기',
    open = $bindable<boolean | undefined>(),
    oncancel,
    onclose,
    children,
    className = '',
    class: classProp = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? true);

  let modalRoot: HTMLElement | undefined = $state();
  let restoreFocus: HTMLElement | null = null;
  let wasOpen = false;
  let hasObservedModalState = false;

  $effect(() => {
    if (!modalRoot) return;
    if (!hasObservedModalState) {
      hasObservedModalState = true;
      wasOpen = isOpen;
      return;
    }
    if (isOpen && !wasOpen) {
      restoreFocus =
        typeof document !== 'undefined' && document.activeElement instanceof HTMLElement
          ? document.activeElement
          : null;
      queueMicrotask(() => {
        modalRoot
          ?.querySelector<HTMLElement>(
            'button, input, select, textarea, a[href], [tabindex]:not([tabindex="-1"])',
          )
          ?.focus();
      });
    } else if (!isOpen && wasOpen) {
      restoreFocus?.focus();
      restoreFocus = null;
    }
    wasOpen = isOpen;
  });

  const closeModal = (event: Event) => {
    if (event.type === 'cancel') {
      invoke(oncancel, event);
      if (event.defaultPrevented) return;
    }
    open = false;
    if (event.currentTarget instanceof Element) {
      event.currentTarget.closest('.krds-modal')?.classList.remove('in', 'shown');
    }
    if (event.type !== 'cancel') invoke(onclose, event);
  };

  const handleModalKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Tab' && isOpen) {
      const focusable = Array.from(
        modalRoot?.querySelectorAll<HTMLElement>(
          'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
        ) ?? [],
      );
      if (!focusable.length) return;
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      const activeElement = modalRoot?.ownerDocument.activeElement;
      if (event.shiftKey && (activeElement === first || !modalRoot?.contains(activeElement))) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && activeElement === last) {
        event.preventDefault();
        first.focus();
      }
      return;
    }
    if (event.key !== 'Escape') return;
    const cancelEvent = new Event('cancel', { cancelable: true });
    invoke(oncancel, cancelEvent);
    if (cancelEvent.defaultPrevented) return;
    event.preventDefault();
    open = false;
    if (event.currentTarget instanceof Element) {
      event.currentTarget.closest('.krds-modal')?.classList.remove('in', 'shown');
    }
    invoke(onclose, event);
  };

  // ModalSample uses the same template as the default Modal export

</script>
<section
  {...rest}
  bind:this={modalRoot}
  id={`${id}-dialog`}
  class={`krds-modal fade ${isOpen ? 'in shown' : ''} ${rootClass}`}
  role="dialog"
  aria-labelledby={`${id}-title`}
  onkeydown={handleModalKeydown}
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 id={`${id}-title`} class="modal-title">{title}</h2>
      </div>
      <div class="modal-conts">
        <div class="conts-area">
          {#if items.length}
            {#each items as item, index}
              {labelOf(item)}{#if index < items.length - 1}<br />{/if}
            {/each}
          {:else if children}
            {@render children()}
          {:else}
            {description}
          {/if}
        </div>
      </div>
      <div class="modal-btn btn-wrap">
        <button type="button" class="krds-btn medium tertiary close-modal" onclick={closeModal}>
          {cancelLabel}
        </button>
        <button type="button" class="krds-btn medium primary close-modal" onclick={closeModal}>
          {confirmLabel}
        </button>
      </div>
      <button type="button" class="krds-btn medium icon btn-close close-modal" onclick={closeModal}>
        <span class="sr-only">{closeLabel}</span>
        <i class="svg-icon ico-popup-close"></i>
      </button>
    </div>
  </div>
  <div class={`modal-back ${isOpen ? 'in' : ''}`}></div>
</section>
