// packages/react/src/components/Pagination.tsx
import { type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsPaginationItem } from "@krds-community/recipes";
import type { CommonProps } from "./_utils.js";

export interface PaginationProps extends Omit<CommonProps, "items"> {
  items?: KrdsPaginationItem[];
  current?: number;
  previousDisabled?: boolean;
  nextDisabled?: boolean;
  previousLabel?: ReactNode;
  nextLabel?: ReactNode;
  navigationLabel?: string;
  onPageChange?: (page: number) => void;
  className?: string;
  children?: ReactNode;
}
export function Pagination({
  items = [1, 2, 3, 4, 5],
  current = 1,
  previousDisabled = Number(current) <= 1,
  nextDisabled = Number(current) >=
    Math.max(...items.filter((item): item is number => item !== "ellipsis")),
  previousLabel = "이전",
  nextLabel = "다음",
  navigationLabel = "페이지 이동",
  onPageChange,
  className,
  ref,
  ..._props
}: PaginationProps & { ref?: Ref<HTMLDivElement> }) {
  const currentPage = Number(current) || 1;
  const pageLink = (page: number) => (
    <a
      className={cx("page-link", page === currentPage && "active")}
      href="#"
      onClick={(event) => {
        event.preventDefault();
        onPageChange?.(page);
      }}
      key={page}
    >
      {page === currentPage ? <span className="sr-only">현재페이지 </span> : null}
      {page}
    </a>
  );
  return (
    <div
      ref={ref}
      className={cx("krds-pagination", className)}
      role="navigation"
      aria-label={navigationLabel}
    >
      {previousDisabled ? (
        <span {...{ href: "#" }} className="page-navi prev disabled">
          {previousLabel}
        </span>
      ) : (
        <a
          className="page-navi prev"
          href="#"
          onClick={(event) => {
            event.preventDefault();
            onPageChange?.(currentPage - 1);
          }}
        >
          {previousLabel}
        </a>
      )}
      <div className="page-links">
        {items.map((item, index) =>
          item === "ellipsis" ? (
            <span className="page-link link-dot" key={`ellipsis-${index}`} />
          ) : (
            pageLink(item)
          ),
        )}
      </div>
      {nextDisabled ? (
        <span {...{ href: "#" }} className="page-navi next disabled">
          {nextLabel}
        </span>
      ) : (
        <a
          className="page-navi next"
          href="#"
          onClick={(event) => {
            event.preventDefault();
            onPageChange?.(currentPage + 1);
          }}
        >
          {nextLabel}
        </a>
      )}
    </div>
  );
}

// packages/svelte/src/Pagination.svelte
<script lang="ts">
  import { invoke, labelOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    current?: number;
    items?: unknown[];
    previousLabel?: string;
    nextLabel?: string;
    navigationLabel?: string;
    message?: string;
    modelValue?: string | number;
    href?: string;
    title?: string;
    label?: string;
    previousDisabled?: boolean;
    nextDisabled?: boolean;
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    current = $bindable<number | undefined>(),
    items = [1, 2, 3, 4, 5] as unknown[],
    previousLabel = '이전',
    nextLabel = '다음',
    navigationLabel = '페이지 이동',
    message = '현재페이지',
    title,
    label,
    modelValue = $bindable<string | number | undefined>(),
    href = '#',
    previousDisabled = false,
    nextDisabled: nextDisabledProp,
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const currentIndex = $derived(Number(current) || 1);
  const maxPage = $derived(
    Math.max(...items.map((item) => Number(labelOf(item))).filter(Number.isFinite), 1),
  );
  const nextDisabled = $derived(nextDisabledProp ?? currentIndex >= maxPage);
  const selectPage = (page: number, event: Event) => {
    current = page;
    modelValue = page;
    invoke(onclick, event);
  };

  </script>

  <div
    {...rest}
    class={`krds-pagination ${rootClass}`}
    role="navigation"
    aria-label={navigationLabel}
  >
    {#if previousDisabled || currentIndex <= 1}
      <span class="page-navi prev disabled" href={href ?? '#'}>{previousLabel}</span>
    {:else}
      <a
        href={href}
        class="page-navi prev"
        onclick={(event) => {
          event.preventDefault();
          selectPage(currentIndex - 1, event);
        }}
      >{previousLabel}</a>
    {/if}
    <div class="page-links">
      {#each items as item}
        {#if labelOf(item) === 'ellipsis'}
          <span class="page-link link-dot"></span>
        {:else}
          {@const page = Number(labelOf(item))}
          <a
            href={href}
            class="page-link"
            class:active={page === currentIndex}
            onclick={(event) => {
              event.preventDefault();
              selectPage(page, event);
            }}
          >
            {#if page === currentIndex}<span class="sr-only">{message} </span>{/if}
            {page}
          </a>
        {/if}
      {/each}
    </div>
    {#if nextDisabled}
      <span class="page-navi next disabled" href={href ?? '#'}>{nextLabel}</span>
    {:else}
      <a
        href={href}
        class="page-navi next"
        onclick={(event) => {
          event.preventDefault();
          selectPage(currentIndex + 1, event);
        }}
      >{nextLabel}</a>
    {/if}
  </div>
