// packages/angular/src/components/resize.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-resize",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-drop-wrap krds-resize" data-adjust="scale">
      <button
        type="button"
        class="krds-btn small text drop-btn"
        aria-expanded="false"
        [attr.aria-controls]="resizeMenuId"
      >
        {{ label }} <i class="svg-icon ico-toggle"></i>
      </button>
      <div class="drop-menu" [id]="resizeMenuId">
        <div class="drop-in">
          <ul class="drop-list">
            @for (option of options; track $index) {
              <li>
                <button
                  type="button"
                  [class]="
                    'item-link ' + option.value + (option.value === selected ? ' active' : '')
                  "
                  [attr.data-adjust-scale]="option.value"
                  (click)="setSelected(option.value)"
                >
                  {{ option.label }}
                  <span class="sr-only">{{ option.value === selected ? selectedLabel : "" }}</span>
                </button>
              </li>
            }
          </ul>
          <div class="drop-bottom">
            <button
              type="button"
              class="krds-btn medium text"
              data-adjust-scale="md"
              (click)="setSelected('md')"
            >
              <i class="svg-icon ico-reset"></i> {{ resetLabel }}
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class KrdsResizeComponent {
  @Input() id = createStableId("krds-resize");
  @Input() label = "레이블";
  @Input() selected = "";
  @Input() selectedLabel = "";
  @Input() resetLabel = "";
  @Input() options: Array<{ value: string; label: string }> = [];

  get resizeMenuId(): string {
    return `${this.id}-menu`;
  }

  setSelected(value: string): void {
    this.selected = value;
  }
}

// packages/svelte/src/Resize.svelte
<script lang="ts">
  import { invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    label?: string;
    open?: boolean;
    options?: { value: string; label: string; disabled?: boolean }[];
    selected?: string;
    modelValue?: string;
    defaultValue?: string;
    selectedLabel?: string;
    resetLabel?: string;
    onclick?: (event: Event) => void;
    onchange?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    label = '레이블',
    open = $bindable<boolean | undefined>(),
    options = [] as { value: string; label: string; disabled?: boolean }[],
    selected = $bindable<string | undefined>(),
    modelValue = $bindable<string | undefined>(),
    defaultValue = '',
    selectedLabel = '',
    resetLabel = '',
    onclick,
    onchange,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const selection = $derived(
    modelValue !== undefined
      ? String(modelValue)
      : selected !== undefined
        ? selected
        : defaultValue || 'md',
  );
  const isOpen = $derived(open ?? false);
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
  const setSelection = (next: string, event?: Event) => {
    selected = next;
    modelValue = next;
    if (event) invoke(onchange, event);
  };
</script>

<div {...rest} class={`krds-drop-wrap krds-resize ${rootClass}`} data-adjust="scale">
  <button
    type="button"
    class="krds-btn small text drop-btn"
    aria-expanded={isOpen}
    aria-controls={`${id}-menu`}
    onclick={() => toggleOpen()}
  >
    {label} <i class="svg-icon ico-toggle"></i>
  </button>
  <div class="drop-menu" id={`${id}-menu`}>
    <div class="drop-in">
      <ul class="drop-list">
        {#each options as option}
          <li>
            <button
              type="button"
              class={`item-link ${option.value}`}
              class:active={(selection || 'md') === option.value}
              data-adjust-scale={option.value}
              onclick={(event) => setSelection(option.value, event)}
            >
              {option.label}<span class="sr-only">{(selection || 'md') === option.value ? selectedLabel : ''}</span>
            </button>
          </li>
        {/each}
      </ul>
      <div class="drop-bottom">
        <button
          type="button"
          class="krds-btn medium text"
          data-adjust-scale="md"
          onclick={(event) => setSelection('md', event)}
        >
          <i class="svg-icon ico-reset"></i> {resetLabel}
        </button>
      </div>
    </div>
  </div>
</div>
