// packages/react/src/components/Snackbar.tsx
import { useEffect, useState, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

const CLOSE_ANIMATION_MS = 200;

export interface SnackbarProps extends BoxProps {
  title?: ReactNode;
  message: ReactNode;
  icon?: string;
  actionLabel?: ReactNode;
  onAction?: () => void;
  closeLabel?: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function Snackbar({
  title,
  message,
  icon,
  actionLabel,
  onAction,
  closeLabel = "닫기",
  open: controlledOpen,
  defaultOpen = false,
  onOpenChange,
  className,
}: SnackbarProps) {
  const controlled = controlledOpen !== undefined;
  const [rendered, setRendered] = useState(
    controlled ? controlledOpen === true : defaultOpen === true,
  );
  const [closing, setClosing] = useState(false);

  const close = () => {
    if (controlled) onOpenChange?.(false);
    else setClosing(true);
  };

  useEffect(() => {
    if (controlledOpen === true) {
      setClosing(false);
      setRendered(true);
      return;
    }
    if (!rendered) return;
    if (controlledOpen === false) {
      setClosing(true);
      const timer = setTimeout(() => {
        setRendered(false);
        setClosing(false);
      }, CLOSE_ANIMATION_MS);
      return () => clearTimeout(timer);
    }
  }, [controlledOpen, rendered]);

  useEffect(() => {
    if (!closing || !rendered || controlled) return;
    const timer = setTimeout(() => {
      setRendered(false);
      setClosing(false);
      onOpenChange?.(false);
    }, CLOSE_ANIMATION_MS);
    return () => clearTimeout(timer);
  }, [closing, rendered, controlled, onOpenChange]);

  if (!rendered) return null;
  return (
    <div className={cx("krds-snackbar", className, closing && "closing")} role="alert">
      {icon ? <i className={cx("svg-icon snackbar-icon", icon)} aria-hidden="true" /> : null}
      <div className="snackbar-conts">
        {title ? <strong className="snackbar-title">{title}</strong> : null}
        <p className="snackbar-text">{message}</p>
      </div>
      {actionLabel ? (
        <button type="button" className="krds-btn small text snackbar-action" onClick={onAction}>
          {actionLabel}
        </button>
      ) : null}
      <button
        type="button"
        className="krds-btn small icon snackbar-close"
        aria-label={closeLabel ?? "닫기"}
        onClick={close}
      >
        <SvgIcon name="ico-modal-close" />
      </button>
    </div>
  );
}

// packages/svelte/src/Snackbar.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  const CLOSE_ANIMATION_MS = 200;

  type Props = {
    title?: string;
    message: string;
    icon?: string;
    actionLabel?: string;
    onaction?: () => void;
    closeLabel?: string;
    open?: boolean;
    defaultOpen?: boolean;
    onopenchange?: (open: boolean) => void;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    title = '',
    message,
    icon = '',
    actionLabel = '',
    onaction,
    closeLabel = '닫기',
    open = $bindable<boolean | undefined>(),
    defaultOpen = false,
    onopenchange,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const controlled = $derived(open !== undefined);

  let rendered = $state(open === true || (open === undefined && defaultOpen === true));
  let closing = $state(false);
  let wasOpen = false;
  let removeTimer: ReturnType<typeof setTimeout> | undefined;

  const startClose = () => {
    if (!rendered || closing) return;
    closing = true;
    removeTimer = setTimeout(() => {
      rendered = false;
      closing = false;
      onopenchange?.(false);
    }, CLOSE_ANIMATION_MS);
  };

  const requestClose = () => {
    if (controlled) {
      onopenchange?.(false);
    } else {
      startClose();
    }
  };

  $effect(() => {
    const isOpen = controlled ? open === true : rendered;
    if (isOpen && !wasOpen) {
      if (removeTimer) clearTimeout(removeTimer);
      closing = false;
      rendered = true;
    } else if (!isOpen && wasOpen) {
      startClose();
    }
    wasOpen = isOpen;
  });

  onDestroy(() => {
    if (removeTimer) clearTimeout(removeTimer);
  });
</script>

{#if rendered}
  <div {...rest} class={`krds-snackbar ${rootClass}`} class:closing={closing} role="alert">
    {#if icon}
      <i class={`svg-icon snackbar-icon ${icon}`} aria-hidden="true"></i>
    {/if}
    <div class="snackbar-conts">
      {#if title}
        <strong class="snackbar-title">{title}</strong>
      {/if}
      <p class="snackbar-text">{message}</p>
    </div>
    {#if actionLabel}
      <button type="button" class="krds-btn small text snackbar-action" onclick={onaction}>{actionLabel}</button>
    {/if}
    <button type="button" class="krds-btn small icon snackbar-close" aria-label={closeLabel} onclick={requestClose}>
      <i class="svg-icon ico-modal-close"></i>
    </button>
  </div>
{/if}
