// packages/solid/src/components/Spinner.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface SpinnerProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  id?: string;
  inputLabel?: string;
  placeholder?: string;
  [key: string]: unknown;
}

export function Spinner(rawProps: SpinnerProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "id",
    "inputLabel",
    "placeholder",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label;
  return (
    <div class="form-group">
      <div class="form-tit">
        <label for={`${props.id}-input`}>{props.inputLabel ?? "Label"}</label>
      </div>
      <div class="form-conts">
        <div class="form-spinner">
          <input
            type="text"
            id={`${props.id}-input`}
            class="krds-input"
            aria-label={props.inputLabel}
            placeholder={props.placeholder ?? "placeholder"}
          />
          <div
            {...(native as Record<string, any>)}
            class={`krds-spinner${className() ? ` ${className()}` : ""}`}
            role="status"
          >
            <span class="sr-only">{content()}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/svelte/src/Spinner.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    id?: string;
    label?: string;
    inputLabel?: string;
    placeholder?: string;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id,
    label = '레이블',
    inputLabel = 'Label',
    placeholder = 'placeholder',
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div class="form-group">
  <div class="form-tit">
    <label for={`${id}-input`}>{inputLabel}</label>
  </div>
  <div class="form-conts">
    <div class="form-spinner">
      <input type="text" id={`${id}-input`} class="krds-input" aria-label={inputLabel} {placeholder} />
      <div {...rest} class={`krds-spinner ${rootClass}`} role="status">
        <span class="sr-only">{label}</span>
      </div>
    </div>
  </div>
</div>
