// packages/solid/src/components/StructuredList.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import { labelOf, type StructuredItem } from "../shared.js";

export interface StructuredListProps {
  class?: string;
  className?: string;
  items?: (StructuredItem | string | number)[];
  dateLabel?: string;
  dateValue?: string;
  actionLabel?: string;
  shareLabel?: string;
  favoriteLabel?: string;
  tags?: string[];
  [key: string]: unknown;
}

export function StructuredList(rawProps: StructuredListProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "items",
    "dateLabel",
    "dateValue",
    "actionLabel",
    "shareLabel",
    "favoriteLabel",
    "tags",
  ]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <ul
      {...(native as Record<string, any>)}
      class={["krds-structured-list", "type-full", className()].filter(Boolean).join(" ")}
    >
      <For each={props.items ?? []}>
        {(item) => {
          const structured =
            typeof item === "string" || typeof item === "number"
              ? undefined
              : (item as StructuredItem);
          return (
            <li class="structured-item">
              <div class="in">
                <Show when={structured?.badge}>
                  <div class="card-top">
                    <span class={["krds-badge", structured?.badgeClass].filter(Boolean).join(" ")}>
                      {structured?.badge}
                    </span>
                  </div>
                </Show>
                <div class="card-body">
                  <a class="c-text" href={structured?.href ?? "#"}>
                    <p class="c-tit">
                      <span class="span">{labelOf(item)}</span>
                    </p>
                    <Show when={structured?.description}>
                      <p class="c-txt">{structured?.description}</p>
                    </Show>
                    <p class="c-date">
                      <strong class="key">{structured?.dateLabel ?? props.dateLabel}</strong>
                      <span class="value">{structured?.dateValue ?? props.dateValue}</span>
                    </p>
                  </a>
                  <div class="c-btn">
                    <a
                      class="krds-btn secondary"
                      href={structured?.href ?? "#"}
                      title={labelOf(item)}
                    >
                      {structured?.actionLabel ?? props.actionLabel}
                    </a>
                  </div>
                </div>
                <div class="card-btm">
                  <For each={structured?.tags ?? props.tags ?? []}>
                    {(tag) => <span class="tag">{tag}</span>}
                  </For>
                </div>
                <div class="card-btn">
                  <button type="button" class="krds-btn medium text" title={labelOf(item)}>
                    <i class="svg-icon ico-share" />
                    {(structured?.shareLabel ?? props.shareLabel) ? " " + (structured?.shareLabel ?? props.shareLabel) : null}
                  </button>
                  <button type="button" class="krds-btn medium text" title={labelOf(item)}>
                    <i class="svg-icon ico-like" />
                    {(structured?.favoriteLabel ?? props.favoriteLabel) ? " " + (structured?.favoriteLabel ?? props.favoriteLabel) : null}
                  </button>
                </div>
              </div>
            </li>
          );
        }}
      </For>
    </ul>
  );
}

// packages/svelte/src/StructuredList.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf, labelOf, hrefOf } from './lib/shared.js';

  type ListItem = Record<string, unknown>;

  type Props = {
    id?: string;
    items?: ListItem[];
    dateLabel?: string;
    dateValue?: string;
    actionLabel?: string;
    tags?: string[];
    shareLabel?: string;
    favoriteLabel?: string;
    children?: Snippet;
    className?: string;
    class?: string;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    items = [],
    dateLabel = '',
    dateValue = '',
    actionLabel = '',
    tags = [],
    shareLabel = '',
    favoriteLabel = '',
    children,
    className = '',
    class: classProp = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<ul {...rest} class={`krds-structured-list type-full ${rootClass}`}>
  {#each items as item}
    <li class="structured-item">
      <div class="in">
        <div class="card-top">
          {#if fieldOf(item, 'badge')}
            <span class={`krds-badge ${fieldOf(item, 'badgeClass') || fieldOf(item, 'tone')}`}
              >{fieldOf(item, 'badge')}</span
            >
          {/if}
        </div>
        <div class="card-body">
          <a class="c-text" href={hrefOf(item)}>
            <p class="c-tit"><span class="span">{labelOf(item)}</span></p>
            {#if fieldOf(item, 'description')}<p class="c-txt">{fieldOf(item, 'description')}</p>{/if}
            <p class="c-date">
              <strong class="key">{fieldOf(item, 'dateLabel') || dateLabel}</strong>
              <span class="value">{fieldOf(item, 'date') || dateValue}</span>
            </p>
          </a>
          <div class="c-btn"><a class="krds-btn secondary" href={hrefOf(item)} title={labelOf(item)}>{actionLabel}</a></div>
        </div>
        <div class="card-btm">{#each tags as tag}<span class="tag">{tag}</span>{/each}</div>
        <div class="card-btn">
          <button class="krds-btn medium text" title={labelOf(item)} type="button"><i class="ico-share svg-icon"></i>{' '}{shareLabel}</button>
          <button class="krds-btn medium text" title={labelOf(item)} type="button"><i class="ico-like svg-icon"></i>{' '}{favoriteLabel}</button>
        </div>
      </div>
    </li>
  {/each}
</ul>
