// packages/react/src/components/Tab.tsx
import { useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx, tabRecipe } from "@krds-community/recipes";
import type { KrdsTabItem } from "@krds-community/recipes";

export interface TabItem extends Omit<KrdsTabItem, "label"> {
  label: ReactNode;
  tabId?: string;
  panelId?: string;
  quickNav?: boolean;
}

export interface TabProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "onChange"> {
  tabs: TabItem[];
  panels: Record<string, ReactNode>;
  defaultTab?: string;
  defaultValue?: string;
  value?: string;
  selected?: string;
  message?: ReactNode;
  panelTitle?: ReactNode;
  full?: boolean;
  onTabChange?: (id: string) => void;
  onChange?: (id: string) => void;
}
export function Tab({
  tabs,
  panels,
  defaultTab,
  defaultValue,
  value,
  selected,
  message,
  panelTitle,
  full = true,
  onTabChange,
  onChange,
  className,
  ref,
  ...props
}: TabProps & { ref?: Ref<HTMLDivElement> }) {
  const controlledSelected = value ?? selected;
  const selectedControlled = value !== undefined || selected !== undefined;
  const firstEnabled = tabs.find((tab) => !tab.disabled);
  const requestedDefault = defaultValue ?? defaultTab;
  const initialSelected = tabs.some((tab) => tab.id === requestedDefault && !tab.disabled)
    ? (requestedDefault ?? "")
    : (firstEnabled?.id ?? "");
  const [uncontrolledSelected, setUncontrolledSelected] = useState(initialSelected);
  const requestedSelected = controlledSelected ?? uncontrolledSelected;
  const activeTab = tabs.some((tab) => tab.id === requestedSelected && !tab.disabled)
    ? requestedSelected
    : (firstEnabled?.id ?? "");
  const tabClasses = tabRecipe({ full });
  const enabledTabs = tabs.filter((tab) => !tab.disabled);
  const selectTab = (id: string) => {
    const tab = tabs.find((item) => item.id === id);
    if (!tab || tab.disabled) return;
    if (!selectedControlled) setUncontrolledSelected(id);
    onTabChange?.(id);
    onChange?.(id);
  };
  return (
    <div {...props} ref={ref} className={cx(tabClasses.root, className)}>
      <div className={tabClasses.listContainer}>
        <ul role="tablist">
          {tabs.map((tab) => {
            const tabId = tab.tabId ?? `tab_${tab.id}`;
            const panelId = tab.panelId ?? `panel_${tab.id}`;
            const active = activeTab === tab.id;
            const itemClass = tabRecipe({ full, active }).item;
            return (
              <li role="presentation" className={itemClass || undefined} key={tab.id}>
                <button
                  id={tabId}
                  type="button"
                  role="tab"
                  aria-selected={active}
                  aria-controls={panelId}
                  tabIndex={active ? 0 : -1}
                  className={tabClasses.trigger}
                  disabled={tab.disabled}
                  onClick={() => selectTab(tab.id)}
                  onKeyDown={(event) => {
                    if (!["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) {
                      return;
                    }
                    const currentIndex = enabledTabs.findIndex((item) => item.id === tab.id);
                    const nextIndex =
                      event.key === "Home"
                        ? 0
                        : event.key === "End"
                          ? enabledTabs.length - 1
                          : event.key === "ArrowRight"
                            ? (currentIndex + 1) % enabledTabs.length
                            : (currentIndex - 1 + enabledTabs.length) % enabledTabs.length;
                    const nextTab = enabledTabs[nextIndex];
                    if (!nextTab) return;
                    event.preventDefault();
                    selectTab(nextTab.id);
                    const nextTabId = nextTab.tabId ?? `tab_${nextTab.id}`;
                    event.currentTarget.ownerDocument.getElementById(nextTabId)?.focus();
                  }}
                >
                  {tab.label}
                  {active && message ? <i className="sr-only created"> {message}</i> : null}
                </button>
              </li>
            );
          })}
        </ul>
      </div>
      <div className="tab-conts-wrap">
        {tabs.map((tab) => {
          const tabId = tab.tabId ?? `tab_${tab.id}`;
          const panelId = tab.panelId ?? `panel_${tab.id}`;
          return (
            <section
              id={panelId}
              aria-labelledby={tabId}
              role="tabpanel"
              className={cx("tab-conts", activeTab === tab.id && "active")}
              hidden={activeTab !== tab.id}
              data-quick-nav={tab.quickNav ?? false}
              key={tab.id}
            >
              {panelTitle ? <h3 className="sr-only">{panelTitle}</h3> : null}
              {panels[tab.id]}
            </section>
          );
        })}
      </div>
    </div>
  );
}

// packages/svelte/src/Tab.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { tabRecipe } from './lib/shared.js';

  type TabItem = {
    id: string;
    label?: string;
    disabled?: boolean;
    [key: string]: unknown;
  };

  type Props = {
    id?: string;
    tabs?: TabItem[];
    panels?: Record<string, unknown>;
    defaultValue?: string;
    selection?: string;
    selected?: string;
    modelValue?: string;
    description?: string;
    message?: string;
    panelTitle?: string;
    onclick?: (event: Event) => void;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    tabs = [],
    panels = {},
    defaultValue = undefined,
    selection = $bindable<string | undefined>(),
    selected = $bindable<string | undefined>(),
    modelValue = $bindable<string | undefined>(),
    description = '',
    message = '',
    panelTitle = '',
    onclick,
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const tabClasses = $derived(tabRecipe());
  const active = $derived(selection ?? selected ?? modelValue ?? defaultValue ?? tabs[0]?.id);

  const selectTab = (tabId: string, event?: Event) => {
    selection = tabId;
    selected = tabId;
    modelValue = tabId;
    if (event) {
      if (typeof onclick === 'function') onclick(event);
    }
  };

  const handleTabKeydown = (event: KeyboardEvent, index: number) => {
    if (!tabs.length || !['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
    event.preventDefault();
    const direction = event.key === 'ArrowLeft' || event.key === 'Home' ? -1 : 1;
    let nextIndex =
      event.key === 'Home'
        ? 0
        : event.key === 'End'
          ? tabs.length - 1
          : (index + direction + tabs.length) % tabs.length;
    while (tabs[nextIndex]?.disabled && nextIndex !== index) {
      nextIndex = (nextIndex + direction + tabs.length) % tabs.length;
    }
    if (tabs[nextIndex]?.disabled) return;
    selectTab(tabs[nextIndex].id);
    (event.currentTarget as HTMLButtonElement).parentElement?.parentElement
      ?.querySelectorAll<HTMLButtonElement>('.btn-tab')
      [nextIndex]?.focus();
  };
</script>

<div {...rest} class={`${tabClasses.root} ${rootClass}`.trim()}>
  <div class={tabClasses.listContainer}>
    <ul role="tablist">
      {#each tabs as tab, index}
        {@const itemClasses = tabRecipe({ active: active === tab.id })}
        <li
          role="presentation"
          class={itemClasses.item}
        >
          <button
            id={`${id}-tab-${tab.id}`}
            role="tab"
            aria-selected={active === tab.id}
            aria-controls={`${id}-panel-${tab.id}`}
            class={itemClasses.trigger}
            type="button"
            disabled={tab.disabled}
            tabindex={active === tab.id ? 0 : -1}
            onclick={(event) => selectTab(tab.id, event)}
            onkeydown={(event) => handleTabKeydown(event, index)}
          >
            {tab.label}
            {#if active === tab.id && message}<i class="created sr-only">{message}</i>{/if}
          </button>
        </li>
      {/each}
    </ul>
  </div>
  <div class="tab-conts-wrap">
    {#each tabs as tab}
      <!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
<section
        role="tabpanel"
        id={`${id}-panel-${tab.id}`}
        aria-labelledby={`${id}-tab-${tab.id}`}
        data-quick-nav="false"
        class={`tab-conts ${active === tab.id ? 'active' : ''}`}
        hidden={active !== tab.id}
      >{#if panelTitle}<h3 class="sr-only">{panelTitle}</h3>{/if}{panels[tab.id] ?? (tab.id === active ? description : '')}</section>
    {/each}
  </div>
</div>
