// packages/react/src/components/Table.tsx
import { type ReactNode, type TableHTMLAttributes, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import type { DataTableColumn } from "./StructuredListTable.js";
export interface TableProps extends Omit<TableHTMLAttributes<HTMLTableElement>, "children"> {
  columns: DataTableColumn[];
  rows: Array<Record<string, ReactNode>>;
  caption?: ReactNode;
}

export function Table({
  columns,
  rows,
  caption,
  className,
  ref,
  ...props
}: TableProps & { ref?: Ref<HTMLTableElement> }) {
  return (
    <div className="krds-table-wrap">
      <table {...props} ref={ref} className={cx("tbl", "col", "data", className)}>
        <caption>{caption}</caption>
        <colgroup>
          {columns.map((column) => (
            <col style={column.width ? { width: column.width } : undefined} key={column.key} />
          ))}
        </colgroup>
        <thead>
          <tr>
            {columns.map((column) => (
              <th scope="col" key={column.key}>
                {column.visuallyHidden ? (
                  <span className="sr-only">{column.label}</span>
                ) : (
                  column.label
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={index}>
              {columns.map((column, columnIndex) =>
                columnIndex === 0 ? (
                  <th scope="row" key={column.key}>
                    {row[column.key]}
                  </th>
                ) : (
                  <td key={column.key}>{row[column.key]}</td>
                ),
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// packages/svelte/src/Table.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf } from './lib/shared.js';

  type Props = {
    id?: string;
    columns?: Record<string, unknown>[];
    rows?: Record<string, unknown>[];
    caption?: string;
    title?: string;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    columns = [],
    rows = [],
    caption = '',
    title = '제목',
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div class="krds-table-wrap">
  <table {...rest} class="tbl col data">
    <caption>{caption || title}</caption>
    <colgroup>
      {#each columns as column}
        <col style={fieldOf(column, 'width') ? `width: ${fieldOf(column, 'width')};` : undefined} />
      {/each}
    </colgroup>
    <thead>
      <tr>
        {#each columns as column}
          <th scope="col">{column.label}</th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each rows as row}
        <tr>
          {#each columns as column, columnIndex}
            {#if columnIndex === 0}<th scope="row">{row[column.key]}</th>{:else}<td>{row[column.key]}</td>{/if}
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
