// packages/react/src/components/Tag.tsx
import type { ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsTone } from "@krds-community/recipes";
import { toneClass } from "./_utils.js";

export function Tag({
  label,
  tone,
  removable = true,
  onRemove,
  className,
}: {
  label: ReactNode;
  tone?: KrdsTone;
  removable?: boolean;
  onRemove?: () => void;
  className?: string;
}) {
  return (
    <div className="krds-tag-wrap large">
      <span className={cx("krds-btn-tag", tone && `bg-${toneClass[tone]}`, className)}>
        {label}
        {removable ? (
          <button type="button" className="btn-delete" onClick={onRemove}>
            <span className="sr-only">삭제</span>
          </button>
        ) : null}
      </span>
    </div>
  );
}

// packages/svelte/src/Tag.svelte
<script lang="ts">
  import { invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    id?: string;
    label?: string;
    size?: string;
    removable?: boolean;
    message?: string;
    className?: string;
    class?: string;
    onclick?: (event: Event) => void;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class'>;

  let {
    id,
    label = '레이블',
    size = 'large',
    removable = false,
    message = '삭제',
    className = '',
    class: classProp = '',
    onclick,
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div class={`krds-tag-wrap ${size || 'large'}`}>
  <span {...rest} class={`krds-btn-tag ${rootClass}`}>
    {label}
    {#if removable}
      <button class="btn-delete" type="button" onclick={(event) => invoke(onclick, event)}>
        <span class="sr-only">{message}</span>
      </button>
    {/if}
  </span>
</div>
