// packages/solid/src/components/Textarea.tsx
import { Show, createSignal, createUniqueId, mergeProps, splitProps } from "solid-js";

export interface TextareaProps {
  class?: string;
  className?: string;
  id?: string;
  label?: string;
  hint?: string;
  maxLength?: number;
  value?: string;
  modelValue?: string;
  ["aria-describedby"]?: string;
  [key: string]: unknown;
}

export function Textarea(rawProps: TextareaProps) {
  const merged = mergeProps({ id: `krds-textarea-${createUniqueId()}` }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "label",
    "hint",
    "maxLength",
    "value",
    "modelValue",
    "aria-describedby",
  ]);
  const [localValue, setLocalValue] = createSignal("");
  const value = () => {
    if (props.value !== undefined) return String(props.value ?? "");
    if (typeof props.modelValue === "string" || typeof props.modelValue === "number")
      return String(props.modelValue);
    return localValue();
  };
  const setValue = (next: string) => {
    if (props.value === undefined) setLocalValue(next);
  };
  const updateInput = (
    event: InputEvent & { currentTarget: HTMLInputElement | HTMLTextAreaElement },
  ) => {
    setValue(event.currentTarget.value);
    (native as Record<string, any>).onInput?.(event);
  };
  const className = () => props.class ?? props.className ?? "";
  const hintId = () => (props.hint ? `${props.id}-hint` : undefined);
  const describedBy = () =>
    [props["aria-describedby"], hintId()].filter(Boolean).join(" ") || undefined;
  return (
    <>
      <textarea
        {...(native as Record<string, any>)}
        id={props.id}
        class={["krds-input", className()].filter(Boolean).join(" ")}
        maxlength={props.maxLength}
        value={value()}
        aria-describedby={describedBy()}
        onInput={updateInput}
      />
      <label for={props.id}>{props.label}</label>
      <Show when={props.hint}>
        <p id={hintId()}>{props.hint}</p>
      </Show>
    </>
  );
}

// packages/svelte/src/Textarea.svelte
<script lang="ts">
  import { invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    name?: string;
    label?: string;
    placeholder?: string;
    hint?: string;
    maxLength?: number;
    value?: string;
    modelValue?: string | number | boolean;
    disabled?: boolean;
    required?: boolean;
    readonly?: boolean;
    autocomplete?: string;
    form?: string;
    oninput?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    name = '',
    label = '',
    placeholder = '',
    hint,
    maxLength,
    value = $bindable<string | undefined>(),
    modelValue = $bindable<string | number | boolean | undefined>(),
    disabled = false,
    required = false,
    readonly = false,
    autocomplete,
    form,
    oninput,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const inputValue = $derived(
    value !== undefined
      ? String(value)
      : typeof modelValue === 'string' || typeof modelValue === 'number' || typeof modelValue === 'boolean'
        ? String(modelValue)
        : '',
  );
  const setValue = (event: Event) => {
    const next = (event.currentTarget as HTMLTextAreaElement).value;
    if (value !== undefined) value = next;
    else modelValue = next;
    invoke(oninput, event);
  };
</script>

<textarea
  {...rest}
  id={id}
  name={name || undefined}
  class={`krds-input ${rootClass}`}
  {placeholder}
  maxlength={maxLength}
  aria-describedby={hint ? `${id}-hint` : undefined}
  {disabled}
  {required}
  {readonly}
  {autocomplete}
  {form}
  oninput={setValue}
></textarea>{#if label}<label for={id}>{label}</label>{/if}{#if hint}<p id={`${id}-hint`}>{hint}</p>{/if}
