// packages/angular/src/components.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  forwardRef,
  Input,
  Output,
  EventEmitter,
} from '@angular/core';
import { FormsModule, NG_VALUE_ACCESSOR, ReactiveFormsModule } from '@angular/forms';
import type { ControlValueAccessor } from '@angular/forms';
import type {
  AccordionContractProps,
  ButtonContractProps,
  ChoiceContractProps,
  RadioContractProps,
  TextInputContractProps,
} from '@krds-community/recipes';

@Component({
  selector: 'krds-button',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<button
    [attr.type]="type"
    [disabled]="disabled"
    [class]="'krds-button ' + className"
    [attr.data-variant]="variant"
    [attr.data-size]="size"
    (click)="clicked.emit($event)"
  >
    <ng-content />
  </button>`,
})
export class KrdsButtonComponent implements ButtonContractProps {
  @Input() variant: 'primary' | 'secondary' | 'tertiary' = 'primary';
  @Input() size: 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' = 'medium';
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() disabled = false;
  @Input() className = '';
  @Output() clicked = new EventEmitter<MouseEvent>();
}

@Component({
  selector: 'krds-text-input',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => KrdsTextInputComponent),
      multi: true,
    },
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<label class="krds-field"
    ><span *ngIf="label" class="krds-field-label">{{ label }}</span
    ><input
      [id]="id"
      [name]="name"
      [type]="type"
      [value]="value"
      [placeholder]="placeholder"
      [disabled]="disabled"
      [readonly]="readonly"
      [required]="required"
      [class]="'krds-input ' + className"
      [attr.data-state]="state"
      [attr.data-size]="size"
      [attr.aria-invalid]="state === 'error' ? 'true' : null"
      [attr.aria-describedby]="hint ? id + '-hint' : null"
      (input)="input($event)"
      (blur)="blur()"
    /><span *ngIf="hint" [id]="id + '-hint'" class="krds-field-message" [attr.data-state]="state">{{
      hint
    }}</span></label
  >`,
})
export class KrdsTextInputComponent implements ControlValueAccessor, TextInputContractProps {
  @Input() id = 'krds-input';
  @Input() name: string | null = null;
  @Input() type = 'text';
  @Input() label = '';
  @Input() hint = '';
  @Input() placeholder = '';
  @Input() state: 'default' | 'error' | 'success' | 'information' = 'default';
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() className = '';
  @Input() required = false;
  @Input() readonly = false;
  disabled = false;
  value = '';
  private onChange: (value: string) => void = () => undefined;
  private onTouched: () => void = () => undefined;
  writeValue(value: string | null): void {
    this.value = value ?? '';
  }
  registerOnChange(fn: (value: string) => void): void {
    this.onChange = fn;
  }
  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }
  setDisabledState(disabled: boolean): void {
    this.disabled = disabled;
  }
  input(event: Event): void {
    this.value = (event.target as HTMLInputElement).value;
    this.onChange(this.value);
  }
  blur(): void {
    this.onTouched();
  }
}

@Component({
  selector: 'krds-checkbox',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="krds-form-check" [attr.data-size]="size">
    <input
      [id]="id"
      [name]="name"
      type="checkbox"
      [checked]="checked"
      [disabled]="disabled"
      (change)="changed($event)"
    /><label [for]="id">{{ label }}</label
    ><span *ngIf="description" class="krds-field-message">{{ description }}</span>
  </div>`,
})
export class KrdsCheckboxComponent implements ChoiceContractProps {
  @Input() id = 'krds-checkbox';
  @Input() name: string | undefined = undefined;
  @Input() label = '';
  @Input() description = '';
  @Input() size: 'medium' | 'large' = 'medium';
  @Input() checked = false;
  @Input() disabled = false;
  @Output() checkedChange = new EventEmitter<boolean>();
  changed(event: Event): void {
    if (!this.disabled) {
      this.checkedChange.emit((event.target as HTMLInputElement).checked);
    }
  }
}

@Component({
  selector: 'krds-radio',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="krds-form-check" [attr.data-size]="size">
    <input
      [id]="id"
      [name]="name"
      type="radio"
      [value]="value"
      [checked]="checked"
      [disabled]="disabled"
      (change)="selected.emit(value)"
    /><label [for]="id">{{ label }}</label
    ><span *ngIf="description" class="krds-field-message">{{ description }}</span>
  </div>`,
})
export class KrdsRadioComponent implements RadioContractProps {
  @Input() id = 'krds-radio';
  @Input() name = '';
  @Input() label = '';
  @Input() description = '';
  @Input() size: 'medium' | 'large' = 'medium';
  @Input() value = '';
  @Input() checked = false;
  @Input() disabled = false;
  @Output() selected = new EventEmitter<string>();
}

@Component({
  selector: 'krds-switch',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="krds-form-toggle-switch" [attr.data-size]="size">
    <input
      [id]="id"
      [name]="name"
      type="checkbox"
      [checked]="checked"
      [disabled]="disabled"
      (change)="changed($event)"
    /><label [for]="id"
      ><span class="switch-toggle" aria-hidden="true"><i></i></span>{{ label }}</label
    >
  </div>`,
})
export class KrdsSwitchComponent implements ChoiceContractProps {
  @Input() id = 'krds-switch';
  @Input() name: string | undefined = undefined;
  @Input() label = '';
  @Input() size: 'medium' | 'large' = 'medium';
  @Input() checked = false;
  @Input() disabled = false;
  @Output() checkedChange = new EventEmitter<boolean>();
  changed(event: Event): void {
    this.checkedChange.emit((event.target as HTMLInputElement).checked);
  }
}

export interface KrdsAccordionItem {
  id: string;
  title: string;
  content: string;
  disabled?: boolean;
}
@Component({
  selector: 'krds-accordion',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="krds-accordion" [attr.data-type]="type">
    <div *ngFor="let item of items" class="krds-accordion-item" [class.is-open]="isOpen(item.id)">
      <h5 class="krds-accordion-heading">
        <button
          type="button"
          class="krds-accordion-trigger"
          [id]="'krds-accordion-header-' + item.id"
          [attr.aria-expanded]="isOpen(item.id)"
          [attr.aria-controls]="'krds-accordion-panel-' + item.id"
          [disabled]="item.disabled"
          (click)="toggle(item.id)"
        >
          {{ item.title }}
        </button>
      </h5>
      <div
        class="krds-accordion-panel"
        role="region"
        [id]="'krds-accordion-panel-' + item.id"
        [attr.aria-labelledby]="'krds-accordion-header-' + item.id"
        [hidden]="!isOpen(item.id)"
      >
        {{ item.content }}
      </div>
    </div>
  </div>`,
})
export class KrdsAccordionComponent implements AccordionContractProps {
  @Input() items: KrdsAccordionItem[] = [];
  @Input() type: 'default' | 'line' = 'default';
  @Input() multiple = false;
  @Input() defaultOpen: string[] = [];
  openItems: string[] = [];
  ngOnInit(): void {
    this.openItems = [...this.defaultOpen];
  }
  isOpen(id: string): boolean {
    return this.openItems.includes(id);
  }
  toggle(id: string): void {
    this.openItems = this.isOpen(id)
      ? this.openItems.filter((item) => item !== id)
      : this.multiple
        ? [...this.openItems, id]
        : [id];
  }
}

// packages/react/src/components.tsx
import {
  forwardRef,
  useId,
  useState,
  type ButtonHTMLAttributes,
  type ChangeEvent,
  type InputHTMLAttributes,
  type ReactNode,
} from 'react';
import {
  accordionRecipe,
  buttonRecipe,
  choiceRecipe,
  fieldRecipe,
  inputRecipe,
  switchRecipe,
} from '@krds-community/recipes';
import type {
  AccordionContractProps,
  AccordionItemContract,
  ButtonContractProps,
  ChoiceContractProps,
  RadioContractProps,
  TextInputContractProps,
} from '@krds-community/recipes';

export interface ButtonProps
  extends ButtonContractProps, Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'disabled'> {}
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  { variant, size, className, type = 'button', disabled, ...props },
  ref,
) {
  const recipe = buttonRecipe({ variant, size, disabled, className });
  return (
    <button
      {...props}
      ref={ref}
      type={type}
      disabled={disabled}
      className={recipe.className}
      data-variant={recipe.data.variant}
      data-size={recipe.data.size}
    />
  );
});

export interface TextInputProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'value' | 'disabled'>,
    Omit<TextInputContractProps, 'label' | 'hint'> {
  label?: ReactNode;
  hint?: ReactNode;
}
export const TextInput = forwardRef<HTMLInputElement, TextInputProps>(function TextInput(
  { label, hint, state = 'default', size = 'medium', id: providedId, className, ...props },
  ref,
) {
  const generatedId = useId();
  const id = providedId ?? `krds-input-${generatedId}`;
  const hintId = hint ? `${id}-hint` : undefined;
  const recipe = inputRecipe({ state, size, className });
  return (
    <label className={fieldRecipe().className}>
      {label ? <span className="krds-field-label">{label}</span> : null}
      <input
        {...props}
        id={id}
        ref={ref}
        className={recipe.className}
        data-state={recipe.data.state}
        data-size={recipe.data.size}
        aria-invalid={state === 'error' ? 'true' : props['aria-invalid']}
        aria-describedby={props['aria-describedby'] ?? hintId}
      />
      {hint ? (
        <span id={hintId} className="krds-field-message" data-state={state}>
          {hint}
        </span>
      ) : null}
    </label>
  );
});

export interface CheckboxProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size' | 'disabled'>,
    Omit<ChoiceContractProps, 'label' | 'description'> {
  label: ReactNode;
  description?: ReactNode;
}
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  { label, description, size, id: providedId, className, ...props },
  ref,
) {
  const generatedId = useId();
  const id = providedId ?? `krds-checkbox-${generatedId}`;
  return (
    <div className={choiceRecipe({ size, className }).className} data-size={size ?? 'medium'}>
      <input {...props} ref={ref} id={id} type="checkbox" />
      <label htmlFor={id}>{label}</label>
      {description ? <span className="krds-field-message">{description}</span> : null}
    </div>
  );
});

export interface RadioProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size' | 'disabled' | 'value'>,
    Omit<RadioContractProps, 'label' | 'description' | 'value'> {
  label: ReactNode;
  value: string;
  description?: ReactNode;
}
export const Radio = forwardRef<HTMLInputElement, RadioProps>(function Radio(
  { label, description, size, id: providedId, className, value, ...props },
  ref,
) {
  const generatedId = useId();
  const id = providedId ?? `krds-radio-${generatedId}`;
  return (
    <div className={choiceRecipe({ size, className }).className} data-size={size ?? 'medium'}>
      <input {...props} ref={ref} id={id} type="radio" value={value} />
      <label htmlFor={id}>{label}</label>
      {description ? <span className="krds-field-message">{description}</span> : null}
    </div>
  );
});

export interface SwitchProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size' | 'disabled'>,
    Omit<ChoiceContractProps, 'label' | 'description'> {
  label: ReactNode;
}
export const Switch = forwardRef<HTMLInputElement, SwitchProps>(function Switch(
  { label, size, id: providedId, className, ...props },
  ref,
) {
  const generatedId = useId();
  const id = providedId ?? `krds-switch-${generatedId}`;
  return (
    <div className={switchRecipe({ size, className }).className} data-size={size ?? 'medium'}>
      <input {...props} ref={ref} id={id} type="checkbox" />
      <label htmlFor={id}>
        <span className="switch-toggle" aria-hidden="true">
          <i />
        </span>
        {label}
      </label>
    </div>
  );
});

export interface AccordionItemData extends Omit<AccordionItemContract, 'title' | 'content'> {
  title: ReactNode;
  content: ReactNode;
}
export interface AccordionProps extends Omit<AccordionContractProps, 'items'> {
  items: AccordionItemData[];
  defaultOpen?: string[];
  className?: string;
}
export function Accordion({
  items,
  type = 'default',
  multiple = false,
  defaultOpen = [],
  className,
}: AccordionProps) {
  const [openItems, setOpenItems] = useState<string[]>(defaultOpen);
  const toggle = (id: string) =>
    setOpenItems((current) =>
      current.includes(id)
        ? current.filter((item) => item !== id)
        : multiple
          ? [...current, id]
          : [id],
    );
  const recipe = accordionRecipe({ type, className });
  return (
    <div className={recipe.className} data-type={type}>
      {items.map((item) => {
        const open = openItems.includes(item.id);
        const headerId = `krds-accordion-header-${item.id}`;
        const panelId = `krds-accordion-panel-${item.id}`;
        return (
          <div className={`krds-accordion-item${open ? ' is-open' : ''}`} key={item.id}>
            <h5 className="krds-accordion-heading">
              <button
                type="button"
                className="krds-accordion-trigger"
                id={headerId}
                aria-expanded={open}
                aria-controls={panelId}
                disabled={item.disabled}
                onClick={() => toggle(item.id)}
              >
                {item.title}
              </button>
            </h5>
            <div
              id={panelId}
              className="krds-accordion-panel"
              role="region"
              aria-labelledby={headerId}
              hidden={!open}
            >
              {item.content}
            </div>
          </div>
        );
      })}
    </div>
  );
}

export const AccordionLine = Accordion;
export const RadioButton = Radio;
export const TextInputSize = TextInput;
export const TextInputState = TextInput;

export type InputChange = ChangeEvent<HTMLInputElement>;
