// packages/angular/src/components/calendar.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId, CALENDAR_MONTHS, type AngularCalendarCell } from "../kinds";

@Component({
  selector: "krds-calendar",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-calendar-area">
      <div
        class="calendar-wrap bottom"
        [class.single]="single"
        [attr.aria-label]="calendarLabel || null"
        tabindex="0"
      >
        <div class="calendar-head">
          <button type="button" class="btn-cal-move prev" (click)="moveCalendarMonth(-1)">
            <span class="sr-only">{{ previousMonthLabel }}</span>
          </button>
          <div class="calendar-switch-wrap">
            <div class="calendar-drop-down">
              <button
                type="button"
                class="btn-cal-switch year"
                role="combobox"
                [attr.aria-label]="yearSelectLabel || null"
                [attr.aria-controls]="id + '-calendar-year'"
                [attr.aria-expanded]="calendarYearOpen"
                aria-haspopup="listbox"
                (click)="toggleCalendarYear()"
              >
                {{ calendarYear }}년
              </button>
              <div class="calendar-select calendar-year-wrap" [class.active]="calendarYearOpen">
                <ul class="sel year" [id]="id + '-calendar-year'" role="listbox">
                  @for (optionYear of calendarYears; track optionYear) {
                    <li role="none">
                      <button
                        type="button"
                        role="option"
                        [class.active]="optionYear === calendarSelectedYear"
                        [attr.aria-selected]="optionYear === calendarSelectedYear"
                        [disabled]="disabledYears.includes(optionYear)"
                        (click)="selectCalendarYear(optionYear)"
                      >
                        {{ optionYear }}년
                      </button>
                    </li>
                  }
                </ul>
              </div>
            </div>
            <div class="calendar-drop-down">
              <button
                type="button"
                class="btn-cal-switch month"
                role="combobox"
                [attr.aria-label]="monthSelectLabel || null"
                [attr.aria-controls]="id + '-calendar-month'"
                [attr.aria-expanded]="calendarMonthOpen"
                aria-haspopup="listbox"
                (click)="toggleCalendarMonth()"
              >
                {{ padCalendarPart(calendarMonth) }}월
              </button>
              <div class="calendar-select calendar-mon-wrap" [class.active]="calendarMonthOpen">
                <ul class="sel month" [id]="id + '-calendar-month'" role="listbox">
                  @for (optionMonth of calendarMonths; track optionMonth) {
                    <li role="none">
                      <button
                        type="button"
                        role="option"
                        [class.active]="optionMonth === calendarSelectedMonth"
                        [attr.aria-selected]="optionMonth === calendarSelectedMonth"
                        [disabled]="disabledMonths.includes(optionMonth)"
                        (click)="selectCalendarMonth(optionMonth)"
                      >
                        {{ padCalendarPart(optionMonth) }}월
                      </button>
                    </li>
                  }
                </ul>
              </div>
            </div>
          </div>
          <button type="button" class="btn-cal-move next" (click)="moveCalendarMonth(1)">
            <span class="sr-only">{{ nextMonthLabel }}</span>
          </button>
        </div>
        <div class="calendar-body">
          <div class="calendar-table-wrap">
            <table class="calendar-tbl">
              <caption>
                {{
                  calendarYear
                }}년
                {{
                  padCalendarPart(calendarMonth)
                }}월
              </caption>
              <thead>
                <tr>
                  @for (weekday of weekdays; track $index) {
                    <th>{{ weekday }}</th>
                  }
                </tr>
              </thead>
              <tbody>
                @for (week of calendarWeeks; track $index) {
                  <tr>
                    @for (cell of week; track cell.date) {
                      <td [class]="cell.className" [attr.data-date]="cell.date">
                        <button
                          type="button"
                          class="btn-set-date"
                          [disabled]="cell.disabled"
                          [attr.aria-pressed]="cell.pressed ? true : null"
                          [attr.aria-label]="cell.ariaLabel"
                          (click)="selectCalendarDate(cell)"
                        >
                          <span>{{ cell.day }}</span>
                        </button>
                      </td>
                    }
                  </tr>
                }
              </tbody>
            </table>
          </div>
        </div>
        <div class="calendar-footer">
          <div class="calendar-btn-wrap">
            <button
              type="button"
              class="krds-btn small text"
              id="get-today"
              (click)="selectCalendarToday()"
            >
              {{ todayLabel }}
            </button>
            <button type="button" class="krds-btn small tertiary" (click)="touch()">
              {{ cancelLabel }}
            </button>
            <button type="button" class="krds-btn small primary" (click)="touch()">
              {{ confirmLabel }}
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class KrdsCalendarComponent {
  @Input() id = createStableId("krds-calendar");
  @Input() single = true;
  @Input() year: number | null = null;
  @Input() month: number | null = null;
  @Input() displayYear: number | null = null;
  @Input() displayMonth: number | null = null;
  @Input() selectedYear: number | null = null;
  @Input() selectedMonth: number | null = null;
  @Input() years: number[] = [];
  @Input() disabledYears: number[] = [];
  @Input() disabledMonths: number[] = [];
  @Input() leadingDays = 0;
  @Input() previousMonthDayCount = 0;
  @Input() dayCount = 0;
  @Input() rangeStartDay: number | null = null;
  @Input() rangeEndDay: number | null = null;
  @Input() todayDay: number | null = null;
  @Input() eventDays: number[] = [];
  @Input() disabledDays: number[] = [];
  @Input() calendarLabel = "";
  @Input() previousMonthLabel = "";
  @Input() nextMonthLabel = "";
  @Input() yearSelectLabel = "";
  @Input() monthSelectLabel = "";
  @Input() weekdays: string[] = [];
  @Input() todayLabel = "";
  @Input() eventLabel = "";
  @Input() cancelLabel = "";
  @Input() confirmLabel = "";
  @Input() value = "";
  @Output() valueChange = new EventEmitter<string>();
  @Output() yearChange = new EventEmitter<number>();
  @Output() monthChange = new EventEmitter<number>();
  calendarYearOpen = false;
  calendarMonthOpen = false;

  private onChange: (value: string | number | boolean | string[]) => void = () => undefined;

  get calendarYear(): number {
    return this.displayYear ?? this.year ?? this.years[0] ?? new Date().getFullYear();
  }

  get calendarMonth(): number {
    return this.displayMonth ?? this.month ?? new Date().getMonth() + 1;
  }

  get calendarSelectedYear(): number {
    return this.selectedYear ?? this.year ?? this.calendarYear;
  }

  get calendarSelectedMonth(): number {
    return this.selectedMonth ?? this.month ?? this.calendarMonth;
  }

  get calendarYears(): number[] {
    return this.years.length > 0 ? this.years : this.calendarYear === 0 ? [] : [this.calendarYear];
  }

  get calendarMonths(): readonly number[] {
    return CALENDAR_MONTHS;
  }

  get calendarWeeks(): AngularCalendarCell[][] {
    const activeYear = this.calendarYear;
    const activeMonth = this.calendarMonth;
    const leadingDays = Math.max(
      0,
      Math.min(6, this.leadingDays || new Date(activeYear, activeMonth - 1, 1).getDay()),
    );
    const dayCount = Math.max(0, this.dayCount || new Date(activeYear, activeMonth, 0).getDate());
    const previousMonthDayCount = Math.max(
      0,
      this.previousMonthDayCount || new Date(activeYear, activeMonth - 1, 0).getDate(),
    );
    const totalCells = Math.ceil((leadingDays + dayCount) / 7) * 7;
    const weeks: AngularCalendarCell[][] = [];

    for (let row = 0; row < totalCells / 7; row += 1) {
      const week: AngularCalendarCell[] = [];
      for (let column = 0; column < 7; column += 1) {
        const index = row * 7 + column;
        const offset = index - leadingDays + 1;
        let day: number;
        let month = activeMonth;
        let year = activeYear;
        let offMonth: "old" | "new" | null = null;

        if (offset < 1) {
          day = previousMonthDayCount + offset;
          offMonth = "old";
          month = activeMonth === 1 ? 12 : activeMonth - 1;
          year = activeMonth === 1 ? activeYear - 1 : activeYear;
        } else if (offset > dayCount) {
          day = offset - dayCount;
          offMonth = "new";
          month = activeMonth === 12 ? 1 : activeMonth + 1;
          year = activeMonth === 12 ? activeYear + 1 : activeYear;
        } else {
          day = offset;
        }

        const currentMonth = offMonth === null;
        const period =
          currentMonth &&
          this.rangeStartDay !== null &&
          this.rangeEndDay !== null &&
          day >= this.rangeStartDay &&
          day <= this.rangeEndDay;
        const start = period && day === this.rangeStartDay;
        const end = period && day === this.rangeEndDay;
        const today = currentMonth && day === this.todayDay;
        const event = currentMonth && this.eventDays.includes(day);
        const dateDisabled = currentMonth && this.disabledDays.includes(day);
        const disabled = !currentMonth || dateDisabled;
        const date = `${year}.${this.padCalendarPart(month)}.${this.padCalendarPart(day)}`;
        const selected = this.value === date;
        const classes = [
          offMonth,
          column === 0 ? "day-off" : null,
          period || (selected && !period) ? "period" : null,
          start || (selected && !period) ? "start" : null,
          end || (selected && !period) ? "end" : null,
          today ? "today" : null,
          event ? "day-event" : null,
          dateDisabled ? "disabled" : null,
        ].filter((className): className is string => className !== null);

        week.push({
          day,
          date,
          className: classes.join(" "),
          disabled,
          pressed: period || selected,
          ariaLabel: today
            ? `${day} ${this.todayLabel}`.trim()
            : event
              ? `${day} ${this.eventLabel}`.trim()
              : null,
        });
      }
      weeks.push(week);
    }

    return weeks;
  }

  padCalendarPart(value: number): string {
    return value.toString().padStart(2, "0");
  }

  toggleCalendarYear(): void {
    this.calendarYearOpen = !this.calendarYearOpen;
    this.calendarMonthOpen = false;
  }

  toggleCalendarMonth(): void {
    this.calendarMonthOpen = !this.calendarMonthOpen;
    this.calendarYearOpen = false;
  }

  selectCalendarYear(year: number): void {
    if (this.disabledYears.includes(year)) return;
    this.year = year;
    this.displayYear = year;
    this.selectedYear = year;
    this.calendarYearOpen = false;
    this.yearChange.emit(year);
  }

  selectCalendarMonth(month: number): void {
    if (this.disabledMonths.includes(month)) return;
    this.month = month;
    this.displayMonth = month;
    this.selectedMonth = month;
    this.calendarMonthOpen = false;
    this.monthChange.emit(month);
  }

  moveCalendarMonth(direction: -1 | 1): void {
    let year = this.calendarYear;
    let month = this.calendarMonth + direction;
    if (month === 0) {
      month = 12;
      year -= 1;
    } else if (month === 13) {
      month = 1;
      year += 1;
    }
    this.year = year;
    this.month = month;
    this.displayYear = year;
    this.displayMonth = month;
    this.selectedYear = year;
    this.selectedMonth = month;
    this.calendarYearOpen = false;
    this.calendarMonthOpen = false;
    this.yearChange.emit(year);
    this.monthChange.emit(month);
  }

  selectCalendarDate(cell: AngularCalendarCell): void {
    if (!cell.disabled) this.setValue(cell.date);
  }

  selectCalendarToday(): void {
    if (this.todayDay === null) return;
    const date = `${this.calendarYear}.${this.padCalendarPart(
      this.calendarMonth,
    )}.${this.padCalendarPart(this.todayDay)}`;
    this.setValue(date);
  }

  private setValue(value: string): void {
    this.value = value;
    this.onChange(value);
    this.valueChange.emit(value);
  }

  touch(): void {
    this.onTouched();
  }

  private onTouched: () => void = () => undefined;
}

// packages/react/src/components/Calendar.tsx
import { useId, useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";

export interface CalendarProps extends Omit<
  HTMLAttributes<HTMLDivElement>,
  "onChange" | "onSelect"
> {
  label?: ReactNode;
  hint?: ReactNode;
  year?: number;
  displayYear?: number;
  selectedYear?: number;
  defaultYear?: number;
  month?: number;
  displayMonth?: number;
  selectedMonth?: number;
  defaultMonth?: number;
  years?: number[];
  disabledYears?: number[];
  disabledMonths?: number[];
  leadingDays?: number;
  previousMonthDayCount?: number;
  dayCount?: number;
  rangeStartDay?: number;
  rangeEndDay?: number;
  todayDay?: number;
  eventDays?: number[];
  disabledDays?: number[];
  value?: string;
  calendarLabel?: string;
  calendarOpenLabel?: string;
  previousMonthLabel?: ReactNode;
  nextMonthLabel?: ReactNode;
  yearSelectLabel?: string;
  monthSelectLabel?: string;
  weekdays?: ReactNode[];
  todayLabel?: ReactNode;
  cancelLabel?: ReactNode;
  confirmLabel?: ReactNode;
  eventLabel?: string;
  onValueChange?: (value: string) => void;
  onChange?: (value: string) => void;
  onYearChange?: (year: number) => void;
  onMonthChange?: (month: number) => void;
  onPreviousMonth?: () => void;
  onNextMonth?: () => void;
  onCancel?: () => void;
  onConfirm?: () => void;
}

export function CalendarSurface({
  single,
  label: _label,
  hint: _hint,
  year: controlledYear,
  displayYear: controlledDisplayYear,
  selectedYear: controlledSelectedYear,
  defaultYear = new Date().getFullYear(),
  month: controlledMonth,
  displayMonth: controlledDisplayMonth,
  selectedMonth: controlledSelectedMonth,
  defaultMonth = new Date().getMonth() + 1,
  years,
  disabledYears = [],
  disabledMonths = [],
  leadingDays: providedLeadingDays,
  previousMonthDayCount: providedPreviousMonthDayCount,
  dayCount: providedDayCount,
  rangeStartDay,
  rangeEndDay,
  todayDay,
  eventDays = [],
  disabledDays = [],
  value: controlledValue,
  defaultValue = "",
  calendarLabel,
  calendarOpenLabel: _calendarOpenLabel,
  previousMonthLabel,
  nextMonthLabel,
  yearSelectLabel,
  monthSelectLabel,
  weekdays = [],
  todayLabel,
  cancelLabel,
  confirmLabel,
  eventLabel,
  onValueChange,
  onChange,
  onYearChange,
  onMonthChange,
  onPreviousMonth,
  onNextMonth,
  onCancel,
  onConfirm,
  className,
  ref,
  ...props
}: CalendarProps & { single?: boolean } & { ref?: Ref<HTMLDivElement> }) {
  const generatedId = useId();
  const yearListId = `krds-calendar-year-${generatedId}`;
  const monthListId = `krds-calendar-month-${generatedId}`;
  const [uncontrolledDisplayYear, setUncontrolledDisplayYear] = useState(
    controlledDisplayYear ?? controlledYear ?? defaultYear,
  );
  const [uncontrolledDisplayMonth, setUncontrolledDisplayMonth] = useState(
    controlledDisplayMonth ?? controlledMonth ?? defaultMonth,
  );
  const [uncontrolledSelectedYear, setUncontrolledSelectedYear] = useState(
    controlledSelectedYear ?? controlledYear ?? defaultYear,
  );
  const [uncontrolledSelectedMonth, setUncontrolledSelectedMonth] = useState(
    controlledSelectedMonth ?? controlledMonth ?? defaultMonth,
  );
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
  const [yearOpen, setYearOpen] = useState(false);
  const [monthOpen, setMonthOpen] = useState(false);
  const displayYear = controlledDisplayYear ?? uncontrolledDisplayYear;
  const displayMonth = controlledDisplayMonth ?? uncontrolledDisplayMonth;
  const selectedYear = controlledSelectedYear ?? controlledYear ?? uncontrolledSelectedYear;
  const selectedMonth = controlledSelectedMonth ?? controlledMonth ?? uncontrolledSelectedMonth;
  const value = controlledValue ?? uncontrolledValue;
  const availableYears = years ?? [selectedYear];
  const leadingDays = providedLeadingDays ?? new Date(displayYear, displayMonth - 1, 1).getDay();
  const previousMonthDayCount =
    providedPreviousMonthDayCount ?? new Date(displayYear, displayMonth - 1, 0).getDate();
  const dayCount = providedDayCount ?? new Date(displayYear, displayMonth, 0).getDate();
  const totalCells = Math.ceil((leadingDays + dayCount) / 7) * 7;
  const pad = (part: number) => String(part).padStart(2, "0");
  const chooseYear = (next: number) => {
    if (controlledDisplayYear === undefined) setUncontrolledDisplayYear(next);
    if (controlledSelectedYear === undefined && controlledYear === undefined) {
      setUncontrolledSelectedYear(next);
    }
    setYearOpen(false);
    onYearChange?.(next);
  };
  const chooseMonth = (next: number) => {
    if (controlledDisplayMonth === undefined) setUncontrolledDisplayMonth(next);
    if (controlledSelectedMonth === undefined && controlledMonth === undefined) {
      setUncontrolledSelectedMonth(next);
    }
    setMonthOpen(false);
    onMonthChange?.(next);
  };
  const cells = Array.from({ length: totalCells }, (_, index) => {
    const offset = index - leadingDays + 1;
    if (offset < 1) {
      const day = previousMonthDayCount + offset;
      const month = displayMonth === 1 ? 12 : displayMonth - 1;
      const year = displayMonth === 1 ? displayYear - 1 : displayYear;
      return { day, month, year, offMonth: "old" as const };
    }
    if (offset > dayCount) {
      const day = offset - dayCount;
      const month = displayMonth === 12 ? 1 : displayMonth + 1;
      const year = displayMonth === 12 ? displayYear + 1 : displayYear;
      return { day, month, year, offMonth: "new" as const };
    }
    return { day: offset, month: displayMonth, year: displayYear, offMonth: undefined };
  });
  return (
    <div {...props} ref={ref} className={cx("krds-calendar-area", className)}>
      <div
        className={cx("calendar-wrap", "bottom", single && "single")}
        aria-label={calendarLabel}
        tabIndex={0}
      >
        <div className="calendar-head">
          <button type="button" className="btn-cal-move prev" onClick={onPreviousMonth}>
            <span className="sr-only">{previousMonthLabel}</span>
          </button>
          <div className="calendar-switch-wrap">
            <div className="calendar-drop-down">
              <button
                type="button"
                className="btn-cal-switch year"
                aria-label={yearSelectLabel}
                aria-controls={yearListId}
                aria-expanded={yearOpen}
                aria-haspopup="listbox"
                role="combobox"
                onClick={() => setYearOpen((open) => !open)}
              >
                {`${displayYear}년`}
              </button>
              <div className="calendar-select calendar-year-wrap">
                <ul className="sel year" id={yearListId} role="listbox">
                  {availableYears.map((year) => (
                    <li role="none" key={year}>
                      <button
                        type="button"
                        role="option"
                        className={year === selectedYear ? "active" : undefined}
                        aria-selected={year === selectedYear}
                        disabled={disabledYears.includes(year)}
                        onClick={() => chooseYear(year)}
                      >
                        {`${year}년`}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
            <div className="calendar-drop-down">
              <button
                type="button"
                className="btn-cal-switch month"
                aria-label={monthSelectLabel}
                aria-controls={monthListId}
                aria-expanded={monthOpen}
                aria-haspopup="listbox"
                role="combobox"
                onClick={() => setMonthOpen((open) => !open)}
              >
                {`${pad(displayMonth)}월`}
              </button>
              <div className="calendar-select calendar-mon-wrap">
                <ul className="sel month" id={monthListId} role="listbox">
                  {Array.from({ length: 12 }, (_, index) => index + 1).map((month) => (
                    <li role="none" key={month}>
                      <button
                        type="button"
                        role="option"
                        className={month === selectedMonth ? "active" : undefined}
                        aria-selected={month === selectedMonth}
                        disabled={disabledMonths.includes(month)}
                        onClick={() => chooseMonth(month)}
                      >
                        {`${pad(month)}월`}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
          <button type="button" className="btn-cal-move next" onClick={onNextMonth}>
            <span className="sr-only">{nextMonthLabel}</span>
          </button>
        </div>
        <div className="calendar-body">
          <div className="calendar-table-wrap">
            <table className="calendar-tbl">
              <caption>{`${displayYear}년 ${pad(displayMonth)}월`}</caption>
              <thead>
                <tr>
                  {weekdays.map((weekday, index) => (
                    <th key={index}>{weekday}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {Array.from({ length: Math.ceil(cells.length / 7) }, (_, rowIndex) => (
                  <tr key={rowIndex}>
                    {cells.slice(rowIndex * 7, rowIndex * 7 + 7).map((cell, columnIndex) => {
                      const currentMonth = cell.offMonth === undefined;
                      const period =
                        currentMonth &&
                        rangeStartDay !== undefined &&
                        rangeEndDay !== undefined &&
                        cell.day >= rangeStartDay &&
                        cell.day <= rangeEndDay;
                      const start = period && cell.day === rangeStartDay;
                      const end = period && cell.day === rangeEndDay;
                      const today = currentMonth && cell.day === todayDay;
                      const event = currentMonth && eventDays.includes(cell.day);
                      const disabled = currentMonth && disabledDays.includes(cell.day);
                      const date = `${cell.year}.${pad(cell.month)}.${pad(cell.day)}`;
                      const selected = value === date;
                      const offMonth = cell.offMonth !== undefined;
                      return (
                        <td
                          className={
                            cx(
                              cell.offMonth,
                              columnIndex === 0 && "day-off",
                              period && "period",
                              start && "start",
                              end && "end",
                              today && "today",
                              event && "day-event",
                              disabled && "disabled",
                              selected && !period && "period start end",
                            ) || undefined
                          }
                          data-date={date}
                          key={date}
                        >
                          <button
                            type="button"
                            className="btn-set-date"
                            disabled={offMonth || disabled}
                            ref={
                              offMonth
                                ? (node) => node?.setAttribute("disabled", "true")
                                : undefined
                            }
                            aria-pressed={period || selected ? true : undefined}
                            aria-label={
                              today
                                ? `${cell.day} ${todayLabel ?? ""}`.trim()
                                : event
                                  ? `${cell.day} ${eventLabel ?? ""}`.trim()
                                  : undefined
                            }
                            onClick={() => {
                              if (controlledValue === undefined) setUncontrolledValue(date);
                              onValueChange?.(date);
                              onChange?.(date);
                            }}
                          >
                            <span>{cell.day}</span>
                          </button>
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        <div className="calendar-footer">
          <div className="calendar-btn-wrap">
            <button type="button" className="krds-btn small text" id="get-today">
              {todayLabel}
            </button>
            <button type="button" className="krds-btn small tertiary" onClick={onCancel}>
              {cancelLabel}
            </button>
            <button type="button" className="krds-btn small primary" onClick={onConfirm}>
              {confirmLabel}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export function Calendar({ ref, ...props }: CalendarProps & { ref?: Ref<HTMLDivElement> }) {
  return <CalendarSurface {...props} {...(ref !== undefined ? { ref } : {})} single />;
}
