// packages/svelte/src/Card.svelte
<script lang="ts">
  import Badge from './Badge.svelte';
  import Button from './Button.svelte';
  import Checkbox from './Checkbox.svelte';

  type Action = { label: string; onClick?: () => void };

  type Props = {
    type?: 'vertical' | 'horizontal';
    image?: string;
    imageAlt?: string;
    title: string;
    description?: string;
    badges?: string[];
    actions?: Action[];
    checkbox?: Record<string, unknown>;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    type = 'vertical',
    image = '',
    imageAlt = '',
    title,
    description = '',
    badges = [],
    actions = [],
    checkbox,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<article {...rest} class={`krds-card ${type} ${rootClass}`}>
  {#if image || badges.length || checkbox}
    <div class="card-top">
      {#if image}
        <img class="card-image" src={image} alt={imageAlt} />
      {/if}
      {#each badges as badge}
        <Badge label={badge} appearance="solid" className="card-badge" />
      {/each}
      {#if checkbox}
        <Checkbox {...checkbox} />
      {/if}
    </div>
  {/if}
  <div class="card-conts">
    <h3 class="card-title">{title}</h3>
    {#if description}
      <p class="card-description">{description}</p>
    {/if}
    {#if actions.length}
      <div class="card-actions">
        {#each actions as action}
          <Button size="small" variant="primary" onclick={action.onClick}>{action.label}</Button>
        {/each}
      </div>
    {/if}
  </div>
</article>

// packages/react/src/components/Card.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { Badge } from "./Badge.js";
import { Button } from "./Button.js";
import { Checkbox, type CheckboxProps } from "./Checkbox.js";
import type { BoxProps } from "./_utils.js";

export interface CardAction {
  label: string;
  onClick?: () => void;
}

export interface CardProps extends BoxProps {
  type?: "vertical" | "horizontal";
  image?: string;
  imageAlt?: string;
  title: ReactNode;
  description?: ReactNode;
  badges?: string[];
  actions?: CardAction[];
  checkbox?: CheckboxProps;
}

export function Card({
  type = "vertical",
  image,
  imageAlt = "",
  title,
  description,
  badges,
  actions,
  checkbox,
  className,
}: CardProps) {
  const hasTop = Boolean(image || badges?.length || checkbox);
  return (
    <article className={cx("krds-card", type, className)}>
      {hasTop ? (
        <div className="card-top">
          {checkbox ? <Checkbox {...checkbox} /> : null}
          {image ? <img className="card-image" src={image} alt={imageAlt} /> : null}
          {badges?.length ? (
            <div className="card-badge">
              {badges.map((badge) => (
                <Badge key={badge} tone="primary" appearance="solid">
                  {badge}
                </Badge>
              ))}
            </div>
          ) : null}
        </div>
      ) : null}
      <div className="card-conts">
        <h3 className="card-title">{title}</h3>
        {description ? <p className="card-description">{description}</p> : null}
        {actions?.length ? (
          <div className="card-actions">
            {actions.map((action) => (
              <Button
                key={action.label}
                type="button"
                size="small"
                variant="primary"
                onClick={action.onClick}
              >
                {action.label}
              </Button>
            ))}
          </div>
        ) : null}
      </div>
    </article>
  );
}
