// packages/svelte/src/Checkbox.svelte
<script lang="ts">
  import type { ChoiceContractProps } from '@krds-community/recipes';
  type Props = ChoiceContractProps & {
    checked?: boolean;
    indeterminate?: boolean;
    class?: string;
    className?: string;
  };
  const generatedId = $props.id();
  let {
    checked = $bindable(false),
    indeterminate = false,
    label = '',
    description = '',
    size,
    id = generatedId,
    disabled = false,
    class: classValue = '',
    className = '',
    ...restProps
  }: Props = $props();
  let input: HTMLInputElement;
  $effect(() => {
    input && (input.indeterminate = indeterminate);
  });
</script>

<div class={`krds-form-check${size ? ` ${size}` : ''}${classValue ? ` ${classValue}` : ''}${className ? ` ${className}` : ''}`}>
  <input {...restProps} type="checkbox" {id} bind:this={input} bind:checked {disabled} aria-describedby={description ? `${id}-description` : undefined} />
  <label for={id}>{label}</label>
  {#if description}
    <div class="krds-form-check-cnt">
      <p id={`${id}-description`} class="krds-form-check-p">{description}</p>
    </div>
  {/if}
</div>

// packages/react/src/components/Checkbox.tsx
import { useId, type InputHTMLAttributes, type ReactNode, type Ref } from "react";
import { choiceRecipe } from "@krds-community/recipes";
import type { ChoiceContractProps } from "@krds-community/recipes";

function joinAriaIds(...ids: Array<string | undefined>) {
  const unique = new Set(ids.flatMap((value) => value?.split(/\s+/).filter(Boolean) ?? []));
  return unique.size ? Array.from(unique).join(" ") : undefined;
}

export interface CheckboxProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, "type" | "size" | "disabled">,
    Omit<ChoiceContractProps, "label" | "description"> {
  label: ReactNode;
  description?: ReactNode;
}
export function Checkbox({
  label,
  description,
  size,
  id: providedId,
  className,
  ref,
  ...props
}: CheckboxProps & { ref?: Ref<HTMLInputElement> }) {
  const generatedId = useId();
  const id = providedId ?? `krds-checkbox-${generatedId}`;
  const descriptionId = description ? `${id}-description` : undefined;
  const recipe = choiceRecipe({ size, className });
  return (
    <div className={recipe.className}>
      <input
        {...props}
        ref={ref}
        id={id}
        type="checkbox"
        aria-describedby={joinAriaIds(props["aria-describedby"], descriptionId)}
      />
      <label htmlFor={id}>{label}</label>
      {description ? (
        <div className="krds-form-check-cnt">
          <p id={descriptionId} className="krds-form-check-p">
            {description}
          </p>
        </div>
      ) : null}
    </div>
  );
}
