// packages/angular/src/components/chip.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId } from "../kinds";

export interface KrdsChipOption {
  value: string;
  label: string;
  disabled?: boolean;
}

@Component({
  selector: "krds-chip",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      [class]="'krds-chip ' + type + ' ' + size"
      [attr.role]="type === 'single' ? 'radiogroup' : 'group'"
      [attr.aria-label]="ariaLabel"
    >
      @for (option of options; track $index) {
        <button
          type="button"
          [class]="'krds-btn small text chip' + (isSelected(option) ? ' active' : '')"
          [attr.aria-pressed]="isSelected(option)"
          [disabled]="option.disabled ?? false"
          (click)="toggle(option)"
        >
          {{ option.label }}
        </button>
      }
    </div>
  `,
})
export class KrdsChipComponent {
  @Input() id = createStableId("krds-chip");
  @Input() type: "single" | "multi" = "single";
  @Input() size: "large" | "medium" = "medium";
  @Input() options: KrdsChipOption[] = [];
  @Input() selected: string | string[] | undefined = undefined;
  @Input() defaultSelected: string | string[] | undefined = undefined;
  @Input() ariaLabel = "선택";
  @Output() change = new EventEmitter<string | string[]>();

  private internalSelected: string | string[] | null = null;

  get isControlled(): boolean {
    return this.selected !== undefined;
  }

  get currentSelected(): string | string[] {
    if (this.selected !== undefined) return this.selected;
    if (this.internalSelected !== null) return this.internalSelected;
    return this.defaultSelected ?? (this.type === "multi" ? [] : "");
  }

  isSelected(option: KrdsChipOption): boolean {
    const current = this.currentSelected;
    return typeof current === "string" ? current === option.value : current.includes(option.value);
  }

  toggle(option: KrdsChipOption): void {
    if (option.disabled) return;
    if (this.type === "single") {
      if (!this.isControlled) {
        this.internalSelected = option.value;
      }
      this.change.emit(option.value);
      return;
    }
    const next = [...(this.currentSelected as string[])];
    const index = next.indexOf(option.value);
    if (index >= 0) {
      next.splice(index, 1);
    } else {
      next.push(option.value);
    }
    if (!this.isControlled) {
      this.internalSelected = next;
    }
    this.change.emit(next);
  }
}

// packages/react/src/components/Chip.tsx
import { useState } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface ChipOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface ChipProps extends Omit<BoxProps, "selected" | "options"> {
  type?: "single" | "multi";
  size?: "large" | "medium";
  options: ChipOption[];
  selected?: string | string[];
  defaultSelected?: string | string[];
  onChange?: (value: string | string[]) => void;
  ariaLabel?: string;
}

export function Chip({
  type = "single",
  size = "medium",
  options,
  selected: controlledSelected,
  defaultSelected,
  onChange,
  ariaLabel = "선택",
  className,
}: ChipProps) {
  const controlled = controlledSelected !== undefined;
  const [internalSelected, setInternalSelected] = useState<string | string[] | undefined>(
    defaultSelected ?? (type === "multi" ? [] : undefined),
  );
  const current = controlled ? controlledSelected : internalSelected;

  const isSelected = (option: ChipOption) =>
    type === "multi"
      ? Array.isArray(current) && current.includes(option.value)
      : current === option.value;

  const toggle = (option: ChipOption) => {
    if (option.disabled) return;
    if (type === "multi") {
      const next = Array.isArray(current) && current.includes(option.value)
        ? current.filter((item) => item !== option.value)
        : [...(Array.isArray(current) ? current : []), option.value];
      if (!controlled) setInternalSelected(next);
      onChange?.(next);
    } else {
      if (current === option.value) return;
      if (!controlled) setInternalSelected(option.value);
      onChange?.(option.value);
    }
  };

  return (
    <div
      className={cx("krds-chip", type, size, className)}
      role={type === "single" ? "radiogroup" : "group"}
      aria-label={ariaLabel}
    >
      {options.map((option) => (
        <button
          key={option.value}
          type="button"
          className={cx("krds-btn small text chip", isSelected(option) && "active")}
          aria-pressed={isSelected(option)}
          disabled={option.disabled}
          onClick={() => toggle(option)}
        >
          {option.label}
        </button>
      ))}
    </div>
  );
}
