// packages/solid/src/components/CriticalAlerts.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import { labelOf } from "../shared.js";
import type { AlertItem } from "../shared.js";

export interface CriticalAlertsProps {
  class?: string;
  className?: string;
  items: AlertItem[];
  actionLabel?: string;
  [key: string]: unknown;
}

export function CriticalAlerts(rawProps: CriticalAlertsProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, ["class", "className", "items", "actionLabel"]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`main-urgent-wrap${className() ? ` ${className()}` : ""}`}
      role="alert"
    >
      <ul class="krds-critical-alerts">
        <For each={props.items}>
          {(item) => {
            const alert = () =>
              typeof item === "string" || typeof item === "number"
                ? undefined
                : (item as AlertItem);
            const badge = () => alert()?.badge;
            const href = () => alert()?.href;
            return (
              <li>
                <div class="critical-ban">
                  <Show when={badge()}>
                    <span class={`critical-badge ${badge()}`}>{alert()?.badgeLabel}</span>
                  </Show>
                  <p class="critical-txt">{alert()?.message ?? alert()?.text ?? labelOf(item)}</p>
                  <Show when={href()}>
                    <a class="krds-btn medium basic link" href={href()}>
                      <span class="m-hide">{alert()?.linkLabel ?? props.actionLabel}</span>{" "}
                      <i class="svg-icon ico-angle right" />
                    </a>
                  </Show>
                </div>
              </li>
            );
          }}
        </For>
      </ul>
    </div>
  );
}

// packages/react/src/components/CriticalAlerts.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

export interface CriticalAlertItem {
  id?: string;
  badge?: ReactNode;
  badgeLabel?: ReactNode;
  tone?: "danger" | "ok" | "info";
  message?: ReactNode;
  title?: ReactNode;
  text?: ReactNode;
  href?: string;
  linkLabel?: ReactNode;
}

export interface CriticalAlertsProps extends Omit<BoxProps, "items"> {
  items?: Array<string | CriticalAlertItem>;
}

export function CriticalAlerts({ items = [], className }: CriticalAlertsProps) {
  return (
    <div className="main-urgent-wrap" role="alert">
      <ul className={cx("krds-critical-alerts", className)}>
        {items.map((rawItem, index) => {
          const item: CriticalAlertItem =
            typeof rawItem === "string" ? { message: rawItem } : rawItem;
          const badgeTone =
            item.tone ??
            (item.badge === "danger" || item.badge === "ok" || item.badge === "info"
              ? item.badge
              : undefined);
          const badgeLabel = item.badgeLabel ?? (item.badge === badgeTone ? undefined : item.badge);
          const message = item.message ?? item.text ?? item.title;
          return (
            <li key={item.id ?? index}>
              <div className="critical-ban">
                {badgeLabel ? (
                  <span className={cx("critical-badge", badgeTone)}>{badgeLabel}</span>
                ) : null}
                <p className="critical-txt">{message}</p>
                {item.linkLabel ? (
                  <a href={item.href ?? "#"} className="krds-btn medium link basic">
                    <span className="m-hide">{item.linkLabel}</span>{" "}
                    <SvgIcon name="ico-angle right" />
                  </a>
                ) : null}
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
