// packages/svelte/src/Footer.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf, labelOf, hrefOf, flagOf } from './lib/shared.js';

  type NavItem = {
    label?: string;
    href?: string;
    [key: string]: unknown;
  };

  type ContactItem = {
    title?: string;
    description?: string;
    [key: string]: unknown;
  };

  type SocialLink = NavItem & {
    target?: string;
    icon?: string;
  };

  type Props = {
    id?: string;
    relatedSites?: NavItem[];
    logoLabel?: string;
    address?: string;
    contacts?: ContactItem[];
    links?: NavItem[];
    socialLinks?: SocialLink[];
    policyLinks?: NavItem[];
    organization?: string;
    description?: string;
    copyright?: string;
    children?: Snippet;
    className?: string;
    class?: string;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-footer',
    relatedSites = [],
    logoLabel = '',
    address = '',
    contacts = [],
    links = [],
    socialLinks = [],
    policyLinks = [],
    organization = '',
    description = '',
    copyright = '',
    children,
    className = '',
    class: classProp = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<footer {...rest} id={id} class={rootClass}>
  <div class="foot-quick">
    <div class="inner">
      {#each relatedSites as item}
        <button class="link" type="button" title={fieldOf(item, 'title') || undefined}>
          {labelOf(item)}
        </button>
      {/each}
    </div>
  </div>
  <div class="inner">
    <div class="f-logo"><span class="sr-only">{logoLabel}</span></div>
    <div class="f-cnt">
      <div class="f-info">
        <p class="info-addr">{address}</p>
        <ul class="info-cs">
          {#each contacts as contact}
            <li>
              <strong class="strong">{fieldOf(contact, 'title')}</strong><span class="span">{fieldOf(contact, 'description')}</span>
            </li>
          {/each}
        </ul>
      </div>
      <div class="f-link">
        <div class="link-go">
          {#each links as item}
            <a href={hrefOf(item)} class="krds-btn medium text">
              {labelOf(item)} <i class="svg-icon ico-angle right"></i>
            </a>
          {/each}
        </div>
        <div class="link-sns">
          {#each socialLinks as item}
            <a
              href={hrefOf(item)}
              class="krds-btn xlarge icon border"
              target={fieldOf(item, 'target') || undefined}
              title={fieldOf(item, 'title') || undefined}
            >
              <span class="sr-only">{labelOf(item)}</span>
              <i class={`svg-icon ico-${fieldOf(item, 'icon')}`}></i>
            </a>
          {/each}
        </div>
      </div>
    </div>
    <div class="f-btm">
      <div class="f-btm-text">
        <div class="f-menu">
          {#each policyLinks as item}
            <a class:point={flagOf(item, 'emphasis')} href={hrefOf(item)}>{labelOf(item)}</a>
          {/each}
        </div>
        <p class="f-copy">{copyright}</p>
      </div>
      <div class="krds-identifier">
        <span class="logo"><span class="sr-only">{organization}</span></span>
        <span class="ban-txt">{description}</span>
      </div>
    </div>
  </div>
</footer>

// packages/react/src/components/Footer.tsx
import { type HTMLAttributes, type ReactNode, type Ref } from "react";
import { SvgIcon } from "./_utils.js";

export interface FooterLink {
  id?: string;
  label: ReactNode;
  href?: string;
  target?: string;
  title?: string;
  icon?: string;
  emphasis?: boolean;
}
export interface FooterProps extends Omit<HTMLAttributes<HTMLElement>, "children" | "title"> {
  relatedSites?: FooterLink[];
  logoLabel?: ReactNode;
  address?: ReactNode;
  contacts?: Array<{ title: ReactNode; description?: ReactNode }>;
  links?: FooterLink[];
  socialLinks?: FooterLink[];
  policyLinks?: FooterLink[];
  copyright?: ReactNode;
  organization?: ReactNode;
  description?: ReactNode;
  onRelatedSite?: (item: FooterLink) => void;
}
export function Footer({
  relatedSites = [],
  logoLabel,
  address,
  contacts = [],
  links = [],
  socialLinks = [],
  policyLinks = [],
  copyright,
  organization,
  description,
  onRelatedSite,
  id = "krds-footer",
  className,
  ref,
  ...props
}: FooterProps & { ref?: Ref<HTMLElement> }) {
  return (
    <footer {...props} ref={ref} id={id} className={className}>
      <div className="foot-quick">
        <div className="inner">
          {relatedSites.map((item) => (
            <button
              type="button"
              className="link"
              title={item.title}
              onClick={() => onRelatedSite?.(item)}
              key={item.id ?? String(item.label)}
            >
              {item.label}
            </button>
          ))}
        </div>
      </div>
      <div className="inner">
        <div className="f-logo">
          <span className="sr-only">{logoLabel}</span>
        </div>
        <div className="f-cnt">
          <div className="f-info">
            <p className="info-addr">{address}</p>
            <ul className="info-cs">
              {contacts.map((contact, index) => (
                <li key={index}>
                  <strong className="strong">{contact.title}</strong>
                  <span className="span">{contact.description}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="f-link">
            <div className="link-go">
              {links.map((item) => (
                <a
                  href={item.href ?? "#"}
                  className="krds-btn medium text"
                  target={item.target}
                  title={item.title}
                  key={item.id ?? String(item.label)}
                >
                  {item.label} <SvgIcon name="ico-angle right" />
                </a>
              ))}
            </div>
            <div className="link-sns">
              {socialLinks.map((item) => (
                <a
                  href={item.href ?? "#"}
                  className="krds-btn xlarge icon border"
                  target={item.target}
                  title={item.title}
                  key={item.id ?? String(item.label)}
                >
                  <span className="sr-only">{item.label}</span>
                  <SvgIcon name={`ico-${item.icon}`} />
                </a>
              ))}
            </div>
          </div>
        </div>
        <div className="f-btm">
          <div className="f-btm-text">
            <div className="f-menu">
              {policyLinks.map((item) => (
                <a
                  href={item.href ?? "#"}
                  className={item.emphasis ? "point" : undefined}
                  key={item.id ?? String(item.label)}
                >
                  {item.label}
                </a>
              ))}
            </div>
            <p className="f-copy">{copyright}</p>
          </div>
          <div className="krds-identifier">
            <span className="logo">
              <span className="sr-only">{organization}</span>
            </span>
            <span className="ban-txt">{description}</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
