// packages/solid/src/components/HelpPanel.tsx
import {
  For,
  Show,
  createEffect,
  createSignal,
  createUniqueId,
  mergeProps,
  splitProps,
  type JSX,
} from "solid-js";

// ====== Exported types ======

export interface HelpPanelTab {
  id: string;
  panelId: string;
  label: string;
  value?: string;
  disabled?: boolean;
}

export interface HelpPanelLink {
  id?: string;
  label: JSX.Element;
  href?: string;
  target?: string;
  title?: string;
  icon?: string;
}

export interface HelpPanelRelatedGroup {
  id?: string;
  title: JSX.Element;
  links: HelpPanelLink[];
}

export interface HelpPanelTask {
  id?: string;
  title: JSX.Element;
  current?: boolean;
  summary: JSX.Element;
  steps: JSX.Element[];
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export interface HelpPanelProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  open?: boolean;
  defaultOpen?: boolean;
  activeTab?: string;
  defaultActiveTab?: string;
  tabs?: HelpPanelTab[];
  label?: JSX.Element;
  title?: JSX.Element;
  selectedLabel?: JSX.Element;
  helpTitle?: JSX.Element;
  helpDescription?: JSX.Element;
  downloadLinks?: HelpPanelLink[];
  relatedGroups?: HelpPanelRelatedGroup[];
  tutorialTitle?: JSX.Element;
  tutorialBackTitle?: string;
  backTitle?: string;
  externalTitle?: string;
  tasks?: HelpPanelTask[];
  stopLabel?: JSX.Element;
  collapseLabel?: JSX.Element;
  onOpenChange?: (open: boolean) => void;
  onActiveTabChange?: (tab: string) => void;
  onStop?: () => void;
  [key: string]: unknown;
}

// ====== Helpers (inlined from React _utils) ======

function SvgIcon({ name }: { name: string }) {
  return <i class={`svg-icon ${name}`} />;
}

function inlineSpacedText(
  value: JSX.Element | string | undefined,
  leading: boolean,
  trailing: boolean,
): JSX.Element | undefined {
  const val = value;
  if (typeof val === "string") {
    const parts = val.split(" ");
    if (parts.length < 2) {
      let result = val;
      if (leading) result = " " + result;
      if (trailing) result = result + " ";
      return result as unknown as JSX.Element;
    }
    let result = val;
    if (leading) result = " " + result;
    if (trailing) result = result + " ";
    return result as unknown as JSX.Element;
  }
  return val as JSX.Element;
}

// ====== Task disclosure subcomponent ======

function HelpTaskDisclosure({ task, panelId }: { task: HelpPanelTask; panelId: string }) {
  const [uncontrolledOpen, setUncontrolledOpen] = createSignal(task.defaultOpen ?? false);
  const open = () => task.open ?? uncontrolledOpen();
  let expandWrapRef: HTMLDivElement | undefined;
  createEffect(() => {
    if (expandWrapRef) {
      if (!open()) {
        expandWrapRef.setAttribute("inert", "");
      } else {
        expandWrapRef.removeAttribute("inert");
      }
    }
  });
  return (
    <div
      classList={{
        "krds-disclosure": true,
        "conts-expand-area": true,
        active: open(),
      }}
    >
      <button
        type="button"
        class="btn-conts-expand"
        aria-expanded={open()}
        aria-controls={panelId}
        onClick={() => {
          const next = !open();
          if (task.open === undefined) setUncontrolledOpen(next);
          task.onOpenChange?.(next);
        }}
      >
        {task.summary}
      </button>
      <div
        id={panelId}
        class="expand-wrap"
        ref={(element) => {
          expandWrapRef = element;
        }}
      >
        <div class="expand-in">
          <ul class="krds-info-list decimal" role="list">
            <For each={task.steps}>{(step, _index) => <li role="listitem">{step}</li>}</For>
          </ul>
        </div>
      </div>
    </div>
  );
}

// ====== Main surface component ======

function HelpPanelSurface(rawProps: HelpPanelProps & { tutorialDefault?: boolean }) {
  const uid = createUniqueId();
  const merged = mergeProps(
    {
      tabs: [] as HelpPanelTab[],
      downloadLinks: [] as HelpPanelLink[],
      relatedGroups: [] as HelpPanelRelatedGroup[],
      tasks: [] as HelpPanelTask[],
      defaultOpen: false,
      tutorialDefault: false,
    },
    rawProps,
  );
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "open",
    "defaultOpen",
    "activeTab",
    "defaultActiveTab",
    "tabs",
    "label",
    "title",
    "selectedLabel",
    "helpTitle",
    "helpDescription",
    "downloadLinks",
    "relatedGroups",
    "tutorialTitle",
    "tutorialBackTitle",
    "backTitle",
    "externalTitle",
    "tasks",
    "stopLabel",
    "collapseLabel",
    "onOpenChange",
    "onActiveTabChange",
    "onStop",
    "tutorialDefault",
  ]);

  const className = () => props.class ?? props.className ?? "";

  const initialTab =
    props.defaultActiveTab ??
    (props.tutorialDefault
      ? (props.tabs.find((tab) => tab.value === "tutorial")?.value ??
        props.tabs.find((tab) => tab.value === "tutorial")?.id)
      : undefined) ??
    props.tabs[0]?.value ??
    props.tabs[0]?.id ??
    "";

  const [uncontrolledOpen, setUncontrolledOpen] = createSignal(props.defaultOpen);
  const [uncontrolledActiveTab, setUncontrolledActiveTab] = createSignal(initialTab);

  const open = () => props.open ?? uncontrolledOpen();
  const activeTab = () => props.activeTab ?? uncontrolledActiveTab();

  const setOpen = (next: boolean) => {
    if (props.open === undefined) setUncontrolledOpen(next);
    props.onOpenChange?.(next);
  };

  const setActiveTab = (next: string) => {
    if (props.activeTab === undefined) setUncontrolledActiveTab(next);
    props.onActiveTabChange?.(next);
  };

  return (
    <div
      {...(native as Record<string, any>)}
      classList={{
        "krds-help-panel": true,
        expand: open(),
        [className()]: !!className(),
      }}
    >
      <div class="help-panel-wrap" tabIndex={open() ? 0 : undefined}>
        <div class="help-conts-area">
          <div class="krds-tab-area layer">
            <div class="tab line">
              <ul role="tablist">
                <For each={props.tabs}>
                  {(tab) => {
                    const tabValue = tab.value ?? tab.id;
                    const active = () => {
                      const av = activeTab();
                      return tabValue === av || tabValue.replace(/-tab$/, "") === av;
                    };
                    return (
                      <li role="presentation" classList={{ active: active() }}>
                        <button
                          id={tab.id}
                          type="button"
                          role="tab"
                          aria-selected={active()}
                          aria-controls={tab.panelId}
                          tabIndex={active() ? 0 : -1}
                          class="btn-tab"
                          disabled={tab.disabled}
                          onClick={() => {
                            if (!tab.disabled) setActiveTab(tabValue);
                          }}
                        >
                          {tab.label}
                          {active() && props.selectedLabel ? (
                            <i class="sr-only created"> {props.selectedLabel}</i>
                          ) : null}
                        </button>
                      </li>
                    );
                  }}
                </For>
              </ul>
            </div>
            <div class="tab-conts-wrap">
              <For each={props.tabs}>
                {(tab, tabIndex) => {
                  const tabValue = tab.value ?? tab.id;
                  const active = () => {
                    const av = activeTab();
                    return tabValue === av || tabValue.replace(/-tab$/, "") === av;
                  };
                  const helpTab = () =>
                    tabValue === "help" || (tabIndex() === 0 && tabValue !== "tutorial");
                  return (
                    <section
                      id={tab.panelId}
                      role="tabpanel"
                      aria-labelledby={tab.id}
                      hidden={!active()}
                      classList={{
                        "tab-conts": true,
                        active: active(),
                      }}
                    >
                      <Show when={tab.label}>
                        <h3 class="sr-only">{tab.label}</h3>
                      </Show>
                      <div class="help-conts-area-inner">
                        <Show when={helpTab()}>
                          <div class="conts-area help-conts">
                            <div class="conts-wrap">
                              <h4 class="help-title">
                                {inlineSpacedText(props.helpTitle, false, true)}
                                <span class="krds-btn medium icon">
                                  <span class="sr-only">{props.label ?? props.title}</span>
                                  <SvgIcon name="ico-help" />
                                </span>
                              </h4>
                              <div class="conts-desc">
                                <p>{props.helpDescription ?? props.children}</p>
                              </div>
                              <ul class="link-list">
                                <For each={props.downloadLinks}>
                                  {(link) => (
                                    <li>
                                      <a
                                        href={link.href ?? "#"}
                                        target={link.target}
                                        title={link.title ?? props.externalTitle}
                                        class="krds-btn xsmall link basic"
                                      >
                                        {inlineSpacedText(link.label, false, true)}
                                        <SvgIcon name="ico-go" />
                                      </a>
                                    </li>
                                  )}
                                </For>
                              </ul>
                            </div>
                          </div>
                          <div class="conts-area related-service">
                            <For each={props.relatedGroups}>
                              {(group) => (
                                <div class="conts-wrap">
                                  <h4 class="help-title">{group.title}</h4>
                                  <ul class="link-list">
                                    <For each={group.links}>
                                      {(link) => {
                                        const rawIcon = link.icon;
                                        const isTrailingOnly = rawIcon === "ico-angle right";
                                        const icon =
                                          !isTrailingOnly && rawIcon
                                            ? rawIcon.startsWith("ico-")
                                              ? rawIcon
                                              : `ico-${rawIcon}`
                                            : undefined;
                                        const hasLeadingIcon = !!icon && !isTrailingOnly;
                                        const hasTrailingIcon = !icon || isTrailingOnly;
                                        return (
                                          <li>
                                            <a
                                              href={link.href ?? "#"}
                                              class="krds-btn xsmall link basic"
                                            >
                                              {hasLeadingIcon ? <SvgIcon name={icon!} /> : null}
                                              {inlineSpacedText(
                                                link.label,
                                                hasLeadingIcon,
                                                hasTrailingIcon,
                                              )}
                                              {hasTrailingIcon ? (
                                                <SvgIcon name="ico-angle right" />
                                              ) : null}
                                            </a>
                                          </li>
                                        );
                                      }}
                                    </For>
                                  </ul>
                                </div>
                              )}
                            </For>
                          </div>
                        </Show>
                        <Show when={!helpTab()}>
                          <div class="conts-area">
                            <h4 class="help-title">
                              <a href="#;" title={props.tutorialBackTitle ?? props.backTitle}>
                                {props.tutorialTitle}
                              </a>
                            </h4>
                            <ul class="coach-help-process">
                              <For each={props.tasks}>
                                {(task, taskIndex) => (
                                  <li>
                                    <h4
                                      classList={{
                                        tit: true,
                                        current: task.current,
                                      }}
                                    >
                                      {task.title}
                                    </h4>
                                    <HelpTaskDisclosure
                                      task={task}
                                      panelId={`krds-help-task-${uid}-${taskIndex()}`}
                                    />
                                  </li>
                                )}
                              </For>
                            </ul>
                          </div>
                          <div class="help-panel-action">
                            <button
                              type="button"
                              class="krds-btn medium secondary coach-btn-stop"
                              onClick={props.onStop}
                            >
                              {props.stopLabel}
                            </button>
                          </div>
                        </Show>
                      </div>
                    </section>
                  );
                }}
              </For>
            </div>
          </div>
          <button
            type="button"
            class="krds-btn small tertiary btn-help-panel fold"
            onClick={() => setOpen(false)}
          >
            <span class="sr-only">{props.label ?? props.title}</span>
            {inlineSpacedText(props.collapseLabel ?? props.label ?? props.title, true, true)}
            <SvgIcon name="ico-angle right" />
          </button>
        </div>
      </div>
    </div>
  );
}

// ====== Public exports ======

export function HelpPanel(props: HelpPanelProps) {
  return <HelpPanelSurface {...props} />;
}

export function TutorialPanel(props: HelpPanelProps) {
  return <HelpPanelSurface {...props} tutorialDefault={true} />;
}

// packages/react/src/components/HelpPanel.tsx
import { useId, useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, inlineSpacedText } from "./_utils.js";

export interface HelpPanelTab {
  id: string;
  panelId: string;
  label: string;
  value?: string;
  disabled?: boolean;
}
export interface HelpPanelLink {
  id?: string;
  label: ReactNode;
  href?: string;
  target?: string;
  title?: string;
  icon?: string;
}
export interface HelpPanelRelatedGroup {
  id?: string;
  title: ReactNode;
  links: HelpPanelLink[];
}
export interface HelpPanelTask {
  id?: string;
  title: ReactNode;
  current?: boolean;
  summary: ReactNode;
  steps: ReactNode[];
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
}
export interface HelpPanelProps extends Omit<
  HTMLAttributes<HTMLDivElement>,
  "children" | "title" | "onChange"
> {
  children?: ReactNode;
  open?: boolean;
  defaultOpen?: boolean;
  activeTab?: string;
  defaultActiveTab?: string;
  tabs?: HelpPanelTab[];
  label?: ReactNode;
  title?: ReactNode;
  selectedLabel?: ReactNode;
  helpTitle?: ReactNode;
  helpDescription?: ReactNode;
  downloadLinks?: HelpPanelLink[];
  relatedGroups?: HelpPanelRelatedGroup[];
  tutorialTitle?: ReactNode;
  tutorialBackTitle?: string;
  backTitle?: string;
  externalTitle?: string;
  tasks?: HelpPanelTask[];
  stopLabel?: ReactNode;
  collapseLabel?: ReactNode;
  onOpenChange?: (open: boolean) => void;
  onActiveTabChange?: (tab: string) => void;
  onStop?: () => void;
}

export function HelpTaskDisclosure({ task, panelId }: { task: HelpPanelTask; panelId: string }) {
  const [uncontrolledOpen, setUncontrolledOpen] = useState(task.defaultOpen ?? false);
  const open = task.open ?? uncontrolledOpen;
  return (
    <div className={cx("krds-disclosure", "conts-expand-area", open && "active")}>
      <button
        type="button"
        className="btn-conts-expand"
        aria-expanded={open}
        aria-controls={panelId}
        onClick={() => {
          const next = !open;
          if (task.open === undefined) setUncontrolledOpen(next);
          task.onOpenChange?.(next);
        }}
      >
        {task.summary}
      </button>
      <div id={panelId} className="expand-wrap" inert={!open}>
        <div className="expand-in">
          <ul className="krds-info-list decimal" role="list">
            {task.steps.map((step, index) => (
              <li role="listitem" key={index}>
                {step}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

export function HelpPanelSurface({
  tutorialDefault = false,
  children,
  open: controlledOpen,
  defaultOpen = false,
  activeTab: controlledActiveTab,
  defaultActiveTab,
  tabs = [],
  label,
  title,
  selectedLabel,
  helpTitle,
  helpDescription,
  downloadLinks = [],
  relatedGroups = [],
  tutorialTitle,
  tutorialBackTitle,
  backTitle,
  externalTitle,
  tasks = [],
  stopLabel,
  collapseLabel,
  onOpenChange,
  onActiveTabChange,
  onStop,
  className,
  ref,
  ...props
}: HelpPanelProps & { tutorialDefault?: boolean } & { ref?: Ref<HTMLDivElement> }) {
  const generatedId = useId();
  const initialTab =
    defaultActiveTab ??
    (tutorialDefault
      ? (tabs.find((tab) => tab.value === "tutorial")?.value ??
        tabs.find((tab) => tab.value === "tutorial")?.id)
      : undefined) ??
    tabs[0]?.value ??
    tabs[0]?.id ??
    "";
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const [uncontrolledActiveTab, setUncontrolledActiveTab] = useState(initialTab);
  const open = controlledOpen ?? uncontrolledOpen;
  const activeTab = controlledActiveTab ?? uncontrolledActiveTab;
  const setOpen = (next: boolean) => {
    if (controlledOpen === undefined) setUncontrolledOpen(next);
    onOpenChange?.(next);
  };
  const setActiveTab = (next: string) => {
    if (controlledActiveTab === undefined) setUncontrolledActiveTab(next);
    onActiveTabChange?.(next);
  };
  return (
    <div {...props} ref={ref} className={cx("krds-help-panel", open && "expand", className)}>
      <div className="help-panel-wrap" tabIndex={open ? 0 : undefined}>
        <div className="help-conts-area">
          <div className="krds-tab-area layer">
            <div className="tab line">
              <ul role="tablist">
                {tabs.map((tab) => {
                  const tabValue = tab.value ?? tab.id;
                  const active = tabValue === activeTab;
                  return (
                    <li className={active ? "active" : undefined} role="presentation" key={tab.id}>
                      <button
                        id={tab.id}
                        type="button"
                        role="tab"
                        aria-selected={active}
                        aria-controls={tab.panelId}
                        tabIndex={active ? 0 : -1}
                        className="btn-tab"
                        disabled={tab.disabled}
                        onClick={() => {
                          if (!tab.disabled) setActiveTab(tabValue);
                        }}
                      >
                        {tab.label}
                        {active && selectedLabel ? (
                          <i className="sr-only created"> {selectedLabel}</i>
                        ) : null}
                      </button>
                    </li>
                  );
                })}
              </ul>
            </div>
            <div className="tab-conts-wrap">
              {tabs.map((tab, tabIndex) => {
                const tabValue = tab.value ?? tab.id;
                const active = tabValue === activeTab;
                const helpTab = tabValue === "help" || (tabIndex === 0 && tabValue !== "tutorial");
                return (
                  <section
                    id={tab.panelId}
                    role="tabpanel"
                    aria-labelledby={tab.id}
                    hidden={!active}
                    className={cx("tab-conts", active && "active")}
                    key={tab.panelId}
                  >
                    <h3 className="sr-only">{tab.label}</h3>
                    <div className="help-conts-area-inner">
                      {helpTab ? (
                        <>
                          <div className="conts-area help-conts">
                            <div className="conts-wrap">
                              <h4 className="help-title">
                                {inlineSpacedText(helpTitle, false, true)}
                                <span className="krds-btn medium icon">
                                  <span className="sr-only">{label ?? title}</span>
                                  <SvgIcon name="ico-help" />
                                </span>
                              </h4>
                              <div className="conts-desc">
                                <p>{helpDescription ?? children}</p>
                              </div>
                              <ul className="link-list">
                                {downloadLinks.map((link, index) => (
                                  <li key={link.id ?? index}>
                                    <a
                                      href={link.href ?? "#"}
                                      target={link.target}
                                      title={link.title ?? externalTitle}
                                      className="krds-btn xsmall link basic"
                                    >
                                      {link.label + " "}
                                      <SvgIcon name="ico-go" />
                                    </a>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          </div>
                          <div className="conts-area related-service">
                            {relatedGroups.map((group, groupIndex) => (
                              <div className="conts-wrap" key={group.id ?? groupIndex}>
                                <h4 className="help-title">{group.title}</h4>
                                <ul className="link-list">
                                  {group.links.map((link, linkIndex) => {
                                    const icon = link.icon
                                      ? link.icon.startsWith("ico-")
                                        ? link.icon
                                        : `ico-${link.icon}`
                                      : undefined;
                                    return (
                                      <li key={link.id ?? linkIndex}>
                                        <a
                                          href={link.href ?? "#"}
                                          className="krds-btn xsmall link basic"
                                        >
                                          {icon ? <SvgIcon name={icon} /> : null}
                                          {icon ? " " + link.label + " " : link.label + " "}
                                          {!icon ? <SvgIcon name="ico-angle right" /> : null}
                                        </a>
                                      </li>
                                    );
                                  })}
                                </ul>
                              </div>
                            ))}
                          </div>
                        </>
                      ) : (
                        <>
                          <div className="conts-area">
                            <h4 className="help-title">
                              <a href="#;" title={tutorialBackTitle ?? backTitle}>
                                {tutorialTitle}
                              </a>
                            </h4>
                            <ul className="coach-help-process">
                              {tasks.map((task, taskIndex) => (
                                <li key={task.id ?? taskIndex}>
                                  <h4 className={cx("tit", task.current && "current")}>
                                    {task.title}
                                  </h4>
                                  <HelpTaskDisclosure
                                    task={task}
                                    panelId={`krds-help-task-${generatedId}-${taskIndex}`}
                                  />
                                </li>
                              ))}
                            </ul>
                          </div>
                          <div className="help-panel-action">
                            <button
                              type="button"
                              className="krds-btn medium secondary coach-btn-stop"
                              onClick={onStop}
                            >
                              {stopLabel}
                            </button>
                          </div>
                        </>
                      )}
                    </div>
                  </section>
                );
              })}
            </div>
          </div>
          <button
            type="button"
            className="krds-btn small tertiary btn-help-panel fold"
            onClick={() => setOpen(false)}
          >
            <span className="sr-only">{label ?? title}</span>
            {inlineSpacedText(collapseLabel, true, true)}
            <SvgIcon name="ico-angle right" />
          </button>
        </div>
      </div>
    </div>
  );
}

export function HelpPanel({ ref, ...props }: HelpPanelProps & { ref?: Ref<HTMLDivElement> }) {
  return <HelpPanelSurface {...props} {...(ref !== undefined ? { ref } : {})} />;
}
