// packages/angular/src/components/in-page-navigation.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId, type AngularNavItem } from "../kinds";

@Component({
  selector: "krds-in-page-navigation",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-in-page-navigation-type">
      <div class="krds-in-page-navigation-area">
        <div class="in-page-navigation-header">
          <p class="quick-caption">{{ title }}</p>
          <p class="quick-title">{{ pageTitle }}</p>
        </div>
        <nav class="in-page-navigation-list" [attr.aria-label]="title || null">
          <ul>
            @for (item of items; track $index) {
              <li>
                <a [href]="navHref(item)" [class.active]="$index === 0">
                  {{ navLabel(item) }}
                </a>
              </li>
            }
          </ul>
        </nav>
        <div class="in-page-navigation-action">
          <button type="button" class="krds-btn medium">{{ actionLabel }}</button>
          @if (actionInfo || actionCount) {
            <p class="quick-info">
              {{ actionInfo }} <strong>{{ actionCount }}</strong>
            </p>
          }
        </div>
      </div>
    </div>
  `,
})
export class KrdsInPageNavigationComponent {
  @Input() id = createStableId("krds-in-page-navigation");
  @Input() title = "제목";
  @Input() pageTitle = "";
  @Input() actionLabel = "";
  @Input() actionInfo = "";
  @Input() actionCount = "";
  @Input() items: AngularNavItem[] = [];

  navLabel(item: unknown): string {
    if (typeof item === "string" || typeof item === "number") return String(item);
    if (!item || typeof item !== "object") return "";
    if ("label" in item) return String(item.label ?? "");
    if ("title" in item) return String(item.title ?? "");
    if ("text" in item) return String(item.text ?? "");
    if ("message" in item) return String(item.message ?? "");
    return "";
  }

  navHref(item: unknown): string {
    if (!item || typeof item !== "object" || !("href" in item)) return "#";
    return String(item.href || "#");
  }
}

// packages/react/src/components/InPageNavigation.tsx
import { cx, type KrdsNavItem } from "@krds-community/recipes";
import type { ReactNode } from "react";
import { type BoxProps } from "./_utils.js";

export interface InPageNavigationProps extends BoxProps {
  items?: KrdsNavItem[];
  title?: string;
  pageTitle?: ReactNode;
  actionLabel?: ReactNode;
  actionInfo?: ReactNode;
  actionCount?: ReactNode;
  onAction?: () => void;
}
export function InPageNavigation({
  items = [],
  title,
  pageTitle,
  actionLabel,
  actionInfo,
  actionCount,
  onAction,
  className,
}: InPageNavigationProps) {
  return (
    <div className="krds-in-page-navigation-type">
      <div className={cx("krds-in-page-navigation-area", className)}>
        <div className="in-page-navigation-header">
          <p className="quick-caption">{title}</p>
          <p className="quick-title">{pageTitle}</p>
        </div>
        <nav className="in-page-navigation-list" aria-label={title}>
          <ul>
            {items.map((item) => (
              <li key={item.id ?? item.label}>
                <a className={item.current ? "active" : undefined} href={item.href ?? "#"}>
                  {item.label}
                </a>
              </li>
            ))}
          </ul>
        </nav>
        <div className="in-page-navigation-action">
          <button type="button" className="krds-btn medium" onClick={onAction}>
            {actionLabel}
          </button>
          <p className="quick-info">
            {actionInfo} {actionCount ? <strong>{actionCount}</strong> : null}
          </p>
        </div>
      </div>
    </div>
  );
}
