// packages/svelte/src/LanguageSwitcher.svelte
<script lang="ts">
  import { fieldOf, flagOf, invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    label?: string;
    kind?: 'default' | 'page' | string;
    open?: boolean;
    languages?: unknown[];
    options?: unknown[];
    selected?: string;
    modelValue?: string;
    defaultValue?: string;
    selectedLabel?: string;
    currentLabel?: string;
    externalTitle?: string;
    onclick?: (event: Event) => void;
    onchange?: (event: Event) => void;
    className?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    label = '레이블',
    kind = 'default',
    open = $bindable<boolean | undefined>(),
    languages = [],
    options = [],
    selected = $bindable<string | undefined>(),
    modelValue = $bindable<string | undefined>(),
    defaultValue = '',
    selectedLabel = '',
    currentLabel = '',
    externalTitle = '새 창 열림',
    onclick,
    onchange,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const languageItems = $derived(languages.length ? languages : options);
  const selection = $derived(
    modelValue !== undefined
      ? String(modelValue)
      : selected !== undefined
        ? selected
      : defaultValue || fieldOf(languageItems[0], 'value'),
  );
  const currentLanguage = $derived(languageItems.find((language) => fieldOf(language, 'value') === selection));
  const isOpen = $derived(open ?? false);
  const isPage = $derived(kind === 'page');
  const visibleLanguages = $derived(
    isPage ? languageItems.filter((language) => fieldOf(language, 'value') !== selection) : languageItems,
  );
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
  const setSelection = (next: string, event?: Event) => {
    selected = next;
    modelValue = next;
    open = false;
    if (event) invoke(onchange, event);
  };

</script>

<div {...rest} class={`krds-drop-wrap krds-language ${rootClass}`.trim()}>
  <button
    class="krds-btn small text drop-btn"
    class:active={isOpen}
    type="button"
    aria-expanded={isOpen}
    aria-controls={`${id}-menu`}
    onclick={() => toggleOpen()}
  ><i class="svg-icon ico-global"></i>{' '}{label}{' '}<i class="svg-icon ico-toggle"></i></button>
  <div class="drop-menu" id={`${id}-menu`}>
    <div class="drop-in">
      {#if isPage}
        <div class="drop-top">
          <p class="current-laguage">
            <span>{currentLabel}</span>
            <strong>{fieldOf(currentLanguage, 'label')}</strong>
          </p>
        </div>
      {/if}
      <ul class="drop-list">
        {#each visibleLanguages as language}
          {@const value = fieldOf(language, 'value')}
          {@const external = isPage || flagOf(language, 'external') || fieldOf(language, 'target') === '_blank'}
          {@const target = fieldOf(language, 'target') || (external ? '_blank' : '')}
          {@const title = fieldOf(language, 'title') || (external ? externalTitle : '')}
          <li>
            <a
              class="item-link"
              class:active={!isPage && selection === value}
              href={fieldOf(language, 'href') || './'}
              lang={fieldOf(language, 'lang') || value}
              target={target || undefined}
              title={title || undefined}
              aria-disabled={flagOf(language, 'disabled') || undefined}
              onclick={(event: Event) => {
                event.preventDefault();
                if (!flagOf(language, 'disabled')) setSelection(value, event);
              }}
            >
              {fieldOf(language, 'label')}
              {#if isPage}<i class="svg-icon ico-go"></i>{/if}
              <span class="sr-only">{!isPage && selection === value ? selectedLabel : ''}</span>
            </a>
          </li>
        {/each}
      </ul>
    </div>
  </div>
</div>

// packages/react/src/components/LanguageSwitcher.tsx
import { useId, useRef, useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx, type KrdsOption } from "@krds-community/recipes";
import { SvgIcon } from "./_utils.js";

export interface LanguageOption extends KrdsOption {
  href?: string;
  lang?: string;
  target?: string;
  title?: string;
  external?: boolean;
}
export interface LanguageSwitcherProps extends Omit<
  HTMLAttributes<HTMLDivElement>,
  "children" | "onChange"
> {
  languages?: LanguageOption[];
  options?: LanguageOption[];
  value?: string;
  selected?: string;
  defaultValue?: string;
  open?: boolean;
  defaultOpen?: boolean;
  label?: ReactNode;
  currentLabel?: ReactNode;
  selectedLabel?: ReactNode;
  externalTitle?: string;
  text?: string;
  onChange?: (value: string) => void;
  onOpenChange?: (open: boolean) => void;
}

export function LanguageMenu({
  page,
  languages,
  options,
  value,
  selected,
  defaultValue,
  open: controlledOpen,
  defaultOpen = false,
  label,
  currentLabel,
  selectedLabel,
  externalTitle,
  text,
  onChange,
  onOpenChange,
  className,
  ref,
  ...props
}: LanguageSwitcherProps & { page: boolean } & { ref?: Ref<HTMLDivElement> }) {
  const items = languages?.length ? languages : (options ?? []);
  const controlledValue = value ?? selected;
  const valueControlled = value !== undefined || selected !== undefined;
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue ?? items[0]?.value ?? "");
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const dropId = useId();
  const selectedValue = controlledValue ?? uncontrolledValue;
  const open = controlledOpen ?? uncontrolledOpen;
  const setOpen = (next: boolean) => {
    if (controlledOpen === undefined) setUncontrolledOpen(next);
    onOpenChange?.(next);
  };
  const select = (next: string) => {
    if (!valueControlled) setUncontrolledValue(next);
    onChange?.(next);
    setOpen(false);
    triggerRef.current?.focus();
  };
  const current = items.find((language) => language.value === selectedValue);
  const links = page ? items.filter((language) => language.value !== selectedValue) : items;
  return (
    <div {...props} ref={ref} className={cx("krds-drop-wrap", "krds-language", className)}>
      <button
        ref={triggerRef}
        type="button"
        className={cx("krds-btn", "small", "text", "drop-btn", open && "active")}
        aria-expanded={open}
        aria-controls={dropId}
        onClick={() => setOpen(!open)}
      >
        <SvgIcon name="ico-global" /> {label} <SvgIcon name="ico-toggle" />
      </button>
      <div id={dropId} className="drop-menu">
        <div className="drop-in">
          {page ? (
            <div className="drop-top">
              <p className="current-laguage">
                <span>{currentLabel}</span>
                <strong>{current?.label}</strong>
              </p>
            </div>
          ) : null}
          <ul className="drop-list">
            {links.map((language) => {
              const external = page || language.external || language.target === "_blank";
              const active = !page && selectedValue === language.value;
              return (
                <li key={language.value}>
                  <a
                    href={language.href ?? "#"}
                    className={cx("item-link", active && "active")}
                    lang={language.lang ?? language.value}
                    target={language.target ?? (external ? "_blank" : undefined)}
                    title={language.title ?? (external ? (externalTitle ?? text) : undefined)}
                    aria-disabled={language.disabled || undefined}
                    onClick={(event) => {
                      event.preventDefault();
                      if (!language.disabled) select(language.value);
                    }}
                  >
                    {language.label}
                    {page ? <SvgIcon name="ico-go" /> : null}
                    <span className="sr-only">{active ? selectedLabel : null}</span>
                  </a>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    </div>
  );
}

export function LanguageSwitcher({
  ref,
  ...props
}: LanguageSwitcherProps & { ref?: Ref<HTMLDivElement> }) {
  return <LanguageMenu {...props} {...(ref !== undefined ? { ref } : {})} page={false} />;
}
