// packages/angular/src/components/link.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-link",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [":host { display: contents; }"],
  template: `
    <a
      [href]="href"
      class="krds-btn small link"
      [attr.target]="target"
      [attr.title]="external ? title || '새 창 열림' : title"
    >
      <span class="underline">{{ label }}</span
      >{{ " "
      }}<i
        class="svg-icon"
        [class.ico-go]="external || target === '_blank'"
        [class.ico-angle]="!external && target !== '_blank'"
        [class.right]="!external && target !== '_blank'"
      ></i>
    </a>
  `,
})
export class KrdsLinkComponent {
  @Input() id = createStableId("krds-link");
  @Input() label = "레이블";
  @Input() href = "#";
  @Input() target: "_blank" | "_self" | null = null;
  @Input() external = false;
  @Input() title: string | null = null;
}

// packages/react/src/components/Link.tsx
import { type AnchorHTMLAttributes, type ReactNode, type Ref } from "react";
import { SvgIcon, cx } from "./_utils.js";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  external?: boolean;
  label?: ReactNode;
}
export function Link({
  external = false,
  label,
  children,
  className,
  href = "#",
  target,
  rel,
  title,
  ref,
  ...props
}: LinkProps & { ref?: Ref<HTMLAnchorElement> }) {
  return (
    <a
      {...props}
      ref={ref}
      href={href}
      className={cx("krds-btn", "small", "link", className)}
      target={external ? "_blank" : target}
      rel={rel}
      title={external ? (title ?? "새 창 열림") : title}
    >
      <span className="underline">{children ?? label}</span>{" "}
      <SvgIcon name={external ? "ico-go" : "ico-angle right"} />
    </a>
  );
}
