// packages/svelte/src/MainMenuMobile.svelte
<script lang="ts">
  import type { KrdsNavItem } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { invoke, labelOf, hrefOf, childrenOf, fieldOf } from './lib/shared.js';

  type Props = {
    id?: string;
    items?: KrdsNavItem[];
    links?: KrdsNavItem[];
    nav?: KrdsNavItem[];
    utilityItems?: KrdsNavItem[];
    serviceItems?: KrdsNavItem[];
    bottomItems?: KrdsNavItem[];
    loginLabel?: string;
    menuLabel?: string;
    searchPlaceholder?: string;
    searchTitle?: string;
    searchLabel?: string;
    closeLabel?: string;
    previousLabel?: string;
    sample?: boolean;
    open?: boolean;
    onclick?: (event: Event) => void;
    children?: Snippet;
    class?: string;
    className?: string;
  } & Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-main-menu-mobile',
    items = [],
    links = [],
    nav = [],
    utilityItems = [],
    serviceItems = [],
    bottomItems = [],
    loginLabel = '',
    menuLabel = '',
    searchPlaceholder = '',
    searchTitle = '',
    searchLabel = '',
    closeLabel = '',
    previousLabel = '',
    sample = false,
    open = $bindable<boolean | undefined>(),
    onclick,
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const navigationItems = $derived(items.length ? items : links.length ? links : nav);
  const isOpen = $derived(open ?? false);

  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event) invoke(onclick, event);
  };
</script>

<div
  {...rest}
  id={id}
  class={`krds-main-menu-mobile ${rootClass}`}
  class:sample={sample}
  style={sample ? 'display: block; position: static; visibility: visible;' : 'display: none;'}
  role="navigation"
  aria-label={menuLabel || "전체 메뉴"}
>
  <div class="gnb-wrap">
    <div class="gnb-header">
      <div class="gnb-utils">
        <ul class="utility-list">
          {#each utilityItems as item}
            <li><button type="button" class="krds-btn xsmall text">{item.label}</button></li>
          {/each}
        </ul>
      </div>
      <div class="gnb-login">
        <button type="button" class="krds-btn large text">
          <i class="svg-icon ico-log"></i> {loginLabel}
        </button>
      </div>
      <div class="gnb-service-menu">
        {#each serviceItems as item}<a href={hrefOf(item)} class="link">{item.label}</a>{/each}
      </div>
      <div class="sch-input">
        <input
          type="text"
          class="krds-input"
          placeholder={searchPlaceholder}
          title={searchTitle}
          aria-label={searchLabel || searchTitle || undefined}
        />
        <button type="button" class="krds-btn medium icon ico-search">
          <span class="sr-only">{searchLabel}</span>
          <i class="svg-icon ico-sch"></i>
        </button>
      </div>
    </div>
    <div class="gnb-body">
      <div class="gnb-menu">
        <div class="menu-wrap">
          <ul role={sample ? undefined : 'tablist'}>
            {#each navigationItems as item, itemIndex}
              <li role={sample ? undefined : 'none'}>
                <a
                  href={`#${item.id}`}
                  id={sample ? undefined : `${id}-tab-${itemIndex}`}
                  class="gnb-main-trigger"
                  class:active={!sample && itemIndex === 0}
                  role={sample ? undefined : 'tab'}
                  aria-selected={sample ? undefined : itemIndex === 0 ? 'true' : 'false'}
                  aria-controls={sample ? undefined : item.id}
                >{labelOf(item)}</a>
              </li>
            {/each}
          </ul>
        </div>
        <div class="submenu-wrap">
          {#each navigationItems as item, itemIndex}
            <div
              class="gnb-sub-list"
              id={item.id}
              role={sample ? undefined : 'tabpanel'}
              aria-labelledby={sample ? undefined : `${id}-tab-${itemIndex}`}
            >
              <h2 class="sub-title">{labelOf(item)}</h2>
              <ul>
                {#each childrenOf(item) as child, childIndex}
                  <li>
                    <a
                      href={hrefOf(child)}
                      class="gnb-sub-trigger"
                      class:has-depth3={childrenOf(child).length > 0}
                      aria-expanded={!sample && childrenOf(child).length > 0 ? 'false' : undefined}
                      aria-controls={!sample && childrenOf(child).length > 0 ? `${id}-depth3-${itemIndex}-${childIndex}` : undefined}
                    >{labelOf(child)}</a>
                    {#if childrenOf(child).length}
                      <div class="depth3-wrap" id={!sample ? `${id}-depth3-${itemIndex}-${childIndex}` : undefined}>
                        <ul>
                          {#each childrenOf(child) as depthThree}
                            <li>
                              <a
                                href={hrefOf(depthThree)}
                                class="depth3-trigger"
                                class:has-depth4={childrenOf(depthThree).length > 0}
                              >{labelOf(depthThree)}</a>
                              {#if childrenOf(depthThree).length}
                                <div class="depth4-wrap">
                                  <div class="depth4-head">
                                    <button type="button" class="krds-btn icon trigger-prev">
                                      <span class="sr-only">{previousLabel}</span>
                                      <i class="svg-icon ico-angle left"></i>
                                    </button>
                                    <button type="button" class="krds-btn icon trigger-close">
                                      <span class="sr-only">{closeLabel}</span>
                                      <i class="svg-icon ico-popup-close"></i>
                                    </button>
                                  </div>
                                  <ul class="depth4-body">
                                    <h4 class="sub-title">{fieldOf(depthThree, 'title')}</h4>
                                    <ul class="depth4-ul">
                                      {#each childrenOf(depthThree) as depthFour}
                                        <li><a href={hrefOf(depthFour)}>{labelOf(depthFour)}</a></li>
                                      {/each}
                                    </ul>
                                  </ul>
                                </div>
                              {/if}
                            </li>
                          {/each}
                        </ul>
                      </div>
                    {/if}
                  </li>
                {/each}
              </ul>
            </div>
          {/each}
        </div>
      </div>
      <div class="gnb-bottom">
        {#each bottomItems as item}
          <a
            href={hrefOf(item)}
            class="krds-btn small text"
            target={fieldOf(item, 'target') || undefined}
            title={fieldOf(item, 'title') || undefined}
          >
            {labelOf(item)}
            <i class={`svg-icon ${fieldOf(item, 'target') ? 'ico-go' : 'ico-angle right'}`}></i>
          </a>
        {/each}
      </div>
    </div>
    <button
      type="button"
      class="krds-btn medium icon"
      id={sample ? 'close-nav' : `${id}-close`}
      onclick={sample ? undefined : toggleOpen}
    >
      <span class="sr-only">{closeLabel}</span>
      <i class="svg-icon ico-popup-close"></i>
    </button>
  </div>
</div>

// packages/react/src/components/MainMenuMobile.tsx
import { useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon } from "./_utils.js";
import type { MainMenuItem } from "./MainMenuPc.js";

export interface MainMenuMobileProps extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  utilityItems?: MainMenuItem[];
  loginLabel?: ReactNode;
  serviceItems?: MainMenuItem[];
  searchPlaceholder?: string;
  searchTitle?: string;
  searchLabel?: ReactNode;
  searchValue?: string;
  defaultSearchValue?: string;
  items?: MainMenuItem[];
  bottomItems?: MainMenuItem[];
  previousLabel?: ReactNode;
  closeLabel?: ReactNode;
  bottomSize?: "small" | "medium";
  menuLabel?: string;
  sample?: boolean;
  standalone?: boolean;
  onSearchChange?: (value: string) => void;
  onSearch?: (value: string) => void;
  onPrevious?: () => void;
  onClose?: () => void;
}
export function MainMenuMobile({
  utilityItems = [],
  loginLabel,
  serviceItems = [],
  searchPlaceholder,
  searchTitle,
  searchLabel,
  searchValue: controlledSearchValue,
  defaultSearchValue = "",
  items = [],
  bottomItems = [],
  previousLabel,
  closeLabel,
  bottomSize = "small",
  menuLabel,
  sample = true,
  standalone = true,
  onSearchChange,
  onSearch,
  onPrevious,
  onClose,
  id = "mobile-nav",
  role,
  "aria-label": ariaLabel,
  style,
  className,
  ref,
  ...props
}: MainMenuMobileProps & { ref?: Ref<HTMLDivElement> }) {
  const [uncontrolledSearchValue, setUncontrolledSearchValue] = useState(defaultSearchValue);
  const searchValue = controlledSearchValue ?? uncontrolledSearchValue;
  return (
    <div
      {...props}
      ref={ref}
      id={id}
      role={standalone ? (role ?? "navigation") : role}
      aria-label={standalone ? (ariaLabel ?? menuLabel ?? "전체 메뉴") : ariaLabel}
      className={cx("krds-main-menu-mobile", sample && "sample", className)}
      style={
        standalone
          ? { display: "block", position: "static", visibility: "visible", ...style }
          : style
      }
    >
      <div className="gnb-wrap">
        <div className="gnb-header">
          <div className="gnb-utils">
            <ul className="utility-list">
              {utilityItems.map((item) => (
                <li key={item.id ?? item.label}>
                  <button type="button" className="krds-btn xsmall text">
                    {item.label}
                  </button>
                </li>
              ))}
            </ul>
          </div>
          <div className="gnb-login">
            <button type="button" className="krds-btn large text">
              <SvgIcon name="ico-log" /> {loginLabel}
            </button>
          </div>
          <div className="gnb-service-menu">
            {serviceItems.map((item) => (
              <a href={item.href ?? "#"} className="link" key={item.id ?? item.label}>
                {item.label}
              </a>
            ))}
          </div>
          <div className="sch-input">
            <input
              type="text"
              className="krds-input"
              placeholder={searchPlaceholder}
              title={searchTitle}
              aria-label={typeof searchLabel === "string" ? searchLabel : searchTitle}
              value={controlledSearchValue}
              defaultValue={
                controlledSearchValue === undefined && defaultSearchValue
                  ? defaultSearchValue
                  : undefined
              }
              onChange={(event) => {
                const next = event.currentTarget.value;
                if (controlledSearchValue === undefined) setUncontrolledSearchValue(next);
                onSearchChange?.(next);
              }}
            />
            <button
              type="button"
              className="krds-btn medium icon ico-search"
              onClick={() => onSearch?.(searchValue)}
            >
              <span className="sr-only">{searchLabel}</span>
              <SvgIcon name="ico-sch" />
            </button>
          </div>
        </div>
        <div className="gnb-body">
          <div className="gnb-menu">
            <div className="menu-wrap">
              <ul role={standalone ? undefined : "tablist"}>
                {items.map((item, index) => (
                  <li role={standalone ? undefined : "none"} key={item.id ?? item.label}>
                    <a
                      id={standalone ? undefined : `tab-${index}`}
                      href={`#${item.id}`}
                      className={cx("gnb-main-trigger", !standalone && index === 0 && "active")}
                      role={standalone ? undefined : "tab"}
                      aria-selected={standalone ? undefined : index === 0}
                      aria-controls={standalone ? undefined : item.id}
                    >
                      {item.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            <div className="submenu-wrap">
              {items.map((item, index) => (
                <div
                  className="gnb-sub-list"
                  id={item.id}
                  role={standalone ? undefined : "tabpanel"}
                  aria-labelledby={standalone ? undefined : `tab-${index}`}
                  key={item.id ?? item.label}
                >
                  <h2 className="sub-title">{item.label}</h2>
                  <ul>
                    {item.children?.map((second) => (
                      <li key={second.id ?? second.label}>
                        <a
                          href={second.href ?? "#"}
                          className={cx("gnb-sub-trigger", second.children?.length && "has-depth3")}
                          aria-expanded={standalone || !second.children?.length ? undefined : false}
                          aria-controls={
                            standalone || !second.children?.length
                              ? undefined
                              : `${item.id}-${second.id}-depth3`
                          }
                        >
                          {second.label}
                        </a>
                        {second.children?.length ? (
                          <div
                            id={standalone ? undefined : `${item.id}-${second.id}-depth3`}
                            className="depth3-wrap"
                          >
                            <ul>
                              {second.children.map((third) => (
                                <li key={third.id ?? third.label}>
                                  <a
                                    href={third.href ?? "#"}
                                    className={cx(
                                      "depth3-trigger",
                                      third.children?.length && "has-depth4",
                                    )}
                                  >
                                    {third.label}
                                  </a>
                                  {third.children?.length ? (
                                    <div className="depth4-wrap">
                                      <div className="depth4-head">
                                        <button
                                          type="button"
                                          className="krds-btn icon trigger-prev"
                                          onClick={onPrevious}
                                        >
                                          <span className="sr-only">{previousLabel}</span>
                                          <SvgIcon name="ico-angle left" />
                                        </button>
                                        <button
                                          type="button"
                                          className="krds-btn icon trigger-close"
                                          onClick={onClose}
                                        >
                                          <span className="sr-only">{closeLabel}</span>
                                          <SvgIcon name="ico-popup-close" />
                                        </button>
                                      </div>
                                      <ul className="depth4-body">
                                        <h4 className="sub-title">{third.title}</h4>
                                        <ul className="depth4-ul">
                                          {third.children.map((fourth) => (
                                            <li key={fourth.id ?? fourth.label}>
                                              <a href={fourth.href ?? "#"}>{fourth.label}</a>
                                            </li>
                                          ))}
                                        </ul>
                                      </ul>
                                    </div>
                                  ) : null}
                                </li>
                              ))}
                            </ul>
                          </div>
                        ) : null}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
          <div className="gnb-bottom">
            {bottomItems.map((item, index) => (
              <a
                href={item.href ?? "#"}
                className={cx("krds-btn", bottomSize, "text")}
                target={item.target}
                title={item.title}
                key={item.id ?? index}
              >
                {item.label} <SvgIcon name={item.target ? "ico-go" : "ico-angle right"} />
              </a>
            ))}
          </div>
        </div>
        <button type="button" className="krds-btn medium icon" id="close-nav" onClick={onClose}>
          <span className="sr-only">{closeLabel}</span>
          <SvgIcon name="ico-popup-close" />
        </button>
      </div>
    </div>
  );
}
