// packages/svelte/src/Masthead.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    id?: string;
    message?: string;
    description?: string;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-masthead',
    message = '도움말',
    description = '',
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div {...rest} id={id} class={rootClass}>
  <div class="toggle-wrap">
    <div class="toggle-head">
      <div class="inner"><span class="nuri-txt">{message || description}</span></div>
    </div>
  </div>
</div>

// packages/react/src/components/Masthead.tsx
import { type ReactNode, type Ref } from "react";
import { type BoxProps } from "./_utils.js";

export interface MastheadProps extends BoxProps {
  message?: ReactNode;
}
export function Masthead({
  id = "krds-masthead",
  message = "도움말",
  className,
  ref,
  ...props
}: MastheadProps & { ref?: Ref<HTMLDivElement> }) {
  return (
    <div {...props} ref={ref} id={id} className={className}>
      <div className="toggle-wrap">
        <div className="toggle-head">
          <div className="inner">
            <span className="nuri-txt">{message}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
