// packages/solid/src/components/Masthead.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface MastheadProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  message?: string;
  description?: string;
  id?: string;
  [key: string]: unknown;
}

export function Masthead(rawProps: MastheadProps) {
  const merged = mergeProps({ message: "도움말" }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "message",
    "description",
    "id",
  ]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      id={props.id ?? "krds-masthead"}
      class={className() || undefined}
    >
      <div class="toggle-wrap">
        <div class="toggle-head">
          <div class="inner">
            <span class="nuri-txt">{props.message ?? props.description ?? props.children}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/react/src/components/Masthead.tsx
import { type ReactNode, type Ref } from "react";
import { type BoxProps } from "./_utils.js";

export interface MastheadProps extends BoxProps {
  message?: ReactNode;
}
export function Masthead({
  id = "krds-masthead",
  message = "도움말",
  className,
  ref,
  ...props
}: MastheadProps & { ref?: Ref<HTMLDivElement> }) {
  return (
    <div {...props} ref={ref} id={id} className={className}>
      <div className="toggle-wrap">
        <div className="toggle-head">
          <div className="inner">
            <span className="nuri-txt">{message}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
