// packages/angular/src/components/masthead.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

@Component({
  selector: "krds-masthead",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [id]="id">
      <div class="toggle-wrap">
        <div class="toggle-head">
          <div class="inner">
            <span class="nuri-txt">{{ message }}</span>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class KrdsMastheadComponent {
  @Input() id = "krds-masthead";
  @Input() message = "도움말";
}

@Component({
  selector: "krds-identifier",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-identifier">
      <span class="logo">
        <span class="sr-only">KRDS - Korea Design System</span>
      </span>
      <span class="ban-txt">{{ description || organization }}</span>
    </div>
  `,
})
export class KrdsIdentifierComponent {
  @Input() description = "";
  @Input() organization = "KRDS Community";
}

// packages/react/src/components/Masthead.tsx
import { type ReactNode, type Ref } from "react";
import { type BoxProps } from "./_utils.js";

export interface MastheadProps extends BoxProps {
  message?: ReactNode;
}
export function Masthead({
  id = "krds-masthead",
  message = "도움말",
  className,
  ref,
  ...props
}: MastheadProps & { ref?: Ref<HTMLDivElement> }) {
  return (
    <div {...props} ref={ref} id={id} className={className}>
      <div className="toggle-wrap">
        <div className="toggle-head">
          <div className="inner">
            <span className="nuri-txt">{message}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
