// packages/angular/src/components/pagination.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-pagination",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [":host { display: contents; }"],
  template: `
    <div class="krds-pagination" role="navigation" [attr.aria-label]="navigationLabel">
      @if (previousDisabled || current <= 1) {
        <span class="page-navi prev disabled" href="#">{{ previousLabel }}</span>
      } @else {
        <a class="page-navi prev" href="#" (click)="setCurrentPage(current - 1, $event)">{{
          previousLabel
        }}</a>
      }
      <div class="page-links">
        @for (page of items; track $index) {
          @if (paginationValue(page) === "ellipsis") {
            <span class="page-link link-dot"></span>
          } @else {
            <a
              href="#"
              class="page-link"
              [class.active]="paginationValue(page) === currentPage"
              (click)="setCurrentPage(page, $event)"
            >
              @if (paginationValue(page) === currentPage) {
                <span class="sr-only">{{ message }} </span>
              }
              {{ paginationValue(page) }}
            </a>
          }
        }
      </div>
      @if (nextDisabled || current >= maxPage) {
        <span class="page-navi next disabled" href="#">{{ nextLabel }}</span>
      } @else {
        <a class="page-navi next" href="#" (click)="setCurrentPage(current + 1, $event)">{{
          nextLabel
        }}</a>
      }
    </div>
  `,
})
export class KrdsPaginationComponent {
  @Input() id = createStableId("krds-pagination");
  @Input() current = 1;
  @Input() message = "현재페이지";
  @Input() navigationLabel = "페이지 이동";
  @Input() previousLabel = "이전";
  @Input() nextLabel = "다음";
  @Input() previousDisabled = false;
  @Input() nextDisabled = false;
  @Input() items: (string | number | { label: string })[] = [1, 2, 3, 4, 5];
  @Output() currentChange = new EventEmitter<number>();

  get currentPage(): string {
    return this.current.toString();
  }

  paginationValue(item: unknown): string {
    if (typeof item === "number" || typeof item === "string") return String(item);
    if (item && typeof item === "object" && "label" in item) {
      return String(item.label ?? "");
    }
    return "";
  }

  get maxPage(): number {
    return Math.max(
      1,
      ...this.items
        .map((item) => Number(this.paginationValue(item)))
        .filter((value) => Number.isFinite(value)),
    );
  }

  setCurrentPage(item: unknown, event: Event): void {
    event.preventDefault();
    const value = Number(this.paginationValue(item));
    if (!Number.isNaN(value)) {
      this.current = value;
      this.currentChange.emit(value);
    }
  }
}

// packages/react/src/components/Pagination.tsx
import { type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsPaginationItem } from "@krds-community/recipes";
import type { CommonProps } from "./_utils.js";

export interface PaginationProps extends Omit<CommonProps, "items"> {
  items?: KrdsPaginationItem[];
  current?: number;
  previousDisabled?: boolean;
  nextDisabled?: boolean;
  previousLabel?: ReactNode;
  nextLabel?: ReactNode;
  navigationLabel?: string;
  onPageChange?: (page: number) => void;
  className?: string;
  children?: ReactNode;
}
export function Pagination({
  items = [1, 2, 3, 4, 5],
  current = 1,
  previousDisabled = Number(current) <= 1,
  nextDisabled = Number(current) >=
    Math.max(...items.filter((item): item is number => item !== "ellipsis")),
  previousLabel = "이전",
  nextLabel = "다음",
  navigationLabel = "페이지 이동",
  onPageChange,
  className,
  ref,
  ..._props
}: PaginationProps & { ref?: Ref<HTMLDivElement> }) {
  const currentPage = Number(current) || 1;
  const pageLink = (page: number) => (
    <a
      className={cx("page-link", page === currentPage && "active")}
      href="#"
      onClick={(event) => {
        event.preventDefault();
        onPageChange?.(page);
      }}
      key={page}
    >
      {page === currentPage ? <span className="sr-only">현재페이지 </span> : null}
      {page}
    </a>
  );
  return (
    <div
      ref={ref}
      className={cx("krds-pagination", className)}
      role="navigation"
      aria-label={navigationLabel}
    >
      {previousDisabled ? (
        <span {...{ href: "#" }} className="page-navi prev disabled">
          {previousLabel}
        </span>
      ) : (
        <a
          className="page-navi prev"
          href="#"
          onClick={(event) => {
            event.preventDefault();
            onPageChange?.(currentPage - 1);
          }}
        >
          {previousLabel}
        </a>
      )}
      <div className="page-links">
        {items.map((item, index) =>
          item === "ellipsis" ? (
            <span className="page-link link-dot" key={`ellipsis-${index}`} />
          ) : (
            pageLink(item)
          ),
        )}
      </div>
      {nextDisabled ? (
        <span {...{ href: "#" }} className="page-navi next disabled">
          {nextLabel}
        </span>
      ) : (
        <a
          className="page-navi next"
          href="#"
          onClick={(event) => {
            event.preventDefault();
            onPageChange?.(currentPage + 1);
          }}
        >
          {nextLabel}
        </a>
      )}
    </div>
  );
}
