// packages/angular/src/components/progress-bar.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-progress-bar",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'krds-progress-bar ' + size + ' ' + state">
      <progress class="krds-progress" [attr.value]="value" [attr.max]="max">
        {{ label || value + "%" }}
      </progress>
      @if (label) {
        <span class="progress-label">{{ label }}</span>
      }
    </div>
  `,
})
export class KrdsProgressBarComponent {
  @Input() id = createStableId("krds-progress-bar");
  @Input() size: "large" | "medium" = "medium";
  @Input() state: "active" | "success" | "error" = "active";
  @Input() value = 0;
  @Input() max = 100;
  @Input() label = "";
}

// packages/react/src/components/ProgressBar.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface ProgressBarProps extends BoxProps {
  size?: "large" | "medium";
  state?: "active" | "success" | "error";
  value?: number;
  max?: number;
  label?: ReactNode;
}

export function ProgressBar({
  size = "medium",
  state = "active",
  value = 0,
  max = 100,
  label,
  className,
}: ProgressBarProps) {
  return (
    <div className={cx("krds-progress-bar", size, state, className)}>
      <progress className="krds-progress" value={value} max={max}>
        {label ?? `${value}%`}
      </progress>
      {label ? <span className="progress-label">{label}</span> : null}
    </div>
  );
}
