// packages/solid/src/components/ProgressBar.tsx
import { Show, mergeProps, splitProps, type JSX } from "solid-js";

export interface ProgressBarProps {
  class?: string;
  className?: string;
  size?: "large" | "medium";
  state?: "active" | "success" | "error";
  value?: number;
  max?: number;
  label?: JSX.Element;
  [key: string]: unknown;
}

export function ProgressBar(rawProps: ProgressBarProps) {
  const merged = mergeProps(
    { size: "medium" as const, state: "active" as const, value: 0, max: 100 },
    rawProps,
  );
  const [props, native] = splitProps(merged, ["class", "className", "size", "state", "value", "max", "label"]);

  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-progress-bar ${props.size} ${props.state}${className() ? ` ${className()}` : ""}`}
    >
      <progress class="krds-progress" value={props.value} max={props.max}>
        {props.label ?? `${props.value}%`}
      </progress>
      <Show when={props.label}>
        <span class="progress-label">{props.label}</span>
      </Show>
    </div>
  );
}

// packages/react/src/components/ProgressBar.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface ProgressBarProps extends BoxProps {
  size?: "large" | "medium";
  state?: "active" | "success" | "error";
  value?: number;
  max?: number;
  label?: ReactNode;
}

export function ProgressBar({
  size = "medium",
  state = "active",
  value = 0,
  max = 100,
  label,
  className,
}: ProgressBarProps) {
  return (
    <div className={cx("krds-progress-bar", size, state, className)}>
      <progress className="krds-progress" value={value} max={max}>
        {label ?? `${value}%`}
      </progress>
      {label ? <span className="progress-label">{label}</span> : null}
    </div>
  );
}
