// packages/svelte/src/Radio.svelte
<script lang="ts">
  import type { RadioContractProps } from '@krds-community/recipes';
  type RadioValue = string | number | boolean;
  type Props = Omit<RadioContractProps, 'value'> & {
    checked?: boolean;
    group?: RadioValue;
    value?: RadioValue;
    class?: string;
    className?: string;
  };
  const generatedId = $props.id();
  let {
    checked = $bindable(false),
    group = $bindable<RadioValue | undefined>(),
    value,
    name = '',
    label = '',
    description = '',
    size,
    id = generatedId,
    disabled = false,
    class: classValue = '',
    className = '',
    ...restProps
  }: Props = $props();
  const grouped = $derived(group !== undefined);
  const radioChecked = $derived(grouped ? group === value : checked);
  const handleChange = (event: Event) => {
    checked = true;
    if (grouped) group = value;
    const handler = (restProps as Record<string, unknown>).onchange;
    if (typeof handler === 'function') (handler as (event: Event) => void)(event);
  };
</script>

<div class={`krds-form-check${size ? ` ${size}` : ''}${classValue ? ` ${classValue}` : ''}${className ? ` ${className}` : ''}`}>
  <input {...restProps} type="radio" {id} {name} {value} checked={radioChecked} {disabled} onchange={handleChange} aria-describedby={description ? `${id}-description` : undefined} />
  <label for={id}>{label}</label>
  {#if description}
    <div class="krds-form-check-cnt">
      <p id={`${id}-description`} class="krds-form-check-p">{description}</p>
    </div>
  {/if}
</div>

// packages/react/src/components/Radio.tsx
import { useId, type InputHTMLAttributes, type ReactNode, type Ref } from "react";
import { choiceRecipe } from "@krds-community/recipes";
import type { RadioContractProps } from "@krds-community/recipes";

function joinAriaIds(...ids: Array<string | undefined>) {
  const unique = new Set(ids.flatMap((value) => value?.split(/\s+/).filter(Boolean) ?? []));
  return unique.size ? Array.from(unique).join(" ") : undefined;
}

export interface RadioProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, "type" | "size" | "disabled" | "value">,
    Omit<RadioContractProps, "label" | "description" | "value"> {
  label: ReactNode;
  value?: string;
  description?: ReactNode;
}
export function Radio({
  label,
  description,
  size,
  id: providedId,
  className,
  value,
  ref,
  ...props
}: RadioProps & { ref?: Ref<HTMLInputElement> }) {
  const generatedId = useId();
  const id = providedId ?? `krds-radio-${generatedId}`;
  const descriptionId = description ? `${id}-description` : undefined;
  const recipe = choiceRecipe({ size, className });
  return (
    <div className={recipe.className}>
      <input
        {...props}
        ref={ref}
        id={id}
        type="radio"
        value={value}
        aria-describedby={joinAriaIds(props["aria-describedby"], descriptionId)}
      />
      <label htmlFor={id}>{label}</label>
      {description ? (
        <div className="krds-form-check-cnt">
          <p id={descriptionId} className="krds-form-check-p">
            {description}
          </p>
        </div>
      ) : null}
    </div>
  );
}
