// packages/solid/src/components/Resize.tsx
import { For, createSignal, createUniqueId, mergeProps, splitProps } from "solid-js";
import type { KrdsOption } from "@krds-community/recipes";

export interface ResizeProps {
  class?: string;
  className?: string;
  label?: string;
  open?: boolean;
  selected?: string;
  selectedLabel?: string;
  defaultValue?: string;
  resetLabel?: string;
  value?: string;
  modelValue?: string;
  options?: KrdsOption[];
  languages?: KrdsOption[];
  [key: string]: unknown;
}

export function Resize(rawProps: ResizeProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "label",
    "open",
    "selected",
    "selectedLabel",
    "defaultValue",
    "resetLabel",
    "value",
    "modelValue",
    "options",
    "languages",
  ]);
  const [localOpen, setLocalOpen] = createSignal(false);
  const open = () => (props.open !== undefined ? Boolean(props.open) : localOpen());
  const setOpen = (next: boolean) => {
    if (props.open === undefined) setLocalOpen(next);
  };
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "string" || typeof mv === "number") return String(mv);
    return props.selected ?? localSelected() ?? props.defaultValue ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const optionItems = () => props.languages ?? props.options ?? [];
  const dropMenuId = `krds-resize-drop-${createUniqueId()}`;
  return (
    <div
      {...(native as Record<string, any>)}
      class={["krds-drop-wrap", "krds-resize", className()].filter(Boolean).join(" ")}
      data-adjust="scale"
    >
      <button
        type="button"
        class="krds-btn small text drop-btn"
        aria-expanded={open()}
        aria-controls={dropMenuId}
        onClick={() => setOpen(!open())}
      >
        {props.label} <i class="svg-icon ico-toggle" />
      </button>
      <div class="drop-menu" id={dropMenuId} style={{ display: open() ? "block" : undefined }}>
        <div class="drop-in">
          <ul class="drop-list">
            <For each={optionItems()}>
              {(option) => (
                <li>
                  <button
                    type="button"
                    class={`item-link ${option.value}`}
                    classList={{ active: selected() === option.value }}
                    data-adjust-scale={option.value}
                    onClick={(event) => {
                      setSelected(option.value);
                      (native as Record<string, any>).onChange?.(event);
                    }}
                  >
                    {option.label}
                    <span class="sr-only">
                      {selected() === option.value ? props.selectedLabel : undefined}
                    </span>
                  </button>
                </li>
              )}
            </For>
          </ul>
          <div class="drop-bottom">
            <button
              type="button"
              class="krds-btn medium text"
              data-adjust-scale={props.defaultValue}
              onClick={() => setSelected(props.defaultValue ?? "")}
            >
              <i class="svg-icon ico-reset" /> {props.resetLabel}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/react/src/components/Resize.tsx
import { useId, useRef, useState, type HTMLAttributes, type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsOption } from "@krds-community/recipes";
import { SvgIcon } from "./_utils.js";

export interface ResizeProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "onChange"> {
  dataAdjust?: boolean;
  label?: ReactNode;
  options?: KrdsOption[];
  value?: string;
  selected?: string;
  defaultValue?: string;
  selectedLabel?: ReactNode;
  resetLabel?: ReactNode;
  open?: boolean;
  defaultOpen?: boolean;
  onChange?: (value: string) => void;
  onOpenChange?: (open: boolean) => void;
  onReset?: () => void;
}
export function Resize({
  dataAdjust = true,
  className,
  label,
  options = [],
  value,
  selected,
  defaultValue,
  selectedLabel,
  resetLabel,
  open: controlledOpen,
  defaultOpen = false,
  onChange,
  onOpenChange,
  onReset,
  ref,
  ...props
}: ResizeProps & { ref?: Ref<HTMLDivElement> }) {
  const controlledValue = value ?? selected;
  const valueControlled = value !== undefined || selected !== undefined;
  const resetValue = defaultValue ?? options[0]?.value ?? "";
  const [uncontrolledValue, setUncontrolledValue] = useState(resetValue);
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const dropId = useId();
  const selectedValue = controlledValue ?? uncontrolledValue;
  const open = controlledOpen ?? uncontrolledOpen;
  const setOpen = (next: boolean) => {
    if (controlledOpen === undefined) setUncontrolledOpen(next);
    onOpenChange?.(next);
  };
  const select = (next: string) => {
    if (!valueControlled) setUncontrolledValue(next);
    onChange?.(next);
    setOpen(false);
    triggerRef.current?.focus();
  };
  return (
    <div
      {...props}
      ref={ref}
      className={cx("krds-drop-wrap", "krds-resize", className)}
      {...(dataAdjust ? { "data-adjust": "scale" } : {})}
    >
      <button
        ref={triggerRef}
        type="button"
        className={cx("krds-btn", "small", "text", "drop-btn", open && "active")}
        aria-expanded={open}
        aria-controls={dropId}
        onClick={() => setOpen(!open)}
      >
        {label + " "}
        <SvgIcon name="ico-toggle" />
      </button>
      <div id={dropId} className="drop-menu">
        <div className="drop-in">
          <ul className="drop-list">
            {options.map((option) => {
              const active = selectedValue === option.value;
              return (
                <li key={option.value}>
                  <button
                    type="button"
                    className={cx(
                      "item-link",
                      (option as KrdsOption & { className?: string }).className ?? option.value,
                      active && "active",
                    )}
                    {...(dataAdjust ? { "data-adjust-scale": option.value } : {})}
                    disabled={option.disabled}
                    onClick={() => select(option.value)}
                  >
                    {option.label}
                    <span className="sr-only">{active ? selectedLabel : null}</span>
                  </button>
                </li>
              );
            })}
          </ul>
          <div className="drop-bottom">
            <button
              type="button"
              className="krds-btn medium text"
              {...(dataAdjust ? { "data-adjust-scale": resetValue } : {})}
              onClick={() => {
                select(resetValue);
                onReset?.();
              }}
            >
              <SvgIcon name="ico-reset" /> {resetLabel}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
