// packages/svelte/src/Select.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { selectRecipe, type InputState, type SelectRecipeSize } from '@krds-community/recipes';

  type Option = {
    value?: string;
    label?: string;
    disabled?: boolean;
    [key: string]: unknown;
  };

  type Props = {
    id?: string;
    name?: string;
    label?: string;
    value?: unknown;
    modelValue?: unknown;
    selected?: string;
    defaultValue?: string;
    options?: Option[];
    disabled?: boolean;
    required?: boolean;
    form?: string;
    hint?: string;
    controlState?: string;
    size?: string;
    variant?: string;
    type?: string;
    title?: string;
    onchange?: (event: Event) => void;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  const generatedId = $props.id();
  let {
    id = generatedId,
    name = '',
    label = '레이블',
    value,
    modelValue = $bindable<unknown>(),
    selected = $bindable<string | undefined>(),
    defaultValue = '',
    options = [],
    disabled = false,
    required = false,
    form,
    hint = '',
    state: stateProp,
    controlState = stateProp ?? 'default',
    size = '',
    variant = '',
    type = '',
    title = '제목',
    onchange,
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const selectState: InputState = $derived(
    controlState === 'error' ||
      controlState === 'success' ||
      controlState === 'information'
      ? controlState
      : 'default',
  );
  const selectVariant = $derived(
    variant === 'size' || size
      ? 'size'
      : variant === 'state' || selectState !== 'default'
        ? 'state'
        : 'default',
  );
  const selectClasses = $derived(
    selectRecipe({
      variant: selectVariant,
      size: (size || variant === 'size' ? (size as SelectRecipeSize) : undefined),
      state: selectState,
    }),
  );
  const selection = $derived(
    modelValue !== undefined
      ? String(modelValue)
      : selected !== undefined
        ? selected
        : defaultValue || String(options[0]?.value ?? ''),
  );

  const setSelection = (next: string, event?: Event) => {
    selected = next;
    modelValue = next;
    if (event && typeof onchange === 'function') onchange(event);
  };
</script>

<div class="form-group">
  <div class="form-tit"><label for={id}>{label}</label></div>
  <div class="form-conts">
    <select
      {...rest}
      id={id}
      name={name || undefined}
      {disabled}
      {required}
      {form}
      title={title}
      value={selection}
      onchange={(event) => setSelection(event.currentTarget.value, event)}
      class={`${selectClasses.control} ${rootClass}`.trim()}
      aria-invalid={selectState === 'error' ? 'true' : undefined}
      aria-describedby={hint ? `${id}-hint` : undefined}
    >
      {#each options as option, index}
        <option
          value={option.value}
          disabled={option.disabled}
          selected={selectVariant === 'size' && index === 0}
        >{option.label}</option>
      {/each}
    </select>
  </div>
  {#if hint}
    <p
      id={`${id}-hint`}
      class={selectState === 'error'
        ? 'form-hint-invalid'
        : selectState === 'success'
          ? 'form-hint-success'
          : selectState === 'information'
            ? 'form-hint-information'
            : 'form-hint'}
    >{hint}</p>
  {/if}
</div>

// packages/react/src/components/Select.tsx
import { useId, type SelectHTMLAttributes, type Ref } from "react";
import { cx, selectRecipe } from "@krds-community/recipes";
import type { KrdsOption } from "@krds-community/recipes";
import type { NativeCommonProps, LabelProps } from "./_utils.js";
import { joinAriaIds } from "./_utils.js";

export interface SelectOption extends KrdsOption {
  selected?: boolean;
}
export interface SelectProps
  extends
    NativeCommonProps,
    Omit<SelectHTMLAttributes<HTMLSelectElement>, "className" | "size">,
    LabelProps {
  options?: SelectOption[];
  state?: "default" | "error" | "complete";
  size?: "small" | "medium" | "large";
  variant?: "default" | "size" | "state" | "sorting";
  className?: string;
}
export function Select({
  options = [],
  label = "선택",
  hint,
  id: providedId,
  state = "default",
  size,
  variant = "default",
  className,
  children,
  title = "선택",
  "aria-describedby": ariaDescribedBy,
  "aria-invalid": ariaInvalid,
  ref,
  ...props
}: SelectProps & { ref?: Ref<HTMLSelectElement> }) {
  const generatedId = useId();
  const id = providedId ?? `krds-select-${generatedId}`;
  const hintId = variant !== "sorting" && hint ? `${id}-hint` : undefined;
  const selectClasses = selectRecipe(
    variant === "sorting"
      ? { variant: "sorting", state: state === "error" ? "error" : "default" }
      : {
          variant,
          size: variant === "size" ? size : undefined,
          state: state === "error" ? "error" : "default",
        },
  );
  const control = (
    <select
      {...props}
      ref={ref}
      id={id}
      className={cx(selectClasses.control, className)}
      title={title}
      aria-label={variant === "sorting" && typeof label === "string" ? label : undefined}
      aria-invalid={state === "error" ? "true" : ariaInvalid}
      aria-describedby={
        variant === "sorting" ? ariaDescribedBy : joinAriaIds(ariaDescribedBy, hintId)
      }
    >
      {children ??
        options.map((option, index) => {
          const selected = option.selected ?? (variant === "size" && index === 0);
          return (
            <option
              key={`${option.value}-${index}`}
              ref={(node) => {
                if (!node) return;
                if (selected) node.setAttribute("selected", "");
                else node.removeAttribute("selected");
              }}
              value={option.value}
              disabled={option.disabled}
              selected={selected}
            >
              {option.label}
            </option>
          );
        })}
    </select>
  );

  if (variant === "sorting") return control;

  return (
    <div className="form-group">
      <div className="form-tit">
        <label htmlFor={id}>{label}</label>
      </div>
      <div className="form-conts">{control}</div>
      {hint ? (
        <p id={hintId} className={state === "error" ? "form-hint-invalid" : "form-hint"}>
          {hint}
        </p>
      ) : null}
    </div>
  );
}
