// packages/solid/src/components/SideNavigation.tsx
import { For, createSignal, mergeProps, splitProps } from "solid-js";
import type { KrdsNavItem } from "@krds-community/recipes";

export interface SideNavigationItem extends KrdsNavItem {
  children?: SideNavigationItem[];
  description?: string;
  current?: boolean;
}

export interface SideNavigationProps {
  class?: string;
  className?: string;
  title?: string;
  id?: string;
  nav?: KrdsNavItem[];
  links?: KrdsNavItem[];
  items?: (KrdsNavItem | string | number)[];
  selected?: string;
  defaultValue?: string;
  modelValue?: string;
  value?: string;
  [key: string]: unknown;
}

export function SideNavigation(rawProps: SideNavigationProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "id",
    "nav",
    "links",
    "items",
    "selected",
    "defaultValue",
    "modelValue",
    "value",
  ]);
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "string" || typeof mv === "number") return String(mv);
    return props.selected ?? localSelected() ?? props.defaultValue ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const hasCurrentItem = (item: KrdsNavItem): boolean => {
    if (item.current) return true;
    return item.children?.some(hasCurrentItem) ?? false;
  };
  const navigation = () =>
    (props.nav?.length
      ? props.nav
      : props.links?.length
        ? props.links
        : (props.items ?? []).filter(
            (item): item is KrdsNavItem => typeof item !== "string" && typeof item !== "number",
          )) as KrdsNavItem[];
  return (
    <nav
      {...(native as Record<string, any>)}
      class={`krds-side-navigation${className() ? ` ${className()}` : ""}`}
    >
      <h2 class="lnb-tit">{props.title}</h2>
      <ul class="lnb-list" role="menubar">
        <For each={navigation()}>
          {(item, topIndex) => {
            const submenuId = `${props.id}-submenu-${topIndex()}`;
            const expanded = () =>
              selected() === item.id || (selected() === "" && hasCurrentItem(item));
            return item.children?.length ? (
              <li class="lnb-item" classList={{ active: expanded() }} role="none">
                <button
                  type="button"
                  class="lnb-btn lnb-toggle"
                  classList={{ active: expanded() }}
                  role="menuitem"
                  aria-controls={submenuId}
                  aria-expanded={expanded()}
                  onClick={() => setSelected(expanded() ? "" : (item.id ?? submenuId))}
                >
                  {item.label}
                </button>
                <div class="lnb-submenu">
                  <ul id={submenuId} role="menu">
                    <For each={(item as SideNavigationItem).children}>
                      {(child, childIndex) => {
                        const popupId = `${submenuId}-${childIndex()}`;
                        return (child as SideNavigationItem).children?.length ? (
                          <li class="lnb-subitem" role="none">
                            <button
                              type="button"
                              class="lnb-btn lnb-toggle-popup"
                              role="menuitem"
                              aria-controls={popupId}
                              aria-expanded="false"
                              aria-haspopup="true"
                            >
                              {child.label}
                            </button>
                            <div class="lnb-submenu-lv2" id={popupId} role="menu">
                              <button type="button" class="lnb-btn-tit">
                                {typeof child.description === "string"
                                  ? child.description
                                  : child.label}
                              </button>
                              <ul>
                                <For each={(child as SideNavigationItem).children}>
                                  {(leaf) => (
                                    <li role="none">
                                      <a href={leaf.href ?? "#"} class="lnb-btn" role="menuitem">
                                        {leaf.label}
                                      </a>
                                    </li>
                                  )}
                                </For>
                              </ul>
                            </div>
                          </li>
                        ) : (
                          <li class="lnb-subitem" classList={{ active: child.current }} role="none">
                            <a
                              href={child.href ?? "#"}
                              class="lnb-btn lnb-link"
                              role="menuitem"
                              aria-current={child.current ? "page" : undefined}
                            >
                              {child.label}
                            </a>
                          </li>
                        );
                      }}
                    </For>
                  </ul>
                </div>
              </li>
            ) : (
              <li class="lnb-item" classList={{ active: item.current }} role="none">
                <a
                  href={item.href ?? "#"}
                  class="lnb-btn lnb-link"
                  role="menuitem"
                  aria-current={item.current ? "page" : undefined}
                >
                  {item.label}
                </a>
              </li>
            );
          }}
        </For>
      </ul>
    </nav>
  );
}

// packages/react/src/components/SideNavigation.tsx
import {
  useEffect,
  useId,
  useRef,
  useState,
  type HTMLAttributes,
  type ReactNode,
  type Ref,
} from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsNavItem } from "@krds-community/recipes";

export interface SideNavigationItem extends Omit<KrdsNavItem, "children"> {
  description?: ReactNode;
  title?: ReactNode;
  target?: string;
  children?: SideNavigationItem[];
}
export interface SideNavigationProps extends Omit<
  HTMLAttributes<HTMLElement>,
  "children" | "title"
> {
  items?: SideNavigationItem[];
  links?: SideNavigationItem[];
  title?: ReactNode;
  expandedItems?: string[];
  defaultExpandedItems?: string[];
  onExpandedChange?: (ids: string[]) => void;
}

function SideNavigationPopup({ item, panelId }: { item: SideNavigationItem; panelId: string }) {
  const [open, setOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const titleRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (open) titleRef.current?.focus();
  }, [open]);
  return (
    <li className="lnb-subitem" role="none">
      <button
        ref={triggerRef}
        type="button"
        className="lnb-btn lnb-toggle-popup"
        role="menuitem"
        aria-controls={panelId}
        aria-expanded={open}
        aria-haspopup="true"
        disabled={item.disabled}
        onClick={() => setOpen(true)}
      >
        {item.label}
      </button>
      <div
        ref={panelRef}
        id={panelId}
        className={cx("lnb-submenu-lv2", open && "active")}
        role="menu"
        onBlur={(event) => {
          if (!panelRef.current?.contains(event.relatedTarget as Node)) {
            setOpen(false);
            triggerRef.current?.focus();
          }
        }}
      >
        <button
          ref={titleRef}
          type="button"
          className="lnb-btn-tit"
          onClick={() => {
            setOpen(false);
            triggerRef.current?.focus();
          }}
        >
          {item.description ?? item.title ?? item.label}
        </button>
        <ul>
          {item.children?.map((leaf, index) => (
            <li role="none" key={leaf.id ?? index}>
              <a
                href={leaf.href ?? "#"}
                className="lnb-btn"
                role="menuitem"
                aria-current={leaf.current ? "page" : undefined}
                target={leaf.target}
                title={leaf.title as string | undefined}
              >
                {leaf.label}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </li>
  );
}

export function SideNavigation({
  items,
  links,
  title,
  expandedItems: controlledExpandedItems,
  defaultExpandedItems,
  onExpandedChange,
  className,
  ref,
  ...props
}: SideNavigationProps & { ref?: Ref<HTMLElement> }) {
  const navigationItems = items?.length ? items : (links ?? []);
  const generatedId = useId();
  const [uncontrolledExpandedItems, setUncontrolledExpandedItems] = useState(
    defaultExpandedItems ??
      navigationItems
        .filter(
          (item) =>
            item.current ||
            item.children?.some(
              (child) => child.current || child.children?.some((leaf) => leaf.current),
            ),
        )
        .map((item, index) => item.id ?? String(index)),
  );
  const expandedItems = controlledExpandedItems ?? uncontrolledExpandedItems;
  const setExpandedItems = (next: string[]) => {
    if (controlledExpandedItems === undefined) setUncontrolledExpandedItems(next);
    onExpandedChange?.(next);
  };
  return (
    <nav {...props} ref={ref} className={cx("krds-side-navigation", className)}>
      <h2 className="lnb-tit">{title}</h2>
      <ul className="lnb-list" role="menubar">
        {navigationItems.map((item, topIndex) => {
          const itemId = item.id ?? String(topIndex);
          const submenuId = `krds-side-${generatedId}-${topIndex}`;
          const expanded = expandedItems.includes(itemId);
          return item.children?.length ? (
            <li className={cx("lnb-item", expanded && "active")} role="none" key={itemId}>
              <button
                type="button"
                className={cx("lnb-btn", "lnb-toggle", expanded && "active")}
                role="menuitem"
                aria-controls={submenuId}
                aria-expanded={expanded}
                disabled={item.disabled}
                onClick={() =>
                  setExpandedItems(
                    expanded
                      ? expandedItems.filter((id) => id !== itemId)
                      : [...expandedItems, itemId],
                  )
                }
              >
                {item.label}
              </button>
              <div className="lnb-submenu">
                <ul id={submenuId} role="menu">
                  {item.children?.map((child, childIndex) =>
                    child.children?.length ? (
                      <SideNavigationPopup
                        item={child}
                        panelId={`${submenuId}-${childIndex}`}
                        key={child.id ?? childIndex}
                      />
                    ) : (
                      <li
                        className={cx("lnb-subitem", child.current && "active")}
                        role="none"
                        key={child.id ?? childIndex}
                      >
                        <a
                          href={child.href ?? "#"}
                          className="lnb-btn lnb-link"
                          role="menuitem"
                          aria-current={child.current ? "page" : undefined}
                          target={child.target}
                          title={child.title as string | undefined}
                        >
                          {child.label}
                        </a>
                      </li>
                    ),
                  )}
                </ul>
              </div>
            </li>
          ) : (
            <li className={cx("lnb-item", item.current && "active")} role="none" key={itemId}>
              <a
                href={item.href ?? "#"}
                className="lnb-btn lnb-link"
                role="menuitem"
                aria-current={item.current ? "page" : undefined}
                target={item.target}
                title={item.title as string | undefined}
              >
                {item.label}
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
