// packages/svelte/src/Spinner.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    id?: string;
    label?: string;
    inputLabel?: string;
    placeholder?: string;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id,
    label = '레이블',
    inputLabel = 'Label',
    placeholder = 'placeholder',
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div class="form-group">
  <div class="form-tit">
    <label for={`${id}-input`}>{inputLabel}</label>
  </div>
  <div class="form-conts">
    <div class="form-spinner">
      <input type="text" id={`${id}-input`} class="krds-input" {placeholder} />
      <div {...rest} class={`krds-spinner ${rootClass}`} role="status">
        <span class="sr-only">{label}</span>
      </div>
    </div>
  </div>
</div>

// packages/react/src/components/Spinner.tsx
import { useId, type HTMLAttributes, type Ref } from "react";
import { cx } from "@krds-community/recipes";

export function Spinner({
  label = "처리 중",
  inputLabel = "Label",
  placeholder = "placeholder",
  className,
  ref,
  ...props
}: HTMLAttributes<HTMLDivElement> & {
  label?: string;
  inputLabel?: string;
  placeholder?: string;
} & { ref?: Ref<HTMLDivElement> }) {
  const inputId = `krds-spinner-input-${useId()}`;
  return (
    <div className="form-group">
      <div className="form-tit">
        <label htmlFor={inputId}>{inputLabel}</label>
      </div>
      <div className="form-conts">
        <div className="form-spinner">
          <input type="text" id={inputId} className="krds-input" placeholder={placeholder} />
          <div {...props} ref={ref} className={cx("krds-spinner", className)} role="status">
            <span className="sr-only">{label}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
