// packages/angular/src/components/step-indicator.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import type { KrdsStep } from "@krds-community/recipes";

@Component({
  selector: "krds-step-indicator",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ol class="krds-step-wrap">
      @for (step of steps; track step.id) {
        <li [class.done]="$index < current" [class.active]="$index === current">
          <span>
            @if ($index === current) {
              <em class="sr-only">{{ message }}</em>
            }
            <i class="step">{{ $index + 1 }}{{ label }}</i>
            <span class="step-tit">{{ step.label }}</span>
          </span>
        </li>
      }
    </ol>
  `,
})
export class KrdsStepIndicatorComponent {
  @Input() current = 0;
  @Input() stepLabel = "";
  @Input() label = "단계";
  @Input() message = "현재단계";
  @Input() steps: KrdsStep[] = [];
}

// packages/react/src/components/StepIndicator.tsx
import type { ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsStep } from "@krds-community/recipes";

export function StepIndicator({
  steps,
  current = 0,
  label = "단계",
  message = "현재단계",
  className,
}: {
  steps: KrdsStep[];
  current?: number;
  label?: ReactNode;
  message?: ReactNode;
  className?: string;
}) {
  const currentIndex = current;
  return (
    <ol className={cx("krds-step-wrap", className)}>
      {steps.map((step, index) => (
        <li
          className={
            cx(index < currentIndex && "done", index === currentIndex && "active") || undefined
          }
          key={step.id}
        >
          <span>
            {index === currentIndex ? <em className="sr-only">{message}</em> : null}
            <i className="step">
              {typeof label === "string" || typeof label === "number" ? (
                `${index + 1}${label}`
              ) : (
                <>
                  {index + 1}
                  {label}
                </>
              )}
            </i>
            <span className="step-tit">{step.label}</span>
          </span>
        </li>
      ))}
    </ol>
  );
}
