// packages/solid/src/components/StructuredListTable.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import type { TableColumn, TableRow, TablePagination, CalendarAction } from "../shared.js";

export interface StructuredListTableProps {
  class?: string;
  className?: string;
  id?: string;
  columns?: TableColumn[];
  rows?: TableRow[];
  pagination?: TablePagination;
  caption?: string;
  selectAllLabel?: string;
  countLabel?: string;
  countOptions?: string[];
  sortLabel?: string;
  sortOptions?: string[];
  sortValue?: string;
  actions?: CalendarAction[];
  [key: string]: unknown;
}

export function StructuredListTable(rawProps: StructuredListTableProps) {
  const merged = mergeProps({ columns: [] as TableColumn[], rows: [] as TableRow[] }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "columns",
    "rows",
    "pagination",
    "caption",
    "selectAllLabel",
    "countLabel",
    "countOptions",
    "sortLabel",
    "sortOptions",
    "sortValue",
    "actions",
  ]);
  const className = () => props.class ?? props.className ?? "sample";
  const pageMax = () =>
    Math.max(
      1,
      ...(props.pagination?.items ?? []).filter((item): item is number => item !== "ellipsis"),
    );
  return (
    <div
      {...(native as Record<string, any>)}
      class={["krds-structured-list-table", className()].filter(Boolean).join(" ")}
    >
      <div class="search-list-top">
        <div class="sch-left">
          <div class="krds-check-area">
            <div class="krds-form-check">
              <input type="checkbox" class="chk" id={`${props.id}-all`} />
              <label for={`${props.id}-all`}>{props.selectAllLabel}</label>
            </div>
          </div>
          <ul class="side-line-ul">
            <For each={props.actions ?? []}>
              {(action) => (
                <li>
                  <button type="button" class="krds-btn medium text">
                    <i class={`svg-icon ico-${action.icon}`} />
                    {" " + action.label}
                  </button>
                </li>
              )}
            </For>
          </ul>
        </div>
        <ul class="sch-sort">
          <li>
            <strong class="sort-label">
              <label for={`${props.id}-count`}>{props.countLabel}</label>
            </strong>{" "}
            <select
              class="krds-form-select-sort"
              id={`${props.id}-count`}
              value={props.countOptions?.[0]}
            >
              <For each={props.countOptions ?? []}>{(option) => <option>{option}</option>}</For>
            </select>
          </li>
          <li>
            <strong class="sort-label">
              <label for={`${props.id}-sort`}>{props.sortLabel}</label>
            </strong>{" "}
            <div class="w-sort-btn">
              <For each={props.sortOptions ?? []}>
                {(option) => (
                  <>
                    <button type="button" classList={{ active: props.sortValue === option }}>
                      {option}
                    </button>{" "}
                  </>
                )}
              </For>
            </div>
            <div class="m-sort-btn">
              <select
                class="krds-form-select-sort"
                id={`${props.id}-sort`}
                value={props.sortValue}
              >
                <For each={props.sortOptions ?? []}>{(option) => <option>{option}</option>}</For>
              </select>
            </div>
          </li>
        </ul>
      </div>
      <div class="krds-table-wrap">
        <table class="tbl col data">
          <caption>{props.caption}</caption>
          <colgroup>
            <For each={props.columns}>
              {(column) => (
                <col
                  style={
                    "width" in column && typeof column.width === "string" && column.width
                      ? { width: column.width }
                      : undefined
                  }
                />
              )}
            </For>
            <col />
          </colgroup>
          <thead>
            <tr>
              <For each={props.columns}>
                {(column) => (
                  <th scope="col">
                    <Show
                      when={"visuallyHidden" in column && column.visuallyHidden === true}
                      fallback={column.label}
                    >
                      <span class="sr-only">{column.label}</span>
                    </Show>
                  </th>
                )}
              </For>
            </tr>
          </thead>
          <tbody>
            <For each={props.rows}>
              {(row) => (
                <tr>
                  <For each={props.columns}>
                    {(column, columnIndex) =>
                      column.key === "selected" ? (
                        <th scope="row">
                          <div class="krds-form-check">
                            <input
                              type="checkbox"
                              class="chk"
                              id={`${props.id}-row-${String(row.id)}`}
                              aria-label={row.selectionLabel}
                              checked={Boolean(row.selected)}
                            />
                            <label for={`${props.id}-row-${String(row.id)}`} />
                          </div>
                        </th>
                      ) : column.key === "download" ? (
                        <td>
                          <button type="button" class="krds-btn medium text">
                            <i class="svg-icon ico-down" />
                            {" " + String(row[column.key] ?? "")}
                          </button>
                        </td>
                      ) : columnIndex() === 0 ? (
                        <th scope="row">{String(row[column.key] ?? "")}</th>
                      ) : (
                        <td>{String(row[column.key] ?? "")}</td>
                      )
                    }
                  </For>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </div>
      <div class="krds-pagination">
        <Show
          when={!props.pagination?.previousDisabled}
          fallback={
            <span {...({ href: "#" } as Record<string, string>)} class="page-navi prev disabled">
              {props.pagination?.previousLabel}
            </span>
          }
        >
          <a class="page-navi prev" href="#">
            {props.pagination?.previousLabel}
          </a>
        </Show>
        <div class="page-links">
          <For each={props.pagination?.items}>
            {(item) =>
              item === "ellipsis" ? (
                <span class="page-link link-dot" />
              ) : (
                <a
                  class="page-link"
                  classList={{ active: props.pagination?.current === item }}
                  href="#"
                >
                  <Show when={props.pagination?.current === item}>
                    <span class="sr-only">{props.pagination?.currentLabel} </span>
                  </Show>
                  {item}
                </a>
              )
            }
          </For>
        </div>
        <Show
          when={(props.pagination?.current ?? 0) < pageMax()}
          fallback={
            <span {...({ href: "#" } as Record<string, string>)} class="page-navi next disabled">
              {props.pagination?.nextLabel}
            </span>
          }
        >
          <a class="page-navi next" href="#">
            {props.pagination?.nextLabel}
          </a>
        </Show>
      </div>
    </div>
  );
}

// packages/react/src/components/StructuredListTable.tsx
import { Fragment, useId, useState, type ReactNode, type Ref } from "react";
import { SvgIcon, cx } from "./_utils.js";
import type { KrdsTableColumn } from "@krds-community/recipes";

export interface StructuredListTableAction {
  id?: string;
  label: ReactNode;
  icon?: string;
}

export interface DataTableColumn extends KrdsTableColumn {
  width?: string;
  visuallyHidden?: boolean;
}

export interface StructuredListTableRow extends Record<
  string,
  string | number | boolean | undefined
> {
  id: string;
  selected?: boolean;
  selectionLabel?: string;
}

export interface StructuredListTableProps {
  columns?: DataTableColumn[];
  rows?: StructuredListTableRow[];
  caption?: ReactNode;
  className?: string;
  selectAllLabel?: ReactNode;
  actions?: StructuredListTableAction[];
  countLabel?: ReactNode;
  countOptions?: string[];
  sortLabel?: ReactNode;
  sortOptions?: string[];
  sortValue?: string;
  pagination?: {
    current: number;
    items: Array<number | "ellipsis">;
    previousDisabled?: boolean;
    previousLabel?: ReactNode;
    nextLabel?: ReactNode;
    nextDisabled?: boolean;
    currentLabel?: string;
  };
  onSelectionChange?: (ids: string[]) => void;
  onDownload?: (row: StructuredListTableRow) => void;
}
export function StructuredListTable({
  columns = [],
  rows = [],
  caption,
  className: _className,
  selectAllLabel = "전체선택",
  actions = [],
  countLabel = "표시 개수",
  countOptions = [],
  sortLabel = "정렬",
  sortOptions = [],
  sortValue,
  pagination,
  onSelectionChange,
  onDownload,
  ref,
  ..._props
}: StructuredListTableProps & { ref?: Ref<HTMLDivElement> }) {
  const generatedId = useId();
  const countId = `krds-table-count-${useId()}`;
  const sortId = `krds-table-sort-${useId()}`;
  const controlled = rows.some((row) => row.selected !== undefined);
  const [selectedIds, setSelectedIds] = useState(
    () => new Set(rows.filter((row) => row.selected).map((row) => row.id)),
  );
  const selected = controlled
    ? new Set(rows.filter((row) => row.selected).map((row) => row.id))
    : selectedIds;
  const allSelected = rows.length > 0 && rows.every((row) => selected.has(row.id));
  const toggle = (row: StructuredListTableRow) => {
    const next = new Set(selected);
    if (next.has(row.id)) next.delete(row.id);
    else next.add(row.id);
    if (!controlled) setSelectedIds(next);
    onSelectionChange?.([...next]);
  };
  const toggleAll = (checked: boolean) => {
    const next = checked ? new Set(rows.map((row) => row.id)) : new Set<string>();
    if (!controlled) setSelectedIds(next);
    onSelectionChange?.([...next]);
  };
  const pageItems = pagination?.items ?? [];
  const pageMax = Math.max(1, ...pageItems.filter((item): item is number => item !== "ellipsis"));
  const pageLink = (page: number) => (
    <a
      className={cx("page-link", page === pagination?.current && "active")}
      href="#"
      onClick={(event) => event.preventDefault()}
      key={page}
    >
      {page === pagination?.current ? (
        <span className="sr-only">{pagination.currentLabel}</span>
      ) : null}
      {page}
    </a>
  );
  return (
    <div ref={ref} className={cx("krds-structured-list-table", _className || "sample")}>
      <div className="search-list-top">
        <div className="sch-left">
          <div className="krds-check-area">
            <div className="krds-form-check">
              <input
                type="checkbox"
                className="chk"
                id={generatedId}
                checked={allSelected}
                onChange={(event) => toggleAll(event.currentTarget.checked)}
              />
              <label htmlFor={generatedId}>{selectAllLabel}</label>
            </div>
          </div>
          <ul className="side-line-ul">
            {actions.map((action, index) => (
              <li key={action.id ?? index}>
                <button type="button" className="krds-btn medium text">
                  <SvgIcon name={`ico-${action.icon ?? "down"}`} /> {action.label}
                </button>
              </li>
            ))}
          </ul>
        </div>
        <ul className="sch-sort">
          <li>
            <strong className="sort-label">
              <label htmlFor={countId}>{countLabel}</label>
            </strong>{" "}
            <select className="krds-form-select-sort" id={countId}>
              {countOptions.map((option) => (
                <option key={option}>{option}</option>
              ))}
            </select>
          </li>
          <li>
            <strong className="sort-label">
              <label htmlFor={sortId}>{sortLabel}</label>
            </strong>
            <div className="w-sort-btn">
              {sortOptions.map((option) => (
                <Fragment key={option}>
                  <button type="button" className={option === sortValue ? "active" : undefined}>
                    {option}
                  </button>{" "}
                </Fragment>
              ))}
            </div>
            <div className="m-sort-btn">
              <select className="krds-form-select-sort" id={sortId}>
                {sortOptions.map((option) => (
                  <option key={option}>{option}</option>
                ))}
              </select>
            </div>
          </li>
        </ul>
      </div>
      <div className="krds-table-wrap">
        <table className="tbl col data">
          <caption>{caption}</caption>
          <colgroup>
            {columns.map((column) => (
              <col style={column.width ? { width: column.width } : undefined} key={column.key} />
            ))}
            <col />
          </colgroup>
          <thead>
            <tr>
              {columns.map((column) => (
                <th scope="col" key={column.key}>
                  {column.visuallyHidden ? (
                    <span className="sr-only">{column.label}</span>
                  ) : (
                    column.label
                  )}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.id}>
                {columns.map((column, columnIndex) => {
                  if (column.key === "selected") {
                    const inputId = `krds-table-${generatedId}-${row.id}`;
                    return (
                      <th scope="row" key={column.key}>
                        <div className="krds-form-check">
                          <input
                            type="checkbox"
                            className="chk"
                            id={inputId}
                            aria-label={row.selectionLabel}
                            checked={selected.has(row.id)}
                            onChange={() => toggle(row)}
                          />
                          <label htmlFor={inputId} />
                        </div>
                      </th>
                    );
                  }
                  if (column.key === "download") {
                    return (
                      <td key={column.key}>
                        <button
                          type="button"
                          className="krds-btn medium text"
                          onClick={() => onDownload?.(row)}
                        >
                          <SvgIcon name="ico-down" /> {String(row[column.key] ?? "")}
                        </button>
                      </td>
                    );
                  }
                  if (columnIndex === 0) {
                    return (
                      <th scope="row" key={column.key}>
                        {String(row[column.key] ?? "")}
                      </th>
                    );
                  }
                  return <td key={column.key}>{String(row[column.key] ?? "")}</td>;
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {pagination ? (
        <div className="krds-pagination">
          {pagination.previousDisabled ? (
            <span {...{ href: "#" }} className="page-navi prev disabled">
              {pagination.previousLabel}
            </span>
          ) : (
            <a href="#" className="page-navi prev" onClick={(event) => event.preventDefault()}>
              {pagination.previousLabel}
            </a>
          )}
          <div className="page-links">
            {pageItems.map((item, index) =>
              item === "ellipsis" ? (
                <span className="page-link link-dot" key={`ellipsis-${index}`} />
              ) : (
                pageLink(item)
              ),
            )}
          </div>
          {pagination.current >= pageMax ? (
            <span {...{ href: "#" }} className="page-navi next disabled">
              {pagination.nextLabel}
            </span>
          ) : (
            <a href="#" className="page-navi next" onClick={(event) => event.preventDefault()}>
              {pagination.nextLabel}
            </a>
          )}
        </div>
      ) : null}
    </div>
  );
}
