// packages/svelte/src/TagLink.svelte
<script lang="ts">
  import { invoke } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    label?: string;
    href?: string;
    size?: string;
    className?: string;
    class?: string;
    onclick?: (event: Event) => void;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class'>;

  let {
    label = '레이블',
    href = '#',
    size = 'large',
    className = '',
    class: classProp = '',
    onclick,
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div class={`krds-tag-wrap ${size || 'large'}`}>
  <a
    {...rest}
    {href}
    class={`krds-btn-tag link ${rootClass}`}
    onclick={(event) => invoke(onclick, event)}
  >{label}</a>
</div>

// packages/react/src/components/TagLink.tsx
import { type AnchorHTMLAttributes, type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";

export function TagLink({
  href = "#",
  label,
  children,
  className,
  ref,
  ...props
}: AnchorHTMLAttributes<HTMLAnchorElement> & { label?: ReactNode } & {
  ref?: Ref<HTMLAnchorElement>;
}) {
  return (
    <div className="krds-tag-wrap large">
      <a {...props} ref={ref} href={href} className={cx("krds-btn-tag", "link", className)}>
        {children ?? label}
      </a>
    </div>
  );
}
