// packages/solid/src/components/TextList.tsx
import { For, mergeProps, splitProps, type JSX } from "solid-js";
import { labelOf } from "../shared.js";

export interface TextListProps {
  class?: string;
  className?: string;
  items?: (string | number | { label?: string; title?: string; children?: any[] })[];
  ordered?: boolean;
  [key: string]: unknown;
}

const infoList = (
  items: () => (
    | string
    | number
    | { label?: string; title?: string; marker?: string; children?: any[] }
  )[],
  ordered: () => boolean,
  depth = 0,
): JSX.Element => {
  const alphabet = "abcdefghijklmnopqrstuvwxyz";
  const listItems = (
    <For each={items()}>
      {(item, index) => {
        const structured = typeof item !== "string" && typeof item !== "number" ? item : null;
        const nested =
          structured && Array.isArray(structured.children)
            ? (structured.children as (
                | string
                | number
                | { label?: string; title?: string; marker?: string; children?: any[] }
              )[])
            : [];
        const marker = structured
          ? (structured.marker ??
            (ordered()
              ? depth === 0
                ? `${index() + 1}. `
                : depth === 1
                  ? `${alphabet[index()] ?? index() + 1}. `
                  : String.fromCodePoint(0x2460 + index())
              : null))
          : null;
        return (
          <li role="listitem">
            {marker !== null ? <span class="num">{marker}</span> : null}
            {labelOf(item)}
            {nested.length > 0 && infoList(() => nested, ordered, depth + 1)}
          </li>
        );
      }}
    </For>
  );
  if (ordered()) {
    return (
      <ol class="krds-info-list ordered" role="list">
        {listItems}
      </ol>
    );
  }
  return (
    <ul
      class={`krds-info-list ${depth === 0 ? "decimal" : depth === 1 ? "dash" : "hollow"}`}
      role="list"
    >
      {listItems}
    </ul>
  );
};

export function TextList(rawProps: TextListProps) {
  const merged = mergeProps({}, rawProps);
  const [props] = splitProps(merged, ["items", "ordered"]);
  return infoList(
    () => props.items ?? [],
    () => false,
  );
}

export function TextListOrdered(rawProps: TextListProps) {
  const merged = mergeProps({}, rawProps);
  const [props] = splitProps(merged, ["items", "ordered"]);
  return infoList(
    () => props.items ?? [],
    () => true,
  );
}

// packages/react/src/components/TextList.tsx
import { isValidElement, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";

type StructuredTextListItem = {
  id?: string;
  label?: ReactNode;
  title?: ReactNode;
  marker?: ReactNode;
  children?: TextListItem[];
};
export type TextListItem = ReactNode | StructuredTextListItem;

function isTextListReactNode(item: TextListItem): item is ReactNode {
  if (item === null || typeof item !== "object" || isValidElement(item)) {
    return true;
  }
  if (Symbol.iterator in item) {
    return true;
  }
  if ("then" in item && typeof item.then === "function") {
    return true;
  }
  return "$$typeof" in item;
}

function TextListItems({
  items,
  ordered,
  depth,
}: {
  items: TextListItem[];
  ordered: boolean;
  depth: number;
}) {
  const alphabet = "abcdefghijklmnopqrstuvwxyz";
  return items.map((item, index) => {
    if (isTextListReactNode(item)) {
      return (
        <li role="listitem" key={index}>
          {item}
        </li>
      );
    }
    const content = item.label ?? item.title;
    const marker = ordered
      ? (item.marker ??
        (depth === 0
          ? `${index + 1}. `
          : depth === 1
            ? `${alphabet[index] ?? index + 1}. `
            : String.fromCodePoint(0x2460 + index)))
      : null;
    const NestedList = ordered ? "ol" : "ul";
    const nestedClass = ordered ? "ordered" : depth === 0 ? "dash" : "hollow";
    return (
      <li role="listitem" key={item.id ?? index}>
        {marker !== null ? <span className="num">{marker}</span> : null}
        {content}
        {item.children?.length ? (
          <NestedList role="list" className={cx("krds-info-list", nestedClass)}>
            <TextListItems items={item.children} ordered={ordered} depth={depth + 1} />
          </NestedList>
        ) : null}
      </li>
    );
  });
}

export function TextList({
  items = [],
  ordered = false,
  className,
}: {
  items?: TextListItem[];
  ordered?: boolean;
  className?: string;
}) {
  const List = ordered ? "ol" : "ul";
  return (
    <List role="list" className={cx("krds-info-list", ordered ? "ordered" : "decimal", className)}>
      <TextListItems items={items} ordered={ordered} depth={0} />
    </List>
  );
}
