// packages/svelte/src/TextInput.svelte
<script lang="ts">
  import type { TextInputContractProps } from '@krds-community/recipes';
  type Props = Omit<TextInputContractProps, 'value'> & {
    value?: string;
    id?: string;
    class?: string;
    className?: string;
  };

  const generatedId = $props.id();
  let {
    value = $bindable(''),
    label = '',
    hint = '',
    state = 'default',
    size,
    id = generatedId,
    disabled = false,
    readonly = false,
    required = false,
    class: classValue = '',
    className = '',
    ...restProps
  }: Props = $props();
</script>

<div class="form-group">
  <div class="form-tit">
    <label for={id}>{label}</label>
  </div>
  <div
    class="form-conts"
    class:is-error={state === 'error'}
    class:is-success={state === 'success'}
    class:is-information={state === 'information'}
  >
    <input
      {...restProps}
      bind:value
      {id}
      {disabled}
      {readonly}
      {required}
      class={`krds-input${size ? ` ${size}` : ''}${classValue ? ` ${classValue}` : ''}${className ? ` ${className}` : ''}`}
      aria-invalid={state === 'error' ? 'true' : undefined}
      aria-describedby={hint ? `${id}-hint` : undefined}
    />
  </div>
  {#if hint}
    <p
      id={`${id}-hint`}
      class={state === 'error'
        ? 'form-hint-invalid'
        : state === 'success'
          ? 'form-hint-success'
          : state === 'information'
            ? 'form-hint-information'
            : 'form-hint'}
    >
      {hint}
    </p>
  {/if}
</div>

// packages/react/src/components/TextInput.tsx
import { useId, type InputHTMLAttributes, type ReactNode, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import type { TextInputContractProps } from "@krds-community/recipes";

function joinAriaIds(...ids: Array<string | undefined>) {
  const unique = new Set(ids.flatMap((value) => value?.split(/\s+/).filter(Boolean) ?? []));
  return unique.size ? Array.from(unique).join(" ") : undefined;
}

export interface TextInputProps
  extends
    Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "value" | "disabled">,
    Omit<TextInputContractProps, "label" | "hint"> {
  label?: ReactNode;
  hint?: ReactNode;
}
export function TextInput({
  label,
  hint,
  state = "default",
  size,
  id: providedId,
  className,
  readonly,
  readOnly,
  ref,
  ...props
}: TextInputProps & { ref?: Ref<HTMLInputElement> }) {
  const generatedId = useId();
  const id = providedId ?? `krds-input-${generatedId}`;
  const hintId = hint ? `${id}-hint` : undefined;
  const hintClassName =
    state === "default"
      ? "form-hint"
      : state === "error"
        ? "form-hint-invalid"
        : `form-hint-${state}`;
  return (
    <div className="form-group">
      <div className="form-tit">
        <label htmlFor={id}>{label}</label>
      </div>
      <div className={cx("form-conts", state === "default" ? undefined : `is-${state}`)}>
        <input
          {...props}
          id={id}
          ref={ref}
          readOnly={readonly ?? readOnly}
          className={cx("krds-input", size, className)}
          aria-invalid={state === "error" ? "true" : props["aria-invalid"]}
          aria-describedby={joinAriaIds(props["aria-describedby"], hintId)}
        />
      </div>
      {hint ? (
        <p id={hintId} className={hintClassName}>
          {hint}
        </p>
      ) : null}
    </div>
  );
}
