// packages/svelte/src/Toast.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  const CLOSE_ANIMATION_MS = 200;

  type Props = {
    message: string;
    tone?: 'information' | 'warning';
    open?: boolean;
    defaultOpen?: boolean;
    duration?: number;
    onopenchange?: (open: boolean) => void;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    message,
    tone = 'information',
    open = $bindable<boolean | undefined>(),
    defaultOpen = false,
    duration,
    onopenchange,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const controlled = $derived(open !== undefined);

  let rendered = $state(open === true || (open === undefined && defaultOpen === true));
  let closing = $state(false);
  let wasOpen = false;
  let closeTimer: ReturnType<typeof setTimeout> | undefined;
  let removeTimer: ReturnType<typeof setTimeout> | undefined;

  const startClose = () => {
    if (!rendered || closing) return;
    closing = true;
    removeTimer = setTimeout(() => {
      rendered = false;
      closing = false;
      onopenchange?.(false);
    }, CLOSE_ANIMATION_MS);
  };

  $effect(() => {
    const isOpen = controlled ? open === true : rendered;
    if (isOpen && !wasOpen) {
      if (removeTimer) clearTimeout(removeTimer);
      closing = false;
      rendered = true;
      closeTimer = setTimeout(
        () => {
          if (controlled) {
            onopenchange?.(false);
          } else {
            startClose();
          }
        },
        duration ?? (tone === 'warning' ? 4000 : 3000),
      );
    } else if (!isOpen && wasOpen) {
      if (closeTimer) clearTimeout(closeTimer);
      startClose();
    }
    wasOpen = isOpen;
  });

  onDestroy(() => {
    if (closeTimer) clearTimeout(closeTimer);
    if (removeTimer) clearTimeout(removeTimer);
  });
</script>

{#if rendered}
  <div
    {...rest}
    class={`krds-toast ${rootClass}`}
    class:closing={closing}
    role={tone === 'warning' ? 'alert' : 'status'}
  >
    <p class="toast-text">{message}</p>
  </div>
{/if}

// packages/react/src/components/Toast.tsx
import { useEffect, useState, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

const CLOSE_ANIMATION_MS = 200;

export interface ToastProps extends BoxProps {
  message: ReactNode;
  tone?: "information" | "warning";
  open?: boolean;
  defaultOpen?: boolean;
  duration?: number;
  onOpenChange?: (open: boolean) => void;
}

export function Toast({
  message,
  tone = "information",
  open: controlledOpen,
  defaultOpen = false,
  duration,
  onOpenChange,
  className,
}: ToastProps) {
  const controlled = controlledOpen !== undefined;
  const [rendered, setRendered] = useState(
    controlled ? controlledOpen === true : defaultOpen === true,
  );
  const [closing, setClosing] = useState(false);

  useEffect(() => {
    if (controlledOpen === true) {
      setClosing(false);
      setRendered(true);
      const timer = setTimeout(
        () => {
          if (controlled) onOpenChange?.(false);
          else setClosing(true);
        },
        duration ?? (tone === "warning" ? 4000 : 3000),
      );
      return () => clearTimeout(timer);
    }
    if (!rendered) return;
    if (controlledOpen === false) {
      setClosing(true);
      const timer = setTimeout(() => {
        setRendered(false);
        setClosing(false);
      }, CLOSE_ANIMATION_MS);
      return () => clearTimeout(timer);
    }
    if (!controlled) {
      const timer = setTimeout(
        () => setClosing(true),
        duration ?? (tone === "warning" ? 4000 : 3000),
      );
      return () => clearTimeout(timer);
    }
  }, [controlledOpen, controlled, rendered, duration, tone, onOpenChange]);

  useEffect(() => {
    if (!closing || !rendered || controlled) return;
    const timer = setTimeout(() => {
      setRendered(false);
      setClosing(false);
      onOpenChange?.(false);
    }, CLOSE_ANIMATION_MS);
    return () => clearTimeout(timer);
  }, [closing, rendered, controlled, onOpenChange]);

  if (!rendered) return null;
  return (
    <div
      className={cx("krds-toast", className, closing && "closing")}
      role={tone === "warning" ? "alert" : "status"}
    >
      <p className="toast-text">{message}</p>
    </div>
  );
}
