// packages/react/src/components/BottomSheet.tsx
import { useEffect, useId, useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

const CLOSE_ANIMATION_MS = 200;

export interface BottomSheetProps extends BoxProps {
  open?: boolean;
  defaultOpen?: boolean;
  title?: ReactNode;
  description?: ReactNode;
  closeLabel?: string;
  onOpenChange?: (open: boolean) => void;
}

export function BottomSheet({
  open: controlledOpen,
  defaultOpen = false,
  title,
  description,
  closeLabel = "닫기",
  onOpenChange,
  id,
  className,
  children,
}: BottomSheetProps) {
  const generatedId = useId();
  const sheetId = id ?? `krds-bottom-sheet-${generatedId}`;
  const titleId = `${sheetId}-title`;
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const open = controlledOpen ?? uncontrolledOpen;
  const [rendered, setRendered] = useState(open === true);
  const [closing, setClosing] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);
  const restoreFocusRef = useRef<HTMLElement | null>(null);
  const wasVisibleRef = useRef(open && rendered);

  const close = () => {
    if (controlledOpen === undefined) setUncontrolledOpen(false);
    onOpenChange?.(false);
  };

  const focusableElements = () =>
    Array.from(
      panelRef.current?.querySelectorAll<HTMLElement>(
        '[autofocus], button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
      ) ?? [],
    );

  useEffect(() => {
    if (open === true) {
      setClosing(false);
      setRendered(true);
      return;
    }
    if (!rendered) return;
    setClosing(true);
    const timer = setTimeout(() => {
      setRendered(false);
      setClosing(false);
    }, CLOSE_ANIMATION_MS);
    return () => clearTimeout(timer);
  }, [open, rendered]);

  useEffect(() => {
    const panel = panelRef.current;
    const visible = open && rendered;
    if (!panel) return;
    if (visible && !wasVisibleRef.current) {
      const activeElement = panel.ownerDocument.activeElement;
      const view = panel.ownerDocument.defaultView;
      restoreFocusRef.current =
        view && activeElement instanceof view.HTMLElement && !panel.contains(activeElement)
          ? activeElement
          : null;
      focusableElements()[0]?.focus();
    } else if (!visible && wasVisibleRef.current) {
      if (restoreFocusRef.current?.isConnected) restoreFocusRef.current.focus();
      restoreFocusRef.current = null;
    }
    wasVisibleRef.current = visible;
  }, [open, rendered]);

  useEffect(
    () => () => {
      if (restoreFocusRef.current?.isConnected) restoreFocusRef.current.focus();
    },
    [],
  );

  if (!rendered) return null;

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === "Escape" || event.key === "Esc") {
      event.preventDefault();
      close();
      return;
    }
    if (event.key !== "Tab") return;
    const focusables = focusableElements();
    if (focusables.length === 0) return;
    const first = focusables[0];
    const last = focusables[focusables.length - 1];
    const activeElement = panelRef.current?.ownerDocument.activeElement;
    if (
      event.shiftKey &&
      (activeElement === first || !activeElement || !panelRef.current?.contains(activeElement))
    ) {
      event.preventDefault();
      last?.focus();
    } else if (!event.shiftKey && activeElement === last) {
      event.preventDefault();
      first?.focus();
    }
  };

  return (
    <div
      id={sheetId}
      className={cx("krds-bottom-sheet", closing && "closing", className)}
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? titleId : undefined}
      onKeyDown={handleKeyDown}
      onClick={(event) => {
        if ((event.target as HTMLElement).closest?.("[data-close]")) close();
      }}
    >
      <div className="bottom-sheet-overlay" data-close />
      <div className="bottom-sheet-panel" role="document" ref={panelRef}>
        <button
          type="button"
          className="bottom-sheet-handle"
          data-close
          aria-hidden="true"
          tabIndex={-1}
        />
        {title ? (
          <div className="bottom-sheet-header">
            <h2 id={titleId} className="bottom-sheet-title">
              {title}
            </h2>
            {description ? <p className="bottom-sheet-description">{description}</p> : null}
          </div>
        ) : null}
        <div className="bottom-sheet-body">{children}</div>
        <button
          type="button"
          className="krds-btn medium icon bottom-sheet-close"
          aria-label={closeLabel ?? "닫기"}
          onClick={close}
        >
          <SvgIcon name="ico-modal-close" />
        </button>
      </div>
    </div>
  );
}

// packages/solid/src/components/BottomSheet.tsx
import {
  Show,
  createEffect,
  createSignal,
  createUniqueId,
  mergeProps,
  onCleanup,
  splitProps,
  type JSX,
} from "solid-js";
import { focusableSelector, trapTabFocus } from "../shared.js";

const CLOSE_ANIMATION_MS = 200;

export interface BottomSheetProps {
  class?: string;
  className?: string;
  id?: string;
  open?: boolean;
  defaultOpen?: boolean;
  title?: JSX.Element;
  description?: JSX.Element;
  closeLabel?: string;
  children?: JSX.Element;
  onOpenChange?: (open: boolean) => void;
  [key: string]: unknown;
}

export function BottomSheet(rawProps: BottomSheetProps) {
  const merged = mergeProps({ closeLabel: "닫기" }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "open",
    "defaultOpen",
    "title",
    "description",
    "closeLabel",
    "children",
    "onOpenChange",
  ]);

  const generatedId = createUniqueId();
  const sheetId = () => props.id ?? `krds-bottom-sheet-${generatedId}`;
  const titleId = () => `tit_${sheetId()}`;

  const [localOpen, setLocalOpen] = createSignal(Boolean(props.defaultOpen));
  const open = () => (props.open === undefined ? localOpen() : Boolean(props.open));
  const setOpen = (next: boolean) => {
    if (props.open === undefined) setLocalOpen(next);
    props.onOpenChange?.(next);
  };

  const [closing, setClosing] = createSignal(false);
  const [rendered, setRendered] = createSignal(open());

  let removeTimer: number | undefined;
  const clearTimer = () => {
    clearTimeout(removeTimer);
    removeTimer = undefined;
  };

  const startClose = () => setOpen(false);

  let sheetRoot: HTMLDivElement | undefined;
  let panelRef: HTMLDivElement | undefined;
  let restoreFocus: HTMLElement | undefined;
  let wasOpen = false;
  let isInitialMount = true;

  createEffect(() => {
    const isOpen = open();
    const root = sheetRoot;
    if (!root) return;
    if (isOpen && !wasOpen) {
      clearTimer();
      setClosing(false);
      setRendered(true);
      const activeElement = root.ownerDocument.activeElement;
      const view = root.ownerDocument.defaultView;
      restoreFocus =
        view && activeElement instanceof view.HTMLElement && !root.contains(activeElement)
          ? activeElement
          : undefined;
      if (!isInitialMount) {
        panelRef?.querySelector<HTMLElement>(focusableSelector)?.focus();
      }
    } else if (!isOpen && wasOpen) {
      if (restoreFocus?.isConnected) restoreFocus.focus();
      restoreFocus = undefined;
      if (rendered()) {
        setClosing(true);
        props.onOpenChange?.(false);
        removeTimer = window.setTimeout(() => {
          setRendered(false);
          setClosing(false);
        }, CLOSE_ANIMATION_MS);
      }
    }
    wasOpen = isOpen;
    isInitialMount = false;
  });

  onCleanup(() => {
    clearTimer();
    if (restoreFocus?.isConnected) restoreFocus.focus();
  });

  const invokeHandler = (handler: unknown, event: Event) => {
    if (typeof handler === "function") handler(event);
    else if (Array.isArray(handler) && typeof handler[0] === "function")
      handler[0](handler[1], event);
  };

  const className = () => props.class ?? props.className ?? "";
  return (
    <Show when={rendered()}>
      <div
        {...(native as Record<string, any>)}
        ref={(element) => {
          sheetRoot = element;
        }}
        id={sheetId()}
        role="dialog"
        aria-modal={true}
        aria-labelledby={props.title ? titleId() : undefined}
        class={`krds-bottom-sheet${closing() ? " closing" : ""}${className() ? ` ${className()}` : ""}`}
        onClick={(event) => {
          invokeHandler(native.onClick, event);
          if (!event.defaultPrevented && (event.target as Element).closest(".bottom-sheet-overlay")) {
            startClose();
          }
        }}
        onKeyDown={(event) => {
          invokeHandler(native.onKeyDown, event);
          if (event.defaultPrevented) return;
          if (event.key === "Escape" || event.key === "Esc") {
            event.preventDefault();
            startClose();
            return;
          }
          const panel = panelRef;
          if (panel && open()) trapTabFocus(event, panel);
        }}
      >
        <div class="bottom-sheet-overlay" data-close />
        <div
          class="bottom-sheet-panel"
          role="document"
          ref={(element) => {
            panelRef = element;
          }}
        >
          <button type="button" class="bottom-sheet-handle" aria-hidden="true" tabindex="-1" />
          <Show when={props.title}>
            <div class="bottom-sheet-header">
              <h2 id={titleId()} class="bottom-sheet-title">
                {props.title}
              </h2>
              <Show when={props.description}>
                <p class="bottom-sheet-description">{props.description}</p>
              </Show>
            </div>
          </Show>
          <div class="bottom-sheet-body">{props.children}</div>
          <button
            type="button"
            class="krds-btn medium icon bottom-sheet-close"
            aria-label={props.closeLabel}
            onClick={startClose}
          >
            <i class="svg-icon ico-modal-close" />
          </button>
        </div>
      </div>
    </Show>
  );
}
