// packages/angular/src/components/calendar.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId, CALENDAR_MONTHS, type AngularCalendarCell } from "../kinds";

@Component({
  selector: "krds-calendar",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-calendar-area">
      <div
        class="calendar-wrap bottom"
        [class.single]="single"
        [attr.aria-label]="calendarLabel || null"
        tabindex="0"
      >
        <div class="calendar-head">
          <button type="button" class="btn-cal-move prev" (click)="moveCalendarMonth(-1)">
            <span class="sr-only">{{ previousMonthLabel }}</span>
          </button>
          <div class="calendar-switch-wrap">
            <div class="calendar-drop-down">
              <button
                type="button"
                class="btn-cal-switch year"
                role="combobox"
                [attr.aria-label]="yearSelectLabel || null"
                [attr.aria-controls]="id + '-calendar-year'"
                [attr.aria-expanded]="calendarYearOpen"
                aria-haspopup="listbox"
                (click)="toggleCalendarYear()"
              >
                {{ calendarYear }}년
              </button>
              <div class="calendar-select calendar-year-wrap" [class.active]="calendarYearOpen">
                <ul class="sel year" [id]="id + '-calendar-year'" role="listbox">
                  @for (optionYear of calendarYears; track optionYear) {
                    <li role="none">
                      <button
                        type="button"
                        role="option"
                        [class.active]="optionYear === calendarSelectedYear"
                        [attr.aria-selected]="optionYear === calendarSelectedYear"
                        [disabled]="disabledYears.includes(optionYear)"
                        (click)="selectCalendarYear(optionYear)"
                      >
                        {{ optionYear }}년
                      </button>
                    </li>
                  }
                </ul>
              </div>
            </div>
            <div class="calendar-drop-down">
              <button
                type="button"
                class="btn-cal-switch month"
                role="combobox"
                [attr.aria-label]="monthSelectLabel || null"
                [attr.aria-controls]="id + '-calendar-month'"
                [attr.aria-expanded]="calendarMonthOpen"
                aria-haspopup="listbox"
                (click)="toggleCalendarMonth()"
              >
                {{ padCalendarPart(calendarMonth) }}월
              </button>
              <div class="calendar-select calendar-mon-wrap" [class.active]="calendarMonthOpen">
                <ul class="sel month" [id]="id + '-calendar-month'" role="listbox">
                  @for (optionMonth of calendarMonths; track optionMonth) {
                    <li role="none">
                      <button
                        type="button"
                        role="option"
                        [class.active]="optionMonth === calendarSelectedMonth"
                        [attr.aria-selected]="optionMonth === calendarSelectedMonth"
                        [disabled]="disabledMonths.includes(optionMonth)"
                        (click)="selectCalendarMonth(optionMonth)"
                      >
                        {{ padCalendarPart(optionMonth) }}월
                      </button>
                    </li>
                  }
                </ul>
              </div>
            </div>
          </div>
          <button type="button" class="btn-cal-move next" (click)="moveCalendarMonth(1)">
            <span class="sr-only">{{ nextMonthLabel }}</span>
          </button>
        </div>
        <div class="calendar-body">
          <div class="calendar-table-wrap">
            <table class="calendar-tbl">
              <caption>
                {{
                  calendarYear
                }}년
                {{
                  padCalendarPart(calendarMonth)
                }}월
              </caption>
              <thead>
                <tr>
                  @for (weekday of weekdays; track $index) {
                    <th>{{ weekday }}</th>
                  }
                </tr>
              </thead>
              <tbody>
                @for (week of calendarWeeks; track $index) {
                  <tr>
                    @for (cell of week; track cell.date) {
                      <td [class]="cell.className" [attr.data-date]="cell.date">
                        <button
                          type="button"
                          class="btn-set-date"
                          [disabled]="cell.disabled"
                          [attr.aria-pressed]="cell.pressed ? true : null"
                          [attr.aria-label]="cell.ariaLabel"
                          (click)="selectCalendarDate(cell)"
                        >
                          <span>{{ cell.day }}</span>
                        </button>
                      </td>
                    }
                  </tr>
                }
              </tbody>
            </table>
          </div>
        </div>
        <div class="calendar-footer">
          <div class="calendar-btn-wrap">
            <button
              type="button"
              class="krds-btn small text"
              id="get-today"
              (click)="selectCalendarToday()"
            >
              {{ todayLabel }}
            </button>
            <button type="button" class="krds-btn small tertiary" (click)="touch()">
              {{ cancelLabel }}
            </button>
            <button type="button" class="krds-btn small primary" (click)="touch()">
              {{ confirmLabel }}
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class KrdsCalendarComponent {
  @Input() id = createStableId("krds-calendar");
  @Input() single = true;
  @Input() year: number | null = null;
  @Input() month: number | null = null;
  @Input() displayYear: number | null = null;
  @Input() displayMonth: number | null = null;
  @Input() selectedYear: number | null = null;
  @Input() selectedMonth: number | null = null;
  @Input() years: number[] = [];
  @Input() disabledYears: number[] = [];
  @Input() disabledMonths: number[] = [];
  @Input() leadingDays = 0;
  @Input() previousMonthDayCount = 0;
  @Input() dayCount = 0;
  @Input() rangeStartDay: number | null = null;
  @Input() rangeEndDay: number | null = null;
  @Input() todayDay: number | null = null;
  @Input() eventDays: number[] = [];
  @Input() disabledDays: number[] = [];
  @Input() calendarLabel = "";
  @Input() previousMonthLabel = "";
  @Input() nextMonthLabel = "";
  @Input() yearSelectLabel = "";
  @Input() monthSelectLabel = "";
  @Input() weekdays: string[] = [];
  @Input() todayLabel = "";
  @Input() eventLabel = "";
  @Input() cancelLabel = "";
  @Input() confirmLabel = "";
  @Input() value = "";
  @Output() valueChange = new EventEmitter<string>();
  @Output() yearChange = new EventEmitter<number>();
  @Output() monthChange = new EventEmitter<number>();
  calendarYearOpen = false;
  calendarMonthOpen = false;

  private onChange: (value: string | number | boolean | string[]) => void = () => undefined;

  get calendarYear(): number {
    return this.displayYear ?? this.year ?? this.years[0] ?? new Date().getFullYear();
  }

  get calendarMonth(): number {
    return this.displayMonth ?? this.month ?? new Date().getMonth() + 1;
  }

  get calendarSelectedYear(): number {
    return this.selectedYear ?? this.year ?? this.calendarYear;
  }

  get calendarSelectedMonth(): number {
    return this.selectedMonth ?? this.month ?? this.calendarMonth;
  }

  get calendarYears(): number[] {
    return this.years.length > 0 ? this.years : this.calendarYear === 0 ? [] : [this.calendarYear];
  }

  get calendarMonths(): readonly number[] {
    return CALENDAR_MONTHS;
  }

  get calendarWeeks(): AngularCalendarCell[][] {
    const activeYear = this.calendarYear;
    const activeMonth = this.calendarMonth;
    const leadingDays = Math.max(
      0,
      Math.min(6, this.leadingDays || new Date(activeYear, activeMonth - 1, 1).getDay()),
    );
    const dayCount = Math.max(0, this.dayCount || new Date(activeYear, activeMonth, 0).getDate());
    const previousMonthDayCount = Math.max(
      0,
      this.previousMonthDayCount || new Date(activeYear, activeMonth - 1, 0).getDate(),
    );
    const totalCells = Math.ceil((leadingDays + dayCount) / 7) * 7;
    const weeks: AngularCalendarCell[][] = [];

    for (let row = 0; row < totalCells / 7; row += 1) {
      const week: AngularCalendarCell[] = [];
      for (let column = 0; column < 7; column += 1) {
        const index = row * 7 + column;
        const offset = index - leadingDays + 1;
        let day: number;
        let month = activeMonth;
        let year = activeYear;
        let offMonth: "old" | "new" | null = null;

        if (offset < 1) {
          day = previousMonthDayCount + offset;
          offMonth = "old";
          month = activeMonth === 1 ? 12 : activeMonth - 1;
          year = activeMonth === 1 ? activeYear - 1 : activeYear;
        } else if (offset > dayCount) {
          day = offset - dayCount;
          offMonth = "new";
          month = activeMonth === 12 ? 1 : activeMonth + 1;
          year = activeMonth === 12 ? activeYear + 1 : activeYear;
        } else {
          day = offset;
        }

        const currentMonth = offMonth === null;
        const period =
          currentMonth &&
          this.rangeStartDay !== null &&
          this.rangeEndDay !== null &&
          day >= this.rangeStartDay &&
          day <= this.rangeEndDay;
        const start = period && day === this.rangeStartDay;
        const end = period && day === this.rangeEndDay;
        const today = currentMonth && day === this.todayDay;
        const event = currentMonth && this.eventDays.includes(day);
        const dateDisabled = currentMonth && this.disabledDays.includes(day);
        const disabled = !currentMonth || dateDisabled;
        const date = `${year}.${this.padCalendarPart(month)}.${this.padCalendarPart(day)}`;
        const selected = this.value === date;
        const classes = [
          offMonth,
          column === 0 ? "day-off" : null,
          period || (selected && !period) ? "period" : null,
          start || (selected && !period) ? "start" : null,
          end || (selected && !period) ? "end" : null,
          today ? "today" : null,
          event ? "day-event" : null,
          dateDisabled ? "disabled" : null,
        ].filter((className): className is string => className !== null);

        week.push({
          day,
          date,
          className: classes.join(" "),
          disabled,
          pressed: period || selected,
          ariaLabel: today
            ? `${day} ${this.todayLabel}`.trim()
            : event
              ? `${day} ${this.eventLabel}`.trim()
              : null,
        });
      }
      weeks.push(week);
    }

    return weeks;
  }

  padCalendarPart(value: number): string {
    return value.toString().padStart(2, "0");
  }

  toggleCalendarYear(): void {
    this.calendarYearOpen = !this.calendarYearOpen;
    this.calendarMonthOpen = false;
  }

  toggleCalendarMonth(): void {
    this.calendarMonthOpen = !this.calendarMonthOpen;
    this.calendarYearOpen = false;
  }

  selectCalendarYear(year: number): void {
    if (this.disabledYears.includes(year)) return;
    this.year = year;
    this.displayYear = year;
    this.selectedYear = year;
    this.calendarYearOpen = false;
    this.yearChange.emit(year);
  }

  selectCalendarMonth(month: number): void {
    if (this.disabledMonths.includes(month)) return;
    this.month = month;
    this.displayMonth = month;
    this.selectedMonth = month;
    this.calendarMonthOpen = false;
    this.monthChange.emit(month);
  }

  moveCalendarMonth(direction: -1 | 1): void {
    let year = this.calendarYear;
    let month = this.calendarMonth + direction;
    if (month === 0) {
      month = 12;
      year -= 1;
    } else if (month === 13) {
      month = 1;
      year += 1;
    }
    this.year = year;
    this.month = month;
    this.displayYear = year;
    this.displayMonth = month;
    this.selectedYear = year;
    this.selectedMonth = month;
    this.calendarYearOpen = false;
    this.calendarMonthOpen = false;
    this.yearChange.emit(year);
    this.monthChange.emit(month);
  }

  selectCalendarDate(cell: AngularCalendarCell): void {
    if (!cell.disabled) this.setValue(cell.date);
  }

  selectCalendarToday(): void {
    if (this.todayDay === null) return;
    const date = `${this.calendarYear}.${this.padCalendarPart(
      this.calendarMonth,
    )}.${this.padCalendarPart(this.todayDay)}`;
    this.setValue(date);
  }

  private setValue(value: string): void {
    this.value = value;
    this.onChange(value);
    this.valueChange.emit(value);
  }

  touch(): void {
    this.onTouched();
  }

  private onTouched: () => void = () => undefined;
}

// packages/solid/src/components/Calendar.tsx
import { For, Show, createSignal, createUniqueId, mergeProps, splitProps } from "solid-js";
import {
  numberValue,
  choiceNumber,
  padCalendarPart,
  type CalendarChoiceInput,
  type CalendarDay,
  type CalendarAction,
} from "../shared.js";

export interface CalendarProps {
  class?: string;
  className?: string;
  id?: string;
  label?: string;
  calendarLabel?: string;
  todayLabel?: string;
  yearLabel?: string;
  monthLabel?: string;
  previousMonthLabel?: string;
  previousmonthlabel?: string;
  nextmonthlabel?: string;
  nextMonthLabel?: string;
  previousLabel?: string;
  nextLabel?: string;
  cancelLabel?: string;
  confirmLabel?: string;
  yearSelectLabel?: string;
  monthSelectLabel?: string;
  eventLabel?: string;
  year?: string | number;
  month?: string | number;
  displayYear?: string | number;
  displayMonth?: string | number;
  selectedYear?: string | number;
  selectedMonth?: string | number;
  years?: CalendarChoiceInput[];
  months?: CalendarChoiceInput[];
  disabledYears?: number[];
  disabledMonths?: number[];
  leadingDays?: number;
  previousMonthDayCount?: number;
  dayCount?: number;
  rangeStartDay?: number;
  rangeEndDay?: number;
  todayDay?: number;
  eventDays?: number[];
  disabledDays?: number[];
  weekdays?: string[];
  weeks?: CalendarDay[][];
  actions?: CalendarAction[];
  defaultValue?: string;
  value?: string;
  modelValue?: string;
  selected?: string;
  selectedLabel?: string;
  open?: boolean;
  hint?: string;
  name?: string;
  [key: string]: unknown;
}

const renderCalendarSurface = (
  props: Record<string, any>,
  native: Record<string, any>,
  single: boolean,
  includeNative: boolean,
) => {
  const p = props as unknown as CalendarProps;
  const n = native as Record<string, any>;

  const calendarDisplayYear = () =>
    numberValue(
      (p as Record<string, any>).displayYear ??
        (p as Record<string, any>).year ??
        (p as Record<string, any>).selectedYear,
      new Date().getFullYear(),
    );
  const calendarDisplayMonth = () =>
    Math.min(
      12,
      Math.max(
        1,
        numberValue(
          (p as Record<string, any>).displayMonth ??
            (p as Record<string, any>).month ??
            (p as Record<string, any>).selectedMonth,
          new Date().getMonth() + 1,
        ),
      ),
    );
  const calendarSelectedYear = () =>
    numberValue(
      (p as Record<string, any>).selectedYear ??
        (p as Record<string, any>).year ??
        (p as Record<string, any>).displayYear,
      calendarDisplayYear(),
    );
  const calendarSelectedMonth = () =>
    Math.min(
      12,
      Math.max(
        1,
        numberValue(
          (p as Record<string, any>).selectedMonth ??
            (p as Record<string, any>).month ??
            (p as Record<string, any>).displayMonth,
          calendarDisplayMonth(),
        ),
      ),
    );
  const calendarYears = () => {
    const source =
      p.years && p.years.length > 0
        ? p.years
        : Array.from({ length: 24 }, (_, offset) => calendarDisplayYear() - 1 + offset);
    return source.map((choice: CalendarChoiceInput) => {
      const year = choiceNumber(choice, calendarDisplayYear());
      const original = typeof choice === "number" ? undefined : choice;
      return {
        label: original?.label ?? `${year}년`,
        value: String(year),
        active: year === calendarSelectedYear(),
        disabled: original?.disabled === true || ((p.disabledYears ?? []).includes(year) ?? false),
      };
    });
  };
  const calendarMonths = () => {
    const source =
      p.months && p.months.length > 0
        ? p.months
        : Array.from({ length: 12 }, (_, offset) => offset + 1);
    return source.map((choice: CalendarChoiceInput) => {
      const month = choiceNumber(choice, calendarDisplayMonth());
      const original = typeof choice === "number" ? undefined : choice;
      return {
        label: original?.label ?? `${padCalendarPart(month)}월`,
        value: String(month),
        active: month === calendarSelectedMonth(),
        disabled:
          original?.disabled === true || ((p.disabledMonths ?? []).includes(month) ?? false),
      };
    });
  };
  const calendarSelectedDate = () => {
    const raw = (p as Record<string, any>).value ?? (p as Record<string, any>).modelValue;
    const match = typeof raw === "string" && /^(\d{4})[.-](\d{2})[.-](\d{2})$/.exec(raw);
    return match ? `${match[1]}.${match[2]}.${match[3]}` : undefined;
  };
  const calendarWeeks = () => {
    if (p.weeks && p.weeks.length > 0) return p.weeks;
    const displayYear = calendarDisplayYear();
    const displayMonth = calendarDisplayMonth();
    const leadingDays = Math.min(
      6,
      Math.max(0, numberValue(p.leadingDays, new Date(displayYear, displayMonth - 1, 1).getDay())),
    );
    const previousMonthDayCount = Math.max(
      0,
      numberValue(p.previousMonthDayCount, new Date(displayYear, displayMonth - 1, 0).getDate()),
    );
    const dayCount = Math.max(
      0,
      numberValue(p.dayCount, new Date(displayYear, displayMonth, 0).getDate()),
    );
    const totalCells = Math.ceil((leadingDays + dayCount) / 7) * 7;
    const selectedDate = calendarSelectedDate();
    return Array.from({ length: totalCells / 7 }, (_, row) =>
      Array.from({ length: 7 }, (_, column) => {
        const index = row * 7 + column;
        const offset = index - leadingDays + 1;
        const old = offset < 1;
        const next = offset > dayCount;
        const day = old ? previousMonthDayCount + offset : next ? offset - dayCount : offset;
        const month = old
          ? displayMonth === 1
            ? 12
            : displayMonth - 1
          : next
            ? displayMonth === 12
              ? 1
              : displayMonth + 1
            : displayMonth;
        const year =
          old && displayMonth === 1
            ? displayYear - 1
            : next && displayMonth === 12
              ? displayYear + 1
              : displayYear;
        const currentMonth = !old && !next;
        const period =
          currentMonth &&
          p.rangeStartDay !== undefined &&
          p.rangeEndDay !== undefined &&
          day >= p.rangeStartDay &&
          day <= p.rangeEndDay;
        const start = period && day === p.rangeStartDay;
        const end = period && day === p.rangeEndDay;
        const today = currentMonth && day === p.todayDay;
        const event = currentMonth && (p.eventDays?.includes(day) ?? false);
        const disabled = currentMonth && (p.disabledDays?.includes(day) ?? false);
        const date = `${year}.${padCalendarPart(month)}.${padCalendarPart(day)}`;
        const selected = currentMonth && selectedDate === date;
        const classes = [
          old ? "old" : next ? "new" : undefined,
          column === 0 ? "day-off" : undefined,
          period ? "period" : undefined,
          start ? "start" : undefined,
          end ? "end" : undefined,
          today ? "today" : undefined,
          event ? "day-event" : undefined,
          disabled ? "disabled" : undefined,
        ]
          .filter(Boolean)
          .join(" ");
        return {
          label: String(day),
          value: date,
          className: classes,
          disabled: !currentMonth || disabled,
          pressed: period || selected,
          ariaLabel: today
            ? `${day} ${p.todayLabel ?? ""}`.trim()
            : event
              ? `${day} ${p.eventLabel ?? ""}`.trim()
              : undefined,
        };
      }),
    );
  };
  const calendarActions = (): CalendarAction[] =>
    p.actions && p.actions.length > 0
      ? p.actions
      : [
          { id: "get-today", label: String(p.todayLabel ?? ""), variant: "text" },
          { label: String(p.cancelLabel ?? ""), variant: "tertiary" },
          { label: String(p.confirmLabel ?? ""), variant: "primary" },
        ];
  const [calendarYearOpen, setCalendarYearOpen] = createSignal(false);
  const [calendarMonthOpen, setCalendarMonthOpen] = createSignal(false);
  return (
    <div
      {...(includeNative ? n : {})}
      class={`krds-calendar-area${((p as Record<string, any>).className as string) ? ` ${(p as Record<string, any>).className}` : ""}`}
    >
      <div
        class={["calendar-wrap", "bottom", single && "single"].filter(Boolean).join(" ")}
        aria-label={p.calendarLabel ?? "달력"}
        tabIndex={0}
      >
        <div class="calendar-head">
          <button type="button" class="btn-cal-move prev">
            <span class="sr-only">
              {p.previousMonthLabel ?? p.previousmonthlabel ?? p.previousLabel}
            </span>
          </button>
          <div class="calendar-switch-wrap">
            <div class="calendar-drop-down">
              <button
                type="button"
                class="btn-cal-switch year"
                role="combobox"
                aria-label={p.yearSelectLabel ?? p.yearLabel}
                aria-haspopup="listbox"
                aria-expanded={calendarYearOpen()}
                aria-controls={`${p.id}-calendar-year`}
                onClick={() => setCalendarYearOpen((o) => !o)}
              >
                {`${calendarDisplayYear()}년`}
              </button>
              <div class="calendar-select calendar-year-wrap">
                <ul class="sel year" id={`${p.id}-calendar-year`} role="listbox">
                  <For each={calendarYears()}>
                    {(choice) => (
                      <li role="none">
                        <button
                          type="button"
                          role="option"
                          classList={{ active: choice.active }}
                          aria-selected={choice.active}
                          disabled={choice.disabled}
                        >
                          {choice.label}
                        </button>
                      </li>
                    )}
                  </For>
                </ul>
              </div>
            </div>
            <div class="calendar-drop-down">
              <button
                type="button"
                class="btn-cal-switch month"
                role="combobox"
                aria-label={p.monthSelectLabel ?? p.monthLabel}
                aria-haspopup="listbox"
                aria-expanded={calendarMonthOpen()}
                aria-controls={`${p.id}-calendar-month`}
                onClick={() => setCalendarMonthOpen((o) => !o)}
              >
                {`${padCalendarPart(calendarDisplayMonth())}월`}
              </button>
              <div class="calendar-select calendar-mon-wrap">
                <ul class="sel month" id={`${p.id}-calendar-month`} role="listbox">
                  <For each={calendarMonths()}>
                    {(choice) => (
                      <li role="none">
                        <button
                          type="button"
                          role="option"
                          classList={{ active: choice.active }}
                          aria-selected={choice.active}
                          disabled={choice.disabled}
                        >
                          {choice.label}
                        </button>
                      </li>
                    )}
                  </For>
                </ul>
              </div>
            </div>
          </div>
          <button type="button" class="btn-cal-move next">
            <span class="sr-only">{p.nextMonthLabel ?? p.nextmonthlabel ?? p.nextLabel}</span>
          </button>
        </div>
        <div class="calendar-body">
          <div class="calendar-table-wrap">
            <table class="calendar-tbl">
              <caption>{`${calendarDisplayYear()}년 ${padCalendarPart(calendarDisplayMonth())}월`}</caption>
              <thead>
                <tr>
                  <For each={p.weekdays ?? ["일", "월", "화", "수", "목", "금", "토"]}>
                    {(weekday) => <th>{weekday}</th>}
                  </For>
                </tr>
              </thead>
              <tbody>
                <For each={calendarWeeks()}>
                  {(week) => (
                    <tr>
                      <For each={week}>
                        {(day) => {
                          const pressedResult = "pressed" in day && day.pressed;
                          const ariaLabel = "ariaLabel" in day ? day.ariaLabel : undefined;
                          return (
                            <td class={day.className || undefined} data-date={day.value}>
                              <button
                                type="button"
                                class="btn-set-date"
                                disabled={day.disabled}
                                aria-pressed={pressedResult ? "true" : undefined}
                                aria-label={ariaLabel}
                                onClick={(event) => {
                                  (p as Record<string, any>).onChange?.(event);
                                }}
                              >
                                <span>{day.label}</span>
                              </button>
                            </td>
                          );
                        }}
                      </For>
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>
        </div>
        <div class="calendar-footer">
          <div class="calendar-btn-wrap">
            <For each={calendarActions()}>
              {(action) => (
                <button
                  type="button"
                  id={action.id}
                  class={["krds-btn", "small", action.variant].filter(Boolean).join(" ")}
                  onClick={(event) => (p as Record<string, any>).onClick?.(event)}
                >
                  {action.label}
                  <Show when={action.icon}>
                    <i class={`svg-icon ico-${action.icon}`} />
                  </Show>
                </button>
              )}
            </For>
          </div>
        </div>
      </div>
    </div>
  );
};

export function Calendar(rawProps: CalendarProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "label",
    "calendarLabel",
    "calendarOpenLabel",
    "todayLabel",
    "yearLabel",
    "monthLabel",
    "previousMonthLabel",
    "previousmonthlabel",
    "nextmonthlabel",
    "nextMonthLabel",
    "previousLabel",
    "nextLabel",
    "cancelLabel",
    "confirmLabel",
    "yearSelectLabel",
    "monthSelectLabel",
    "eventLabel",
    "year",
    "month",
    "displayYear",
    "displayMonth",
    "selectedYear",
    "selectedMonth",
    "years",
    "months",
    "disabledYears",
    "disabledMonths",
    "leadingDays",
    "previousMonthDayCount",
    "dayCount",
    "rangeStartDay",
    "rangeEndDay",
    "todayDay",
    "eventDays",
    "disabledDays",
    "weekdays",
    "weeks",
    "actions",
    "defaultValue",
    "value",
    "modelValue",
    "selected",
    "selectedLabel",
    "open",
    "hint",
    "name",
  ]);
  const instanceId = createUniqueId?.() ?? "cal";
  return renderCalendarSurface(
    { ...props, instanceId } as unknown as Record<string, any>,
    native as unknown as Record<string, any>,
    true,
    true,
  );
}

export function CalendarRange(rawProps: CalendarProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "label",
    "calendarLabel",
    "calendarOpenLabel",
    "todayLabel",
    "yearLabel",
    "monthLabel",
    "previousMonthLabel",
    "previousmonthlabel",
    "nextmonthlabel",
    "nextMonthLabel",
    "previousLabel",
    "nextLabel",
    "cancelLabel",
    "confirmLabel",
    "yearSelectLabel",
    "monthSelectLabel",
    "eventLabel",
    "year",
    "month",
    "displayYear",
    "displayMonth",
    "selectedYear",
    "selectedMonth",
    "years",
    "months",
    "disabledYears",
    "disabledMonths",
    "leadingDays",
    "previousMonthDayCount",
    "dayCount",
    "rangeStartDay",
    "rangeEndDay",
    "todayDay",
    "eventDays",
    "disabledDays",
    "weekdays",
    "weeks",
    "actions",
    "defaultValue",
    "value",
    "modelValue",
    "selected",
    "selectedLabel",
    "open",
    "hint",
    "name",
  ]);
  const instanceId = createUniqueId?.() ?? "cal";
  return renderCalendarSurface(
    { ...props, instanceId } as unknown as Record<string, any>,
    native as unknown as Record<string, any>,
    false,
    true,
  );
}

export function DateInput(rawProps: CalendarProps) {
  const merged = mergeProps({ id: `krds-date-input-${createUniqueId()}` }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "label",
    "calendarLabel",
    "calendarOpenLabel",
    "todayLabel",
    "yearLabel",
    "monthLabel",
    "previousMonthLabel",
    "previousmonthlabel",
    "nextmonthlabel",
    "nextMonthLabel",
    "previousLabel",
    "nextLabel",
    "cancelLabel",
    "confirmLabel",
    "yearSelectLabel",
    "monthSelectLabel",
    "eventLabel",
    "year",
    "month",
    "displayYear",
    "displayMonth",
    "selectedYear",
    "selectedMonth",
    "years",
    "months",
    "disabledYears",
    "disabledMonths",
    "leadingDays",
    "previousMonthDayCount",
    "dayCount",
    "rangeStartDay",
    "rangeEndDay",
    "todayDay",
    "eventDays",
    "disabledDays",
    "weekdays",
    "weeks",
    "actions",
    "defaultValue",
    "value",
    "modelValue",
    "selected",
    "selectedLabel",
    "open",
    "hint",
    "name",
  ]);
  const [localValue, setLocalValue] = createSignal("");
  const value = () => {
    if (props.value !== undefined) return String(props.value ?? "");
    if (typeof props.modelValue === "string" || typeof props.modelValue === "number")
      return String(props.modelValue);
    return localValue();
  };
  const setValue = (next: string) => {
    if (props.value === undefined) setLocalValue(next);
  };
  const updateInput = (
    event: InputEvent & { currentTarget: HTMLInputElement | HTMLTextAreaElement },
  ) => {
    setValue(event.currentTarget.value);
  };
  const instanceId = createUniqueId?.() ?? "di";
  return (
    <div {...(native as Record<string, any>)} class="form-group">
      <div class="form-tit">
        <label for={props.id}>{props.label}</label>
      </div>
      <div class="form-conts">
        <div class="form-conts calendar-conts">
          <div class="calendar-input">
            <input
              id={props.id}
              name={props.name}
              type="number"
              class="krds-input datepicker cal"
              placeholder="YYYY.MM.DD"
              value={value()}
              onInput={updateInput}
            />
            <button type="button" class="krds-btn medium icon form-btn-datepicker">
              <span class="sr-only">{`${props.calendarLabel ?? "달력"} 열기`}</span>
              <i class="svg-icon ico-calendar" />
            </button>
          </div>
          {renderCalendarSurface(
            { ...props, instanceId } as unknown as Record<string, any>,
            {} as Record<string, any>,
            false,
            false,
          )}
        </div>
      </div>
      <Show when={props.hint}>
        <p class="form-hint">{props.hint}</p>
      </Show>
    </div>
  );
}
