// packages/svelte/src/Card.svelte
<script lang="ts">
  import Badge from './Badge.svelte';
  import Button from './Button.svelte';
  import Checkbox from './Checkbox.svelte';

  type Action = { label: string; onClick?: () => void };

  type Props = {
    type?: 'vertical' | 'horizontal';
    image?: string;
    imageAlt?: string;
    title: string;
    description?: string;
    badges?: string[];
    actions?: Action[];
    checkbox?: Record<string, unknown>;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    type = 'vertical',
    image = '',
    imageAlt = '',
    title,
    description = '',
    badges = [],
    actions = [],
    checkbox,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<article {...rest} class={`krds-card ${type} ${rootClass}`}>
  {#if image || badges.length || checkbox}
    <div class="card-top">
      {#if image}
        <img class="card-image" src={image} alt={imageAlt} />
      {/if}
      {#each badges as badge}
        <Badge label={badge} appearance="solid" className="card-badge" />
      {/each}
      {#if checkbox}
        <Checkbox {...checkbox} />
      {/if}
    </div>
  {/if}
  <div class="card-conts">
    <h3 class="card-title">{title}</h3>
    {#if description}
      <p class="card-description">{description}</p>
    {/if}
    {#if actions.length}
      <div class="card-actions">
        {#each actions as action}
          <Button size="small" variant="primary" onclick={action.onClick}>{action.label}</Button>
        {/each}
      </div>
    {/if}
  </div>
</article>

// packages/solid/src/components/Card.tsx
import { For, Show, mergeProps, splitProps, type JSX } from "solid-js";
import { Badge } from "./Badge.js";

export interface CardAction {
  label: string;
  onClick?: () => void;
}

export interface CardCheckboxProps {
  label?: string;
  name?: string;
  value?: string;
  checked?: boolean;
  disabled?: boolean;
  onChange?: (event: Event) => void;
}

export interface CardProps {
  class?: string;
  className?: string;
  type?: "vertical" | "horizontal";
  image?: string;
  imageAlt?: string;
  title: JSX.Element;
  description?: JSX.Element;
  badges?: string[];
  actions?: CardAction[];
  checkbox?: CardCheckboxProps;
  [key: string]: unknown;
}

export function Card(rawProps: CardProps) {
  const merged = mergeProps({ type: "vertical" as const, imageAlt: "" }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "type",
    "image",
    "imageAlt",
    "title",
    "description",
    "badges",
    "actions",
    "checkbox",
  ]);

  const className = () => props.class ?? props.className ?? "";
  return (
    <article
      {...(native as Record<string, any>)}
      class={`krds-card ${props.type}${className() ? ` ${className()}` : ""}`}
    >
      <Show when={props.image || props.badges?.length}>
        <div class="card-top">
          <Show when={props.image}>
            <img class="card-image" src={props.image} alt={props.imageAlt} />
          </Show>
          <For each={props.badges}>
            {(badge) => (
              <div class="card-badge">
                <Badge appearance="solid">{badge}</Badge>
              </div>
            )}
          </For>
        </div>
      </Show>
      <div class="card-conts">
        <Show when={props.checkbox}>
          <div class="krds-form-check">
            <input
              type="checkbox"
              name={props.checkbox?.name}
              value={props.checkbox?.value}
              checked={props.checkbox?.checked}
              disabled={props.checkbox?.disabled}
              onChange={props.checkbox?.onChange}
            />
            <label>{props.checkbox?.label}</label>
          </div>
        </Show>
        <h3 class="card-title">{props.title}</h3>
        <Show when={props.description}>
          <p class="card-description">{props.description}</p>
        </Show>
        <Show when={props.actions?.length}>
          <div class="card-actions">
            <For each={props.actions}>
              {(action) => (
                <button type="button" class="krds-btn small primary" onClick={action.onClick}>
                  {action.label}
                </button>
              )}
            </For>
          </div>
        </Show>
      </div>
    </article>
  );
}
