// packages/react/src/components/Chip.tsx
import { useState } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface ChipOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface ChipProps extends Omit<BoxProps, "selected" | "options"> {
  type?: "single" | "multi";
  size?: "large" | "medium";
  options: ChipOption[];
  selected?: string | string[];
  defaultSelected?: string | string[];
  onChange?: (value: string | string[]) => void;
  ariaLabel?: string;
}

export function Chip({
  type = "single",
  size = "medium",
  options,
  selected: controlledSelected,
  defaultSelected,
  onChange,
  ariaLabel = "선택",
  className,
}: ChipProps) {
  const controlled = controlledSelected !== undefined;
  const [internalSelected, setInternalSelected] = useState<string | string[] | undefined>(
    defaultSelected ?? (type === "multi" ? [] : undefined),
  );
  const current = controlled ? controlledSelected : internalSelected;

  const isSelected = (option: ChipOption) =>
    type === "multi"
      ? Array.isArray(current) && current.includes(option.value)
      : current === option.value;

  const toggle = (option: ChipOption) => {
    if (option.disabled) return;
    if (type === "multi") {
      const next = Array.isArray(current) && current.includes(option.value)
        ? current.filter((item) => item !== option.value)
        : [...(Array.isArray(current) ? current : []), option.value];
      if (!controlled) setInternalSelected(next);
      onChange?.(next);
    } else {
      if (current === option.value) return;
      if (!controlled) setInternalSelected(option.value);
      onChange?.(option.value);
    }
  };

  return (
    <div
      className={cx("krds-chip", type, size, className)}
      role={type === "single" ? "radiogroup" : "group"}
      aria-label={ariaLabel}
    >
      {options.map((option) => (
        <button
          key={option.value}
          type="button"
          className={cx("krds-btn small text chip", isSelected(option) && "active")}
          aria-pressed={isSelected(option)}
          disabled={option.disabled}
          onClick={() => toggle(option)}
        >
          {option.label}
        </button>
      ))}
    </div>
  );
}

// packages/solid/src/components/Chip.tsx
import { For, createSignal, mergeProps, splitProps } from "solid-js";

export interface ChipOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface ChipProps {
  class?: string;
  className?: string;
  type?: "single" | "multi";
  size?: "large" | "medium";
  options: ChipOption[];
  selected?: string | string[];
  defaultSelected?: string | string[];
  onChange?: (value: string | string[]) => void;
  ariaLabel?: string;
  [key: string]: unknown;
}

export function Chip(rawProps: ChipProps) {
  const merged = mergeProps({ type: "single" as const, size: "medium" as const }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "type",
    "size",
    "options",
    "selected",
    "defaultSelected",
    "onChange",
    "ariaLabel",
  ]);

  const [localSelected, setLocalSelected] = createSignal<string | string[] | undefined>(
    props.defaultSelected,
  );
  const selected = () =>
    props.selected !== undefined ? props.selected : localSelected();

  const isSelected = (value: string) => {
    if (props.type === "single") return selected() === value;
    const values = Array.isArray(selected()) ? (selected() as string[]) : [];
    return values.includes(value);
  };

  const select = (value: string) => {
    let next: string | string[];
    if (props.type === "single") {
      next = value;
    } else {
      const current = Array.isArray(selected()) ? (selected() as string[]) : [];
      next = current.includes(value)
        ? current.filter((item) => item !== value)
        : [...current, value];
    }
    if (props.selected === undefined) setLocalSelected(next);
    props.onChange?.(next);
  };

  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-chip ${props.type} ${props.size}${className() ? ` ${className()}` : ""}`}
      role={props.type === "single" ? "radiogroup" : "group"}
      aria-label={props.ariaLabel ?? "선택"}
    >
      <For each={props.options}>
        {(option) => (
          <button
            type="button"
            class={`krds-btn small text chip${isSelected(option.value) ? " active" : ""}`}
            aria-pressed={isSelected(option.value)}
            disabled={option.disabled}
            onClick={() => select(option.value)}
          >
            {option.label}
          </button>
        )}
      </For>
    </div>
  );
}
