// packages/react/src/components/ContextualHelp.tsx
import { useState, useId, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

export interface ContextualHelpProps extends Omit<BoxProps, "position" | "open"> {
  label?: string;
  position?:
    | "top"
    | "bottom"
    | "left"
    | "right"
    | "top-left"
    | "top-right"
    | "bottom-left"
    | "bottom-right";
  caption?: ReactNode;
  title?: ReactNode;
  linkLabel?: ReactNode;
  href?: string;
  closeLabel?: ReactNode;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function ContextualHelp({
  label,
  position = "top-left",
  caption,
  title,
  linkLabel,
  href = "#",
  closeLabel,
  open: controlledOpen,
  defaultOpen = false,
  onOpenChange,
  children,
  className,
}: ContextualHelpProps) {
  const generatedId = useId();
  const popoverId = `krds-contextual-help-${generatedId}`;
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);

  const open = controlledOpen ?? uncontrolledOpen;
  const setOpen = (next: boolean) => {
    if (controlledOpen === undefined) setUncontrolledOpen(next);
    onOpenChange?.(next);
  };
  return (
    <div className={cx("krds-contextual-help", ...position.split("-"), className)}>
      <p className="tooltip-txt">{caption}</p>
      <div className="tooltip-action">
        <button
          type="button"
          className="krds-btn medium icon tooltip-btn"
          aria-expanded={open}
          aria-controls={popoverId}
          onClick={() => setOpen(!open)}
        >
          <span className="sr-only">{label}</span>
          <SvgIcon name="ico-tooltip" />
        </button>
        <div
          id={popoverId}
          className="tooltip-popover"
          role="tooltip"
          style={open ? { display: "block", width: "360px" } : undefined}
        >
          <h4 className="tooltip-title">{title}</h4>
          <div className="tooltip-contents">
            <p>{children}</p>
            {linkLabel ? (
              <div className="btn-wrap">
                <a href={href} className="krds-btn xsmall link basic">
                  {linkLabel} <SvgIcon name="ico-angle right" />
                </a>
              </div>
            ) : null}
          </div>
          <button
            type="button"
            className="krds-btn xsmall icon tooltip-close"
            onClick={() => setOpen(false)}
          >
            <span className="sr-only">{closeLabel}</span>
            <SvgIcon name="ico-modal-close" />
          </button>
        </div>
      </div>
    </div>
  );
}

// packages/solid/src/components/ContextualHelp.tsx
import { Show, createSignal, mergeProps, splitProps, type JSX } from "solid-js";

export interface ContextualHelpProps {
  id?: string;
  label?: string;
  position?: string;
  caption?: string;
  title?: string;
  description?: string;
  href?: string;
  linkLabel?: string;
  closeLabel?: string;
  message?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
  open?: boolean;
}

export function ContextualHelp(rawProps: ContextualHelpProps) {
  const merged = mergeProps(
    {
      closeLabel: "",
    },
    rawProps,
  );
  const [localOpen, setLocalOpen] = createSignal(false);
  const [props, native] = splitProps(merged, [
    "id",
    "label",
    "open",
    "position",
    "caption",
    "title",
    "description",
    "href",
    "linkLabel",
    "closeLabel",
    "message",
    "class",
    "className",
    "children",
  ]);
  const open = () => (props.open !== undefined ? Boolean(props.open) : localOpen());
  const setOpen = (next: boolean) => {
    if (props.open === undefined) setLocalOpen(next);
  };

  const className = () => props.class ?? props.className ?? "";
  const children = () => props.children;

  return (
    <div
      {...(native as Record<string, any>)}
      class={[
        "krds-contextual-help",
        props.position === "top-left" ? "left top" : props.position?.replace("-", " "),
        className(),
      ]
        .filter(Boolean)
        .join(" ")}
    >
      <p class="tooltip-txt">{props.caption}</p>
      <div class="tooltip-action">
        <button
          type="button"
          class="krds-btn medium icon tooltip-btn"
          aria-expanded={open()}
          aria-controls={`${props.id}-popover`}
          onClick={() => setOpen(!open())}
        >
          <span class="sr-only">{props.label}</span>
          <i class="svg-icon ico-tooltip" />
        </button>
        <div
          id={`${props.id}-popover`}
          class="tooltip-popover"
          role="tooltip"
          style={{ display: open() ? "block" : undefined }}
        >
          <h4 class="tooltip-title">{props.title}</h4>
          <div class="tooltip-contents">
            <p>{props.description ?? children()}</p>
            <Show when={props.href}>
              <div class="btn-wrap">
                <a class="krds-btn xsmall basic link" href={props.href}>
                  {props.linkLabel}
                  <i class="svg-icon ico-angle right" />
                </a>
              </div>
            </Show>
          </div>
          <button
            type="button"
            class="krds-btn xsmall icon tooltip-close"
            onClick={() => setOpen(false)}
          >
            <span class="sr-only">{props.closeLabel}</span>
            <i class="svg-icon ico-modal-close" />
          </button>
        </div>
      </div>
    </div>
  );
}
