// packages/svelte/src/CriticalAlerts.svelte
<script lang="ts">
  import { fieldOf, labelOf, hrefOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    items?: unknown[];
    linkLabel?: string;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    items = [] as unknown[],
    linkLabel = '',
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div {...rest} class={`main-urgent-wrap ${rootClass}`} role="alert">
  <ul class="krds-critical-alerts">
    {#each items as item}
      <li>
        <div class="critical-ban">
          <span class={`critical-badge ${fieldOf(item, 'tone') || 'info'}`}
            >{fieldOf(item, 'badgeLabel') || fieldOf(item, 'badge') || labelOf(item)}</span
          >
          <p class="critical-txt"
            >{fieldOf(item, 'message') || fieldOf(item, 'text') || fieldOf(item, 'description') || labelOf(item)}</p
          >
          <a class="basic krds-btn link medium" href={hrefOf(item)}>
            <span class="m-hide">{fieldOf(item, 'linkLabel') || fieldOf(item, 'actionLabel') || linkLabel}</span>
            <i class="ico-angle right svg-icon"></i>
          </a>
        </div>
      </li>
    {/each}
  </ul>
</div>

// packages/solid/src/components/CriticalAlerts.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import { labelOf } from "../shared.js";
import type { AlertItem } from "../shared.js";

export interface CriticalAlertsProps {
  class?: string;
  className?: string;
  items: AlertItem[];
  actionLabel?: string;
  [key: string]: unknown;
}

export function CriticalAlerts(rawProps: CriticalAlertsProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, ["class", "className", "items", "actionLabel"]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`main-urgent-wrap${className() ? ` ${className()}` : ""}`}
      role="alert"
    >
      <ul class="krds-critical-alerts">
        <For each={props.items}>
          {(item) => {
            const alert = () =>
              typeof item === "string" || typeof item === "number"
                ? undefined
                : (item as AlertItem);
            const badge = () => alert()?.badge;
            const href = () => alert()?.href;
            return (
              <li>
                <div class="critical-ban">
                  <Show when={badge()}>
                    <span class={`critical-badge ${badge()}`}>{alert()?.badgeLabel}</span>
                  </Show>
                  <p class="critical-txt">{alert()?.message ?? alert()?.text ?? labelOf(item)}</p>
                  <Show when={href()}>
                    <a class="krds-btn medium basic link" href={href()}>
                      <span class="m-hide">{alert()?.linkLabel ?? props.actionLabel}</span>{" "}
                      <i class="svg-icon ico-angle right" />
                    </a>
                  </Show>
                </div>
              </li>
            );
          }}
        </For>
      </ul>
    </div>
  );
}
