// packages/svelte/src/Disclosure.svelte
<script lang="ts">
  import { inertWhen, labelOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    title?: string;
    open?: boolean;
    description?: string;
    items?: unknown[];
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    title = '제목',
    open = $bindable<boolean | undefined>(),
    description = '',
    items = [] as unknown[],
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
</script>

<div {...rest} class={`conts-expand-area krds-disclosure ${rootClass}`} class:active={isOpen}>
  <button
    id={`${id}-trigger`}
    class="btn-conts-expand"
    type="button"
    aria-controls={`${id}-content`}
    aria-expanded={isOpen}
    onclick={() => toggleOpen()}
  >{title}</button>
  <div
    class="expand-wrap"
    id={`${id}-content`}
    role="region"
    aria-labelledby={`${id}-trigger`}
    use:inertWhen={!isOpen}
  >
    <div class="expand-in">
      {#if items.length}
        <ul class="dash krds-info-list" role="list">
          {#each items as item}<li role="listitem">{labelOf(item)}</li>{/each}
        </ul>
      {:else if children}
        {@render children()}
      {:else}
        {description}
      {/if}
    </div>
  </div>
</div>

// packages/solid/src/components/Disclosure.tsx
import { For, Show, createSignal, mergeProps, splitProps, type JSX } from "solid-js";
import type { KrdsListItem, KrdsNavItem } from "@krds-community/recipes";
import { labelOf } from "../shared.js";

export interface DisclosureProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  id?: string;
  title?: string;
  description?: string;
  items?: (KrdsListItem | KrdsNavItem | string | number)[];
  [key: string]: unknown;
}

export function Disclosure(rawProps: DisclosureProps) {
  const merged = mergeProps({ id: "disclosure" }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "id",
    "title",
    "description",
    "items",
    "open",
  ]);
  const invokeHandler = (handler: unknown, event: Event) => {
    if (typeof handler === "function") handler(event);
    else if (Array.isArray(handler) && typeof handler[0] === "function")
      handler[0](handler[1], event);
  };
  const [localOpen, setLocalOpen] = createSignal(false);
  const open = () => (props.open === undefined ? localOpen() : Boolean(props.open));
  const setOpen = (next: boolean) => {
    if (props.open === undefined) setLocalOpen(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const children = () => props.children;
  return (
    <div
      {...(native as Record<string, any>)}
      class={["krds-disclosure", "conts-expand-area", open() && "active", className()]
        .filter(Boolean)
        .join(" ")}
    >
      <button
        type="button"
        class="btn-conts-expand"
        id={`${props.id}-trigger`}
        aria-expanded={open()}
        aria-controls={`${props.id}-content`}
        onClick={(event) => {
          setOpen(!open());
          invokeHandler((native as Record<string, any>).onClick, event);
        }}
      >
        {props.title}
      </button>
      <div
        id={`${props.id}-content`}
        class="expand-wrap"
        role="region"
        aria-labelledby={`${props.id}-trigger`}
        inert={!open()}
      >
        <div class="expand-in">
          <Show when={(props.items?.length ?? 0) > 0} fallback={props.description ?? children()}>
            <ul class="krds-info-list dash" role="list">
              <For each={props.items}>{(item) => <li role="listitem">{labelOf(item)}</li>}</For>
            </ul>
          </Show>
        </div>
      </div>
    </div>
  );
}
