// packages/svelte/src/FileUpload.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { invoke } from './lib/shared.js';
  import { fieldOf, labelOf, listOf } from './lib/shared.js';

  type FileItem = Record<string, unknown>;

  type Props = {
    id?: string;
    name?: string;
    title?: string;
    description?: string;
    prompt?: string;
    inputId?: string;
    selectLabel?: string;
    accept?: string;
    multiple?: boolean;
    disabled?: boolean;
    required?: boolean;
    form?: string;
    currentCount?: number;
    maxCount?: number;
    countSuffix?: string;
    files?: FileItem[];
    label?: string;
    deleteAllLabel?: string;
    onchange?: (event: Event) => void;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    name = '',
    title = '',
    description = '',
    prompt = '',
    inputId = '',
    selectLabel = '',
    accept,
    multiple = false,
    disabled = false,
    required = false,
    form,
    currentCount,
    maxCount,
    countSuffix = '',
    label,
    files = [],
    deleteAllLabel = '',
    onchange,
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());

  let uploadValue = $state('');
  let uploadInput: HTMLInputElement | undefined = $state();

  const setUpload = (event: Event) => {
    uploadValue = Array.from((event.currentTarget as HTMLInputElement).files ?? [])
      .map((file) => file.name)
      .join(', ');
    invoke(onchange, event);
  };
</script>

<div {...rest} class={`krds-file-upload line ${rootClass}`}>
  <div class="file-head">
    <h3 class="tit">{title}</h3>
    {#if description}<div><p>{description}</p></div>{/if}
  </div>
  <div class="file-upload">
    <p class="txt">{prompt}</p>
    <div class="file-upload-btn-wrap">
      <input
        bind:this={uploadInput}
        hidden
        id={inputId || id}
        name={name}
        type="file"
        aria-label={selectLabel || title || undefined}
        {accept}
        {multiple}
        {disabled}
        {required}
        {form}
        onchange={setUpload}
      />
      <button
        type="button"
        class="krds-btn medium"
        {disabled}
        onclick={() => uploadInput?.click()}
      ><i class="svg-icon ico-upload"></i>{selectLabel}</button>
    </div>
  </div>
  <div class="file-list">
    <div class="total">
      <span class="current">{currentCount ?? files.length}{countSuffix}</span> / {maxCount ?? ''}{countSuffix}
    </div>
    <ul class="upload-list">
      {#each files as file}
        {@const fileStatus = fieldOf(file, 'status')}
        {@const fileErrors = listOf(file, 'errors')}
        <li class:is-error={fileStatus === 'error'}>
          <div class="file-info" class:m-column={fileStatus === 'downloadable'}>
            <div class="file-name">{fieldOf(file, 'name')}</div>
            <div class="btn-wrap">
              {#if fileStatus === 'uploading'}
                <span class="krds-spinner" role="status">
                  <span class="sr-only">{fieldOf(file, 'statusLabel')}</span>
                </span>
              {:else if fileStatus === 'complete'}
                <span class="ico-invalid complete">
                  <em class="sr-only">{fieldOf(file, 'statusLabel')}</em>
                </span>
              {/if}
              {#if fieldOf(file, 'deleteLabel')}
                <button class="krds-btn medium text" type="button">
                  {fieldOf(file, 'deleteLabel')} <i class="svg-icon ico-delete-fill"></i>
                </button>
              {/if}
              {#if fieldOf(file, 'downloadLabel')}
                <button class="krds-btn medium text" type="button">
                  {fieldOf(file, 'downloadLabel')} <i class="svg-icon ico-down"></i>
                </button>
              {/if}
              {#if fieldOf(file, 'previewLabel')}
                <button class="krds-btn medium text" type="button">
                  {fieldOf(file, 'previewLabel')} <i class="svg-icon ico-angle right"></i>
                </button>
              {/if}
            </div>
          </div>
          {#if fileErrors.length}
            <p class="file-hint-invalid">
              {#each fileErrors as fileError, index}
                {labelOf(fileError)}{#if index < fileErrors.length - 1}<br />{/if}
              {/each}
            </p>
          {/if}
        </li>
      {/each}
    </ul>
    {#if uploadValue}<p aria-live="polite">{uploadValue}</p>{/if}
    <div class="upload-delete-btn">
      <button class="krds-btn xsmall tertiary" type="button">
        {deleteAllLabel}<i class="svg-icon ico-angle right"></i>
      </button>
    </div>
  </div>
</div>

// packages/solid/src/components/FileUpload.tsx
import { For, Show, createSignal, mergeProps, splitProps } from "solid-js";
import type { UploadFile } from "../shared.js";

export interface FileUploadProps {
  class?: string;
  className?: string;
  title?: string;
  description?: string;
  prompt?: string;
  inputId?: string;
  name?: string;
  value?: string;
  modelValue?: string | number | boolean;
  disabled?: boolean;
  selectLabel?: string;
  label?: string;
  files?: UploadFile[];
  currentCount?: number;
  maxCount?: number;
  countSuffix?: string;
  deleteAllLabel?: string;
  defaultValue?: string;
  [key: string]: unknown;
}

export function FileUpload(rawProps: FileUploadProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "description",
    "prompt",
    "inputId",
    "name",
    "value",
    "modelValue",
    "disabled",
    "selectLabel",
    "label",
    "files",
    "currentCount",
    "maxCount",
    "countSuffix",
    "deleteAllLabel",
    "defaultValue",
  ]);
  const [, setLocalValue] = createSignal("");
  const setValue = (next: string) => {
    if (
      props.value === undefined &&
      (props.modelValue === undefined ||
        typeof props.modelValue === "boolean" ||
        Array.isArray(props.modelValue))
    )
      setLocalValue(next);
  };
  let uploadInput: HTMLInputElement | undefined;
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-file-upload line${className() ? ` ${className()}` : ""}`}
    >
      <div class="file-head">
        <h3 class="tit">{props.title}</h3>
        <div>
          <p>{props.description}</p>
        </div>
      </div>
      <div class="file-upload">
        <p class="txt">{props.prompt}</p>
        <div class="file-upload-btn-wrap">
          <input
            ref={(element) => {
              uploadInput = element;
            }}
            hidden
            id={props.inputId}
            name={props.name}
            type="file"
            aria-label={props.selectLabel ?? props.title}
            onChange={(event) => {
              setValue(
                Array.from(event.currentTarget.files ?? [])
                  .map((file) => file.name)
                  .join(", "),
              );
              (native as Record<string, any>).onChange?.(event);
            }}
          />
          <button
            type="button"
            class="krds-btn medium"
            disabled={props.disabled}
            onClick={() => uploadInput?.click()}
          >
            <i class="svg-icon ico-upload" />
            {props.selectLabel}
          </button>
        </div>
      </div>
      <div class="file-list">
        <div class="total">
          <span class="current">
            {String(props.currentCount ?? props.files?.length ?? 0) + (props.countSuffix ?? "")}
          </span>
          {" / " + String(props.maxCount ?? "") + (props.countSuffix ?? "")}
        </div>
        <ul class="upload-list">
          <For each={props.files}>
            {(file) => (
              <li classList={{ "is-error": file.status === "error" }}>
                <div class="file-info" classList={{ "m-column": file.status === "downloadable" }}>
                  <div class="file-name">{file.name}</div>
                  <div class="btn-wrap">
                    <Show when={file.status === "uploading"}>
                      <span class="krds-spinner" role="status">
                        <span class="sr-only">{file.statusLabel}</span>
                      </span>
                    </Show>
                    <Show when={file.status === "complete"}>
                      <span class="ico-invalid complete">
                        <em class="sr-only">{file.statusLabel}</em>
                      </span>
                    </Show>
                    <Show when={file.deleteLabel}>
                      <button type="button" class="krds-btn medium text">
                        {file.deleteLabel} <i class="svg-icon ico-delete-fill" />
                      </button>
                    </Show>
                    <Show when={file.downloadLabel}>
                      <button type="button" class="krds-btn medium text">
                        {file.downloadLabel} <i class="svg-icon ico-down" />
                      </button>
                    </Show>
                    <Show when={file.previewLabel}>
                      <button type="button" class="krds-btn medium text">
                        {file.previewLabel} <i class="svg-icon ico-angle right" />
                      </button>
                    </Show>
                  </div>
                </div>
                <Show when={file.errors?.length}>
                  <p class="file-hint-invalid">
                    <For each={file.errors}>
                      {(error, errorIndex) => (
                        <>
                          {error}
                          <Show when={errorIndex() < (file.errors?.length ?? 0) - 1}>
                            <br />
                          </Show>
                        </>
                      )}
                    </For>
                  </p>
                </Show>
              </li>
            )}
          </For>
        </ul>
        <div class="upload-delete-btn">
          <button type="button" class="krds-btn xsmall tertiary">
            {props.deleteAllLabel}
            <i class="svg-icon ico-angle right" />
          </button>
        </div>
      </div>
    </div>
  );
}
