// packages/react/src/components/Identifier.tsx
import { type Ref } from "react";
import { type BoxProps, cx } from "./_utils.js";

export interface IdentifierProps extends BoxProps {
  organization?: string;
  description?: string;
}
export function Identifier({
  organization = "KRDS - Korea Design System",
  description,
  className,
  children,
  ref,
  ...props
}: IdentifierProps & { ref?: Ref<HTMLDivElement> }) {
  return (
    <div {...props} ref={ref} className={cx("krds-identifier", className)}>
      <span className="logo">
        <span className="sr-only">{organization}</span>
      </span>
      <span className="ban-txt">{children ?? description ?? organization}</span>
    </div>
  );
}

// packages/solid/src/components/Identifier.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface IdentifierProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  description?: string;
  organization?: string;
  [key: string]: unknown;
}

export function Identifier(rawProps: IdentifierProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "description",
    "organization",
  ]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-identifier${className() ? ` ${className()}` : ""}`}
    >
      <span class="logo">
        <span class="sr-only">{props.organization}</span>
      </span>
      <span class="ban-txt">{props.children ?? props.description ?? props.organization}</span>
    </div>
  );
}
