// packages/react/src/components/Link.tsx
import { type AnchorHTMLAttributes, type ReactNode, type Ref } from "react";
import { SvgIcon, cx } from "./_utils.js";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  external?: boolean;
  label?: ReactNode;
}
export function Link({
  external = false,
  label,
  children,
  className,
  href = "#",
  target,
  rel,
  title,
  ref,
  ...props
}: LinkProps & { ref?: Ref<HTMLAnchorElement> }) {
  return (
    <a
      {...props}
      ref={ref}
      href={href}
      className={cx("krds-btn", "small", "link", className)}
      target={external ? "_blank" : target}
      rel={rel}
      title={external ? (title ?? "새 창 열림") : title}
    >
      <span className="underline">{children ?? label}</span>{" "}
      <SvgIcon name={external ? "ico-go" : "ico-angle right"} />
    </a>
  );
}

// packages/solid/src/components/Link.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface LinkProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  href?: string;
  target?: string;
  external?: boolean;
  size?: string;
  icon?: JSX.Element;
  title?: string;
  [key: string]: unknown;
}

export function Link(rawProps: LinkProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "href",
    "target",
    "external",
    "size",
    "icon",
    "title",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const size = () => props.size ?? "small";
  const external = () => props.external ?? props.target === "_blank";
  const content = () => props.children ?? props.label;
  return (
    <a
      {...(native as Record<string, any>)}
      href={props.href}
      target={props.target ?? (props.external ? "_blank" : undefined)}
      title={props.external ? props.title : undefined}
      class={["krds-btn", size(), "link", className()].filter(Boolean).join(" ")}
    >
      <span class="underline">{content()}</span>{" "}
      {props.icon ?? <i class={`svg-icon ${external() ? "ico-go" : "ico-angle right"}`} />}
    </a>
  );
}
