// packages/react/src/components/Modal.tsx
import {
  Fragment,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState,
  type HTMLAttributes,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
  type Ref,
} from "react";
import { cx } from "@krds-community/recipes";
import { joinAriaIds, SvgIcon } from "./_utils.js";

export interface ModalProps extends Omit<
  HTMLAttributes<HTMLElement>,
  "children" | "title" | "onKeyDown"
> {
  children?: ReactNode;
  open?: boolean;
  defaultOpen?: boolean;
  title: ReactNode;
  description?: ReactNode;
  items?: ReactNode[];
  cancelLabel?: ReactNode;
  confirmLabel?: ReactNode;
  closeLabel?: ReactNode;
  onOpenChange?: (open: boolean) => void;
  onClose?: () => void;
  onCancel?: (event: ReactKeyboardEvent<HTMLElement>) => void;
  onCancelAction?: () => void;
  onConfirm?: () => void;
  onKeyDown?: HTMLAttributes<HTMLElement>["onKeyDown"];
}
export function Modal({
  open: controlledOpen,
  defaultOpen = false,
  title,
  description,
  items,
  cancelLabel,
  confirmLabel,
  closeLabel = "닫기",
  onOpenChange,
  onClose,
  onCancel,
  onCancelAction,
  onConfirm,
  id,
  children,
  className,
  onKeyDown,
  onMouseDown,
  "aria-labelledby": ariaLabelledBy,
  ref,
  ...props
}: ModalProps & { ref?: Ref<HTMLElement> }) {
  const generatedId = useId();
  const dialogId = id ?? `krds-modal-${generatedId}`;
  const titleId = `${dialogId}-title`;
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const open = controlledOpen ?? uncontrolledOpen;
  const modalRef = useRef<HTMLElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const restoreFocusRef = useRef<HTMLElement | null>(null);
  const wasOpenRef = useRef(open);
  useImperativeHandle(ref, () => modalRef.current as HTMLElement, []);

  const focusableElements = () =>
    Array.from(
      contentRef.current?.querySelectorAll<HTMLElement>(
        '[autofocus], button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
      ) ?? [],
    );
  const setOpen = (next: boolean) => {
    if (controlledOpen === undefined) setUncontrolledOpen(next);
    onOpenChange?.(next);
  };
  const close = () => {
    setOpen(false);
    onClose?.();
  };

  useEffect(() => {
    const modal = modalRef.current;
    if (!modal) return;
    if (open && !wasOpenRef.current) {
      const activeElement = modal.ownerDocument.activeElement;
      const view = modal.ownerDocument.defaultView;
      restoreFocusRef.current =
        view && activeElement instanceof view.HTMLElement && !modal.contains(activeElement)
          ? activeElement
          : null;
      focusableElements()[0]?.focus();
    } else if (!open && wasOpenRef.current) {
      if (restoreFocusRef.current?.isConnected) restoreFocusRef.current.focus();
      restoreFocusRef.current = null;
    }
    wasOpenRef.current = open;
  }, [open]);

  useEffect(
    () => () => {
      if (restoreFocusRef.current?.isConnected) restoreFocusRef.current.focus();
    },
    [],
  );

  return (
    <section
      {...props}
      ref={modalRef}
      id={dialogId}
      className={cx("krds-modal", "fade", open && "in", open && "shown", className)}
      role="dialog"
      aria-labelledby={joinAriaIds(ariaLabelledBy, titleId)}
      onMouseDown={(event) => {
        onMouseDown?.(event);
        if (
          !event.defaultPrevented &&
          contentRef.current &&
          !contentRef.current.contains(event.target as Node)
        ) {
          focusableElements()[0]?.focus();
        }
      }}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (event.defaultPrevented) return;
        if (event.key === "Escape" || event.key === "Esc") {
          onCancel?.(event);
          if (!event.defaultPrevented) {
            event.preventDefault();
            close();
          }
          return;
        }
        if (event.key !== "Tab" || !open) return;
        const focusables = focusableElements();
        if (focusables.length === 0) return;
        const first = focusables[0];
        const last = focusables[focusables.length - 1];
        const activeElement = modalRef.current?.ownerDocument.activeElement;
        if (
          event.shiftKey &&
          (activeElement === first ||
            !activeElement ||
            !contentRef.current?.contains(activeElement))
        ) {
          event.preventDefault();
          last?.focus();
        } else if (!event.shiftKey && activeElement === last) {
          event.preventDefault();
          first?.focus();
        }
      }}
    >
      <div className="modal-dialog">
        <div className="modal-content" ref={contentRef}>
          <div className="modal-header">
            <h2 id={titleId} className="modal-title">
              {title}
            </h2>
          </div>
          <div className="modal-conts">
            <div className="conts-area">
              {items?.length
                ? items.map((item, index) => (
                    <Fragment key={index}>
                      {item}
                      {index < items.length - 1 ? <br /> : null}
                    </Fragment>
                  ))
                : (children ?? description)}
            </div>
          </div>
          <div className="modal-btn btn-wrap">
            <button
              type="button"
              className="krds-btn medium tertiary close-modal"
              onClick={() => {
                onCancelAction?.();
                close();
              }}
            >
              {cancelLabel}
            </button>
            <button
              type="button"
              className="krds-btn medium primary close-modal"
              onClick={() => {
                onConfirm?.();
                close();
              }}
            >
              {confirmLabel}
            </button>
          </div>
          <button
            type="button"
            className="krds-btn medium icon btn-close close-modal"
            onClick={close}
          >
            <span className="sr-only">{closeLabel}</span>
            <SvgIcon name="ico-popup-close" />
          </button>
        </div>
      </div>
      <div className={cx("modal-back", open && "in")} />
    </section>
  );
}
export const ModalSample = Modal;

// packages/solid/src/components/Modal.tsx
import {
  For,
  Show,
  createEffect,
  createSignal,
  createUniqueId,
  mergeProps,
  onCleanup,
  splitProps,
  type JSX,
} from "solid-js";
import { focusableSelector, trapTabFocus, labelOf } from "../shared.js";

export interface ModalProps {
  class?: string;
  className?: string;
  id?: string;
  open?: boolean;
  defaultOpen?: boolean;
  title?: JSX.Element;
  description?: JSX.Element;
  items?: JSX.Element[];
  cancelLabel?: JSX.Element;
  confirmLabel?: JSX.Element;
  closeLabel?: JSX.Element;
  children?: JSX.Element;
  onOpenChange?: (open: boolean) => void;
  onClose?: (event: Event) => void;
  onCancel?: (event: KeyboardEvent) => void;
  onCancelAction?: () => void;
  onConfirm?: () => void;
  onKeyDown?: (event: KeyboardEvent) => void;
  [key: string]: unknown;
}

export function Modal(rawProps: ModalProps) {
  const merged = mergeProps({ closeLabel: "닫기", title: "" as JSX.Element }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "open",
    "defaultOpen",
    "title",
    "description",
    "items",
    "cancelLabel",
    "confirmLabel",
    "closeLabel",
    "children",
    "onOpenChange",
    "onClose",
    "onCancel",
    "onCancelAction",
    "onConfirm",
    "onKeyDown",
  ]);

  const generatedId = createUniqueId();
  const dialogId = () => props.id ?? `krds-modal-${generatedId}`;
  const titleId = () => `tit_${dialogId()}`;

  const [localOpen, setLocalOpen] = createSignal(Boolean(props.defaultOpen));
  const open = () => (props.open === undefined ? localOpen() : Boolean(props.open));
  const setOpen = (next: boolean) => {
    if (props.open === undefined) setLocalOpen(next);
    props.onOpenChange?.(next);
  };

  let modalRoot: HTMLElement | undefined;
  let contentRef: HTMLDivElement | undefined;
  let restoreFocus: HTMLElement | undefined;
  let wasOpen = false;

  const invokeHandler = (handler: unknown, event: Event) => {
    if (typeof handler === "function") handler(event);
    else if (Array.isArray(handler) && typeof handler[0] === "function")
      handler[0](handler[1], event);
  };

  const closeModal = (event: Event) => {
    setOpen(false);
    invokeHandler(native.onClose, event);
  };

  let isInitialMount = true;
  createEffect(() => {
    const currentOpen = open();
    const modal = modalRoot;
    if (!modal) return;
    if (currentOpen && !wasOpen) {
      const activeElement = modal.ownerDocument.activeElement;
      const view = modal.ownerDocument.defaultView;
      restoreFocus =
        view && activeElement instanceof view.HTMLElement && !modal.contains(activeElement)
          ? activeElement
          : undefined;
      if (!isInitialMount) {
        contentRef?.querySelector<HTMLElement>(focusableSelector)?.focus();
      }
    } else if (!currentOpen && wasOpen) {
      if (restoreFocus?.isConnected) restoreFocus.focus();
      restoreFocus = undefined;
    }
    wasOpen = currentOpen;
    isInitialMount = false;
  });

  onCleanup(() => {
    if (restoreFocus?.isConnected) restoreFocus.focus();
  });

  const className = () => props.class ?? props.className ?? "";
  const children = () => props.children;

  return (
    <section
      {...(native as Record<string, any>)}
      ref={(element) => {
        modalRoot = element;
      }}
      id={dialogId()}
      role="dialog"
      aria-labelledby={titleId()}
      class={["krds-modal", "fade", open() && "in", open() && "shown", className()]
        .filter(Boolean)
        .join(" ")}
      onClick={(event) => {
        invokeHandler(native.onClick, event);
        if (
          !event.defaultPrevented &&
          open() &&
          !(event.target as Element).closest(".modal-content")
        ) {
          event.currentTarget.querySelector<HTMLElement>(focusableSelector)?.focus();
        }
      }}
      onKeyDown={(event) => {
        invokeHandler(native.onKeyDown, event);
        if (event.defaultPrevented) return;
        if (event.key === "Escape" || event.key === "Esc") {
          props.onCancel?.(event as KeyboardEvent);
          if (!event.defaultPrevented) {
            event.preventDefault();
            closeModal(event);
          }
          return;
        }
        const content = event.currentTarget.querySelector<HTMLElement>(".modal-content");
        if (content && open()) trapTabFocus(event, content);
      }}
    >
      <div class="modal-dialog">
        <div
          class="modal-content"
          ref={(element) => {
            contentRef = element;
          }}
        >
          <div class="modal-header">
            <h2 id={titleId()} class="modal-title">
              {props.title}
            </h2>
          </div>
          <div class="modal-conts">
            <div class="conts-area">
              <Show when={props.items?.length} fallback={props.description ?? children()}>
                <For each={props.items}>
                  {(item, itemIndex) => (
                    <>
                      {labelOf(item)}
                      <Show when={itemIndex() < (props.items?.length ?? 0) - 1}>
                        <br />
                      </Show>
                    </>
                  )}
                </For>
              </Show>
            </div>
          </div>
          <div class="modal-btn btn-wrap">
            <button
              type="button"
              class="krds-btn medium tertiary close-modal"
              onClick={(event) => {
                props.onCancelAction?.();
                closeModal(event);
              }}
            >
              {props.cancelLabel}
            </button>
            <button
              type="button"
              class="krds-btn medium primary close-modal"
              onClick={(event) => {
                props.onConfirm?.();
                closeModal(event);
              }}
            >
              {props.confirmLabel}
            </button>
          </div>
          <button
            type="button"
            class="krds-btn medium icon btn-close close-modal"
            onClick={closeModal}
          >
            <span class="sr-only">{props.closeLabel}</span>
            <i class="svg-icon ico-popup-close" />
          </button>
        </div>
      </div>
      <div class="modal-back" classList={{ in: open() }} />
    </section>
  );
}

export const ModalSample = Modal;
