// packages/svelte/src/Pagination.svelte
<script lang="ts">
  import { invoke, labelOf } from './lib/shared.js';
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    current?: number;
    items?: unknown[];
    previousLabel?: string;
    nextLabel?: string;
    navigationLabel?: string;
    message?: string;
    modelValue?: string | number;
    href?: string;
    title?: string;
    label?: string;
    previousDisabled?: boolean;
    nextDisabled?: boolean;
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    current = $bindable<number | undefined>(),
    items = [1, 2, 3, 4, 5] as unknown[],
    previousLabel = '이전',
    nextLabel = '다음',
    navigationLabel = '페이지 이동',
    message = '현재페이지',
    title,
    label,
    modelValue = $bindable<string | number | undefined>(),
    href = '#',
    previousDisabled = false,
    nextDisabled: nextDisabledProp,
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const currentIndex = $derived(Number(current) || 1);
  const maxPage = $derived(
    Math.max(...items.map((item) => Number(labelOf(item))).filter(Number.isFinite), 1),
  );
  const nextDisabled = $derived(nextDisabledProp ?? currentIndex >= maxPage);
  const selectPage = (page: number, event: Event) => {
    current = page;
    modelValue = page;
    invoke(onclick, event);
  };

  </script>

  <div
    {...rest}
    class={`krds-pagination ${rootClass}`}
    role="navigation"
    aria-label={navigationLabel}
  >
    {#if previousDisabled || currentIndex <= 1}
      <span class="page-navi prev disabled" href={href ?? '#'}>{previousLabel}</span>
    {:else}
      <a
        href={href}
        class="page-navi prev"
        onclick={(event) => {
          event.preventDefault();
          selectPage(currentIndex - 1, event);
        }}
      >{previousLabel}</a>
    {/if}
    <div class="page-links">
      {#each items as item}
        {#if labelOf(item) === 'ellipsis'}
          <span class="page-link link-dot"></span>
        {:else}
          {@const page = Number(labelOf(item))}
          <a
            href={href}
            class="page-link"
            class:active={page === currentIndex}
            onclick={(event) => {
              event.preventDefault();
              selectPage(page, event);
            }}
          >
            {#if page === currentIndex}<span class="sr-only">{message} </span>{/if}
            {page}
          </a>
        {/if}
      {/each}
    </div>
    {#if nextDisabled}
      <span class="page-navi next disabled" href={href ?? '#'}>{nextLabel}</span>
    {:else}
      <a
        href={href}
        class="page-navi next"
        onclick={(event) => {
          event.preventDefault();
          selectPage(currentIndex + 1, event);
        }}
      >{nextLabel}</a>
    {/if}
  </div>

// packages/solid/src/components/Pagination.tsx
import { For, Show, createSignal, mergeProps, splitProps } from "solid-js";

export interface PaginationProps {
  class?: string;
  className?: string;
  title?: string;
  label?: string;
  message?: string;
  navigationLabel?: string;
  previousDisabled?: boolean;
  nextDisabled?: boolean;
  previousLabel?: string;
  nextLabel?: string;
  items?: (number | "ellipsis" | string)[];
  current?: number;
  modelValue?: number;
  value?: string;
  selected?: string;
  defaultValue?: string;
  [key: string]: unknown;
}

export function Pagination(rawProps: PaginationProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "label",
    "message",
    "navigationLabel",
    "previousDisabled",
    "nextDisabled",
    "previousLabel",
    "nextLabel",
    "items",
    "current",
    "modelValue",
    "value",
    "selected",
    "defaultValue",
  ]);
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "number") return String(mv);
    if (typeof mv === "string") return mv;
    return props.selected ?? localSelected() ?? props.defaultValue ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const paginationPage = () => {
    const page = Number(props.modelValue ?? props.current ?? selected());
    return Number.isFinite(page) && page > 0 ? page : 1;
  };
  const className = () => props.class ?? props.className ?? "";
  const maxPage = () =>
    Math.max(...(props.items ?? [1, 2, 3, 4, 5]).map((item) => Number(item)).filter(Number.isFinite), 1);
  const nextDisabled = () => props.nextDisabled ?? paginationPage() >= maxPage();
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-pagination${className() ? ` ${className()}` : ""}`}
      role="navigation"
      aria-label={props.navigationLabel || "페이지 이동"}
    >
      <Show
        when={!props.previousDisabled && paginationPage() > 1}
        fallback={
          <span {...({ href: "#" } as Record<string, string>)} class="page-navi prev disabled">
            {props.previousLabel ?? "이전"}
          </span>
        }
      >
        <a
          class="page-navi prev"
          href="#"
          onClick={() => setSelected(String(Math.max(1, paginationPage() - 1)))}
        >
          {props.previousLabel ?? "이전"}
        </a>
      </Show>
      <div class="page-links">
        <For each={props.items ?? [1, 2, 3, 4, 5]}>
          {(item) =>
            typeof item === "number" ? (
              <a
                href="#"
                class="page-link"
                classList={{ active: item === paginationPage() }}
                onClick={() => setSelected(String(item))}
              >
                <Show when={item === paginationPage()}>
                  <span class="sr-only">{props.message ?? "현재페이지"} </span>
                </Show>
                {item}
              </a>
            ) : (
              <span class="page-link link-dot" />
            )
          }
        </For>
      </div>
      <Show
        when={!nextDisabled()}
        fallback={
          <span {...({ href: "#" } as Record<string, string>)} class="page-navi next disabled">
            {props.nextLabel ?? "다음"}
          </span>
        }
      >
        <a class="page-navi next" href="#" onClick={() => setSelected(String(paginationPage() + 1))}>
          {props.nextLabel ?? "다음"}
        </a>
      </Show>
    </div>
  );
}
