// packages/svelte/src/SideNavigation.svelte
<script lang="ts">
  import type { KrdsNavItem } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { labelOf, hrefOf, childrenOf, fieldOf, flagOf } from './lib/shared.js';

  type Props = {
    id?: string;
    title?: string;
    items?: KrdsNavItem[];
    links?: KrdsNavItem[];
    nav?: KrdsNavItem[];
    children?: Snippet;
    class?: string;
    className?: string;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-side-navigation',
    title = '',
    items = [],
    links = [],
    nav = [],
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const navigationItems = $derived(items.length ? items : links.length ? links : nav);
</script>

<nav {...rest} class={`krds-side-navigation ${rootClass}`}>
  <h2 class="lnb-tit">{title}</h2>
  <ul class="lnb-list" role="menubar">
    {#each navigationItems as item, index}
      <li class:active={index === 0} class="lnb-item" role="none">
        {#if childrenOf(item).length}
          <button
            class="lnb-btn lnb-toggle"
            class:active={index === 0}
            type="button"
            role="menuitem"
            aria-expanded={index === 0}
            aria-controls={`${id}-side-${index}`}
          >{labelOf(item)}</button>
          <div class="lnb-submenu">
            <ul id={`${id}-side-${index}`} role="menu">
              {#each childrenOf(item) as child, childIndex}
                <li class="lnb-subitem" class:active={flagOf(child, 'current')} role="none">
                  {#if childrenOf(child).length}
                    <button
                      class="lnb-btn lnb-toggle-popup"
                      type="button"
                      role="menuitem"
                      aria-haspopup="true"
                      aria-expanded="false"
                      aria-controls={`${id}-side-${index}-${childIndex}`}
                    >{labelOf(child)}</button>
                    <div class="lnb-submenu-lv2" id={`${id}-side-${index}-${childIndex}`} role="menu">
                      <button class="lnb-btn-tit" type="button">{fieldOf(child, 'description')}</button>
                      <ul>
                        {#each childrenOf(child) as leaf}
                          <li role="none">
                            <a class="lnb-btn" href={hrefOf(leaf)} role="menuitem">{labelOf(leaf)}</a>
                          </li>
                        {/each}
                      </ul>
                    </div>
                  {:else}
                    <a
                      class="lnb-btn lnb-link"
                      href={hrefOf(child)}
                      role="menuitem"
                      aria-current={flagOf(child, 'current') ? 'page' : undefined}
                    >{labelOf(child)}</a>
                  {/if}
                </li>
              {/each}
            </ul>
          </div>
        {:else}
          <a class="lnb-btn lnb-link" href={hrefOf(item)} role="menuitem">{labelOf(item)}</a>
        {/if}
      </li>
    {/each}
  </ul>
</nav>

// packages/solid/src/components/SideNavigation.tsx
import { For, createSignal, mergeProps, splitProps } from "solid-js";
import type { KrdsNavItem } from "@krds-community/recipes";
import type { MenuItem } from "../shared.js";

export interface SideNavigationItem extends KrdsNavItem {
  children?: SideNavigationItem[];
  description?: string;
  current?: boolean;
}

export interface SideNavigationProps {
  class?: string;
  className?: string;
  title?: string;
  id?: string;
  nav?: KrdsNavItem[];
  links?: KrdsNavItem[];
  items?: (KrdsNavItem | string | number)[];
  selected?: string;
  defaultValue?: string;
  modelValue?: string;
  value?: string;
  [key: string]: unknown;
}

export function SideNavigation(rawProps: SideNavigationProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "id",
    "nav",
    "links",
    "items",
    "selected",
    "defaultValue",
    "modelValue",
    "value",
  ]);
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "string" || typeof mv === "number") return String(mv);
    return props.selected ?? localSelected() ?? props.defaultValue ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const hasCurrentItem = (item: KrdsNavItem): boolean => {
    if (item.current) return true;
    return item.children?.some(hasCurrentItem) ?? false;
  };
  const navigation = () =>
    (props.nav?.length
      ? props.nav
      : props.links?.length
        ? props.links
        : (props.items ?? []).filter(
            (item): item is KrdsNavItem => typeof item !== "string" && typeof item !== "number",
          )) as KrdsNavItem[];
  return (
    <nav
      {...(native as Record<string, any>)}
      class={`krds-side-navigation${className() ? ` ${className()}` : ""}`}
    >
      <h2 class="lnb-tit">{props.title}</h2>
      <ul class="lnb-list" role="menubar">
        <For each={navigation()}>
          {(item, topIndex) => {
            const submenuId = `${props.id}-submenu-${topIndex()}`;
            const expanded = () =>
              selected() === item.id || (selected() === "" && hasCurrentItem(item));
            return (
              <li class="lnb-item" classList={{ active: expanded() }} role="none">
                <button
                  type="button"
                  class="lnb-btn lnb-toggle"
                  classList={{ active: expanded() }}
                  role="menuitem"
                  aria-controls={submenuId}
                  aria-expanded={expanded()}
                  onClick={() => setSelected(expanded() ? "" : (item.id ?? submenuId))}
                >
                  {item.label}
                </button>
                <div class="lnb-submenu">
                  <ul id={submenuId} role="menu">
                    <For each={(item as MenuItem).children}>
                      {(child, childIndex) => {
                        const popupId = `${submenuId}-${childIndex()}`;
                        return (child as MenuItem).children?.length ? (
                          <li class="lnb-subitem" role="none">
                            <button
                              type="button"
                              class="lnb-btn lnb-toggle-popup"
                              role="menuitem"
                              aria-controls={popupId}
                              aria-expanded="false"
                              aria-haspopup="true"
                            >
                              {child.label}
                            </button>
                            <div class="lnb-submenu-lv2" id={popupId} role="menu">
                              <button type="button" class="lnb-btn-tit">
                                {"description" in child && typeof child.description === "string"
                                  ? child.description
                                  : undefined}
                              </button>
                              <ul>
                                <For each={(child as MenuItem).children}>
                                  {(leaf) => (
                                    <li role="none">
                                      <a href={leaf.href ?? "#"} class="lnb-btn" role="menuitem">
                                        {leaf.label}
                                      </a>
                                    </li>
                                  )}
                                </For>
                              </ul>
                            </div>
                          </li>
                        ) : (
                          <li class="lnb-subitem" classList={{ active: child.current }} role="none">
                            <a
                              href={child.href ?? "#"}
                              class="lnb-btn lnb-link"
                              role="menuitem"
                              aria-current={child.current ? "page" : undefined}
                            >
                              {child.label}
                            </a>
                          </li>
                        );
                      }}
                    </For>
                  </ul>
                </div>
              </li>
            );
          }}
        </For>
      </ul>
    </nav>
  );
}
