// packages/react/src/components/SkipLink.tsx
import { type AnchorHTMLAttributes, type ReactNode, type Ref } from "react";

export function SkipLink({
  href = "#main",
  label: _label,
  children = "본문 바로가기",
  className,
  id,
  ref,
  ...props
}: AnchorHTMLAttributes<HTMLAnchorElement> & { label?: ReactNode } & {
  ref?: Ref<HTMLAnchorElement>;
}) {
  return (
    <div id={id ?? "krds-skip-link"} className={className}>
      <a {...props} ref={ref} href={href}>
        {children}
      </a>
    </div>
  );
}

// packages/solid/src/components/SkipLink.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface SkipLinkProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  href?: string;
  id?: string;
  [key: string]: unknown;
}

export function SkipLink(rawProps: SkipLinkProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "href",
    "id",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label;
  return (
    <div id={props.id ?? "krds-skip-link"} class={className() || undefined}>
      <a {...(native as Record<string, any>)} href={props.href}>
        {content()}
      </a>
    </div>
  );
}
