// packages/react/src/components/StepIndicator.tsx
import type { ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsStep } from "@krds-community/recipes";

export function StepIndicator({
  steps,
  current = 0,
  label = "단계",
  message = "현재단계",
  className,
}: {
  steps: KrdsStep[];
  current?: number;
  label?: ReactNode;
  message?: ReactNode;
  className?: string;
}) {
  const currentIndex = current;
  return (
    <ol className={cx("krds-step-wrap", className)}>
      {steps.map((step, index) => (
        <li
          className={
            cx(index < currentIndex && "done", index === currentIndex && "active") || undefined
          }
          key={step.id}
        >
          <span>
            {index === currentIndex ? <em className="sr-only">{message}</em> : null}
            <i className="step">
              {typeof label === "string" || typeof label === "number" ? (
                `${index + 1}${label}`
              ) : (
                <>
                  {index + 1}
                  {label}
                </>
              )}
            </i>
            <span className="step-tit">{step.label}</span>
          </span>
        </li>
      ))}
    </ol>
  );
}

// packages/solid/src/components/StepIndicator.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import type { KrdsStep } from "@krds-community/recipes";

export interface StepIndicatorProps {
  class?: string;
  className?: string;
  steps?: KrdsStep[];
  current?: number;
  modelValue?: number;
  label?: string;
  message?: string;
  [key: string]: unknown;
}

export function StepIndicator(rawProps: StepIndicatorProps) {
  const merged = mergeProps({ label: "단계", message: "현재단계" }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "steps",
    "current",
    "modelValue",
    "label",
    "message",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const stepCurrent = () => Number(props.current ?? props.modelValue ?? 0);
  return (
    <ol
      {...(native as Record<string, any>)}
      class={`krds-step-wrap${className() ? ` ${className()}` : ""}`}
    >
      <For each={props.steps ?? []}>
        {(step, stepIndex) => (
          <li
            classList={{ done: stepIndex() < stepCurrent(), active: stepIndex() === stepCurrent() }}
          >
            <span>
              <Show when={stepIndex() === stepCurrent()}>
                <em class="sr-only">{props.message}</em>
              </Show>
              <i class="step">{`${stepIndex() + 1}${props.label ?? "단계"}`}</i>
              <span class="step-tit">{step.label}</span>
            </span>
          </li>
        )}
      </For>
    </ol>
  );
}
