// packages/svelte/src/StructuredListTable.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf, labelOf, flagOf, listOf } from './lib/shared.js';

  const pageMax = (value: Record<string, unknown>) =>
    Math.max(
      1,
      ...listOf(value, 'items')
        .map((item) => Number(labelOf(item)))
        .filter((item) => Number.isFinite(item)),
    );
  type StructuredListTableRow = {
    selectionLabel?: string;
    [key: string]: string | number | boolean | null | undefined;
  };

  type Props = {
    id?: string;
    columns?: Record<string, unknown>[];
    rows?: StructuredListTableRow[];
    caption?: string;
    title?: string;
    selectAllLabel?: string;
    actions?: Record<string, unknown>[];
    countLabel?: string;
    countOptions?: string[];
    sortLabel?: string;
    sortOptions?: string[];
    sortValue?: string;
    pagination?: Record<string, unknown>;
    href?: string;
    children?: Snippet;
    className?: string;
    class?: string;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    columns = [],
    rows = [],
    caption = '',
    title = '제목',
    selectAllLabel = '',
    actions = [],
    countLabel = '',
    countOptions = [],
    sortLabel = '',
    sortOptions = [],
    sortValue = '',
    pagination,
    href = '#',
    children,
    className = '',
    class: classProp = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim() || "sample");
</script>

<div class={`krds-structured-list-table ${rootClass}`}>
  <div class="search-list-top">
    <div class="sch-left">
      <div class="krds-check-area">
        <div class="krds-form-check">
          <input class="chk" id={`${id}-all`} type="checkbox" />
          <label for={`${id}-all`}>{selectAllLabel}</label>
        </div>
      </div>
      <ul class="side-line-ul">
        {#each actions as action}
          <li>
            <button class="krds-btn medium text" type="button">
              <i class={`svg-icon ico-${fieldOf(action, 'icon')}`}></i>{' '}{fieldOf(action, 'label')}
            </button>
          </li>
        {/each}
      </ul>
    </div>
    <ul class="sch-sort">
      <li>
        <strong class="sort-label"><label for={`${id}-result-count`}>{countLabel}</label></strong>
        {' '}
        <select class="krds-form-select-sort" id={`${id}-result-count`}>
          {#each countOptions as option}<option>{option}</option>{/each}
        </select>
</li>
      <li>
        <strong class="sort-label"><label for={`${id}-sort`}>{sortLabel}</label></strong>
        <div class="w-sort-btn">
          {#each sortOptions as option}
            <button class:active={option === sortValue} type="button">{option}</button>
            {' '}
          {/each}
        </div>
        <div class="m-sort-btn">
          <select class="krds-form-select-sort" id={`${id}-sort`} value={sortValue}>
            {#each sortOptions as option}<option>{option}</option>{/each}
          </select>
        </div>
      </li>
    </ul>
  </div>
  <div class="krds-table-wrap">
    <table class="tbl col data">
      <caption>{caption || title}</caption>
      <colgroup>
        {#each columns as column}
          <col style={fieldOf(column, 'width') ? `width: ${fieldOf(column, 'width')};` : undefined} />
        {/each}
        <col />
      </colgroup>
      <thead>
        <tr>
          {#each columns as column}
            <th scope="col">
              {#if column.key === 'download'}<span class="sr-only">{column.label}</span>{:else}{column.label}{/if}
            </th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each rows as row, rowIndex}
          <tr>
            {#each columns as column, columnIndex}
              {#if column.key === 'selected'}
                <th scope="row">
                  <div class="krds-form-check">
                    <input
                      class="chk"
                      id={`${id}-row-${rowIndex + 1}`}
                      type="checkbox"
                      aria-label={fieldOf(row, 'selectionLabel') || undefined}
                      checked={flagOf(row, 'selected')}
                    />
                    <label for={`${id}-row-${rowIndex + 1}`}></label>
                  </div>
                </th>
              {:else if column.key === 'download'}
                <td>
                  <button class="krds-btn medium text" type="button">
                    <i class="svg-icon ico-down"></i>{' '}{row[column.key]}
                  </button>
                </td>
              {:else if columnIndex === 0}
                <th scope="row">{row[column.key]}</th>
              {:else}
                <td>{row[column.key]}</td>
              {/if}
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  {#if pagination}
    <div class="krds-pagination">
      {#if flagOf(pagination, 'previousDisabled')}
        <span class="page-navi prev disabled">{fieldOf(pagination, 'previousLabel')}</span>
      {:else}
        <a class="page-navi prev" href={href}>{fieldOf(pagination, 'previousLabel')}</a>
      {/if}
      <div class="page-links">
        {#each listOf(pagination, 'items') as item}
          {#if labelOf(item) === 'ellipsis'}
            <span class="page-link link-dot"></span>
          {:else}
            {@const page = Number(labelOf(item))}
            <a class:active={page === Number(fieldOf(pagination, 'current'))} class="page-link" href={href}>
              {#if page === Number(fieldOf(pagination, 'current'))}<span class="sr-only">{fieldOf(pagination, 'currentLabel')} </span>{/if}
              {page}
            </a>
          {/if}
        {/each}
      </div>
      {#if Number(fieldOf(pagination, 'current')) >= pageMax(pagination)}
        <span class="page-navi next disabled">{fieldOf(pagination, 'nextLabel')}</span>
      {:else}
        <a class="page-navi next" href={href}>{fieldOf(pagination, 'nextLabel')}</a>
      {/if}
    </div>
  {/if}
</div>

// packages/solid/src/components/StructuredListTable.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import type { TableColumn, TableRow, TablePagination, CalendarAction } from "../shared.js";

export interface StructuredListTableProps {
  class?: string;
  className?: string;
  id?: string;
  columns?: TableColumn[];
  rows?: TableRow[];
  pagination?: TablePagination;
  caption?: string;
  selectAllLabel?: string;
  countLabel?: string;
  countOptions?: string[];
  sortLabel?: string;
  sortOptions?: string[];
  sortValue?: string;
  actions?: CalendarAction[];
  [key: string]: unknown;
}

export function StructuredListTable(rawProps: StructuredListTableProps) {
  const merged = mergeProps({ columns: [] as TableColumn[], rows: [] as TableRow[] }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "id",
    "columns",
    "rows",
    "pagination",
    "caption",
    "selectAllLabel",
    "countLabel",
    "countOptions",
    "sortLabel",
    "sortOptions",
    "sortValue",
    "actions",
  ]);
  const className = () => props.class ?? props.className ?? "sample";
  const pageMax = () =>
    Math.max(
      1,
      ...(props.pagination?.items ?? []).filter((item): item is number => item !== "ellipsis"),
    );
  return (
    <div
      {...(native as Record<string, any>)}
      class={["krds-structured-list-table", className()].filter(Boolean).join(" ")}
    >
      <div class="search-list-top">
        <div class="sch-left">
          <div class="krds-check-area">
            <div class="krds-form-check">
              <input type="checkbox" class="chk" id={`${props.id}-all`} />
              <label for={`${props.id}-all`}>{props.selectAllLabel}</label>
            </div>
          </div>
          <ul class="side-line-ul">
            <For each={props.actions ?? []}>
              {(action) => (
                <li>
                  <button type="button" class="krds-btn medium text">
                    <i class={`svg-icon ico-${action.icon}`} />
                    {" " + action.label}
                  </button>
                </li>
              )}
            </For>
          </ul>
        </div>
        <ul class="sch-sort">
          <li>
            <strong class="sort-label">
              <label for={`${props.id}-count`}>{props.countLabel}</label>
            </strong>{" "}
            <select
              class="krds-form-select-sort"
              id={`${props.id}-count`}
              value={props.countOptions?.[0]}
            >
              <For each={props.countOptions ?? []}>{(option) => <option>{option}</option>}</For>
            </select>
          </li>
          <li>
            <strong class="sort-label">
              <label for={`${props.id}-sort`}>{props.sortLabel}</label>
            </strong>{" "}
            <div class="w-sort-btn">
              <For each={props.sortOptions ?? []}>
                {(option) => (
                  <>
                    <button type="button" classList={{ active: props.sortValue === option }}>
                      {option}
                    </button>{" "}
                  </>
                )}
              </For>
            </div>
            <div class="m-sort-btn">
              <select
                class="krds-form-select-sort"
                id={`${props.id}-sort`}
                value={props.sortValue}
              >
                <For each={props.sortOptions ?? []}>{(option) => <option>{option}</option>}</For>
              </select>
            </div>
          </li>
        </ul>
      </div>
      <div class="krds-table-wrap">
        <table class="tbl col data">
          <caption>{props.caption}</caption>
          <colgroup>
            <For each={props.columns}>
              {(column) => (
                <col
                  style={
                    "width" in column && typeof column.width === "string" && column.width
                      ? { width: column.width }
                      : undefined
                  }
                />
              )}
            </For>
            <col />
          </colgroup>
          <thead>
            <tr>
              <For each={props.columns}>
                {(column) => (
                  <th scope="col">
                    <Show
                      when={"visuallyHidden" in column && column.visuallyHidden === true}
                      fallback={column.label}
                    >
                      <span class="sr-only">{column.label}</span>
                    </Show>
                  </th>
                )}
              </For>
            </tr>
          </thead>
          <tbody>
            <For each={props.rows}>
              {(row) => (
                <tr>
                  <For each={props.columns}>
                    {(column, columnIndex) =>
                      column.key === "selected" ? (
                        <th scope="row">
                          <div class="krds-form-check">
                            <input
                              type="checkbox"
                              class="chk"
                              id={`${props.id}-row-${String(row.id)}`}
                              aria-label={row.selectionLabel}
                              checked={Boolean(row.selected)}
                            />
                            <label for={`${props.id}-row-${String(row.id)}`} />
                          </div>
                        </th>
                      ) : column.key === "download" ? (
                        <td>
                          <button type="button" class="krds-btn medium text">
                            <i class="svg-icon ico-down" />
                            {" " + String(row[column.key] ?? "")}
                          </button>
                        </td>
                      ) : columnIndex() === 0 ? (
                        <th scope="row">{String(row[column.key] ?? "")}</th>
                      ) : (
                        <td>{String(row[column.key] ?? "")}</td>
                      )
                    }
                  </For>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </div>
      <div class="krds-pagination">
        <Show
          when={!props.pagination?.previousDisabled}
          fallback={
            <span {...({ href: "#" } as Record<string, string>)} class="page-navi prev disabled">
              {props.pagination?.previousLabel}
            </span>
          }
        >
          <a class="page-navi prev" href="#">
            {props.pagination?.previousLabel}
          </a>
        </Show>
        <div class="page-links">
          <For each={props.pagination?.items}>
            {(item) =>
              item === "ellipsis" ? (
                <span class="page-link link-dot" />
              ) : (
                <a
                  class="page-link"
                  classList={{ active: props.pagination?.current === item }}
                  href="#"
                >
                  <Show when={props.pagination?.current === item}>
                    <span class="sr-only">{props.pagination?.currentLabel} </span>
                  </Show>
                  {item}
                </a>
              )
            }
          </For>
        </div>
        <Show
          when={(props.pagination?.current ?? 0) < pageMax()}
          fallback={
            <span {...({ href: "#" } as Record<string, string>)} class="page-navi next disabled">
              {props.pagination?.nextLabel}
            </span>
          }
        >
          <a class="page-navi next" href="#">
            {props.pagination?.nextLabel}
          </a>
        </Show>
      </div>
    </div>
  );
}
