// packages/react/src/components/StructuredList.tsx
import { type HTMLAttributes, type ReactNode, type Ref } from "react";
import { SvgIcon, cx } from "./_utils.js";
import type { KrdsListItem } from "@krds-community/recipes";

export interface StructuredListItem extends Omit<KrdsListItem, "title" | "description"> {
  title: ReactNode;
  description?: ReactNode;
  badgeClass?: string;
}

export interface StructuredListProps extends Omit<HTMLAttributes<HTMLUListElement>, "children"> {
  items?: StructuredListItem[];
  dateLabel?: ReactNode;
  dateValue?: ReactNode;
  tags?: ReactNode[];
  actionLabel?: ReactNode;
  shareLabel?: ReactNode;
  favoriteLabel?: ReactNode;
  onShare?: (item: StructuredListItem) => void;
  onFavorite?: (item: StructuredListItem) => void;
}
export function StructuredList({
  items = [],
  dateLabel,
  dateValue,
  tags = [],
  actionLabel,
  shareLabel,
  favoriteLabel,
  onShare,
  onFavorite,
  className,
  ref,
  ...props
}: StructuredListProps & { ref?: Ref<HTMLUListElement> }) {
  return (
    <ul {...props} ref={ref} className={cx("krds-structured-list", "type-full", className)}>
      {items.map((item) => (
        <li className="structured-item" key={item.id}>
          <div className="in">
            <div className="card-top">
              {item.badge ? (
                <span className={cx("krds-badge", item.badgeClass)}>{item.badge}</span>
              ) : null}
            </div>
            <div className="card-body">
              <a href={item.href ?? "#"} className="c-text">
                <p className="c-tit">
                  <span className="span">{item.title}</span>
                </p>
                {item.description ? <p className="c-txt">{item.description}</p> : null}
                <p className="c-date">
                  <strong className="key">{dateLabel}</strong>
                  <span className="value">{dateValue}</span>
                </p>
              </a>
              <div className="c-btn">
                <a
                  href={item.href ?? "#"}
                  className="krds-btn secondary"
                  title={typeof item.title === "string" ? item.title : undefined}
                >
                  {actionLabel}
                </a>
              </div>
            </div>
            <div className="card-btm">
              {tags.map((tag, index) => (
                <span className="tag" key={index}>
                  {tag}
                </span>
              ))}
            </div>
            <div className="card-btn">
              <button
                type="button"
                className="krds-btn medium text"
                title={typeof item.title === "string" ? item.title : undefined}
                onClick={() => onShare?.(item)}
              >
                <SvgIcon name="ico-share" />
                {shareLabel ? " " + shareLabel : null}
              </button>
              <button
                type="button"
                className="krds-btn medium text"
                title={typeof item.title === "string" ? item.title : undefined}
                onClick={() => onFavorite?.(item)}
              >
                <SvgIcon name="ico-like" />
                {favoriteLabel ? " " + favoriteLabel : null}
              </button>
            </div>
          </div>
        </li>
      ))}
    </ul>
  );
}

// packages/solid/src/components/StructuredList.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import { labelOf, type StructuredItem } from "../shared.js";

export interface StructuredListProps {
  class?: string;
  className?: string;
  items?: (StructuredItem | string | number)[];
  dateLabel?: string;
  dateValue?: string;
  actionLabel?: string;
  shareLabel?: string;
  favoriteLabel?: string;
  tags?: string[];
  [key: string]: unknown;
}

export function StructuredList(rawProps: StructuredListProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "items",
    "dateLabel",
    "dateValue",
    "actionLabel",
    "shareLabel",
    "favoriteLabel",
    "tags",
  ]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <ul
      {...(native as Record<string, any>)}
      class={["krds-structured-list", "type-full", className()].filter(Boolean).join(" ")}
    >
      <For each={props.items ?? []}>
        {(item) => {
          const structured =
            typeof item === "string" || typeof item === "number"
              ? undefined
              : (item as StructuredItem);
          return (
            <li class="structured-item">
              <div class="in">
                <Show when={structured?.badge}>
                  <div class="card-top">
                    <span class={["krds-badge", structured?.badgeClass].filter(Boolean).join(" ")}>
                      {structured?.badge}
                    </span>
                  </div>
                </Show>
                <div class="card-body">
                  <a class="c-text" href={structured?.href ?? "#"}>
                    <p class="c-tit">
                      <span class="span">{labelOf(item)}</span>
                    </p>
                    <Show when={structured?.description}>
                      <p class="c-txt">{structured?.description}</p>
                    </Show>
                    <p class="c-date">
                      <strong class="key">{structured?.dateLabel ?? props.dateLabel}</strong>
                      <span class="value">{structured?.dateValue ?? props.dateValue}</span>
                    </p>
                  </a>
                  <div class="c-btn">
                    <a
                      class="krds-btn secondary"
                      href={structured?.href ?? "#"}
                      title={labelOf(item)}
                    >
                      {structured?.actionLabel ?? props.actionLabel}
                    </a>
                  </div>
                </div>
                <div class="card-btm">
                  <For each={structured?.tags ?? props.tags ?? []}>
                    {(tag) => <span class="tag">{tag}</span>}
                  </For>
                </div>
                <div class="card-btn">
                  <button type="button" class="krds-btn medium text" title={labelOf(item)}>
                    <i class="svg-icon ico-share" />
                    {(structured?.shareLabel ?? props.shareLabel) ? " " + (structured?.shareLabel ?? props.shareLabel) : null}
                  </button>
                  <button type="button" class="krds-btn medium text" title={labelOf(item)}>
                    <i class="svg-icon ico-like" />
                    {(structured?.favoriteLabel ?? props.favoriteLabel) ? " " + (structured?.favoriteLabel ?? props.favoriteLabel) : null}
                  </button>
                </div>
              </div>
            </li>
          );
        }}
      </For>
    </ul>
  );
}
