// packages/svelte/src/TabBar.svelte
<script lang="ts">
  import Badge from './Badge.svelte';

  type Item = { id: string; label: string; href?: string; icon?: string; badge?: string };

  type Props = {
    items?: Item[];
    selected?: string;
    defaultSelected?: string;
    onchange?: (id: string) => void;
    ariaLabel?: string;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    items = [],
    selected = $bindable<string | undefined>(),
    defaultSelected,
    onchange,
    ariaLabel = '주요 메뉴',
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  let internal = $state<string | undefined>(defaultSelected);
  const current = $derived(selected !== undefined ? selected : internal);

  const select = (id: string) => {
    if (selected === undefined) internal = id;
    onchange?.(id);
  };
</script>

<nav {...rest} class={`krds-tab-bar ${rootClass}`} aria-label={ariaLabel}>
  {#each items as item}
    {#if item.href}
      <a
        href={item.href}
        class="tab-bar-item"
        class:active={current === item.id}
        aria-current={current === item.id ? 'page' : undefined}
        onclick={(event) => {
          event.preventDefault();
          select(item.id);
        }}
      >
        {#if item.icon}
          <i class={`svg-icon tab-bar-icon ${item.icon}`} aria-hidden="true"></i>
        {/if}
        <span class="tab-bar-label">{item.label}</span>
        {#if item.badge}
          <Badge label={item.badge} className="tab-bar-badge" />
        {/if}
      </a>
    {:else}
      <button
        type="button"
        class="tab-bar-item"
        class:active={current === item.id}
        aria-current={current === item.id ? 'page' : undefined}
        onclick={() => select(item.id)}
      >
        {#if item.icon}
          <i class={`svg-icon tab-bar-icon ${item.icon}`} aria-hidden="true"></i>
        {/if}
        <span class="tab-bar-label">{item.label}</span>
        {#if item.badge}
          <Badge label={item.badge} className="tab-bar-badge" />
        {/if}
      </button>
    {/if}
  {/each}
</nav>

// packages/solid/src/components/TabBar.tsx
import { For, Show, createSignal, mergeProps, splitProps } from "solid-js";
import { Badge } from "./Badge.js";

export interface TabBarItem {
  id: string;
  label: string;
  href?: string;
  icon?: string;
  badge?: string;
}

export interface TabBarProps {
  class?: string;
  className?: string;
  items: TabBarItem[];
  selected?: string;
  defaultSelected?: string;
  onChange?: (id: string) => void;
  ariaLabel?: string;
  [key: string]: unknown;
}

export function TabBar(rawProps: TabBarProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "items",
    "selected",
    "defaultSelected",
    "onChange",
    "ariaLabel",
  ]);

  const [localSelected, setLocalSelected] = createSignal<string | undefined>(props.defaultSelected);
  const selected = () => (props.selected !== undefined ? props.selected : localSelected());

  const select = (id: string) => {
    if (props.selected === undefined) setLocalSelected(id);
    props.onChange?.(id);
  };

  const className = () => props.class ?? props.className ?? "";
  return (
    <nav
      {...(native as Record<string, any>)}
      class={`krds-tab-bar${className() ? ` ${className()}` : ""}`}
      aria-label={props.ariaLabel ?? "주요 메뉴"}
    >
      <For each={props.items}>
        {(item) => {
          const active = () => selected() === item.id;
          const content = (
            <>
              <Show when={item.icon}>
                <i class={`svg-icon tab-bar-icon ${item.icon}`} aria-hidden="true" />
              </Show>
              <span class="tab-bar-label">{item.label}</span>
              <Show when={item.badge}>
                <Badge class="tab-bar-badge" tone="danger" appearance="solid">
                  {item.badge}
                </Badge>
              </Show>
            </>
          );
          return item.href ? (
            <a
              class={`tab-bar-item${active() ? " active" : ""}`}
              href={item.href}
              aria-current={active() ? "page" : undefined}
              onClick={(event) => {
                event.preventDefault();
                select(item.id);
              }}
            >
              {content}
            </a>
          ) : (
            <button
              type="button"
              class={`tab-bar-item${active() ? " active" : ""}`}
              aria-current={active() ? "page" : undefined}
              onClick={() => select(item.id)}
            >
              {content}
            </button>
          );
        }}
      </For>
    </nav>
  );
}
