// packages/svelte/src/Table.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { fieldOf } from './lib/shared.js';

  type Props = {
    id?: string;
    columns?: Record<string, unknown>[];
    rows?: Record<string, unknown>[];
    caption?: string;
    title?: string;
    className?: string;
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLElement>, 'children' | 'class' | 'id'>;

  let {
    id = '',
    columns = [],
    rows = [],
    caption = '',
    title = '제목',
    className = '',
    class: classProp = '',
    children,
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div class="krds-table-wrap">
  <table {...rest} class="tbl col data">
    <caption>{caption || title}</caption>
    <colgroup>
      {#each columns as column}
        <col style={fieldOf(column, 'width') ? `width: ${fieldOf(column, 'width')};` : undefined} />
      {/each}
    </colgroup>
    <thead>
      <tr>
        {#each columns as column}
          <th scope="col">{column.label}</th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each rows as row}
        <tr>
          {#each columns as column, columnIndex}
            {#if columnIndex === 0}<th scope="row">{row[column.key]}</th>{:else}<td>{row[column.key]}</td>{/if}
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// packages/solid/src/components/Table.tsx
import { For, mergeProps, splitProps } from "solid-js";
import type { TableColumn, TableRow } from "../shared.js";

export interface TableProps {
  class?: string;
  className?: string;
  caption?: string;
  columns?: TableColumn[];
  rows?: TableRow[];
  [key: string]: unknown;
}

export function Table(rawProps: TableProps) {
  const merged = mergeProps({ columns: [] as TableColumn[], rows: [] as TableRow[] }, rawProps);
  const [props, native] = splitProps(merged, ["class", "className", "caption", "columns", "rows"]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={["krds-table-wrap", className()].filter(Boolean).join(" ")}
    >
      <table class="tbl col data">
        <caption>{props.caption}</caption>
        <colgroup>
          <For each={props.columns}>
            {(column) => (
              <col
                style={
                  "width" in column && typeof column.width === "string" && column.width
                    ? { width: column.width }
                    : undefined
                }
              />
            )}
          </For>
        </colgroup>
        <thead>
          <tr>
            <For each={props.columns}>{(column) => <th scope="col">{column.label}</th>}</For>
          </tr>
        </thead>
        <tbody>
          <For each={props.rows}>
            {(row) => (
              <tr>
                <For each={props.columns}>
                  {(column, columnIndex) =>
                    columnIndex() === 0 ? (
                      <th scope="row">{String(row[column.key] ?? "")}</th>
                    ) : (
                      <td>{String(row[column.key] ?? "")}</td>
                    )
                  }
                </For>
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
}
