// packages/svelte/src/ToggleSwitch.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    name?: string;
    label?: string;
    disabled?: boolean;
    required?: boolean;
    form?: string;
    size?: string;
    modelValue?: string | number | boolean;
    checked?: boolean;
    onchange?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    name = '',
    label = '',
    disabled = false,
    required = false,
    form,
    size = '',
    modelValue = $bindable<string | number | boolean | undefined>(),
    checked = $bindable<boolean | undefined>(),
    onchange,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const checkedValue = $derived(
    checked !== undefined
      ? Boolean(checked)
      : typeof modelValue === 'boolean'
        ? modelValue
        : Boolean(modelValue),
  );
  const handleChange = (event: Event) => {
    const next = (event.currentTarget as HTMLInputElement).checked;
    checked = next;
    if (typeof modelValue === 'boolean' || modelValue === undefined) modelValue = next;
    if (onchange) onchange(event);
  };
</script>

<div class={`krds-form-toggle-switch ${size} ${rootClass}`}>
  <input
    {...rest}
    id={id}
    type="checkbox"
    name={name || undefined}
    {disabled}
    {required}
    {form}
    checked={checkedValue}
    onchange={handleChange}
  />
  <label for={id}><span class="switch-toggle"><i></i></span>{label}</label>
</div>

// packages/solid/src/components/ToggleSwitch.tsx
import { createSignal, createUniqueId, mergeProps, splitProps, type JSX } from "solid-js";

export interface ToggleSwitchProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  id?: string;
  name?: string;
  checked?: boolean;
  disabled?: boolean;
  playing?: boolean;
  size?: string;
  modelValue?: boolean;
  [key: string]: unknown;
}

export function ToggleSwitch(rawProps: ToggleSwitchProps) {
  const merged = mergeProps({ id: `krds-switch-${createUniqueId()}` }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "id",
    "name",
    "checked",
    "disabled",
    "playing",
    "size",
    "modelValue",
  ]);
  const [localChecked, setLocalChecked] = createSignal(false);
  const checked = () =>
    props.playing !== undefined
      ? Boolean(props.playing)
      : props.checked !== undefined
        ? Boolean(props.checked)
        : typeof props.modelValue === "boolean"
          ? props.modelValue
          : localChecked();
  const setChecked = (next: boolean) => {
    if (
      props.playing === undefined &&
      props.checked === undefined &&
      typeof props.modelValue !== "boolean"
    )
      setLocalChecked(next);
  };
  const updateChecked = (event: Event & { currentTarget: HTMLInputElement }) => {
    setChecked(event.currentTarget.checked);
    (native as Record<string, any>).onChange?.(event);
  };
  const content = () => props.children ?? props.label;
  const className = () => props.class ?? props.className ?? "";
  return (
    <div class={["krds-form-toggle-switch", props.size, className()].filter(Boolean).join(" ")}>
      <input
        {...(native as Record<string, any>)}
        id={props.id}
        type="checkbox"
        name={props.name}
        checked={checked()}
        disabled={props.disabled}
        onChange={updateChecked}
      />
      <label for={props.id}>
        <span class="switch-toggle">
          <i />
        </span>
        {content()}
      </label>
    </div>
  );
}

export const ToggleSwitchSize = ToggleSwitch;
