// packages/svelte/src/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    label?: string;
    message?: string;
    kind?: 'horizontal' | 'box' | 'vertical' | string;
    open?: boolean;
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet | string;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    label = '레이블',
    message = '',
    kind = 'horizontal',
    open = $bindable<boolean | undefined>(),
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);
  const placementClass = $derived(kind === 'box' ? 'tooltip-box' : kind === 'vertical' ? 'tooltip-vertical' : '');
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
</script>

<button
  {...rest}
  type="button"
  class={`krds-btn krds-tooltip small text ${placementClass} ${rootClass}`.trim()}
  data-tooltip={message}
  aria-labelledby={`${id}-tip`}
  onclick={() => toggleOpen()}
>
  {#if children}
    {#if typeof children === 'string'}
      {children}{' '}
    {:else}
      {@render children()}
    {/if}
  {:else}
    {`${label} `}
  {/if}<i class="ico-angle right svg-icon"></i>
</button>
<div id={`${id}-tip`} class={`krds-tooltip-popover ${isOpen ? placementClass : ''}`.trim()} role="tooltip" aria-hidden={isOpen ? 'false' : 'true'}>
  <span class="sr-only">{label}</span>
  {message}
</div>

// packages/solid/src/components/Tooltip.tsx
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface TooltipProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  message?: string;
  icon?: JSX.Element;
  id?: string;
  [key: string]: unknown;
}

export function Tooltip(rawProps: TooltipProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "message",
    "icon",
    "id",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label;
  const spacedContent = () =>
    typeof content() === "string" ? `${content()} ` : content();
  return (
    <>
      <button
        {...(native as Record<string, any>)}
        type="button"
        class={["krds-btn", "krds-tooltip", "small", "text", className()].filter(Boolean).join(" ")}
        data-tooltip={props.message}
        aria-labelledby={`${props.id}-tooltip`}
      >
        {spacedContent()}{props.icon ?? <i class="svg-icon ico-angle right" />}
      </button>
      <div
        id={`${props.id}-tooltip`}
        class="krds-tooltip-popover"
        role="tooltip"
        aria-hidden="true"
      >
        <span class="sr-only">{props.label}</span> {props.message}
      </div>
    </>
  );
}

export function TooltipBox(rawProps: TooltipProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "message",
    "icon",
    "id",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label;
  const spacedContent = () =>
    typeof content() === "string" ? `${content()} ` : content();
  return (
    <>
      <button
        {...(native as Record<string, any>)}
        type="button"
        class={["krds-btn", "krds-tooltip", "small", "text", "tooltip-box", className()]
          .filter(Boolean)
          .join(" ")}
        data-tooltip={props.message}
        aria-labelledby={`${props.id}-tooltip`}
      >
        {spacedContent()}{props.icon ?? <i class="svg-icon ico-angle right" />}
      </button>
      <div
        id={`${props.id}-tooltip`}
        class="krds-tooltip-popover"
        role="tooltip"
        aria-hidden="true"
      >
        <span class="sr-only">{props.label}</span> {props.message}
      </div>
    </>
  );
}

export function TooltipVertical(rawProps: TooltipProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "message",
    "icon",
    "id",
  ]);
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label;
  const spacedContent = () =>
    typeof content() === "string" ? `${content()} ` : content();
  return (
    <>
      <button
        {...(native as Record<string, any>)}
        type="button"
        class={["krds-btn", "krds-tooltip", "small", "text", "tooltip-vertical", className()]
          .filter(Boolean)
          .join(" ")}
        data-tooltip={props.message}
        aria-labelledby={`${props.id}-tooltip`}
      >
        {spacedContent()}{props.icon ?? <i class="svg-icon ico-angle right" />}
      </button>
      <div
        id={`${props.id}-tooltip`}
        class="krds-tooltip-popover"
        role="tooltip"
        aria-hidden="true"
      >
        <span class="sr-only">{props.label}</span> {props.message}
      </div>
    </>
  );
}
