// packages/react/src/components/TopButton.tsx
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

export interface TopButtonProps extends BoxProps {
  type?: "basic" | "label";
  onClick: () => void;
  ariaLabel?: string;
  label?: string;
}

export function TopButton({
  type = "basic",
  onClick,
  ariaLabel,
  label = "TOP",
  className,
}: TopButtonProps) {
  return (
    <div className={cx("krds-top-button", className)}>
      <button
        type="button"
        className="krds-btn medium icon"
        aria-label={ariaLabel ?? "맨 위로"}
        onClick={onClick}
      >
        <SvgIcon name="ico-go-top" />
        {type === "label" ? <span>{label}</span> : null}
      </button>
    </div>
  );
}

// packages/solid/src/components/TopButton.tsx
import { Show, mergeProps, splitProps } from "solid-js";

export interface TopButtonProps {
  class?: string;
  className?: string;
  type?: "basic" | "label";
  onClick: () => void;
  ariaLabel?: string;
  label?: string;
  [key: string]: unknown;
}

export function TopButton(rawProps: TopButtonProps) {
  const merged = mergeProps({ type: "basic" as const }, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "type",
    "onClick",
    "ariaLabel",
    "label",
  ]);

  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-top-button${className() ? ` ${className()}` : ""}`}
    >
      <button
        type="button"
        class="krds-btn medium icon"
        aria-label={props.ariaLabel ?? "맨 위로"}
        onClick={props.onClick}
      >
        <i class="svg-icon ico-go-top" />
        <Show when={props.type === "label"}>
          <span>{props.label ?? "TOP"}</span>
        </Show>
      </button>
    </div>
  );
}
