// packages/react/src/components/Tts.tsx
import { useState, type ReactNode, type ButtonHTMLAttributes, type Ref } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type NativeCommonProps } from "./_utils.js";

export interface TtsProps extends NativeCommonProps, ButtonHTMLAttributes<HTMLButtonElement> {
  label?: ReactNode;
  text?: string;
  iconOnly?: boolean;
  size?: "xsmall" | "small" | "medium" | "large";
  playing?: boolean;
  defaultPlaying?: boolean;
  onPlayingChange?: (playing: boolean) => void;
}

export function Tts({
  label,
  text,
  iconOnly = false,
  size = "medium",
  playing: controlledPlaying,
  defaultPlaying = false,
  onPlayingChange,
  children,
  className,
  onClick,
  ref,
  ...props
}: TtsProps & { ref?: Ref<HTMLButtonElement> }) {
  const [uncontrolledPlaying, setUncontrolledPlaying] = useState(defaultPlaying);
  const playing = controlledPlaying ?? uncontrolledPlaying;
  const textContent = children ?? text ?? label;
  return (
    <button
      {...props}
      ref={ref}
      type={props.type ?? "button"}
      className={cx("krds-tts", size, playing && "play", className)}
      onClick={(event) => {
        const next = !playing;
        if (controlledPlaying === undefined) setUncontrolledPlaying(next);
        onPlayingChange?.(next);
        onClick?.(event);
      }}
    >
      <span className="krds-tts-icon" aria-hidden="true">
        <SvgIcon name={playing ? "ico-stop" : "ico-volume"} />
      </span>
      {iconOnly ? (
        textContent ? (
          <span className="sr-only">{textContent}</span>
        ) : null
      ) : (
        <>
          {" "}
          <span className="krds-tts-text">{textContent}</span>
        </>
      )}
    </button>
  );
}

// packages/solid/src/components/Tts.tsx
import { Show, createSignal, mergeProps, splitProps, type JSX } from "solid-js";

export interface TtsProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  text?: string;
  size?: string;
  checked?: boolean;
  playing?: boolean;
  modelValue?: boolean;
  [key: string]: unknown;
}

export function Tts(rawProps: TtsProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "text",
    "size",
    "checked",
    "playing",
    "modelValue",
  ]);
  const [localChecked, setLocalChecked] = createSignal(false);
  const checked = () =>
    props.playing !== undefined
      ? Boolean(props.playing)
      : props.checked !== undefined
        ? Boolean(props.checked)
        : typeof props.modelValue === "boolean"
          ? props.modelValue
          : localChecked();
  const setChecked = (next: boolean) => {
    if (
      props.playing === undefined &&
      props.checked === undefined &&
      typeof props.modelValue !== "boolean"
    )
      setLocalChecked(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label ?? props.text;
  return (
    <button
      {...(native as Record<string, any>)}
      type="button"
      class={["krds-tts", props.size ?? "medium", className()].filter(Boolean).join(" ")}
      onClick={(event) => {
        setChecked(!checked());
        (native as Record<string, any>).onClick?.(event);
      }}
    >
      <span class="krds-tts-icon" aria-hidden="true">
        <i class={checked() ? "svg-icon ico-pause" : "svg-icon ico-volume"} />
      </span>
      <Show when={true}>
        {" "}
        <span class="krds-tts-text">{content()}</span>
      </Show>
    </button>
  );
}

export function TtsIcon(rawProps: TtsProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "text",
    "size",
    "checked",
    "playing",
    "modelValue",
  ]);
  const [localChecked, setLocalChecked] = createSignal(false);
  const checked = () =>
    props.playing !== undefined
      ? Boolean(props.playing)
      : props.checked !== undefined
        ? Boolean(props.checked)
        : typeof props.modelValue === "boolean"
          ? props.modelValue
          : localChecked();
  const setChecked = (next: boolean) => {
    if (
      props.playing === undefined &&
      props.checked === undefined &&
      typeof props.modelValue !== "boolean"
    )
      setLocalChecked(next);
  };
  const className = () => props.class ?? props.className ?? "";
  return (
    <button
      {...(native as Record<string, any>)}
      type="button"
      class={["krds-tts", props.size ?? "medium", className()].filter(Boolean).join(" ")}
      onClick={(event) => {
        setChecked(!checked());
        (native as Record<string, any>).onClick?.(event);
      }}
    >
      <span class="krds-tts-icon" aria-hidden="true">
        <i class={checked() ? "svg-icon ico-pause" : "svg-icon ico-volume"} />
      </span>
      <Show when={props.label ?? props.text}>
        <span class="sr-only">{props.label ?? props.text}</span>
      </Show>
    </button>
  );
}

export const TtsSize = Tts;
