// packages/svelte/src/Tts.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  type Props = {
    label?: string;
    size?: string;
    iconOnly?: boolean;
    checked?: boolean;
    modelValue?: string | number | boolean;
    onclick?: (event: Event) => void;
    onchange?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    'aria-label'?: string;
    text?: string;
    [key: string]: unknown;
  };
  let {
    label = '레이블',
    size = 'medium',
    iconOnly = false,
    checked = $bindable<boolean | undefined>(),
    modelValue = $bindable<string | number | boolean | undefined>(),
    onclick,
    onchange,
    class: classProp = '',
    className = '',
    children,
    'aria-label': ariaLabel,
    text,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const buttonClass = $derived(
    `${rootClass} krds-tts ${size} ${checkedValue ? 'play' : ''}`.trim(),
  );
  const checkedValue = $derived(
    checked !== undefined
      ? Boolean(checked)
      : typeof modelValue === 'boolean'
        ? modelValue
        : Boolean(modelValue),
  );
  const setChecked = (next: boolean, event: Event, eventName: string) => {
    checked = next;
    if (typeof modelValue === 'boolean' || modelValue === undefined) modelValue = next;
    if (eventName === 'click' && onclick) onclick(event);
    else if (onchange) onchange(event);
  };
</script>

<button
  {...rest}
  type="button"
  class={buttonClass}
  aria-label={iconOnly ? (ariaLabel || label || '음성 재생') : ariaLabel}
  onclick={(event) => setChecked(!checkedValue, event, 'click')}
>
  <span class="krds-tts-icon" aria-hidden="true"><i class="ico-volume svg-icon"></i></span>
  {#if !iconOnly}<span class="krds-tts-text">{#if children}{@render children()}{:else}{label}{/if}</span>{/if}
</button>

// packages/solid/src/components/Tts.tsx
import { createSignal, mergeProps, splitProps, type JSX } from "solid-js";

export interface TtsProps {
  class?: string;
  className?: string;
  children?: JSX.Element;
  label?: string;
  text?: string;
  size?: string;
  checked?: boolean;
  playing?: boolean;
  modelValue?: boolean;
  [key: string]: unknown;
}

export function Tts(rawProps: TtsProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "text",
    "size",
    "checked",
    "playing",
    "modelValue",
  ]);
  const [localChecked, setLocalChecked] = createSignal(false);
  const checked = () =>
    props.playing !== undefined
      ? Boolean(props.playing)
      : props.checked !== undefined
        ? Boolean(props.checked)
        : typeof props.modelValue === "boolean"
          ? props.modelValue
          : localChecked();
  const setChecked = (next: boolean) => {
    if (
      props.playing === undefined &&
      props.checked === undefined &&
      typeof props.modelValue !== "boolean"
    )
      setLocalChecked(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const content = () => props.children ?? props.label ?? props.text;
  return (
    <button
      {...(native as Record<string, any>)}
      type="button"
      class={["krds-tts", props.size ?? "medium", className()].filter(Boolean).join(" ")}
      onClick={(event) => {
        setChecked(!checked());
        (native as Record<string, any>).onClick?.(event);
      }}
    >
      <span class="krds-tts-icon" aria-hidden="true">
        <i class={checked() ? "svg-icon ico-pause" : "svg-icon ico-volume"} />
      </span>
      <span class="krds-tts-text">{content()}</span>
    </button>
  );
}

export function TtsIcon(rawProps: TtsProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "children",
    "label",
    "text",
    "size",
    "checked",
    "playing",
    "modelValue",
  ]);
  const [localChecked, setLocalChecked] = createSignal(false);
  const checked = () =>
    props.playing !== undefined
      ? Boolean(props.playing)
      : props.checked !== undefined
        ? Boolean(props.checked)
        : typeof props.modelValue === "boolean"
          ? props.modelValue
          : localChecked();
  const setChecked = (next: boolean) => {
    if (
      props.playing === undefined &&
      props.checked === undefined &&
      typeof props.modelValue !== "boolean"
    )
      setLocalChecked(next);
  };
  const className = () => props.class ?? props.className ?? "";
  return (
    <button
      {...(native as Record<string, any>)}
      type="button"
      class={["krds-tts", props.size ?? "medium", className()].filter(Boolean).join(" ")}
      onClick={(event) => {
        setChecked(!checked());
        (native as Record<string, any>).onClick?.(event);
      }}
    >
      <span class="krds-tts-icon" aria-hidden="true">
        <i class={checked() ? "svg-icon ico-pause" : "svg-icon ico-volume"} />
      </span>
    </button>
  );
}

export const TtsSize = Tts;
