// packages/react/src/components/UserFeedback.tsx
import { useId, useState, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { Radio } from "./Radio.js";
import type { BoxProps } from "./_utils.js";

const defaultOptions: UserFeedbackOption[] = [
  { value: "satisfied", label: "만족" },
  { value: "dissatisfied", label: "불만족" },
];

export interface UserFeedbackOption {
  value: string;
  label: string;
}

export interface UserFeedbackProps extends BoxProps {
  title?: ReactNode;
  options?: UserFeedbackOption[];
  onSubmit?: (value: string) => void;
  submitLabel?: ReactNode;
}

export function UserFeedback({
  title = "이 페이지에 만족하시나요?",
  options = defaultOptions,
  onSubmit,
  submitLabel = "제출",
  className,
}: UserFeedbackProps) {
  const generatedId = useId();
  const name = `krds-feedback-${generatedId}`;
  const [selected, setSelected] = useState<string | undefined>();

  return (
    <div className={cx("krds-user-feedback", className)}>
      <fieldset>
        <legend className="feedback-title">{title}</legend>
        <div className="feedback-options">
          {options.map((option) => (
            <Radio
              key={option.value}
              name={name}
              value={option.value}
              label={option.label}
              checked={selected === option.value}
              onChange={() => setSelected(option.value)}
            />
          ))}
        </div>
        <button
          type="button"
          className="krds-btn small primary"
          onClick={() => {
            if (selected) onSubmit?.(selected);
          }}
        >
          {submitLabel}
        </button>
      </fieldset>
    </div>
  );
}

// packages/solid/src/components/UserFeedback.tsx
import { For, createSignal, createUniqueId, mergeProps, splitProps, type JSX } from "solid-js";

export interface FeedbackOption {
  value: string;
  label: string;
}

export interface UserFeedbackProps {
  class?: string;
  className?: string;
  title?: JSX.Element;
  options?: FeedbackOption[];
  onSubmit?: (value: string) => void;
  submitLabel?: JSX.Element;
  [key: string]: unknown;
}

export function UserFeedback(rawProps: UserFeedbackProps) {
  const merged = mergeProps(
    {
      title: "이 페이지에 만족하시나요?",
      options: [
        { value: "satisfied", label: "만족" },
        { value: "dissatisfied", label: "불만족" },
      ] as FeedbackOption[],
      submitLabel: "제출",
    },
    rawProps,
  );
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "options",
    "onSubmit",
    "submitLabel",
  ]);

  const [selected, setSelected] = createSignal<string | undefined>(undefined);
  const name = `krds-feedback-${createUniqueId()}`;

  const submit = () => {
    const value = selected();
    if (value !== undefined) props.onSubmit?.(value);
  };

  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-user-feedback${className() ? ` ${className()}` : ""}`}
    >
      <fieldset>
        <legend class="feedback-title">{props.title}</legend>
        <div class="feedback-options">
          <For each={props.options}>
            {(option) => (
              <div class="krds-form-check">
                <input
                  type="radio"
                  id={`${name}-${option.value}`}
                  name={name}
                  value={option.value}
                  checked={selected() === option.value}
                  onChange={(event) => {
                    if (event.currentTarget.checked) setSelected(option.value);
                  }}
                />
                <label for={`${name}-${option.value}`}>{option.label}</label>
              </div>
            )}
          </For>
        </div>
        <button type="button" class="krds-btn small primary" onClick={submit}>
          {props.submitLabel}
        </button>
      </fieldset>
    </div>
  );
}
