// packages/react/src/components/Alert.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

const alertIcons = {
  danger: "ico-error-fill",
  warning: "ico-error-fill",
  success: "ico-success-fill",
  information: "ico-information-fill",
} as const;

export interface AlertProps extends BoxProps {
  state?: "danger" | "warning" | "success" | "information";
  size?: "with-title" | "slim";
  title?: ReactNode;
  message: ReactNode;
}

export function Alert({ state = "danger", size = "slim", title, message, className }: AlertProps) {
  return (
    <div className={cx("krds-alert", state, size, className)} role="status">
      <i className={cx("svg-icon alert-icon", alertIcons[state])} aria-hidden="true" />
      {title ? <strong className="alert-title">{title}</strong> : null}
      <p className="alert-body">{message}</p>
    </div>
  );
}

// packages/angular/src/components/alert.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-alert",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'krds-alert ' + state + ' ' + size" role="status">
      <i class="svg-icon alert-icon {{ stateIcon }}" aria-hidden="true"></i>
      @if (title) {
        <strong class="alert-title">{{ title }}</strong>
      }
      <p class="alert-body">{{ message }}</p>
    </div>
  `,
})
export class KrdsAlertComponent {
  @Input() id = createStableId("krds-alert");
  @Input() state: "danger" | "warning" | "success" | "information" = "danger";
  @Input() size: "with-title" | "slim" = "slim";
  @Input() title = "";
  @Input() message = "";

  get stateIcon(): string {
    switch (this.state) {
      case "success":
        return "ico-success-fill";
      case "information":
        return "ico-information-fill";
      case "warning":
      case "danger":
      default:
        return "ico-error-fill";
    }
  }
}
