// packages/react/src/components/Badge.tsx
import type { ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsTone } from "@krds-community/recipes";
import { toneClass, outlineToneClass } from "./_utils.js";
import type { BoxProps } from "./_utils.js";

export interface BadgeProps extends BoxProps {
  tone?: KrdsTone;
  appearance?: "outline" | "solid" | "light";
  size?: "small" | "medium" | "large";
  number?: boolean;
  label?: ReactNode;
}
export function Badge({
  tone = "primary",
  appearance = "outline",
  size,
  number,
  label,
  children,
  className,
}: BadgeProps) {
  const appearanceClass =
    appearance === "outline"
      ? outlineToneClass[tone]
      : appearance === "light"
        ? `bg-light-${toneClass[tone]}`
        : `bg-${toneClass[tone]}`;
  return (
    <span className={cx("krds-badge", appearanceClass, size, number && "number", className)}>
      {children ?? label}
    </span>
  );
}
export const BadgeNumber = (props: Omit<BadgeProps, "number">) => <Badge {...props} number />;
export const BadgeSize = Badge;

// packages/angular/src/components/badge.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import type { KrdsTone } from "@krds-community/recipes";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-badge",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span
      [class]="
        'krds-badge ' +
        (size !== 'medium' ? size + ' ' : '') +
        (appearance === 'outline' ? 'outline-' : appearance === 'light' ? 'bg-light-' : 'bg-') +
        tone +
        (number ? ' number' : '')
      "
      >{{ label }}</span
    >
  `,
})
export class KrdsBadgeComponent {
  @Input() id = createStableId("krds-badge");
  @Input() label = "레이블";
  @Input() tone: KrdsTone = "primary";
  @Input() appearance: "outline" | "solid" | "light" = "outline";
  @Input() size = "medium";
  @Input() number = false;
}
@Component({
  selector: "krds-badge-number",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span
      [class]="
        'krds-badge ' +
        (size !== 'medium' ? size + ' ' : '') +
        (appearance === 'outline' ? 'outline-' : appearance === 'light' ? 'bg-light-' : 'bg-') +
        tone +
        (number ? ' number' : '')
      "
      >{{ label }}</span
    >
  `,
})
export class KrdsBadgeNumberComponent extends KrdsBadgeComponent {
  @Input() override number = true;
}
export { KrdsBadgeComponent as KrdsBadgeSizeComponent };
