// packages/svelte/src/BottomSheet.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import type { Snippet } from 'svelte';

  const CLOSE_ANIMATION_MS = 200;

  type Props = {
    open?: boolean;
    defaultOpen?: boolean;
    title?: string;
    description?: string;
    closeLabel?: string;
    onopenchange?: (open: boolean) => void;
    children?: Snippet;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  const generatedId = $props.id();

  let {
    id = generatedId,
    open = $bindable<boolean | undefined>(),
    defaultOpen = false,
    title = '',
    description = '',
    closeLabel = '닫기',
    onopenchange,
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const controlled = $derived(open !== undefined);

  let rendered = $state(open === true || (open === undefined && defaultOpen === true));
  let closing = $state(false);
  let wasOpen = false;
  let wasRendered = false;
  let removeTimer: ReturnType<typeof setTimeout> | undefined;
  let sheetRoot: HTMLElement | undefined = $state();
  let restoreFocus: HTMLElement | null = null;

  const startClose = () => {
    if (!rendered || closing) return;
    closing = true;
    restoreFocus?.focus();
    restoreFocus = null;
    removeTimer = setTimeout(() => {
      rendered = false;
      closing = false;
      onopenchange?.(false);
    }, CLOSE_ANIMATION_MS);
  };

  const requestClose = () => {
    if (controlled) {
      onopenchange?.(false);
    } else {
      startClose();
    }
  };

  $effect(() => {
    const isOpen = controlled ? open === true : rendered;
    if (isOpen && !wasOpen) {
      if (removeTimer) clearTimeout(removeTimer);
      closing = false;
      rendered = true;
    } else if (!isOpen && wasOpen) {
      startClose();
    }
    wasOpen = isOpen;
  });

  $effect(() => {
    if (rendered && !wasRendered) {
      restoreFocus =
        typeof document !== 'undefined' && document.activeElement instanceof HTMLElement
          ? document.activeElement
          : null;
      queueMicrotask(() => {
        sheetRoot
          ?.querySelector<HTMLElement>(
            'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
          )
          ?.focus();
      });
    }
    wasRendered = rendered;
  });

  const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      requestClose();
      return;
    }
    if (event.key !== 'Tab') return;
    const focusable = Array.from(
      sheetRoot?.querySelectorAll<HTMLElement>(
        'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
      ) ?? [],
    );
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    const activeElement = sheetRoot?.ownerDocument.activeElement;
    if (event.shiftKey && (activeElement === first || !sheetRoot?.contains(activeElement))) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  };

  onDestroy(() => {
    if (removeTimer) clearTimeout(removeTimer);
  });
</script>

{#if rendered}
  <div
    {...rest}
    bind:this={sheetRoot}
    class={`krds-bottom-sheet ${rootClass}`}
    class:closing={closing}
    role="dialog"
    aria-modal="true"
    aria-labelledby={title ? `${id}-title` : undefined}
    onkeydown={handleKeydown}
  >
    <div class="bottom-sheet-overlay" data-close onclick={requestClose}></div>
    <div class="bottom-sheet-panel" role="document">
      <button type="button" class="bottom-sheet-handle" aria-hidden="true" tabindex="-1"></button>
      {#if title}
        <div class="bottom-sheet-header">
          <h2 id={`${id}-title`} class="bottom-sheet-title">{title}</h2>
          {#if description}
            <p class="bottom-sheet-description">{description}</p>
          {/if}
        </div>
      {/if}
      <div class="bottom-sheet-body">{@render children?.()}</div>
      <button type="button" class="krds-btn medium icon bottom-sheet-close" aria-label={closeLabel} onclick={requestClose}>
        <i class="svg-icon ico-modal-close"></i>
      </button>
    </div>
  </div>
{/if}

// packages/angular/src/components/bottom-sheet.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  Input,
  Output,
  type OnChanges,
  type OnDestroy,
  type OnInit,
  type SimpleChanges,
} from "@angular/core";
import { createStableId } from "../kinds";

const CLOSE_ANIMATION_MS = 200;

@Component({
  selector: "krds-bottom-sheet",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (rendered) {
      <div
        [class]="'krds-bottom-sheet' + (closing ? ' closing' : '')"
        role="dialog"
        aria-modal="true"
        [attr.aria-labelledby]="title ? id + '-title' : null"
      >
        <div class="bottom-sheet-overlay" (click)="close()"></div>
        <div class="bottom-sheet-panel" role="document">
          <button type="button" class="bottom-sheet-handle" aria-hidden="true" tabindex="-1"></button>
          @if (title) {
            <div class="bottom-sheet-header">
              <h2 [id]="id + '-title'" class="bottom-sheet-title">{{ title }}</h2>
              @if (description) {
                <p class="bottom-sheet-description">{{ description }}</p>
              }
            </div>
          }
          <div class="bottom-sheet-body">
            <ng-content></ng-content>
          </div>
          <button
            type="button"
            class="krds-btn medium icon bottom-sheet-close"
            [attr.aria-label]="closeLabel"
            (click)="close()"
          >
            <i class="svg-icon ico-modal-close"></i>
          </button>
        </div>
      </div>
    }
  `,
})
export class KrdsBottomSheetComponent implements OnInit, OnChanges, OnDestroy {
  @Input() id = createStableId("krds-bottom-sheet");
  @Input() open: boolean | undefined = undefined;
  @Input() defaultOpen = false;
  @Input() title = "";
  @Input() description = "";
  @Input() closeLabel = "닫기";
  @Output() openChange = new EventEmitter<boolean>();

  rendered = false;
  closing = false;
  private closeTimer: number | null = null;
  private lastFocused: HTMLElement | null = null;
  private keydownHandler: ((event: KeyboardEvent) => void) | null = null;
  private readonly changeDetector = inject(ChangeDetectorRef);
  private readonly host = inject(ElementRef<HTMLElement>);

  get isControlled(): boolean {
    return this.open !== undefined;
  }

  ngOnInit(): void {
    if (this.isControlled ? this.open === true : this.defaultOpen) {
      this.rendered = true;
      this.openPanel();
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!("open" in changes)) return;
    if (this.open === true) {
      this.closing = false;
      this.rendered = true;
      this.clearCloseTimer();
      this.openPanel();
    } else if (this.open === false && this.rendered) {
      this.beginClose();
    }
  }

  ngOnDestroy(): void {
    this.clearCloseTimer();
    this.detachKeydown();
  }

  close(): void {
    if (this.isControlled) {
      this.openChange.emit(false);
    } else {
      this.beginClose();
    }
  }

  private openPanel(): void {
    if (typeof window === "undefined") return;
    this.attachKeydown();
    this.lastFocused = typeof document === "undefined" ? null : (document.activeElement as HTMLElement | null);
    window.setTimeout(() => {
      this.panelFocusables()[0]?.focus();
    }, 0);
  }

  private beginClose(): void {
    if (typeof window === "undefined") return;
    if (!this.rendered || this.closing) return;
    this.closing = true;
    this.clearCloseTimer();
    this.detachKeydown();
    this.lastFocused?.focus();
    this.lastFocused = null;
    this.closeTimer = window.setTimeout(() => {
      this.closeTimer = null;
      this.rendered = false;
      this.closing = false;
      if (!this.isControlled) {
        this.openChange.emit(false);
      }
      this.changeDetector.markForCheck();
    }, CLOSE_ANIMATION_MS);
    this.changeDetector.markForCheck();
  }

  private panelFocusables(): HTMLElement[] {
    const panel = (this.host.nativeElement as HTMLElement).querySelector<HTMLElement>(
      ".bottom-sheet-panel",
    );
    if (!panel) return [];
    return Array.from(
      panel.querySelectorAll<HTMLElement>(
        'button, a[href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      )
    );
  }

  private attachKeydown(): void {
    if (this.keydownHandler !== null || typeof document === "undefined") return;
    this.keydownHandler = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        this.close();
        return;
      }
      if (event.key !== "Tab") return;
      const focusables = this.panelFocusables();
      if (focusables.length === 0) return;
      const first = focusables[0];
      const last = focusables[focusables.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last?.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first?.focus();
      }
    };
    document.addEventListener("keydown", this.keydownHandler);
  }

  private detachKeydown(): void {
    if (this.keydownHandler !== null) {
      document.removeEventListener("keydown", this.keydownHandler);
      this.keydownHandler = null;
    }
  }

  private clearCloseTimer(): void {
    if (this.closeTimer !== null) {
      window.clearTimeout(this.closeTimer);
      this.closeTimer = null;
    }
  }
}
