// packages/solid/src/components/Breadcrumb.tsx
import { For, createUniqueId, mergeProps, splitProps } from "solid-js";
import { labelOf } from "../shared.js";

export interface BreadcrumbProps {
  class?: string;
  className?: string;
  id?: string;
  label?: string;
  items?: (string | number | { href?: string; label?: string; title?: string })[];
  [key: string]: unknown;
}

export function Breadcrumb(rawProps: BreadcrumbProps) {
  const merged = mergeProps({ id: `krds-breadcrumb-${createUniqueId()}` }, rawProps);
  const [props, native] = splitProps(merged, ["class", "className", "id", "label", "items"]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <nav
      {...(native as Record<string, any>)}
      id={props.id}
      class={`krds-breadcrumb-wrap${className() ? ` ${className()}` : ""}`}
      aria-label={(native as Record<string, string>)?.["aria-label"] ?? props.label ?? "현재 경로"}
    >
      <ol class="breadcrumb">
        <For each={props.items ?? []}>
          {(item, itemIndex) => (
            <li classList={{ home: itemIndex() === 0 }}>
              <a
                class="txt"
                href={
                  typeof item !== "string" && typeof item !== "number" && "href" in item
                    ? (item.href ?? "#")
                    : "#"
                }
              >
                {labelOf(item)}
              </a>
            </li>
          )}
        </For>
      </ol>
    </nav>
  );
}

// packages/angular/src/components/breadcrumb.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId, type AngularNavItem } from "../kinds";

@Component({
  selector: "krds-breadcrumb",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="krds-breadcrumb-wrap" aria-label="현재 경로" [id]="id">
      <ol class="breadcrumb">
        @for (item of items; track $index) {
          <li [class.home]="$index === 0">
            <a class="txt" [href]="navHref(item)">{{ navLabel(item) }}</a>
          </li>
        }
      </ol>
    </nav>
  `,
})
export class KrdsBreadcrumbComponent {
  @Input() id = createStableId("krds-badge");
  @Input() items: AngularNavItem[] = [];

  navLabel(item: unknown): string {
    if (typeof item === "string" || typeof item === "number") return String(item);
    if (!item || typeof item !== "object") return "";
    if ("label" in item) return String((item as { label?: unknown }).label ?? "");
    if ("title" in item) return String((item as { title?: unknown }).title ?? "");
    if ("text" in item) return String((item as { text?: unknown }).text ?? "");
    if ("message" in item) return String((item as { message?: unknown }).message ?? "");
    return "";
  }

  navHref(item: unknown): string {
    if (!item || typeof item !== "object" || !("href" in item)) return "#";
    return String((item as { href?: unknown }).href || "#");
  }
}
