// packages/react/src/components/CoachMark.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { type BoxProps } from "./_utils.js";

export interface CoachMarkProps extends BoxProps {
  title?: string;
  step?: string;
  stepTitle?: ReactNode;
  description?: ReactNode;
  contentTitle?: ReactNode;
  currentStep?: ReactNode;
  totalSteps?: ReactNode;
  currentStepLabel?: string;
  totalStepsLabel?: string;
  stopLabel?: ReactNode;
  nextLabel?: ReactNode;
  onNext?: () => void;
  onClose?: () => void;
}

export function CoachMark({
  title,
  step = "1 / 1",
  stepTitle,
  description,
  contentTitle,
  currentStep,
  totalSteps,
  currentStepLabel = "현재 단계",
  totalStepsLabel = "총 단계",
  stopLabel,
  nextLabel,
  onNext,
  onClose,
  children,
  className,
}: CoachMarkProps) {
  const [stepCurrent = "", stepTotal = ""] = step.split("/").map((part) => part.trim());
  return (
    <div className={cx("txt-box", "bg-white", "bg-white", "krds-coach-mark", className)}>
      <div className="coach-balloon">
        {title ? <h5 className="sr-only">{title}</h5> : null}
        <h6 className="coach-tit">{stepTitle}</h6>
        <p className="desc">{description}</p>
        <div className="coach-controls">
          <div className="num">
            <span className="sr-only">{currentStepLabel}</span>
            <strong>{currentStep ?? stepCurrent}</strong>
            <span className="sr-only">{totalStepsLabel}</span>
            <span>{totalSteps ?? stepTotal}</span>
          </div>
          <div className="btn-wrap">
            <button type="button" className="krds-btn small text" onClick={onClose}>
              {stopLabel}
            </button>
            <button type="button" className="krds-btn small tertiary" onClick={onNext}>
              {nextLabel}
            </button>
          </div>
        </div>
      </div>
      <div>
        <h3>{children ?? contentTitle}</h3>
      </div>
    </div>
  );
}

// packages/angular/src/components/coach-mark.component.ts
import { CommonModule } from "@angular/common";
import { Component, Input } from "@angular/core";

@Component({
  selector: "krds-coach-mark",
  standalone: true,
  imports: [CommonModule],
  styles: [":host { display: contents; }"],
  template: `
    <div class="txt-box bg-white bg-white krds-coach-mark">
      <div class="coach-balloon">
        @if (title) {
          <h5 class="sr-only">{{ title }}</h5>
        }
        <h6 class="coach-tit">{{ stepTitle }}</h6>
        <p class="desc">{{ description }}</p>
        <div class="coach-controls">
          <div class="num">
            <span class="sr-only">{{ currentStepLabel }}</span>
            <strong>{{ currentStep }}</strong>
            <span class="sr-only">{{ totalStepsLabel }}</span>
            <span>{{ totalSteps }}</span>
          </div>
          <div class="btn-wrap">
            <button type="button" class="krds-btn small text">{{ stopLabel }}</button>
            <button type="button" class="krds-btn small tertiary">{{ nextLabel }}</button>
          </div>
        </div>
      </div>
      <div>
        <h3>{{ contentTitle }}</h3>
      </div>
    </div>
  `,
})
export class KrdsCoachMarkComponent {
  @Input() title = "";
  @Input() stepTitle = "";
  @Input() description = "";
  @Input() contentTitle = "";
  @Input() currentStepLabel = "현재 단계";
  @Input() totalStepsLabel = "총 단계";
  @Input() stopLabel = "";
  @Input() nextLabel = "";
  @Input() step = "1 / 1";

  get currentStep(): string {
    return this.step.split("/")[0]?.trim() ?? "";
  }

  // react renders only the parts present in `step` — no "1/1" fallback.
  get totalSteps(): string {
    return this.step.split("/")[1]?.trim() ?? "";
  }
}
