// packages/react/src/components/Infobox.tsx
import { type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { BoxProps } from "./_utils.js";

export interface InfoboxProps extends BoxProps {
  type?: "primary" | "secondary";
  size?: "default" | "slim";
  message: ReactNode;
  "aria-label"?: string;
}

export function Infobox({
  type = "primary",
  size = "default",
  message,
  "aria-label": ariaLabel,
  className,
}: InfoboxProps) {
  return (
    <div
      className={cx("krds-infobox", type, size, className)}
      role="region"
      aria-label={ariaLabel ?? "알림"}
    >
      <p className="infobox-text">{message}</p>
    </div>
  );
}

// packages/angular/src/components/infobox.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-infobox",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'krds-infobox ' + type + ' ' + size" role="region" [attr.aria-label]="ariaLabel">
      <p class="infobox-text">{{ message }}</p>
    </div>
  `,
})
export class KrdsInfoboxComponent {
  @Input() id = createStableId("krds-infobox");
  @Input() type: "primary" | "secondary" = "primary";
  @Input() size: "default" | "slim" = "default";
  @Input() message = "";
  @Input() ariaLabel = "알림";
}
