// packages/svelte/src/MainMenuMobile.svelte
<script lang="ts">
  import type { KrdsNavItem } from '@krds-community/recipes';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { invoke, labelOf, hrefOf, childrenOf, fieldOf } from './lib/shared.js';

  type Props = {
    id?: string;
    items?: KrdsNavItem[];
    links?: KrdsNavItem[];
    nav?: KrdsNavItem[];
    utilityItems?: KrdsNavItem[];
    serviceItems?: KrdsNavItem[];
    bottomItems?: KrdsNavItem[];
    loginLabel?: string;
    menuLabel?: string;
    searchPlaceholder?: string;
    searchTitle?: string;
    searchLabel?: string;
    closeLabel?: string;
    previousLabel?: string;
    sample?: boolean;
    open?: boolean;
    onclick?: (event: Event) => void;
    children?: Snippet;
    class?: string;
    className?: string;
  } & Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'id'>;

  let {
    id = 'krds-main-menu-mobile',
    items = [],
    links = [],
    nav = [],
    utilityItems = [],
    serviceItems = [],
    bottomItems = [],
    loginLabel = '',
    menuLabel = '',
    searchPlaceholder = '',
    searchTitle = '',
    searchLabel = '',
    closeLabel = '',
    previousLabel = '',
    sample = false,
    open = $bindable<boolean | undefined>(),
    onclick,
    children,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const navigationItems = $derived(items.length ? items : links.length ? links : nav);
  const isOpen = $derived(open ?? false);

  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event) invoke(onclick, event);
  };
</script>

<div
  {...rest}
  id={id}
  class={`krds-main-menu-mobile ${rootClass}`}
  class:sample={sample}
  style={sample ? 'display: block; position: static; visibility: visible;' : 'display: none;'}
  role="navigation"
  aria-label={menuLabel || "전체 메뉴"}
>
  <div class="gnb-wrap">
    <div class="gnb-header">
      <div class="gnb-utils">
        <ul class="utility-list">
          {#each utilityItems as item}
            <li><button type="button" class="krds-btn xsmall text">{item.label}</button></li>
          {/each}
        </ul>
      </div>
      <div class="gnb-login">
        <button type="button" class="krds-btn large text">
          <i class="svg-icon ico-log"></i> {loginLabel}
        </button>
      </div>
      <div class="gnb-service-menu">
        {#each serviceItems as item}<a href={hrefOf(item)} class="link">{item.label}</a>{/each}
      </div>
      <div class="sch-input">
        <input
          type="text"
          class="krds-input"
          placeholder={searchPlaceholder}
          title={searchTitle}
          aria-label={searchLabel || searchTitle || undefined}
        />
        <button type="button" class="krds-btn medium icon ico-search">
          <span class="sr-only">{searchLabel}</span>
          <i class="svg-icon ico-sch"></i>
        </button>
      </div>
    </div>
    <div class="gnb-body">
      <div class="gnb-menu">
        <div class="menu-wrap">
          <ul role={sample ? undefined : 'tablist'}>
            {#each navigationItems as item, itemIndex}
              <li role={sample ? undefined : 'none'}>
                <a
                  href={`#${item.id}`}
                  id={sample ? undefined : `${id}-tab-${itemIndex}`}
                  class="gnb-main-trigger"
                  class:active={!sample && itemIndex === 0}
                  role={sample ? undefined : 'tab'}
                  aria-selected={sample ? undefined : itemIndex === 0 ? 'true' : 'false'}
                  aria-controls={sample ? undefined : item.id}
                >{labelOf(item)}</a>
              </li>
            {/each}
          </ul>
        </div>
        <div class="submenu-wrap">
          {#each navigationItems as item, itemIndex}
            <div
              class="gnb-sub-list"
              id={item.id}
              role={sample ? undefined : 'tabpanel'}
              aria-labelledby={sample ? undefined : `${id}-tab-${itemIndex}`}
            >
              <h2 class="sub-title">{labelOf(item)}</h2>
              <ul>
                {#each childrenOf(item) as child, childIndex}
                  <li>
                    <a
                      href={hrefOf(child)}
                      class="gnb-sub-trigger"
                      class:has-depth3={childrenOf(child).length > 0}
                      aria-expanded={!sample && childrenOf(child).length > 0 ? 'false' : undefined}
                      aria-controls={!sample && childrenOf(child).length > 0 ? `${id}-depth3-${itemIndex}-${childIndex}` : undefined}
                    >{labelOf(child)}</a>
                    {#if childrenOf(child).length}
                      <div class="depth3-wrap" id={!sample ? `${id}-depth3-${itemIndex}-${childIndex}` : undefined}>
                        <ul>
                          {#each childrenOf(child) as depthThree}
                            <li>
                              <a
                                href={hrefOf(depthThree)}
                                class="depth3-trigger"
                                class:has-depth4={childrenOf(depthThree).length > 0}
                              >{labelOf(depthThree)}</a>
                              {#if childrenOf(depthThree).length}
                                <div class="depth4-wrap">
                                  <div class="depth4-head">
                                    <button type="button" class="krds-btn icon trigger-prev">
                                      <span class="sr-only">{previousLabel}</span>
                                      <i class="svg-icon ico-angle left"></i>
                                    </button>
                                    <button type="button" class="krds-btn icon trigger-close">
                                      <span class="sr-only">{closeLabel}</span>
                                      <i class="svg-icon ico-popup-close"></i>
                                    </button>
                                  </div>
                                  <ul class="depth4-body">
                                    <h4 class="sub-title">{fieldOf(depthThree, 'title')}</h4>
                                    <ul class="depth4-ul">
                                      {#each childrenOf(depthThree) as depthFour}
                                        <li><a href={hrefOf(depthFour)}>{labelOf(depthFour)}</a></li>
                                      {/each}
                                    </ul>
                                  </ul>
                                </div>
                              {/if}
                            </li>
                          {/each}
                        </ul>
                      </div>
                    {/if}
                  </li>
                {/each}
              </ul>
            </div>
          {/each}
        </div>
      </div>
      <div class="gnb-bottom">
        {#each bottomItems as item}
          <a
            href={hrefOf(item)}
            class="krds-btn small text"
            target={fieldOf(item, 'target') || undefined}
            title={fieldOf(item, 'title') || undefined}
          >
            {labelOf(item)}
            <i class={`svg-icon ${fieldOf(item, 'target') ? 'ico-go' : 'ico-angle right'}`}></i>
          </a>
        {/each}
      </div>
    </div>
    <button
      type="button"
      class="krds-btn medium icon"
      id={sample ? 'close-nav' : `${id}-close`}
      onclick={sample ? undefined : toggleOpen}
    >
      <span class="sr-only">{closeLabel}</span>
      <i class="svg-icon ico-popup-close"></i>
    </button>
  </div>
</div>

// packages/angular/src/components/main-menu-mobile.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId, type AngularNavItem } from "../kinds";

@Component({
  selector: "krds-main-menu-mobile",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      id="mobile-nav"
      class="krds-main-menu-mobile sample"
      role="navigation"
      [attr.aria-label]="menuLabel || '전체 메뉴'"
      [style]="style"
    >
      <div class="gnb-wrap">
        <div class="gnb-header">
          <div class="gnb-utils">
            <ul class="utility-list">
              @for (item of utilityItems; track item.id) {
                <li>
                  <button type="button" class="krds-btn xsmall text">{{ item.label }}</button>
                </li>
              }
            </ul>
          </div>
          <div class="gnb-login">
            <button type="button" class="krds-btn large text">
              <i class="svg-icon ico-log"></i> {{ loginLabel }}
            </button>
          </div>
          <div class="gnb-service-menu">
            @for (item of serviceItems; track item.id) {
              <a [href]="item.href || '#'" class="link">{{ item.label }}</a>
            }
          </div>
          <div class="sch-input">
            <input
              type="text"
              class="krds-input"
              [placeholder]="searchPlaceholder"
              [attr.title]="searchTitle"
              [attr.aria-label]="searchLabel || searchTitle || null"
            />
            <button type="button" class="krds-btn medium icon ico-search">
              <span class="sr-only">{{ searchLabel }}</span>
              <i class="svg-icon ico-sch"></i>
            </button>
          </div>
        </div>
        <div class="gnb-body">
          <div class="gnb-menu">
            <div class="menu-wrap">
              <ul>
                @for (item of items; track item.id) {
                  <li>
                    <a [href]="item.href || '#'" class="gnb-main-trigger">{{ item.label }}</a>
                  </li>
                }
              </ul>
            </div>
            <div class="submenu-wrap">
              @for (item of items; track item.id) {
                <div class="gnb-sub-list" [id]="mobileMenuId(item)">
                  <h2 class="sub-title">{{ item.label }}</h2>
                  <ul>
                    @for (child of item.children || []; track child.id) {
                      <li>
                        <a
                          [href]="child.href || '#'"
                          class="gnb-sub-trigger"
                          [class.has-depth3]="!!child.children?.length"
                        >
                          {{ child.label }}
                        </a>
                        @if (child.children?.length) {
                          <div class="depth3-wrap">
                            <ul>
                              @for (depth3 of child.children || []; track depth3.id) {
                                <li>
                                  <a
                                    [href]="depth3.href || '#'"
                                    class="depth3-trigger"
                                    [class.has-depth4]="!!depth3.children?.length"
                                  >
                                    {{ depth3.label }}
                                  </a>
                                  @if (depth3.children?.length) {
                                    <div class="depth4-wrap">
                                      <div class="depth4-head">
                                        <button type="button" class="krds-btn icon trigger-prev">
                                          <span class="sr-only">{{ previousLabel }}</span>
                                          <i class="svg-icon ico-angle left"></i>
                                        </button>
                                        <button type="button" class="krds-btn icon trigger-close">
                                          <span class="sr-only">{{ closeLabel }}</span>
                                          <i class="svg-icon ico-popup-close"></i>
                                        </button>
                                      </div>
                                      <ul class="depth4-body">
                                        <h4 class="sub-title">{{ depth3.title }}</h4>
                                        <ul class="depth4-ul">
                                          @for (depth4 of depth3.children || []; track depth4.id) {
                                            <li>
                                              <a [href]="depth4.href || '#'">{{ depth4.label }}</a>
                                            </li>
                                          }
                                        </ul>
                                      </ul>
                                    </div>
                                  }
                                </li>
                              }
                            </ul>
                          </div>
                        }
                      </li>
                    }
                  </ul>
                </div>
              }
            </div>
          </div>
          <div class="gnb-bottom">
            @for (item of bottomItems; track $index) {
              <a
                [href]="item.href || '#'"
                class="krds-btn small text"
                [attr.target]="item.target || null"
                [attr.title]="item.title || null"
              >
                {{ item.label }}
                <i [class]="'svg-icon ' + (item.target ? 'ico-go' : 'ico-angle right')"></i>
              </a>
            }
          </div>
        </div>
        <button type="button" class="krds-btn medium icon" id="close-nav">
          <span class="sr-only">{{ closeLabel }}</span>
          <i class="svg-icon ico-popup-close"></i>
        </button>
      </div>
    </div>
  `,
})
export class KrdsMainMenuMobileComponent {
  @Input() id = createStableId("krds-main-menu-mobile");
  @Input() loginLabel = "";
  @Input() searchPlaceholder = "";
  @Input() searchTitle = "";
  @Input() searchLabel = "";
  @Input() previousLabel = "";
  @Input() closeLabel = "";
  @Input() utilityItems: Array<{ id: string; label: string }> = [];
  @Input() serviceItems: AngularNavItem[] = [];
  @Input() items: AngularNavItem[] = [];
  @Input() bottomItems: AngularNavItem[] = [];
  @Input() menuLabel = "";
  @Input() style = "display: block; position: static; visibility: visible;";

  mobileMenuId(item: AngularNavItem): string {
    return item.href?.startsWith("#") ? item.href.slice(1) : (item.id ?? "");
  }
}
