// packages/svelte/src/Search.svelte
<script lang="ts">
  type Props = {
    size?: 'xlarge' | 'large' | 'medium';
    placeholder?: string;
    onsearch?: (value: string) => void;
    buttonLabel?: string;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    size = 'large',
    placeholder = '검색어를 입력해 주세요',
    onsearch,
    buttonLabel = '검색',
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  let value = $state('');

  const submit = () => onsearch?.(value);

  const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Enter') submit();
  };
</script>

<div {...rest} class={`krds-search ${size} ${rootClass}`}>
  <div class="search-input-wrap">
    <input
      type="search"
      class="krds-input"
      {placeholder}
      aria-label="검색어"
      bind:value
      onkeydown={handleKeydown}
    />
  </div>
  <button type="button" class="krds-btn large primary" aria-label={buttonLabel} onclick={submit}>
    {buttonLabel}
  </button>
</div>

// packages/angular/src/components/search.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-search",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'krds-search ' + size">
      <div class="search-input-wrap">
        <input
          type="search"
          class="krds-input"
          [attr.placeholder]="placeholder"
          aria-label="검색어"
          [value]="query"
          (input)="query = $any($event.target).value"
          (keydown.enter)="submitSearch()"
        />
      </div>
      <button
        type="button"
        class="krds-btn large primary"
        [attr.aria-label]="buttonLabel"
        (click)="submitSearch()"
      >
        {{ buttonLabel }}
      </button>
    </div>
  `,
})
export class KrdsSearchComponent {
  @Input() id = createStableId("krds-search");
  @Input() size: "xlarge" | "large" | "medium" = "large";
  @Input() placeholder = "검색어를 입력해 주세요";
  @Input() buttonLabel = "검색";
  @Output() search = new EventEmitter<string>();

  query = "";

  submitSearch(): void {
    this.search.emit(this.query);
  }
}
