// packages/solid/src/components/SideNavigation.tsx
import { For, createSignal, mergeProps, splitProps } from "solid-js";
import type { KrdsNavItem } from "@krds-community/recipes";

export interface SideNavigationItem extends KrdsNavItem {
  children?: SideNavigationItem[];
  description?: string;
  current?: boolean;
}

export interface SideNavigationProps {
  class?: string;
  className?: string;
  title?: string;
  id?: string;
  nav?: KrdsNavItem[];
  links?: KrdsNavItem[];
  items?: (KrdsNavItem | string | number)[];
  selected?: string;
  defaultValue?: string;
  modelValue?: string;
  value?: string;
  [key: string]: unknown;
}

export function SideNavigation(rawProps: SideNavigationProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "id",
    "nav",
    "links",
    "items",
    "selected",
    "defaultValue",
    "modelValue",
    "value",
  ]);
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "string" || typeof mv === "number") return String(mv);
    return props.selected ?? localSelected() ?? props.defaultValue ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const className = () => props.class ?? props.className ?? "";
  const hasCurrentItem = (item: KrdsNavItem): boolean => {
    if (item.current) return true;
    return item.children?.some(hasCurrentItem) ?? false;
  };
  const navigation = () =>
    (props.nav?.length
      ? props.nav
      : props.links?.length
        ? props.links
        : (props.items ?? []).filter(
            (item): item is KrdsNavItem => typeof item !== "string" && typeof item !== "number",
          )) as KrdsNavItem[];
  return (
    <nav
      {...(native as Record<string, any>)}
      class={`krds-side-navigation${className() ? ` ${className()}` : ""}`}
    >
      <h2 class="lnb-tit">{props.title}</h2>
      <ul class="lnb-list" role="menubar">
        <For each={navigation()}>
          {(item, topIndex) => {
            const submenuId = `${props.id}-submenu-${topIndex()}`;
            const expanded = () =>
              selected() === item.id || (selected() === "" && hasCurrentItem(item));
            return item.children?.length ? (
              <li class="lnb-item" classList={{ active: expanded() }} role="none">
                <button
                  type="button"
                  class="lnb-btn lnb-toggle"
                  classList={{ active: expanded() }}
                  role="menuitem"
                  aria-controls={submenuId}
                  aria-expanded={expanded()}
                  onClick={() => setSelected(expanded() ? "" : (item.id ?? submenuId))}
                >
                  {item.label}
                </button>
                <div class="lnb-submenu">
                  <ul id={submenuId} role="menu">
                    <For each={(item as SideNavigationItem).children}>
                      {(child, childIndex) => {
                        const popupId = `${submenuId}-${childIndex()}`;
                        return (child as SideNavigationItem).children?.length ? (
                          <li class="lnb-subitem" role="none">
                            <button
                              type="button"
                              class="lnb-btn lnb-toggle-popup"
                              role="menuitem"
                              aria-controls={popupId}
                              aria-expanded="false"
                              aria-haspopup="true"
                            >
                              {child.label}
                            </button>
                            <div class="lnb-submenu-lv2" id={popupId} role="menu">
                              <button type="button" class="lnb-btn-tit">
                                {typeof child.description === "string"
                                  ? child.description
                                  : child.label}
                              </button>
                              <ul>
                                <For each={(child as SideNavigationItem).children}>
                                  {(leaf) => (
                                    <li role="none">
                                      <a href={leaf.href ?? "#"} class="lnb-btn" role="menuitem">
                                        {leaf.label}
                                      </a>
                                    </li>
                                  )}
                                </For>
                              </ul>
                            </div>
                          </li>
                        ) : (
                          <li class="lnb-subitem" classList={{ active: child.current }} role="none">
                            <a
                              href={child.href ?? "#"}
                              class="lnb-btn lnb-link"
                              role="menuitem"
                              aria-current={child.current ? "page" : undefined}
                            >
                              {child.label}
                            </a>
                          </li>
                        );
                      }}
                    </For>
                  </ul>
                </div>
              </li>
            ) : (
              <li class="lnb-item" classList={{ active: item.current }} role="none">
                <a
                  href={item.href ?? "#"}
                  class="lnb-btn lnb-link"
                  role="menuitem"
                  aria-current={item.current ? "page" : undefined}
                >
                  {item.label}
                </a>
              </li>
            );
          }}
        </For>
      </ul>
    </nav>
  );
}

// packages/angular/src/components/side-navigation.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId, type AngularNavItem } from "../kinds";

@Component({
  selector: "krds-side-navigation",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="krds-side-navigation">
      <h2 class="lnb-tit">{{ title }}</h2>
      <ul class="lnb-list" role="menubar">
        @for (item of items; track $index; let topIndex = $index) {
          <li class="lnb-item" [class.active]="$first" role="none">
            <button
              type="button"
              class="lnb-btn lnb-toggle"
              [class.active]="$first"
              role="menuitem"
              [attr.aria-controls]="sideMenuId(topIndex)"
              [attr.aria-expanded]="$first"
            >
              {{ navLabel(item) }}
            </button>
            <div class="lnb-submenu">
              <ul [id]="sideMenuId(topIndex)" role="menu">
                @for (child of itemChildren(item); track $index; let childIndex = $index) {
                  <li class="lnb-subitem" [class.active]="itemCurrent(child)" role="none">
                    @if (itemChildren(child).length > 0) {
                      <button
                        type="button"
                        class="lnb-btn lnb-toggle-popup"
                        role="menuitem"
                        [attr.aria-controls]="sidePopupId(topIndex, childIndex)"
                        aria-expanded="false"
                        aria-haspopup="true"
                      >
                        {{ navLabel(child) }}
                      </button>
                      <div
                        class="lnb-submenu-lv2"
                        [id]="sidePopupId(topIndex, childIndex)"
                        role="menu"
                      >
                        <button type="button" class="lnb-btn-tit">
                          {{ itemDescription(child) }}
                        </button>
                        <ul>
                          @for (leaf of itemChildren(child); track $index) {
                            <li role="none">
                              <a [href]="navHref(leaf)" class="lnb-btn" role="menuitem">{{
                                navLabel(leaf)
                              }}</a>
                            </li>
                          }
                        </ul>
                      </div>
                    } @else {
                      <a
                        [href]="navHref(child)"
                        class="lnb-btn lnb-link"
                        role="menuitem"
                        [attr.aria-current]="itemCurrent(child) ? 'page' : null"
                      >
                        {{ navLabel(child) }}
                      </a>
                    }
                  </li>
                }
              </ul>
            </div>
          </li>
        }
      </ul>
    </nav>
  `,
})
export class KrdsSideNavigationComponent {
  @Input() id = createStableId("krds-side-navigation");
  @Input() title = "제목";
  @Input() description = "";
  @Input() items: AngularNavItem[] = [];

  navLabel(item: unknown): string {
    if (typeof item === "string" || typeof item === "number") return String(item);
    if (!item || typeof item !== "object") return "";
    if ("label" in item) return String(item.label ?? "");
    if ("title" in item) return String(item.title ?? "");
    if ("text" in item) return String(item.text ?? "");
    if ("message" in item) return String(item.message ?? "");
    return "";
  }

  navHref(item: unknown): string {
    if (!item || typeof item !== "object" || !("href" in item)) return "#";
    return String(item.href ?? "#");
  }

  itemDescription(item: unknown): string {
    if (!item || typeof item !== "object") return this.description;
    if ("content" in item) return String(item.content ?? "");
    if ("description" in item) return String(item.description ?? "");
    return this.description;
  }

  itemChildren(item: unknown): AngularNavItem[] {
    if (!item || typeof item !== "object" || !("children" in item)) return [];
    const children = item.children;
    return Array.isArray(children) ? (children as AngularNavItem[]) : [];
  }

  itemCurrent(item: unknown): boolean {
    return Boolean(item && typeof item === "object" && "current" in item && item.current);
  }

  sideMenuId(index: number): string {
    return `${this.id}-side-${index}`;
  }

  sidePopupId(topIndex: number, childIndex: number): string {
    return `${this.id}-side-${topIndex}-${childIndex}`;
  }
}
