// packages/react/src/components/Snackbar.tsx
import { useEffect, useState, type ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import { SvgIcon, type BoxProps } from "./_utils.js";

const CLOSE_ANIMATION_MS = 200;

export interface SnackbarProps extends BoxProps {
  title?: ReactNode;
  message: ReactNode;
  icon?: string;
  actionLabel?: ReactNode;
  onAction?: () => void;
  closeLabel?: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function Snackbar({
  title,
  message,
  icon,
  actionLabel,
  onAction,
  closeLabel = "닫기",
  open: controlledOpen,
  defaultOpen = false,
  onOpenChange,
  className,
}: SnackbarProps) {
  const controlled = controlledOpen !== undefined;
  const [rendered, setRendered] = useState(
    controlled ? controlledOpen === true : defaultOpen === true,
  );
  const [closing, setClosing] = useState(false);

  const close = () => {
    if (controlled) onOpenChange?.(false);
    else setClosing(true);
  };

  useEffect(() => {
    if (controlledOpen === true) {
      setClosing(false);
      setRendered(true);
      return;
    }
    if (!rendered) return;
    if (controlledOpen === false) {
      setClosing(true);
      const timer = setTimeout(() => {
        setRendered(false);
        setClosing(false);
      }, CLOSE_ANIMATION_MS);
      return () => clearTimeout(timer);
    }
  }, [controlledOpen, rendered]);

  useEffect(() => {
    if (!closing || !rendered || controlled) return;
    const timer = setTimeout(() => {
      setRendered(false);
      setClosing(false);
      onOpenChange?.(false);
    }, CLOSE_ANIMATION_MS);
    return () => clearTimeout(timer);
  }, [closing, rendered, controlled, onOpenChange]);

  if (!rendered) return null;
  return (
    <div className={cx("krds-snackbar", className, closing && "closing")} role="alert">
      {icon ? <i className={cx("svg-icon snackbar-icon", icon)} aria-hidden="true" /> : null}
      <div className="snackbar-conts">
        {title ? <strong className="snackbar-title">{title}</strong> : null}
        <p className="snackbar-text">{message}</p>
      </div>
      {actionLabel ? (
        <button type="button" className="krds-btn small text snackbar-action" onClick={onAction}>
          {actionLabel}
        </button>
      ) : null}
      <button
        type="button"
        className="krds-btn small icon snackbar-close"
        aria-label={closeLabel ?? "닫기"}
        onClick={close}
      >
        <SvgIcon name="ico-modal-close" />
      </button>
    </div>
  );
}

// packages/angular/src/components/snackbar.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  inject,
  Input,
  Output,
  type OnChanges,
  type OnDestroy,
  type OnInit,
  type SimpleChanges,
} from "@angular/core";
import { createStableId } from "../kinds";

const CLOSE_ANIMATION_MS = 200;

@Component({
  selector: "krds-snackbar",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (rendered) {
      <div [class]="'krds-snackbar' + (closing ? ' closing' : '')" role="alert">
        @if (icon) {
          <i class="svg-icon snackbar-icon {{ icon }}" aria-hidden="true"></i>
        }
        <div class="snackbar-conts">
          @if (title) {
            <strong class="snackbar-title">{{ title }}</strong>
          }
          <p class="snackbar-text">{{ message }}</p>
        </div>
        @if (actionLabel) {
          <button type="button" class="krds-btn small text snackbar-action" (click)="emitAction()">
            {{ actionLabel }}
          </button>
        }
        <button
          type="button"
          class="krds-btn small icon snackbar-close"
          [attr.aria-label]="closeLabel"
          (click)="close()"
        >
          <i class="svg-icon ico-modal-close"></i>
        </button>
      </div>
    }
  `,
})
export class KrdsSnackbarComponent implements OnInit, OnChanges, OnDestroy {
  @Input() id = createStableId("krds-snackbar");
  @Input() title = "";
  @Input() message = "";
  @Input() icon = "";
  @Input() actionLabel = "";
  @Input() closeLabel = "닫기";
  @Input() open: boolean | undefined = undefined;
  @Input() defaultOpen = false;
  @Output() openChange = new EventEmitter<boolean>();
  @Output() action = new EventEmitter<void>();

  rendered = false;
  closing = false;
  private closeTimer: number | null = null;
  private readonly changeDetector = inject(ChangeDetectorRef);

  get isControlled(): boolean {
    return this.open !== undefined;
  }

  ngOnInit(): void {
    if (this.isControlled ? this.open === true : this.defaultOpen) {
      this.rendered = true;
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!("open" in changes)) return;
    if (this.open === true) {
      this.closing = false;
      this.rendered = true;
      this.clearCloseTimer();
    } else if (this.open === false && this.rendered) {
      this.beginClose();
    }
  }

  ngOnDestroy(): void {
    this.clearCloseTimer();
  }

  close(): void {
    if (this.isControlled) {
      this.openChange.emit(false);
    } else {
      this.beginClose();
    }
  }

  emitAction(): void {
    this.action.emit();
  }

  private beginClose(): void {
    if (typeof window === "undefined") return;
    if (!this.rendered || this.closing) return;
    this.closing = true;
    this.clearCloseTimer();
    this.closeTimer = window.setTimeout(() => {
      this.closeTimer = null;
      this.rendered = false;
      this.closing = false;
      if (!this.isControlled) {
        this.openChange.emit(false);
      }
      this.changeDetector.markForCheck();
    }, CLOSE_ANIMATION_MS);
    this.changeDetector.markForCheck();
  }

  private clearCloseTimer(): void {
    if (this.closeTimer !== null) {
      window.clearTimeout(this.closeTimer);
      this.closeTimer = null;
    }
  }
}
