// packages/react/src/components/Spinner.tsx
import { useId, type HTMLAttributes, type Ref } from "react";
import { cx } from "@krds-community/recipes";

export function Spinner({
  label = "처리 중",
  inputLabel = "Label",
  placeholder = "placeholder",
  className,
  ref,
  ...props
}: HTMLAttributes<HTMLDivElement> & {
  label?: string;
  inputLabel?: string;
  placeholder?: string;
} & { ref?: Ref<HTMLDivElement> }) {
  const inputId = `krds-spinner-input-${useId()}`;
  return (
    <div className="form-group">
      <div className="form-tit">
        <label htmlFor={inputId}>{inputLabel}</label>
      </div>
      <div className="form-conts">
        <div className="form-spinner">
          <input type="text" id={inputId} className="krds-input" placeholder={placeholder} />
          <div {...props} ref={ref} className={cx("krds-spinner", className)} role="status">
            <span className="sr-only">{label}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/angular/src/components/spinner.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-spinner",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="form-group">
      <div class="form-tit">
        <label [for]="id + '-input'">{{ inputLabel }}</label>
      </div>
      <div class="form-conts">
        <div class="form-spinner">
          <input type="text" [id]="id + '-input'" class="krds-input" placeholder="placeholder" />
          <div class="krds-spinner" role="status">
            <span class="sr-only">{{ label }}</span>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class KrdsSpinnerComponent {
  @Input() id = createStableId("krds-spinner");
  @Input() label = "레이블";
  @Input() inputLabel = "Label";
}
