// packages/solid/src/components/StructuredList.tsx
import { For, Show, mergeProps, splitProps } from "solid-js";
import { labelOf, type StructuredItem } from "../shared.js";

export interface StructuredListProps {
  class?: string;
  className?: string;
  items?: (StructuredItem | string | number)[];
  dateLabel?: string;
  dateValue?: string;
  actionLabel?: string;
  shareLabel?: string;
  favoriteLabel?: string;
  tags?: string[];
  [key: string]: unknown;
}

export function StructuredList(rawProps: StructuredListProps) {
  const merged = mergeProps({}, rawProps);
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "items",
    "dateLabel",
    "dateValue",
    "actionLabel",
    "shareLabel",
    "favoriteLabel",
    "tags",
  ]);
  const className = () => props.class ?? props.className ?? "";
  return (
    <ul
      {...(native as Record<string, any>)}
      class={["krds-structured-list", "type-full", className()].filter(Boolean).join(" ")}
    >
      <For each={props.items ?? []}>
        {(item) => {
          const structured =
            typeof item === "string" || typeof item === "number"
              ? undefined
              : (item as StructuredItem);
          return (
            <li class="structured-item">
              <div class="in">
                <Show when={structured?.badge}>
                  <div class="card-top">
                    <span class={["krds-badge", structured?.badgeClass].filter(Boolean).join(" ")}>
                      {structured?.badge}
                    </span>
                  </div>
                </Show>
                <div class="card-body">
                  <a class="c-text" href={structured?.href ?? "#"}>
                    <p class="c-tit">
                      <span class="span">{labelOf(item)}</span>
                    </p>
                    <Show when={structured?.description}>
                      <p class="c-txt">{structured?.description}</p>
                    </Show>
                    <p class="c-date">
                      <strong class="key">{structured?.dateLabel ?? props.dateLabel}</strong>
                      <span class="value">{structured?.dateValue ?? props.dateValue}</span>
                    </p>
                  </a>
                  <div class="c-btn">
                    <a
                      class="krds-btn secondary"
                      href={structured?.href ?? "#"}
                      title={labelOf(item)}
                    >
                      {structured?.actionLabel ?? props.actionLabel}
                    </a>
                  </div>
                </div>
                <div class="card-btm">
                  <For each={structured?.tags ?? props.tags ?? []}>
                    {(tag) => <span class="tag">{tag}</span>}
                  </For>
                </div>
                <div class="card-btn">
                  <button type="button" class="krds-btn medium text" title={labelOf(item)}>
                    <i class="svg-icon ico-share" />
                    {(structured?.shareLabel ?? props.shareLabel) ? " " + (structured?.shareLabel ?? props.shareLabel) : null}
                  </button>
                  <button type="button" class="krds-btn medium text" title={labelOf(item)}>
                    <i class="svg-icon ico-like" />
                    {(structured?.favoriteLabel ?? props.favoriteLabel) ? " " + (structured?.favoriteLabel ?? props.favoriteLabel) : null}
                  </button>
                </div>
              </div>
            </li>
          );
        }}
      </For>
    </ul>
  );
}

// packages/angular/src/components/structured-list.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-structured-list",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ul class="krds-structured-list type-full">
      @for (item of items; track $index) {
        <li class="structured-item">
          <div class="in">
            <div class="card-top">
              <span [class]="'krds-badge ' + structuredBadgeTone(item)">
                {{ itemBadge(item) }}
              </span>
            </div>
            <div class="card-body">
              <a [href]="navHref(item)" class="c-text">
                <p class="c-tit">
                  <span class="span">{{ navLabel(item) }}</span>
                </p>
                <p class="c-txt">{{ itemDescription(item) }}</p>
                <p class="c-date">
                  <strong class="key">{{ dateLabel }}</strong>
                  <span class="value">{{ dateValue }}</span>
                </p>
              </a>
              <div class="c-btn">
                <a [href]="navHref(item)" class="krds-btn secondary" [attr.title]="navLabel(item)">
                  {{ actionLabel }}
                </a>
              </div>
            </div>
            <div class="card-btm">
              @for (tag of tags; track $index) {
                <span class="tag">{{ tag }}</span>
              }
            </div>
            <div class="card-btn">
              <button type="button" class="krds-btn medium text" [attr.title]="navLabel(item)">
                <i class="svg-icon ico-share"></i> {{ shareLabel }}
              </button>
              <button type="button" class="krds-btn medium text" [attr.title]="navLabel(item)">
                <i class="svg-icon ico-like"></i> {{ favoriteLabel }}
              </button>
            </div>
          </div>
        </li>
      }
    </ul>
  `,
})
export class KrdsStructuredListComponent {
  @Input() id = createStableId("krds-structured-list");
  @Input() description = "";
  @Input() dateLabel = "";
  @Input() dateValue = "";
  @Input() actionLabel = "";
  @Input() shareLabel = "";
  @Input() favoriteLabel = "";
  @Input() tags: string[] = [];
  @Input() items: unknown[] = [];

  navLabel(item: unknown): string {
    if (typeof item === "string" || typeof item === "number") return String(item);
    if (!item || typeof item !== "object") return "";
    if ("label" in item) return String(item.label ?? "");
    if ("title" in item) return String(item.title ?? "");
    if ("text" in item) return String(item.text ?? "");
    if ("message" in item) return String(item.message ?? "");
    return "";
  }

  navHref(item: unknown): string {
    if (!item || typeof item !== "object" || !("href" in item)) return "#";
    return String(item.href ?? "#");
  }

  itemDescription(item: unknown): string {
    if (!item || typeof item !== "object") return this.description;
    if ("content" in item) return String(item.content ?? "");
    if ("description" in item) return String(item.description ?? "");
    return this.description;
  }

  structuredBadgeTone(item: unknown): string {
    if (!item || typeof item !== "object") return "bg-light-primary";
    if ("badgeTone" in item) return String(item.badgeTone ?? "bg-light-primary");
    if ("badgeClass" in item) return String(item.badgeClass ?? "bg-light-primary");
    if ("tone" in item) return String(item.tone ?? "bg-light-primary");
    return "bg-light-primary";
  }

  itemBadge(item: unknown): string {
    if (!item || typeof item !== "object" || !("badge" in item)) return "";
    return String(item.badge ?? "");
  }
}
