// packages/solid/src/components/Tab.tsx
import { For, Show, createSignal, mergeProps, splitProps } from "solid-js";
import { tabRecipe } from "@krds-community/recipes";
import type { KrdsTabItem } from "@krds-community/recipes";

export interface TabItem extends KrdsTabItem {}
export interface TabProps {
  class?: string;
  className?: string;
  tabs?: KrdsTabItem[];
  panels?: Record<string, string>;
  panelTitle?: string;
  message?: string;
  selected?: string;
  defaultValue?: string;
  modelValue?: string;
  value?: string;
  [key: string]: unknown;
}

export function Tab(rawProps: TabProps) {
  const merged = mergeProps(
    { tabs: [] as KrdsTabItem[], panels: {} as Record<string, string> },
    rawProps,
  );
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "tabs",
    "panels",
    "panelTitle",
    "message",
    "selected",
    "defaultValue",
    "modelValue",
    "value",
  ]);
  const [localSelected, setLocalSelected] = createSignal<string>();
  const selected = () => {
    const mv = props.modelValue;
    if (typeof mv === "string" || typeof mv === "number") return String(mv);
    return props.selected ?? localSelected() ?? props.defaultValue ?? props.tabs[0]?.id ?? "";
  };
  const setSelected = (next: string) => {
    if (props.modelValue === undefined) setLocalSelected(next);
  };
  const tabClasses = (active?: boolean) => tabRecipe({ full: true, active });
  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={[tabClasses().root, className()].filter(Boolean).join(" ")}
    >
      <div class={tabClasses().listContainer}>
        <ul role="tablist">
          <For each={props.tabs}>
            {(tab) => {
              const active = () => selected() === tab.id;
              const tabId = `tab-${tab.id}`;
              const panelId = `panel-${tab.id}`;
              return (
                <li role="presentation" class={tabClasses(active()).item}>
                  <button
                    id={tabId}
                    type="button"
                    class={tabClasses().trigger}
                    role="tab"
                    tabIndex={active() ? 0 : -1}
                    disabled={tab.disabled}
                    aria-selected={active()}
                    aria-controls={panelId}
                    onClick={(event) => {
                      setSelected(tab.id);
                      (native as Record<string, any>).onChange?.(event);
                    }}
                  >
                    {tab.label}
                    <Show when={active() && props.message}>
                      <i class="sr-only created"> {props.message}</i>
                    </Show>
                  </button>
                </li>
              );
            }}
          </For>
        </ul>
      </div>
      <div class="tab-conts-wrap">
        <For each={props.tabs}>
          {(tab) => {
            const active = () => selected() === tab.id;
            return (
              <Show when={props.panels[tab.id] !== undefined}>
                <section
                  id={`panel-${tab.id}`}
                  role="tabpanel"
                  aria-labelledby={`tab-${tab.id}`}
                  class="tab-conts"
                  data-quick-nav="false"
                  classList={{ active: active() }}
                  hidden={!active()}
                >
                  <Show when={props.panelTitle}>
                    <h3 class="sr-only">{props.panelTitle}</h3>
                  </Show>
                  {props.panels[tab.id]}
                </section>
              </Show>
            );
          }}
        </For>
      </div>
    </div>
  );
}

// packages/angular/src/components/tab.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { tabRecipe } from "@krds-community/recipes";
import { createStableId } from "../kinds";
import type { KrdsTabItem } from "@krds-community/recipes";

@Component({
  selector: "krds-tab",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="tabClasses.root">
      <div [class]="tabClasses.listContainer">
        <ul role="tablist">
          @for (tab of tabs; track tab.id) {
            <li role="presentation" [attr.class]="tabItemClass(tab)">
              <button
                [id]="'tab_' + tab.id"
                type="button"
                [class]="tabClasses.trigger"
                role="tab"
                [attr.aria-selected]="(selected || tabs[0]?.id) === tab.id"
                [attr.aria-controls]="'panel_' + tab.id"
                [attr.tabindex]="(selected || tabs[0]?.id) === tab.id ? '0' : '-1'"
                (click)="setSelected(tab.id)"
              >
                {{ tab.label }}
                @if ((selected || tabs[0]?.id) === tab.id) {
                  <i class="sr-only created"> {{ selectedLabel || message }}</i>
                }
              </button>
            </li>
          }
        </ul>
      </div>
      <div class="tab-conts-wrap">
        @for (tab of tabs; track tab.id) {
          <section
            [id]="'panel_' + tab.id"
            [attr.aria-labelledby]="'tab_' + tab.id"
            class="tab-conts"
            [class.active]="(selected || tabs[0]?.id) === tab.id"
            [hidden]="(selected || tabs[0]?.id) !== tab.id"
            role="tabpanel"
            data-quick-nav="false"
          >
            @if (panelTitle) {
              <h3 class="sr-only">{{ panelTitle }}</h3>
            }
            {{ panels[tab.id] || "" }}
          </section>
        }
      </div>
      <span data-testid="selected-tab" class="sr-only">{{ selected }}</span>
    </div>
  `,
})
export class KrdsTabComponent {
  @Input() id = createStableId("krds-tab");
  @Input() selected = "";
  @Input() selectedLabel = "";
  @Input() message = "도움말";
  @Input() panelTitle = "";
  @Input() tabs: Array<KrdsTabItem> = [];
  @Input() panels: Record<string, string> = {};
  @Output() selectedChange = new EventEmitter<string>();

  get tabClasses() {
    return tabRecipe({ full: true });
  }

  tabItemClass(tab: KrdsTabItem): string | undefined {
    return tabRecipe({ active: (this.selected || this.tabs[0]?.id) === tab.id }).item;
  }

  setSelected(id: string): void {
    this.selected = id;
    this.selectedChange.emit(id);
  }
}
