// packages/react/src/components/Tag.tsx
import type { ReactNode } from "react";
import { cx } from "@krds-community/recipes";
import type { KrdsTone } from "@krds-community/recipes";
import { toneClass } from "./_utils.js";

export function Tag({
  label,
  tone,
  removable = true,
  onRemove,
  className,
}: {
  label: ReactNode;
  tone?: KrdsTone;
  removable?: boolean;
  onRemove?: () => void;
  className?: string;
}) {
  return (
    <div className="krds-tag-wrap large">
      <span className={cx("krds-btn-tag", tone && `bg-${toneClass[tone]}`, className)}>
        {label}
        {removable ? (
          <button type="button" className="btn-delete" onClick={onRemove}>
            <span className="sr-only">삭제</span>
          </button>
        ) : null}
      </span>
    </div>
  );
}

// packages/angular/src/components/tag.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-tag",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-tag-wrap large">
      <span class="krds-btn-tag">
        {{ label }}
        <button type="button" class="btn-delete">
          <span class="sr-only">{{ message }}</span>
        </button>
      </span>
    </div>
  `,
})
export class KrdsTagComponent {
  @Input() id = createStableId("krds-tag");
  @Input() label = "레이블";
  @Input() message = "삭제";
}

@Component({
  selector: "krds-tag-link",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-tag-wrap large">
      <a class="krds-btn-tag link" [href]="href">{{ label }}</a>
    </div>
  `,
})
export class KrdsTagLinkComponent {
  @Input() id = createStableId("krds-tag-link");
  @Input() label = "레이블";
  @Input() href = "#";
}
