// packages/svelte/src/Toast.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  const CLOSE_ANIMATION_MS = 200;

  type Props = {
    message: string;
    tone?: 'information' | 'warning';
    open?: boolean;
    defaultOpen?: boolean;
    duration?: number;
    onopenchange?: (open: boolean) => void;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    message,
    tone = 'information',
    open = $bindable<boolean | undefined>(),
    defaultOpen = false,
    duration,
    onopenchange,
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
  const controlled = $derived(open !== undefined);

  let rendered = $state(open === true || (open === undefined && defaultOpen === true));
  let closing = $state(false);
  let wasOpen = false;
  let closeTimer: ReturnType<typeof setTimeout> | undefined;
  let removeTimer: ReturnType<typeof setTimeout> | undefined;

  const startClose = () => {
    if (!rendered || closing) return;
    closing = true;
    removeTimer = setTimeout(() => {
      rendered = false;
      closing = false;
      onopenchange?.(false);
    }, CLOSE_ANIMATION_MS);
  };

  $effect(() => {
    const isOpen = controlled ? open === true : rendered;
    if (isOpen && !wasOpen) {
      if (removeTimer) clearTimeout(removeTimer);
      closing = false;
      rendered = true;
      closeTimer = setTimeout(
        () => {
          if (controlled) {
            onopenchange?.(false);
          } else {
            startClose();
          }
        },
        duration ?? (tone === 'warning' ? 4000 : 3000),
      );
    } else if (!isOpen && wasOpen) {
      if (closeTimer) clearTimeout(closeTimer);
      startClose();
    }
    wasOpen = isOpen;
  });

  onDestroy(() => {
    if (closeTimer) clearTimeout(closeTimer);
    if (removeTimer) clearTimeout(removeTimer);
  });
</script>

{#if rendered}
  <div
    {...rest}
    class={`krds-toast ${rootClass}`}
    class:closing={closing}
    role={tone === 'warning' ? 'alert' : 'status'}
  >
    <p class="toast-text">{message}</p>
  </div>
{/if}

// packages/angular/src/components/toast.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  inject,
  Input,
  Output,
  type OnChanges,
  type OnDestroy,
  type OnInit,
  type SimpleChanges,
} from "@angular/core";
import { createStableId } from "../kinds";

const CLOSE_ANIMATION_MS = 200;

@Component({
  selector: "krds-toast",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (rendered) {
      <div
        [class]="'krds-toast' + (closing ? ' closing' : '')"
        [attr.role]="tone === 'warning' ? 'alert' : 'status'"
      >
        <p class="toast-text">{{ message }}</p>
      </div>
    }
  `,
})
export class KrdsToastComponent implements OnInit, OnChanges, OnDestroy {
  @Input() id = createStableId("krds-toast");
  @Input() message = "";
  @Input() tone: "information" | "warning" = "information";
  @Input() open: boolean | undefined = undefined;
  @Input() defaultOpen = false;
  @Input() duration: number | undefined = undefined;
  @Output() openChange = new EventEmitter<boolean>();

  rendered = false;
  closing = false;
  private openTimer: number | null = null;
  private closeTimer: number | null = null;
  private readonly changeDetector = inject(ChangeDetectorRef);

  get isControlled(): boolean {
    return this.open !== undefined;
  }

  ngOnInit(): void {
    if (this.isControlled ? this.open === true : this.defaultOpen) {
      this.rendered = true;
      this.scheduleAutoClose();
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!("open" in changes)) return;
    if (this.open === true) {
      this.closing = false;
      this.rendered = true;
      this.clearCloseTimer();
      this.scheduleAutoClose();
    } else if (this.open === false && this.rendered) {
      this.beginClose();
    }
  }

  ngOnDestroy(): void {
    this.clearTimers();
  }

  private scheduleAutoClose(): void {
    if (typeof window === "undefined") return;
    if (this.openTimer !== null) {
      window.clearTimeout(this.openTimer);
    }
    const delay = this.duration ?? (this.tone === "warning" ? 4000 : 3000);
    this.openTimer = window.setTimeout(() => {
      this.openTimer = null;
      if (this.isControlled) {
        this.openChange.emit(false);
      } else {
        this.beginClose();
      }
    }, delay);
  }

  private beginClose(): void {
    if (typeof window === "undefined") return;
    if (!this.rendered || this.closing) return;
    this.closing = true;
    this.clearTimers();
    this.closeTimer = window.setTimeout(() => {
      this.closeTimer = null;
      this.rendered = false;
      this.closing = false;
      if (!this.isControlled) {
        this.openChange.emit(false);
      }
      this.changeDetector.markForCheck();
    }, CLOSE_ANIMATION_MS);
    this.changeDetector.markForCheck();
  }

  private clearCloseTimer(): void {
    if (this.closeTimer !== null) {
      window.clearTimeout(this.closeTimer);
      this.closeTimer = null;
    }
  }

  private clearTimers(): void {
    if (this.openTimer !== null) {
      window.clearTimeout(this.openTimer);
      this.openTimer = null;
    }
    this.clearCloseTimer();
  }
}
