// packages/svelte/src/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  type Props = {
    id?: string;
    label?: string;
    message?: string;
    kind?: 'horizontal' | 'box' | 'vertical' | string;
    open?: boolean;
    onclick?: (event: Event) => void;
    class?: string;
    className?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
  const generatedId = $props.id();
  let {
    id = generatedId,
    label = '레이블',
    message = '도움말',
    kind = 'horizontal',
    open = $bindable<boolean | undefined>(),
    onclick,
    class: classProp = '',
    className = '',
    children,
    ...rest
  }: Props = $props();
  const rootClass = $derived(`${classProp} ${className}`.trim());
  const isOpen = $derived(open ?? false);
  const placementClass = $derived(kind === 'box' ? 'tooltip-box' : kind === 'vertical' ? 'tooltip-vertical' : '');
  const toggleOpen = (event?: Event) => {
    open = !isOpen;
    if (event && onclick) onclick(event);
  };
</script>

<button
  {...rest}
  type="button"
  class={`krds-btn krds-tooltip small text ${placementClass} ${rootClass}`.trim()}
  data-tooltip={message}
  aria-labelledby={`${id}-tip`}
  onclick={() => toggleOpen()}
>
  {#if children}{@render children()}{:else}{label}{/if}{' '}<i class="ico-angle right svg-icon"></i>
</button>
<div id={`${id}-tip`} class={`krds-tooltip-popover ${placementClass}`.trim()} role="tooltip" aria-hidden={isOpen ? 'false' : 'true'} hidden={!isOpen}>
  <span class="sr-only">{label}</span>
  {message}
</div>

// packages/angular/src/components/tooltip.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-tooltip, krds-tooltip-box, krds-tooltip-vertical",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      [class]="tooltipClass"
      [attr.data-tooltip]="message"
      [attr.aria-labelledby]="tooltipPopoverId"
    >
      {{ label + " " }}<i class="svg-icon ico-angle right"></i>
    </button>
    <div [id]="tooltipPopoverId" class="krds-tooltip-popover" role="tooltip" aria-hidden="true">
      <span class="sr-only">{{ label }}</span>
      {{ message }}
    </div>
  `,
})
export class KrdsTooltipComponent {
  @Input() id = createStableId("krds-tooltip");
  @Input() label = "레이블";
  @Input() message = "도움말";
  @Input() kind: "tooltip" | "tooltip-box" | "tooltip-vertical" = "tooltip";

  get tooltipClass(): string {
    const variation =
      this.kind === "tooltip-box"
        ? " tooltip-box"
        : this.kind === "tooltip-vertical"
          ? " tooltip-vertical"
          : "";
    return `krds-btn small text krds-tooltip${variation}`;
  }

  get tooltipPopoverId(): string {
    return `${this.id}-tooltip`;
  }
}
export {
  KrdsTooltipComponent as KrdsTooltipBoxComponent,
  KrdsTooltipComponent as KrdsTooltipVerticalComponent,
};
