// packages/svelte/src/TopButton.svelte
<script lang="ts">
  type Props = {
    type?: 'basic' | 'label';
    onclick?: () => void;
    ariaLabel?: string;
    label?: string;
    class?: string;
    className?: string;
    [key: string]: unknown;
  };

  let {
    type = 'basic',
    onclick,
    ariaLabel = '맨 위로',
    label = 'TOP',
    class: classProp = '',
    className = '',
    ...rest
  }: Props = $props();

  const rootClass = $derived(`${classProp} ${className}`.trim());
</script>

<div {...rest} class={`krds-top-button ${rootClass}`}>
  <button type="button" class="krds-btn medium icon" aria-label={ariaLabel} onclick={onclick}>
    <i class="svg-icon ico-go-top"></i>
    {#if type === 'label'}
      <span class="top-button-label">{label}</span>
    {/if}
  </button>
</div>

// packages/angular/src/components/top-button.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId } from "../kinds";

@Component({
  selector: "krds-top-button",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-top-button">
      <button
        type="button"
        class="krds-btn medium icon"
        [attr.aria-label]="ariaLabel"
        (click)="topClick.emit()"
      >
        <i class="svg-icon ico-go-top"></i>
        @if (type === "label") {
          <span>{{ label }}</span>
        }
      </button>
    </div>
  `,
})
export class KrdsTopButtonComponent {
  @Input() id = createStableId("krds-top-button");
  @Input() type: "basic" | "label" = "basic";
  @Input() ariaLabel = "맨 위로";
  @Input() label = "TOP";
  @Output() topClick = new EventEmitter<void>();
}
