// packages/solid/src/components/UserFeedback.tsx
import { For, createSignal, createUniqueId, mergeProps, splitProps, type JSX } from "solid-js";

export interface FeedbackOption {
  value: string;
  label: string;
}

export interface UserFeedbackProps {
  class?: string;
  className?: string;
  title?: JSX.Element;
  options?: FeedbackOption[];
  onSubmit?: (value: string) => void;
  submitLabel?: JSX.Element;
  [key: string]: unknown;
}

export function UserFeedback(rawProps: UserFeedbackProps) {
  const merged = mergeProps(
    {
      title: "이 페이지에 만족하시나요?",
      options: [
        { value: "satisfied", label: "만족" },
        { value: "dissatisfied", label: "불만족" },
      ] as FeedbackOption[],
      submitLabel: "제출",
    },
    rawProps,
  );
  const [props, native] = splitProps(merged, [
    "class",
    "className",
    "title",
    "options",
    "onSubmit",
    "submitLabel",
  ]);

  const [selected, setSelected] = createSignal<string | undefined>(undefined);
  const name = `krds-feedback-${createUniqueId()}`;

  const submit = () => {
    const value = selected();
    if (value !== undefined) props.onSubmit?.(value);
  };

  const className = () => props.class ?? props.className ?? "";
  return (
    <div
      {...(native as Record<string, any>)}
      class={`krds-user-feedback${className() ? ` ${className()}` : ""}`}
    >
      <fieldset>
        <legend class="feedback-title">{props.title}</legend>
        <div class="feedback-options">
          <For each={props.options}>
            {(option) => (
              <div class="krds-form-check">
                <input
                  type="radio"
                  id={`${name}-${option.value}`}
                  name={name}
                  value={option.value}
                  checked={selected() === option.value}
                  onChange={(event) => {
                    if (event.currentTarget.checked) setSelected(option.value);
                  }}
                />
                <label for={`${name}-${option.value}`}>{option.label}</label>
              </div>
            )}
          </For>
        </div>
        <button type="button" class="krds-btn small primary" onClick={submit}>
          {props.submitLabel}
        </button>
      </fieldset>
    </div>
  );
}

// packages/angular/src/components/user-feedback.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { createStableId } from "../kinds";

const DEFAULT_FEEDBACK_OPTIONS = [
  { value: "satisfied", label: "만족" },
  { value: "dissatisfied", label: "불만족" },
];

@Component({
  selector: "krds-user-feedback",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="krds-user-feedback">
      <fieldset>
        <legend class="feedback-title">{{ title }}</legend>
        <div class="feedback-options">
          @for (option of options; track $index) {
            <label class="krds-form-check">
              <input
                type="radio"
                [name]="id"
                [value]="option.value"
                [checked]="selectedValue === option.value"
                (change)="selectedValue = option.value"
              />
              <span>{{ option.label }}</span>
            </label>
          }
        </div>
        <button
          type="button"
          class="krds-btn small primary"
          [disabled]="selectedValue === null"
          (click)="submit.emit(selectedValue!)"
        >
          {{ submitLabel }}
        </button>
      </fieldset>
    </div>
  `,
})
export class KrdsUserFeedbackComponent {
  @Input() id = createStableId("krds-user-feedback");
  @Input() title = "이 페이지에 만족하시나요?";
  @Input() options: { value: string; label: string }[] = DEFAULT_FEEDBACK_OPTIONS;
  @Input() submitLabel = "제출";
  @Output() submit = new EventEmitter<string>();

  selectedValue: string | null = null;
}
